### PR TITLE
Fix data race condition during parallel upgrades

### LINKED ISSUE #9366: Data race while performing multiple upgrades in parallel
I am using a custom Go program to perform 1000s of upgrades of helm charts in parallel.

Output of `helm version`:
From `go.mod`: `helm.sh/helm/v3 v3.5.0`

Output of `kubectl version`:
N.A. This is a unit test with memory storage/driver and `fake.PrintingKubeClient{}`.

Cloud Provider/Platform (AKS, GKE, Minikube etc.): 
Local system.

Error:

```

WARNING: DATA RACE
Write at 0x00c00033c2f0 by goroutine 45:
  helm.sh/helm/v3/pkg/action.(*Upgrade).Run()
      /Users/localuser/Desktop/workspace/example/src/example.com/release-management/release-manager/vendor/helm.sh/helm/v3/pkg/action/upgrade.go:129 +0x318
  example.com/release-management/release-manager/pkg/manager.(*helmV3Reconciler).UpgradeRelease()
      /Users/localuser/Desktop/workspace/example/src/example.com/release-management/release-manager/pkg/manager/helm3.go:315 +0x7cd
  example.com/release-management/release-manager/pkg/manager.(*helmV3Reconciler).UpgradeRelease-fm()
      /Users/localuser/Desktop/workspace/example/src/example.com/release-management/release-manager/pkg/manager/helm3.go:277 +0x4f
  example.com/release-management/release-manager/pkg/manager.(*Reconciler).asyncApply()
      /Users/localuser/Desktop/workspace/example/src/example.com/release-management/release-manager/pkg/manager/reconcile.go:263 +0x121

Previous write at 0x00c00033c2f0 by goroutine 38:
  helm.sh/helm/v3/pkg/action.(*Upgrade).Run()
      /Users/localuser/Desktop/workspace/example/src/example.com/release-management/release-manager/vendor/helm.sh/helm/v3/pkg/action/upgrade.go:129 +0x318
  example.com/release-management/release-manager/pkg/manager.(*helmV3Reconciler).UpgradeRelease()
      /Users/localuser/Desktop/workspace/example/src/example.com/release-management/release-manager/pkg/manager/helm3.go:315 +0x7cd
  example.com/release-management/release-manager/pkg/manager.(*helmV3Reconciler).UpgradeRelease-fm()
      /Users/localuser/Desktop/workspace/example/src/example.com/release-management/release-manager/pkg/manager/helm3.go:277 +0x4f
  example.com/release-management/release-manager/pkg/manager.(*Reconciler).asyncApply()
      /Users/localuser/Desktop/workspace/example/src/example.com/release-management/release-manager/pkg/manager/reconcile.go:263 +0x121

Goroutine 45 (running) created at:
  example.com/release-management/release-manager/pkg/manager.(*Reconciler).apply()
      /Users/localuser/Desktop/workspace/example/src/example.com/release-management/release-manager/pkg/manager/reconcile.go:222 +0x20e
  example.com/release-management/release-manager/pkg/manager.(*Reconciler).Reconcile()
      /Users/localuser/Desktop/workspace/example/src/example.com/release-management/release-manager/pkg/manager/reconcile.go:179 +0xdcf
  example.com/release-management/release-manager/pkg/manager.TestReconciler_Reconcile.func1()
      /Users/localuser/Desktop/workspace/example/src/example.com/release-management/release-manager/pkg/manager/reconcile_test.go:830 +0x779
  testing.tRunner()
      /usr/local/opt/go/libexec/src/testing/testing.go:1123 +0x202

Goroutine 38 (finished) created at:
  example.com/release-management/release-manager/pkg/manager.(*Reconciler).apply()
      /Users/localuser/Desktop/workspace/example/src/example.com/release-management/release-manager/pkg/manager/reconcile.go:222 +0x20e
  example.com/release-management/release-manager/pkg/manager.(*Reconciler).Reconcile()
      /Users/localuser/Desktop/workspace/example/src/example.com/release-management/release-manager/pkg/manager/reconcile.go:179 +0xdcf
  example.com/release-management/release-manager/pkg/manager.TestReconciler_Reconcile.func1()
      /Users/localuser/Desktop/workspace/example/src/example.com/release-management/release-manager/pkg/manager/reconcile_test.go:830 +0x779
  testing.tRunner()
      /usr/local/opt/go/libexec/src/testing/testing.go:1123 +0x202

```

Similar to https://github.com/helm/helm/pull/7820 and we might need a mutex to protect the update of the shared variable in https://github.com/helm/helm/blob/master/pkg/action/upgrade.go#L129: `	u.cfg.Releases.MaxHistory = u.MaxHistory`

### PR DESCRIPTION
**Pull request by krish7919**
**What this PR does / why we need it**:
Closes #9366

It also fixes a minor typo in the code/comments.

**Special notes for your reviewer**:
Have not added tests as it should work with all the existing tests already.

**If applicable**:
- [ ] this PR contains documentation
- [ ] this PR contains unit tests
- [ ] this PR has been tested for backwards compatibility

### CODE REVIEW

**Comment by krish7919** [comment]
Well, I pulled off from tag v3.5.1, I will need to rebase with `master`

**Comment by krish7919** [comment]
This does not work correctly. We have a bug somewhere in Helm where `	u.cfg.Releases.MaxHistory = u.MaxHistory` enters into a data race condition, and it is not a simple one to fix.

**Comment by krish7919** [comment]
This was closed in error; I had an error in my program running this changeset.

**Review by bacongobbler — CHANGES_REQUESTED** [review]
Hi @krish7919.

It is required for PR authors to provide unit tests along with their changes. It helps ensure future regressions are not introduced, and ensures that the change you provided fixes the original issue you set out to fix.

Please provide tests along with the PR.

Thanks.

**Comment by krish7919** [comment]
This doesn't fix the issue.

**Pull request closed without merging**
