### PR TITLE
docs: fix capitalization in a few help messages and use non thrid-person verb

### PR DESCRIPTION
**Pull request by liuming-dev**
1. fixed capitalization in a few help messages
2. use no thrid-person verb.

ref #7898

Signed-off-by: Liu Ming <hit_oak_tree@126.com>

### CODE REVIEW

**Review by hickeyma — CHANGES_REQUESTED** [review]
Thanks for fixing this @liuming-dev. From reading up on this (https://www.collinsdictionary.com/dictionary/english/display), it looks like you should use the plural for the verbs e.g. displays, shows etc. Do you mind changing this?

**Comment by liuming-dev** [comment]
@hickeyma Forgive my poor english, I do not really take it into consideration.
I just think that we should keep the same comment style, like: `helm -h`

```bash
Available Commands:
  completion  generate autocompletions script for the specified shell (bash or zsh)
  create      create a new chart with the given name
  dependency  manage a chart's dependencies
  diff        Preview helm upgrade changes as a diff
  env         helm client environment information
  get         download extended information of a named release
  help        Help about any command
  history     fetch release history
  install     install a chart
  lint        examines a chart for possible issues
  list        list releases
  monitor     monitor and rollback in case of failure based on metrics or logs
  package     package a chart directory into a chart archive
  plugin      install, list, or uninstall Helm plugins
  pull        download a chart from a repository and (optionally) unpack it in local directory
  push        Please see https://github.com/chartmuseum/helm-push for usage
  repo        add, list, remove, update, and index chart repositories
  rollback    roll back a release to a previous revision
  schema-gen  generate json schema for values yaml
  search      search for a keyword in charts
  show        show information of a chart
  status      displays the status of the named release
  template    locally render templates
  test        run tests for a release
  uninstall   uninstall a release
  upgrade     upgrade a release
  verify      verify that a chart at the given path has been signed and is valid
  version     print the client version information
```

It seems most command's short description starting with verb not verbs.

**Comment by liuming-dev** [comment]
Need I change `show` to `shows`, `display` to `displays`? And what about `examine `, `generate`? @hickeyma

**Comment by liuming-dev** [comment]
I change this PR as requested.
And within what I have learned, I think there is nothing wrong with this [commit](https://github.com/helm/helm/pull/8054/commits/bc515991f8fb7c3294e7f7809778fd360751d5cb).
Please give me a feedback, thanks @hickeyma

**Review by hickeyma — CHANGES_REQUESTED** [review]
I still think plural reads better to me but that might be just from my background. I agree with you that it would be better to have them all be singular case for consistency.

Do you mind rolling back to the original commit?

**Comment by liuming-dev** [comment]
Roll back  to the original commit, thanks for review @hickeyma :beers:

**Review by hickeyma — APPROVED** [review]
LGTM, thanks @liuming-dev

**Pull request merged**
