### PR TITLE
Add guestbook example for Helm. Issue #3191

### PR DESCRIPTION
**Pull request by yahavb**

### CODE REVIEW

**Comment by yahavb** [comment]
Hello - anything else is needed for approving the PR?

**Comment by bacongobbler** [comment]
Not at this time. :) We’ve just been super busy prepping for KubeCon this last few weeks.

**Comment by yahavb** [comment]
No issue. I am working on the few more examples and I wanted to make sure I have my first PR done correctly.

**Comment by unguiculus** [comment]
Please check out our chart review guidelines: https://github.com/kubernetes/charts/blob/master/REVIEW_GUIDELINES.md

Please follow our best practices, especially regarding names and labels.

**Comment by unguiculus** [comment]
I appreciate your effort but would question why we need yet another example. It adds to the maintenance burden.

**Comment by yahavb** [comment]
Sorry for the confusion. Not more examples but more charts in charts/stable

**Comment by bacongobbler** [comment]
I would suggest that if you wish to contribute a guestbook example chart, it should be provided to https://github.com/kubernetes/charts. That way, the chart maintainers (like @unguiculus) can have a look over the code and have this example conform to their acceptance suite. Once that's done we can point to the guestbook chart from the documentation.

Does that sound fair to you? If so I'd like to close this for now, but we can re-open once it's been submitted to the charts repo and then we can use it as a tutorial for the docs. :smile:

**Comment by yahavb** [comment]
In general, I agree to adhere any standard that will improve the readability and usability of the example. It helped to adopt Kuberentes.  I am not sure what is needed to be provided as a chart. Are you suggesting the guestbook will be composed of already existing published charts instead i.e., resuing the redis chart (https://github.com/unguiculus/charts/tree/master/stable/redis) and apache-php (https://github.com/yahavb/apache-ananware)? If that so, I am ok with that. If not please let me know what is needed to deploy the guestbook as a helm chart.

**Pull request closed without merging**
