### PR TITLE
fix: boilerplate template indentation

### PR DESCRIPTION
**Pull request by f0rmiga**
**What this PR does / why we need it**:

Just an indentation fix. We need this so picky people like me can stop freaking out every time we create a new chart using the template. :joy: 

**Special notes for your reviewer**:

**If applicable**:
- [ ] this PR contains documentation
- [ ] this PR contains unit tests
- [ ] this PR has been tested for backwards compatibility

### CODE REVIEW

**Comment by bacongobbler** [comment]
Hi @f0rmiga. Have you tested this PR to make sure this won't break compatibility? We've introduced small indentation changes like this in the past causing templates to not render correctly.

**Comment by bacongobbler** [comment]
ping.

**Comment by f0rmiga** [comment]
@bacongobbler I cannot imagine how this could ever break. I'd love to see the `small indentation changes` that broke - perhaps I can explain that.

In my case, I'm indenting 2 spaces for the opening and closing sections. They all use `{{-`, which basically does a strip of all the white spaces before it. A grotesque example:
https://play.golang.org/p/2fuvxJ-MoUJ
```go
package main

import (
	"log"
	"os"
	"text/template"
)

const tmplStr = `
foo:
                         



                       {{- if true }}
  bar: baz
  {{- end }}
`

func main() {
	if err := template.Must(template.New("").Parse(tmplStr)).Execute(os.Stdout, nil); err != nil {
		log.Fatal(err)
	}
}

```

**Comment by f0rmiga** [comment]
Ping @bacongobbler.

**Review by bacongobbler — APPROVED** [review]

**Pull request merged**
