### PR TITLE
add chart fuzz tests

### PR DESCRIPTION
**Pull request by AdamKorcz**
**What this PR does / why we need it**:

This moves the chartfuzzer upstream to Helms repository. The fuzzer currently exists [here](https://github.com/cncf/cncf-fuzzing/blob/main/projects/helm/chart_fuzzer.go). OSS-Fuzz runs this fuzzer continuously, and it is better in terms of manageability for Helm to have its fuzzers in its own repository.

**Special notes for your reviewer**:

**If applicable**:
- [ ] this PR contains user facing changes (the `docs needed` label should be applied if so)
- [ ] this PR contains unit tests
- [ ] this PR has been tested for backwards compatibility

### CODE REVIEW

**Comment by robertsirc** [comment]
Hello, thank you for your PR. This is just the test for testing fuzz that was implemented in another PR. I pulled this and the test pass. 

LGTM

**Review by robertsirc — APPROVED** [review]
LGTM

**Comment by mattfarina** [comment]
@AdamKorcz how will the move to the helm source end up working with oss-fuzz?

**Review by mattfarina — APPROVED** [review]

**Comment by AdamKorcz** [comment]
> @AdamKorcz how will the move to the helm source end up working with oss-fuzz?

My plan is to move the fuzzers from CNCF-fuzzing over the next weeks. I will also move the build script over here.

**Pull request merged**
