### PR TITLE
feat(install): introduce --create-namespace

### LINKED ISSUE #6794: Enable Release Namespace Creation in Helm3
### Overview
`Helm2` provided support for the Release namespace `{{ .Release.Namespace }}` via `--namespace` option if the release namespace did not exist. This functionality was considered rudimentary, and there were several requests from the community captured in #3503

`Helm3` took a more opinionated approach on how to handle `--namespace` option w/non-existing namespaces by removing support for the release namespace creation. Irrespective of the `--namespace` option, the `{{ .Release.Namespace }}` is expected to exist before installing/upgrading any `helm` chart that utilizes `--namespace` option.

By dropping support for the Release Namespace creation via `--namespace` option in `Helm3,` we also dropped any possibility to install a Helm chart with non-existent namespace! As a result, the chart authors and chart users must rely on additional, external to Helm3 tools like `kubectl` to
prepare (create) Release Namespace before Helm chart installation.

It is understood that `--namespace` option to create namespace was sub-optimal in `Helm2`, which prompted requests from the helm user community similar to #3503.

### Proposed Change
Rather than to remove support for the Release Namespace creation altogether, we can provide accommodations for helm chart authors to create the release namespace inline during the helm chart install by allow to define release namespace Inside as a `template` resource. Moreover, the helm chart authors will also be able to tailor the release namespace to the needs of the applications by including all necessary labels, annotations.

Consider following template for the Release Namespace manifest.

```yaml
{{- if and .Release.Namespace (.Values.createReleaseNamespace | default false) -}}
apiVersion: v1
kind: Namespace
metadata:
  name: {{ .Release.Namespace }}
  annotations:
    my-annoation: {{ .Values.MyAnnotation }}
  labels:
    release: {{ .Release.Name }}
    my-other-label: other-label
{{- end -}}
```

In the example above, we chose to emulate current Helm3 chart functionality, i.e., do not create the release namespace by default.

The chart authors can decide whether or not allow multiple instances of their application to target the same namespace. For example, removing `{{- if ...  end -}}` lines, effectively ensure that a given chart can only be installed into a newly created namespace and no two chart instances for this application can share the same namespace.

#### Processing and Assumptions
While the Release Namespace resource resembles other Helm `template` resources very closely, the processing of this resource is different.

Helm3 can perform a "special" pre-installation check to see if the Release Namespace is defined in the `templates` section. If it is - Helm3 will attempt to create the release namespace before recording release history, which utilizes the release namespace.

The "special" handling of the Release Namespace hs following assumptions/implications:

- The release namespace creation will be considered as a "special" functionality, i.e., since it is processed separately from the rest of the template resources (similar to crds)
- The release namespace artifact will be defined in the `templates` section, thus will be fully rendered just like any other `templates` resource (unlike crds)
- The release namespace resource will be "immutable," i.e., Helm3 will support only "Create" and "Delete" life-cycle events, and will not support "Update."
- Installing two charts that result in the resource namespace collision will be handled just like any other collision in `templates` resources.

#### Input Result Matrix (Helm3 Current)
Note: here and below, `Namespace` is synonymous to `Release Namespace.`

Note: in this example for simplicity we assume that all Helm chart artifacts are installed into the Release Namespace

| # | Namespace Precondition | Namespace Option | Result | Explanation |
| --- | --- | --- | --- | --- |
| 1 | Does not exist | None | Success: the helm chart is successfully installed into `default` namespace | The Release Namespace is neither existed, provided nor used |
| 2 | Does exist | None | Success: the helm chart is successfully installed into `default` namespace | The Release Namespace exists, however, neither provided nor used |
| 3 | Does not exist | Provided | Failure: the helm chart installation failed with "namespace not found" | The Release Namespace does not exist, and Helm3 will fail to perform all operations against this namespace |
| 4 | Does exist | Provided | Success: the helm chart is successfully installed into `Provided` release namespace | As expected |

#### Input Result Matrix (Proposed)
Same use cases as above, but this time with proposed changed and with Helm chart that includes template definition for the Release Namespace.

| # | Namespace | Namespace Option | Create Namespace Value | Result | Explanation |
| --- | --- | --- | --- | --- | --- |
| 1 | Does not exist | None | False | Success: the helm chart is successfully installed into `default` namespace | Same as current behavior: since the Release Namespace is provided yet it neither created nor used. |
| 2 | Does exits | None | False | Success: the helm chart is successfully installed into `default` namespace | Same as current behavior |
| 3.0 | Does not exist | Provided | False | Failure: the helm chart installation failed with "namespace not found" | Same as current behavior, since `CreateNamespaceValue is set to `false` |
| 3.1 | Does not exist | Provided | True | Success: the helm chart is installed into newly created release namespace | This is the new/proposed behavior |
| 4.0 | Does exist | Provided | False | Success: the helm chart is successfully installed into `Provided` release namespace | Same as current behavior |
| 4.1 | Does exist | Provided | True | Failure: namespace collision | Not "really a new" behavior since in this case the release namespace collision is no different than any Helm2/3 existing artifacts collision errors |

### Summary
The goal of this proposal is to entertain a possibility to provide Helm chart authors with functionality to define and provide support in terms of the properties when it comes down to the Release Namespace artifact.

With this proposal: Helm chart authors can allow users to:
- Install helm chart into an existing namespace (as currently supported)
- Install helm chart into a non-existing namespace (currently not supported)

while maintaining all the current Helm3 chart behaviors when it comes to storing Helm release information.

### PR DESCRIPTION
**Pull request by bacongobbler**
closes #6794

Signed-off-by: Matthew Fisher <matt.fisher@microsoft.com>

### CODE REVIEW

**Review by ichekrygin — CHANGES_REQUESTED** [review]
This does not work as intended.

**Review by mattfarina — APPROVED** [review]
works for me.

**Comment by bacongobbler** [comment]
@ichekrygin can you demonstrate how you tested this? You should just be able to run

```
$ helm install wordpress stable/wordpress --namespace wordpress --create-namespace
```

I manually tested this PR before submission. Happy to hear feedback on this.

**Comment by ichekrygin** [comment]
### Helm version
```
⋊> ~/g/s/g/h/h/bin on fix-6794 ⨯ ./helm version
version.BuildInfo{Version:"v3.1+unreleased", GitCommit:"694cf61aacba6bc4ed59a65d23acd20f6c8b95bd", GitTreeState:"clean", GoVersion:"go1.12.12"}
```
### Git Branch
```
⋊> ~/g/s/g/h/h/bin on fix-6794 ⨯ git log | head
commit 694cf61aacba6bc4ed59a65d23acd20f6c8b95bd
Author: Matthew Fisher <matt.fisher@microsoft.com>
Date:   Thu Feb 20 11:56:03 2020 -0800

    feat(install): introduce --create-namespace

    Signed-off-by: Matthew Fisher <matt.fisher@microsoft.com>

commit f7bcdf194b8782c10ec476a77929807199ad9baf
Merge: 99304c86 2a742
```
### Create new chart foo
```
⋊> ~/g/s/g/h/h/bin on fix-6794 ⨯ ./helm create foo
Creating foo

⋊> ~/g/s/g/h/h/bin on fix-6794 ⨯ ls -l
total 41068
drwxr-xr-x 4 illya illya     4096 Feb 20 16:41 bar/
drwxr-xr-x 4 illya illya     4096 Feb 24 10:48 foo/
-rwxr-xr-x 1 illya illya 42038352 Feb 24 10:48 helm*
```

### Test deploy foo into existing(default) namespace

```
⋊> ~/g/s/g/h/h/bin on fix-6794 ⨯ ./helm install foo ./foo
NAME: foo
LAST DEPLOYED: Mon Feb 24 10:48:49 2020
NAMESPACE: default
STATUS: deployed
REVISION: 1
NOTES:
1. Get the application URL by running these commands:
  export POD_NAME=$(kubectl get pods --namespace default -l "app.kubernetes.io/name=foo,app.kubernetes.io/instance=foo" -o jsonpath="{.items[0].metadata.name}")
  echo "Visit http://127.0.0.1:8080 to use your application"
  kubectl --namespace default port-forward $POD_NAME 8080:80
```
#### Show deployed chart artifacts
```
⋊> ~/g/s/g/h/h/bin on fix-6794 ⨯ kubectl get all
NAME                      READY   STATUS    RESTARTS   AGE
pod/foo-9458c558d-24nbw   1/1     Running   0          9s

NAME                 TYPE        CLUSTER-IP    EXTERNAL-IP   PORT(S)   AGE
service/foo          ClusterIP   10.99.16.16   <none>        80/TCP    9s
service/kubernetes   ClusterIP   10.96.0.1     <none>        443/TCP   24d

NAME                  READY   UP-TO-DATE   AVAILABLE   AGE
deployment.apps/foo   1/1     1            1           9s

NAME                            DESIRED   CURRENT   READY   AGE
replicaset.apps/foo-9458c558d   1         1         1       9s
```
#### Show installed helm chart
```
⋊> ~/g/s/g/h/h/bin on fix-6794 ⨯ ./helm list
NAME    NAMESPACE       REVISION        UPDATED                                 STATUS          CHART           APP VERSION
foo     default         1               2020-02-24 10:48:49.656651438 -0800 PST deployed        foo-0.1.0       1.16.0
```

#### Cleanup - delete helm chart
```
⋊> ~/g/s/g/h/h/bin on fix-6794 ⨯ helm delete foo
release "foo" uninstalled

# Verify that artifacts were removed
⋊> ~/g/s/g/h/h/bin on fix-6794 ⨯ kubectl get all
NAME                      READY   STATUS        RESTARTS   AGE
pod/foo-9458c558d-24nbw   0/1     Terminating   0          22s

NAME                 TYPE        CLUSTER-IP   EXTERNAL-IP   PORT(S)   AGE
service/kubernetes   ClusterIP   10.96.0.1    <none>        443/TCP   24d

# List all namespaces
⋊> ~/g/s/g/h/h/bin on fix-6794 ⨯ kubectl get ns
NAME              STATUS   AGE
bar               Active   3d17h
default           Active   24d
kube-node-lease   Active   24d
kube-public       Active   24d
kube-system       Active   24d
```

### Test install helm chart into non-existing namespace
```
⋊> ~/g/s/g/h/h/bin on fix-6794 ⨯ helm install foo ./foo -n foo
Error: create: failed to create: namespaces "foo" not found

# Install helm chart into non-existing namespace with flag `--create-namespace`
⋊> ~/g/s/g/h/h/bin on fix-6794 ⨯ helm install foo ./foo -n foo --create-namespace
Error: unknown flag: --create-namespace

# Repeat with `--namespace` vs. `-n`
⋊> ~/g/s/g/h/h/bin on fix-6794 ⨯ helm install foo ./foo --namespace foo --create-namespace
Error: unknown flag: --create-namespace
```

**Comment by ichekrygin** [comment]
Yes, it does work - "user error" (embarrasing: I ran wrong `helm` version command for the last test)
---
```
⋊> ~/g/s/g/h/h/bin on fix-6794 ⨯ ./helm install foo ./foo --namespace foo --create-namespace
NAME: foo
LAST DEPLOYED: Mon Feb 24 11:03:07 2020
NAMESPACE: foo
STATUS: deployed
REVISION: 1
NOTES:
1. Get the application URL by running these commands:
  export POD_NAME=$(kubectl get pods --namespace foo -l "app.kubernetes.io/name=foo,app.kubernetes.io/instance=foo" -o jsonpath="{.items[0].metadata.name}")
  echo "Visit http://127.0.0.1:8080 to use your application"
  kubectl --namespace foo port-forward $POD_NAME 8080:80

⋊> ~/g/s/g/h/h/bin on fix-6794 ⨯ kubectl get ns
NAME              STATUS   AGE
bar               Active   3d17h
default           Active   24d
foo               Active   15s
kube-node-lease   Active   24d
kube-public       Active   24d
kube-system       Active   24d
```

**Comment by ichekrygin** [comment]
I am glad this feature is back in!

Just curious, what made you change your mind in light of https://github.com/helm/helm/issues/5753#issuecomment-502163585

**Comment by bacongobbler** [comment]
The user can choose to opt into this functionality or not depending on the presence of the flag. This was not an option before.

**Comment by ichekrygin** [comment]
To clarify `before` as in `Helm2`? 

What about: 
> namespaces are a global cluster resource and the user installing resources into that namespace may not have the proper administrative rights to install the namespace itself, as that implies you have full administrative rights to the cluster 

And:
> Additionally, there have been several asks in the community to allow modifying the namespace helm install creates (e.g. #3503), and the UX to support use cases like that would be incredibly painful to achieve. Offloading the namespace creation to a separate tool (perhaps a plugin?) provides users a way to solve these issues without imposing a restrictive user experience around these use cases.

**Comment by bacongobbler** [comment]
If the user assumes they have administrative rights to the cluster, they can opt into the functionality. Otherwise, they’ll be blocked.

**Comment by bacongobbler** [comment]
The second point is a non-issue. Users who want to modify the namespace can create it with `kubectl create` out-of-band.

**Comment by ichekrygin** [comment]
If the user doesn't have admin functionality the "opt into" functionality is not applicable at all.
If we focus on user experience intalling chart into non-existent namespace:

| User Type | Command | Helm2 | Helm3 (opt in) | Helm3 (not-opt-in)
| --- | --- | --- | --- | --- |
| Non-Admin | `helm install foo ./foo` |  `-n foo`: install fails | `-n foo --create-namespace`: install fails | `-n foo`: install fails |
| Admin | `helm install foo ./foo ` | `-n foo`: install succeeds | `-n foo --create-namespace`: install succeeds | `-n foo`: install fails |

Under what circumstances users would choose to be "not-opt-in" or "opt-out"?

**Comment by bacongobbler** [comment]
You may wish to opt out if you know the namespace was created beforehand (like with `kubectl create`) and you do not want to create more namespaces. Or, you do not want to re-create the namespace if it was deleted out-of-band

A simpler example may be in the `helm upgrade --install` case: If you accidentally mistype `foo` as `fooo`, Helm will return an error reporting the namespace doesn't exist. If you added the `--create-namespace` flag, Helm will create the namespace, report success and install the chart in the `fooo` namespace, even if the intended behaviour was wrong. The operator only wanted to upgrade the existing chart, not create a new one in another namespace.

I think we've exhausted this conversation at this point. We're making mountains out of molehills here. The feature has been implemented and is in 3.2.

**Comment by ichekrygin** [comment]
> I think we've exhausted this conversation at this point. We're making mountains out of molehills here. The feature has been implemented and is in 3.2.

:+1:

**Comment by ishankhare07** [comment]
When can we expect this to be released?

**Comment by bacongobbler** [comment]
v3.2.0

**Comment by Ps3ud-0nym** [comment]
@bacongobbler If I'm installing the parent chart with helm install, is there a way to pass the --create-namespace flag to a subchart?

**Comment by SkySonR** [comment]
We need to have ability to pass custom labels during namespace creation. Please reopen https://github.com/helm/helm/issues/3503

**Pull request merged**
