### PR TITLE
docs: add note on rolling back to the previous release

### PR DESCRIPTION
**Pull request by bacongobbler**
supercedes #4984

### CODE REVIEW

**Review by mattfarina — APPROVED** [review]

**Comment by burnettk** [comment]
does `helm rollback [RELEASE] 0` roll back to the previous release, or the previous successful release? i think i want the latter, but i may be misunderstanding something. i've read through #1796 and i'm wondering if this fully addresses that feature request.

**Comment by bacongobbler** [comment]
The previous successful release.

**Comment by bacongobbler** [comment]
If you would like the latter, we should probably open a new ticket. The original request was for to roll back to last release rather than the last successful release. Those two use cases are distinct and have very different rollback behaviours with regards to how Helm reconciles the two.

**Comment by burnettk** [comment]
yeah, makes sense, thanks. filed https://github.com/helm/helm/issues/5237!

**Comment by ssandy83** [comment]
Don't we need to handle the case where currentRelease.Version = 1?

**Pull request merged**
