### PR TITLE
Updating to latest ingress API

### PR DESCRIPTION
**Pull request by mattfarina**
Ingress is now part of a group. A goal is to eventually remove the extensions group.

### CODE REVIEW

**Review by bacongobbler — APPROVED** [review]

**Comment by bacongobbler** [comment]
Will this work on older kubernetes clusters? e.g. 2.13 and 2.12?

**Comment by mattfarina** [comment]
@bacongobbler it was introduced in 1.14. Should we hold off a bit? Maybe just put this in the helm v3 version?

**Comment by bacongobbler** [comment]
Yeah, we should probably hold off. In general we don't try to support features that won't work on older supported versions of Kubernetes. If this works on just 2.14 clusters, then perhaps we should hold off a bit and port this over to Helm 3.

**Comment by mattfarina** [comment]
For some reason I'd thought this had been around longer.

**Pull request closed without merging**
