### PR TITLE
Fix #3127: Sort resources output by 'helm status'

### LINKED ISSUE #3127: Order resources in `helm status` output
If you execute `helm status` on the same release, the ordering of the Kubernetes resources changes even if nothing else has.

I'm not sure, but it seems like the ordering is non-deterministic. I believe that they should be ordered deterministically so that multiple calls to `helm status` (or, some people run it inside a `watch` or similar) are easier to read.

### PR DESCRIPTION
**Pull request by eladiw**
Signed-off-by: Elad Iwanir <eladiw@users.noreply.github.com>

**What this PR does / why we need it**:
closes #3127
This PR makes the 'helm status' command deterministic in the way it orders the displayed resources.
The functionality stays the same only now it is always sort alphabetically, both Kinds/Versions are sorted and within each KV the resources are also sorted
**Special notes for your reviewer**:
If applicable to v3 I will move the logic to that branch as well

**If applicable**:
- [ ] this PR contains documentation
- [ ] this PR contains unit tests
- [x] this PR has been tested for backwards compatibility

### CODE REVIEW

**Review by michelleN — COMMENTED** [review]
Would it be possible for you to add a unit test for this?

Thank you

**Review by bacongobbler — CHANGES_REQUESTED** [review]
Seems like a similar effort to https://github.com/helm/helm/pull/3214, though differing in approach. Would you mind taking a look at that PR and see which design seems like the right approach?

I also agree that some unit tests to verify this fixes the behaviour would be nice (and more importantly, to verify that future changes to pkg/kube doesn't break this).

Thanks!

**Comment by ian-howell** [comment]
Not sure what the proper way to handle this is, but I've made a PR that adds unit tests on @eladiw's repo here https://github.com/eladiw/helm/pull/1

**Review by michelleN — COMMENTED** [review]
@bacongobbler and I just went through the code and this change looks good to us. Now, we're just working through our options around how to add the test. 
@eladiw looks like @ian-howell has added some tests. If you want to consider merging those that would be great. If you don't want to do that, we can just merge this in and perhaps @ian-howell can make another pull request for the tests. Let us know how you want to proceed. I still need to do some manual testing here.

**Review by bacongobbler — APPROVED** [review]

**Review by michelleN — APPROVED** [review]

**Pull request merged**
