### PR TITLE
fix: provide patch flag replacing force flag for helm rollback

### PR DESCRIPTION
**Pull request by liuming-dev**
This is the second step: provide --patch flag to allow users to perform patch behaviour, and remove --force flag, this may break the backend compatibility: able to be merged in minor or major version, issue: #8465.

First step to see PR: #8473 

Signed-off-by: Liu Ming <hit_oak_tree@126.com>

**What this PR does / why we need it**:

**Special notes for your reviewer**:

**If applicable**:
- [ ] this PR contains documentation
- [ ] this PR contains unit tests
- [ ] this PR has been tested for backwards compatibility

### CODE REVIEW

**Review by hickeyma — COMMENTED** [review]
@liuming-dev As @bacongobbler mentioned in https://github.com/helm/helm/pull/8473#issuecomment-659833507, these PRs break backwards compatibility. It might be best first to discuss an issue like #8465 before pushing the PR.

**Comment by bacongobbler** [comment]
see https://github.com/helm/helm/issues/8465#issuecomment-660161463.

**Comment by liuming-dev** [comment]
I should have left the issue to be discussed and get the suggestions from maintainers. @hickeyma :smiley:

**Comment by hickeyma** [comment]
That's ok @liuming-dev. It just saves you time writing code before deciding on best path forward.

**Pull request closed without merging**
