### PR TITLE
Remove spurious debug output

### PR DESCRIPTION
**Pull request by srueg**
**What this PR does / why we need it**:
It removes spurious debug output which pollutes stdout.

**Special notes for your reviewer**:

**If applicable**:
- [ ] this PR contains documentation
- [ ] this PR contains unit tests
- [ ] this PR has been tested for backwards compatibility

### CODE REVIEW

**Comment by bacongobbler** [comment]
On a side note, I think it may be prudent to consolidate these two functions somewhere to keep the code more DRY. That way we don't have to update the code in two locations. The function signature, name, and behaviour is identical.

**Review by bacongobbler — COMMENTED** [review]
Perhaps it'd be better to demote this informational message to `debug`: https://github.com/helm/helm/blob/eefd939c6cd302c963c89ea0fed695aac62f4cdf/cmd/helm/helm.go#L49

That way users can still retrieve this information with `helm install --debug`.

What do you think?

**Comment by srueg** [comment]
> On a side note, I think it may be prudent to consolidate these two functions somewhere to keep the code more DRY. That way we don't have to update the code in two locations. The function signature, name, and behaviour is identical.

That's what I thought too but then saw the comment of the function:

> // The following functions (writeToFile, createOrOpenFile, and ensureDirectoryForFile)
// are coppied from the actions package. This is part of a change to correct a
// bug introduced by #8156. As part of the todo to refactor renderResources
// this duplicate code should be removed. It is added here so that the API
// surface area is as minimally impacted as possible in fixing the issue.


> Perhaps it'd be better to demote this informational message to debug

Good point, I'll take a look.

**Review by bacongobbler — APPROVED** [review]
code LGTM. Needs another maintainer's approval before we can merge.

**Comment by marckhouzam** [comment]
This looks like a duplicate of #8673 which was not merged due to backwards-compatibility concerns and the ease of working around it.  But @bacongobbler  would know better than I if this should go ahead or not.

**Comment by bacongobbler** [comment]
In this particular case I think it can be argued that this was intended to be debug output and therefore a bug. Users can still fetch this information with `helm install --debug`. I do not believe this could be a breaking change for some users, but I have been wrong before.

The more conservative approach may be to hold off on merging this until Helm 4.

**Comment by srueg** [comment]
Is the decision final to wait for Helm 4?
I'd also argue that it's a bug and the previous behavior can be re-enabled with `--debug`.

**Comment by joejulian** [comment]
As much as I'd love to see this change, reading the discussion on the referenced PR does seem like this is pretty clearly considered a breaking change so the finial decision is, indeed, to wait for Helm 4.

**Review by joejulian — CHANGES_REQUESTED** [review]
blocking as this seems to be considered a breaking change

**Pull request closed without merging**
