### PR TITLE
Add unit test case

### PR DESCRIPTION
**Pull request by zouy414**
Signed-off-by: ZouYu <zouy.fnst@cn.fujitsu.com>

**What this PR does / why we need it**:
Add unit test case for TestEqual() in internal/urlutil/urlutil_test.go
**Special notes for your reviewer**:

**If applicable**:
- [ ] this PR contains documentation
- [x] this PR contains unit tests
- [ ] this PR has been tested for backwards compatibility

### CODE REVIEW

**Comment by bacongobbler** [comment]
Hi there. What’s the reason for these unit tests? Is there a case where this behaviour is not covered by other tests, or some code path this test case covers?

**Comment by Hellcatlk** [comment]
@bacongobbler , this test cases cover these [code path](https://github.com/helm/helm/blob/master/internal/urlutil/urlutil.go#L46-L51).

**Comment by bacongobbler** [comment]
How is that not tested by the test case on line 58?

**Comment by Hellcatlk** [comment]
I think so.
```
Without `line 59-60`
Running tool: /usr/local/go/bin/go test -timeout 30s -coverprofile=/tmp/vscode-gonkzK6N/go-code-cover helm.sh/helm/v3/internal/urlutil

ok  	helm.sh/helm/v3/internal/urlutil	0.002s	coverage: 75.0% of statements
```
```
Running tool: /usr/local/go/bin/go test -timeout 30s -coverprofile=/tmp/vscode-gonkzK6N/go-code-cover helm.sh/helm/v3/internal/urlutil

ok  	helm.sh/helm/v3/internal/urlutil	0.004s	coverage: 87.5% of statements
```

**Review by jdolitsky — APPROVED** [review]

**Review by bacongobbler — APPROVED** [review]

**Pull request merged**
