### PR TITLE
Use repository-cache if specified

### LINKED ISSUE #7141: helm repo update doesnt respect --repository-cache
Output of `helm version`:
`version.BuildInfo{Version:"v3.0.0", GitCommit:"e29ce2a54e96cd02ccfce88bee4f58bb6e2a28b6", GitTreeState:"clean", GoVersion:"go1.13.4"}`
Output of `kubectl version`:
N/A
Cloud Provider/Platform (AKS, GKE, Minikube etc.): 
N/A

Running `helm repo update` with the `--repository-cache` parameter seems to still fill the "default" cache path, and not the one specified in the parameter.

### PR DESCRIPTION
**Pull request by trondhindenes**
Fixes #7141 
Use cache path specified by `--repository-cache` when running `repo update`. 
Added debug logging of path

### CODE REVIEW

**Comment by bacongobbler** [comment]
Thanks for the PR @trondhindenes. Have you confirmed if this fixes the issue for you?

**Comment by trondhindenes** [comment]
@bacongobbler yes it does. Cache file is created in the specified folder.

**Comment by marckhouzam** [comment]
Nice fix!  Simple and effective.
I confirm it fixed the reported issue:
```
$ git checkout master
$ make
$ h3 repo update --repository-cache /tmp
Hang tight while we grab the latest from your chart repositories...
...Successfully got an update from the "astronomer" chart repository
...Successfully got an update from the "stable" chart repository
Update Complete. ⎈ Happy Helming!⎈
$ ls /tmp/*yaml
zsh: no matches found: /tmp/*yaml
$ git checkout pr/7166
Switched to branch 'pr/7166'
$ make
GO111MODULE=on go build  -tags '' -ldflags '-w -s -X helm.sh/helm/v3/internal/version.gitCommit=3c6f8400aa361b5f52578bdfbd66abda558bb893 -X helm.sh/helm/v3/internal/version.gitTreeState=clean' -o /Users/marckhouzam/go/src/helm.sh/helm/bin/helm ./cmd/helm
 $ h3 repo update --repository-cache /tmp
Hang tight while we grab the latest from your chart repositories...
...Successfully got an update from the "astronomer" chart repository
...Successfully got an update from the "stable" chart repository
Update Complete. ⎈ Happy Helming!⎈
$ ls /tmp/*yaml
/tmp/astronomer-index.yaml /tmp/stable-index.yaml
```

I also confirmed the problem affects `helm repo add`, which would be an easy fix to add to this PR.
@trondhindenes do you mind?

Since the `--repository-cache` flag is global, I searched a bit more and, although I haven't confirmed, I believe the problem technically even applies to commands that download the index file just to find a chart URL:
1. helm pull
1. helm install
1. helm template
1. helm upgrade
1. helm show *

Personally, I don't think fixing that second batch of methods needs to be done in this PR.  It's a pretty edge case I think.

**Comment by trondhindenes** [comment]
good point @marckhouzam . I'll do some more digging.

<30 mins later>

As far as I can see, `helm repo add` doesnt actually download a cache, but maybe it will in the future, so I still think it makes sense to add the fix there as well. I tried adding a test for it in `repo_add_test.go`, but since the cache isn't downloaded, its difficult to assert behavior. However, I will add a test to `repo_update_test.go` while I'm in here.

**Comment by trondhindenes** [comment]
so added the things now. I think that's as good as it's gonna get from a non-go dev like me. Hopefully the change is ok.

**Comment by marckhouzam** [comment]
Thanks @trondhindenes for your efforts.  
If you can get the CI build to pass, I think this PR provides added value as is.

FYI, to reproduce for `helm repo add`:
```
$ ls /tmp/cache/astronomer-index.yaml
ls: /tmp/cache/astronomer-index.yaml: No such file or directory

$ ls /Users/marckhouzam/Library/Caches/helm/repository/astronomer-index.yaml
ls: /Users/marckhouzam/Library/Caches/helm/repository/astronomer-index.yaml: No such file or directory

$ h3 repo add astronomer http://helm.astronomer.io --repository-cache /tmp/cache
"astronomer" has been added to your repositories

$ ls /tmp/cache/astronomer-index.yaml
ls: /tmp/cache/astronomer-index.yaml: No such file or directory

$ ls /Users/marckhouzam/Library/Caches/helm/repository/astronomer-index.yaml
/Users/marckhouzam/Library/Caches/helm/repository/astronomer-index.yaml
```

**Comment by marckhouzam** [comment]
To be complete though, this opened a whole can of worms.  By looking at where `helmpath.CachePath` is used, there are other cases where the problem occurs.  For example `helm plugin install` also does not respect the `--repository-cache` flag.

How about we improve things with @trondhindenes PR for `helm repo add/update` and open a separate issue to track the other failures? @bacongobbler what do you recommend?

To keep track of how to reproduce some failures:
```
$ echo /tmp/cache/*last
zsh: no matches found: /tmp/cache/*last
$ echo /Users/marckhouzam/Library/Caches/helm/plugins/*last
zsh: no matches found: /Users/marckhouzam/Library/Caches/helm/plugins/*last
$ h3 plugin install https://github.com/adamreese/helm-last --repository-cache /tmp/cache
Installed plugin: last
$ echo /tmp/cache/*last
zsh: no matches found: /tmp/cache/*last
$ echo /Users/marckhouzam/Library/Caches/helm/plugins/*last
/Users/marckhouzam/Library/Caches/helm/plugins/https-github.com-adamreese-helm-last
```
Here is a way to test for `helm pull`:
```
h3 pull stable/nginx-ingress --repo http://helm.astronomer.io  --repository-cache /tmp/cache
```
where a temporary yaml file (e.g, `T3zcSKKRkUqHXahEdQF+mVXw4nI=-index.yaml`) appears in the normal cache path, not the overridden one.

**Comment by trondhindenes** [comment]
yup, it definetely did :-)
The build is working now, after I fixed some import issues. I won't take offense if someone more involved in the codebase "recreates" this PR and implements fixes in all the right places, but hopefully it provides some value as it stands right now.

**Comment by marckhouzam** [comment]
Well, I think I went a little overboard 😳: `helm plugin` need not respect `--repository-cache` since it's not downloading into the repository cache but the plugins cache instead.

**Comment by trondhindenes** [comment]
not sure if there's more I should do here, but I guess not.

**Comment by marckhouzam** [comment]
You're good. We'll wait for @bacongobbler input

**Comment by lucendio** [comment]
Is there any timeline for this to get merged?

/cc @bacongobbler

**Comment by yurrriq** [comment]
I, too, would love to see this merged.

**Comment by thomasdraebing** [comment]
+1 for getting this fix merged soon

/cc @bacongobbler

**Comment by bacongobbler** [comment]
At this time, I'm focused on other work. I do not have enough time in my work schedule to review this PR in the near future. That being said, there are plenty of other Helm maintainers who may have the time to review your work. I'd reach out and see if someone else is available to review this.

Sorry for the inconvenience.

**Comment by marckhouzam** [comment]
I'll take this one.

@trondhindenes do you have a little time to get this merged?  Here's what is needed:

1. Rebase to master (to check the Go tests still pass).  I tried and it has no conflicts, so super easy.
1. An existing Go test does fails with your PR.  It was added after you PR was first posted.  Could you attempt to fix it?  Just do `make test > output` and look for FAIL
1. The new test this PR adds does not fail when the code changes of this PR are removed.  This means the test is not sufficient.  Could you look into that?

Thanks!  I'm ready to merge this when those three points are resolved.

**Review by marckhouzam — CHANGES_REQUESTED** [review]
Just marking as "changes requested"

**Comment by technosophos** [comment]
I'm going to leave this on 3.2 until Thursday, because I think we can get it merged before then if @marckhouzam 's last issues are fixed.

**Comment by trondhindenes** [comment]
I can have a look!

**Comment by technosophos** [comment]
Just checking in on this one. I looked at the code a little more carefully today, and it appears to catch the main cases I could find. I would like to get this in for 3.3.0 if possible.

**Comment by trondhindenes** [comment]
sorry, I haven't had a chance to do anything here. Swamped at work. If anyone else wants to do what's needed to get this one merged feel free to base it on this branch.

**Comment by hickeyma** [comment]
@trondhindenes That's ok. I will look to tidy up the remaining parts.

**Comment by trondhindenes** [comment]
thanks @hickeyma. sorry to leave this PR in an unfinished state for so long.

**Comment by hickeyma** [comment]
I tried with to get the unit test to pass using this PR but it would not pass regardless of changes I made.  When I changed to a clean branch then it worked. I am unable to explain it.

I have therefore created #8158 to supersede this. I hope that is ok with your @trondhindenes?

**Comment by hickeyma** [comment]
Closing as  #8158 to supersede this.

**Comment by trondhindenes** [comment]
> I hope that is ok with your @trondhindenes?

absolutely!

**Pull request closed without merging**
