### PR TITLE
Introduced fuzzing by adding first fuzzer

### PR DESCRIPTION
**Pull request by AdamKorcz**
**What this PR does / why we need it**:
This PR introduces fuzzing to Helm by adding the first fuzzer to the project. The fuzzer gets decent coverage and has been used to find [this crash](https://github.com/helm/helm/issues/8116). 

The fuzzer can be run locally, and I suggest implementing continuous fuzzing into Helm to keep looking for bugs and keep the fuzzer running. Keeping the fuzzers running for an extended period of time has been proven to find bugs. As an example, [this one](https://www.openssl.org/news/secadv/20170126.txt) took 3 cpu years of fuzzing to find.

I managed to setup the fuzzer on oss-fuzz's infrastructure, and I will be happy to integrate Helm into their platform. This will allow Google to run the fuzzer and all future fuzzers, continuously, and if a bug is found, the maintainers on the email list receive a detailed bug report.
oss-fuzz is a free service with an implied expectation that the bugs are fixed, so that the resources spent on fuzzing Helm are put to good use.

All I need to integrate Helm into oss-fuzz are the emails addresses that should receive the bug reports.

I will be happy to progressively work more on fuzzing Helm to increase the coverage and improve the effectiveness of the fuzzers.

**Special notes for the reviewer**:
This PR reopens https://github.com/helm/helm/pull/8114 which was rejected due to lack of information.
This PR does not change any functionality or update any code in Helm.
This PR does not provide any documentation.
This PR does not contain unit tests.

Signed-off-by: Adam Korczynski adam@adalogics.com

### CODE REVIEW

**Review by mattfarina — CHANGES_REQUESTED** [review]
Thanks for the pull request. I like having fuzzing.

In addition to the comments below, would it be possible to add:

- A make target for someone to run fuzzing that works on linux/mac. You can see what I did on https://github.com/masterminds/semver. I'm not saying it needs to be the same. Rather, I'm sharing to show the idea.
- Some docs to point people in the right direction on the fuzzing so they know what it means. The comments on this PR won't be easily found in the future.

Prior to merging in Fuzz testing I would like to see the parsing issues fixed to remove the crashes. That can be in a separate PR.

**Comment by technosophos** [comment]
Any update on this?

**Comment by AdamKorcz** [comment]
Good evening
I will be glad to wrap up this PR. I have noticed that [my issue](https://github.com/helm/helm/issues/8116) remains open, and while it will be my pleasure to fix the bug therein, unfortunately I most likely won't be able to fix future bugs that the fuzzer finds. Could you confirm that there are contributors to Helm that would be interested in fixing potential bugs? I would hate to work on an initiative that would only stress out the great community.
I have seen https://github.com/helm/helm/issues/8140 and am thrilled that the fuzzer has helped expose that one.

**Comment by technosophos** [comment]
LOL... we do our best to fix bugs. Sorry we didn't get to your other one. I can't guarantee that we'll do it fast. But, you know, we have lots of open source contributors who try to help with stuff like that.

**Comment by AdamKorcz** [comment]
Glad to hear it. And for the record there was no level of judgement or sarcasm in my previous message.

I will get to the comments kindly provided in the weekend.

**Comment by AdamKorcz** [comment]
I checked out the integration of the fuzzer into the build system. It will take a bit longer than I have available at the moment.

Closing this for now, but feel free to open, if it is something you can help with.

**Pull request closed without merging**
