### PR TITLE
Create output-dir if missing

### PR DESCRIPTION
**Pull request by harsimranmaan**

### CODE REVIEW

**Review by bacongobbler — CHANGES_REQUESTED** [review]
this is a breaking behavioral change from what's expected. As the code suggests, the output dir was not intended to be created when `helm template` was invoked, so I'm not sure if we can support this feature as the default. However, if this was hidden behind a feature flag then we may consider this change.

**Comment by tariq1890** [comment]
@bacongobbler I found this change pretty useful.  As a newbie to helm, I am interested in knowing why this would be a breaking change. Any issue/PR that references this?

**Comment by bacongobbler** [comment]
in master, if you do a `helm template -o foo mychart`, it is expected that `foo` already exists and error out if it doesn't. By changing that behaviour to create that directory, we are breaking that assumption.

See https://github.com/helm/helm/blob/master/CONTRIBUTING.md#semantic-versioning for more detail on what's covered under our semver contract.

**Comment by tariq1890** [comment]
@bacongobbler Sure. Makes sense. Thanks!

**Comment by harsimranmaan** [comment]
@bacongobbler I can add a flag to make sure that this is backwards compatible. But I think that we should make this the default in helm 3.

**Comment by bacongobbler** [comment]
ping, are you looking to refactor this PR or should we go ahead and close this?

**Comment by harsimranmaan** [comment]
I think there little value added in adding a new flag. My other tools using helm have evolved with the folder creation restriction already handled outside of helm. I'll close this for now. Thanks.

**Pull request closed without merging**
