### PR TITLE
Print no matches found if none are found

### PR DESCRIPTION
**Pull request by vaikas**
Also update the help strings to match reality.
#691 @michelleN

### CODE REVIEW

**Comment by technosophos** [comment]
I believe this should return an error "no matches found" so that the command exits with a 1.

**Comment by vaikas-google** [comment]
If you feel strongly, I can change, but I think that lack of matches should not be an error, just like grep not finding matches will not err out, or ls with a glob, etc.

**Comment by technosophos** [comment]
Grep seems to output a `1` or a `2` when it doesn't find anything (depending on whether there are un-searched directories). Find, however, seems to exit with 0 if it doesn't find anything. Hmmm.

**Comment by vaikas-google** [comment]
Ah, ok, my bad. Should've relied on google and not my memory :) I'll change :)

**Comment by vaikas-google** [comment]
PTAL @technosophos

**Comment by technosophos** [comment]
This is great. I quick informal poll of the Deis team indicates that we're split over returning an error. So... I don't know. I'm going to mark this as LGTM, and if you feel like we should remove the error and just print a message, feel free to change it. I'll defer to your judgment.

**Pull request merged**
