### PR TITLE
Fix/get wrong version

### PR DESCRIPTION
**Pull request by jianliao82**
when customer use --version flag, the version format include the Build
metadata, the metadata will be ignored.

The change is when customer input exact version ,we just need compare whether the version is same as chart, when the version is empty, we just continue use the old method to get a latest version.

### CODE REVIEW

**Comment by jianliao82** [comment]
#4838

**Review by mattfarina — CHANGES_REQUESTED** [review]
Thanks for submitting the pull request. There are some possible problems that can come up with the current flow and there's a breaking change in the way the version being passed in is handled.

Instead of this flow I would suggest something different. if the `len(version) != 0` check if the version passed in is a valid version. If it is loop over all the possible versions looking for an exact match. Otherwise fall back to the current method.

What do you think?

**Comment by jianliao82** [comment]
@mattfarina Thanks for your review. I have updated the code change. Could you help to take a look at it again?

**Comment by bacongobbler** [comment]
@mattfarina should we consider this for the v2.12.0 release or do we think it needs more time to bake before we merge? Just going down the PR queue looking for potential features to merge for 2.12. Thanks!

**Review by bacongobbler — APPROVED** [review]
LGTM.

**Comment by noam-toga** [comment]
this didnt fix the issue. at least when running helm dep update 
i've opened an issue here:
https://github.com/helm/helm/issues/7563

**Pull request merged**
