### PR TITLE
[FIX]Unified go specification

### PR DESCRIPTION
**Pull request by scaat**
**What this PR does / why we need it**:
Unified go specification.
**Special notes for your reviewer**:

**If applicable**:
- [ ] this PR contains documentation
- [ ] this PR contains unit tests
- [ ] this PR has been tested for backwards compatibility

### CODE REVIEW

**Comment by mattfarina** [comment]
Can you explain what you mean by "Unified go specification". We are looking for a reason for this change.

**Comment by scaat** [comment]
@mattfarina Thank you for your reply.
For example, such as "error string should not be capitalized", you can refer to [here](https://github.com/golang/go/wiki/CodeReviewComments#error-strings).

> Error strings should not be capitalized (unless beginning with proper nouns or acronyms) or end with punctuation, since they are usually printed following other context. That is, use fmt.Errorf("something bad") not fmt.Errorf("Something bad"), so that log.Printf("Reading %s: %v", filename, err) formats without a spurious capital letter mid-message. This does not apply to logging, which is implicitly line-oriented and not combined inside other messages.

**Comment by bacongobbler** [comment]
What's the justification from changing `c` to `cfg`? I see that other actions use a `cfg` field, but the "specification" from the interface's point of view is already unified (`(c *Configuration)`). The two (function signatures vs private struct fields) are mutually exclusive.

I'm wondering the same thing @mattfarina mentions. What is the reason for that particular change?

**Comment by scaat** [comment]
@bacongobbler  Thank you for your reply.
In other files, such as `hooks.go`, the method of `*Configuration` is also defined, and the receiver here is `cfg *Configuration`. This pr is just making some suggested changes, and does not actually affect the code.

**Comment by bacongobbler** [comment]
Right, but as I said, those are private struct fields and do not affect the "public" API in any way. So I'm having a tough time determining what "spec" is being followed here.

When I hear someone refer to the "go specification" they're usually referring to [the public Go API](https://pkg.go.dev/helm.sh/helm/v3@v3.4.1/pkg/action). I can see there are a few spots where `c *Configuration` and `cfg *Configuration` are used interchangeably, but it's far fewer instances than what's being changed here.

**Review by bacongobbler — APPROVED** [review]
I'm okay with these changes. In the future, please separate each unit of work into a separate PR so they can be reviewed and approved in isolation of each other.

**Comment by scaat** [comment]
@bacongobbler Thank you, I will pay attention to the distinction next time.

**Review by hickeyma — APPROVED** [review]
LGTM, thanks @scaat

**Pull request merged**
