### PR TITLE
first spike of #282 to support annotation based secret generation on …

### PR DESCRIPTION
**Pull request by jstrachan**
…install

### CODE REVIEW

**Comment by technosophos** [comment]
Could we also add a top-level command for this? I can see a use case where people may want to generate the secret, but not run `helm install` (maybe use `kubectl` directly instead). Maybe something like `helm gen-secret` or similar? (I'll leave it up to you.)

I had done some similar work with secrets generation in the `plugins/sec/` folder. The idea was to make a functional example plugin, but one of the capabilities that had was generating random "password" or token strings. Would that be a useful feature for this command? (We can add it later... just thinking out loud.)

Also, would you mind amending the commit message so it follows the repo style? Not a huge deal, but we try to stay consistent for our tooling. https://github.com/deis/deis/blob/master/CONTRIBUTING.md#commit-style-guideline

**Comment by technosophos** [comment]
Sorry... I finally got a big PR merged and it's breaking your stuff.

We changed the way we did things internally so that we were not so reliant on hard-coded Kubernetes kinds. I think this will actually make your work a lot easier. There are fewer cases where you'll need Kind-specific code. I also added some utility logic for reading and modifying labels and annotations. It's not great, but its a start.

**Comment by technosophos** [comment]
We're talking about pushing this feature into the 0.3 milestone, which is scheduled to go out a few weeks from now. Does that give you enough time to massage it into orde,r @jstrachan ?

**Comment by jstrachan** [comment]
@technosophos BTW I hit a few issues with the helm codec stuff (was getting SecurityContext generating an upper case RunAsRoute element so I've been mostly using the kubernetes codec when needing to modify things like an RC. We need to modify the RC when doing `helm upgrade` for #292. We might wanna add some helper methods around working with k8s runtime.Object and kubernetes codec?

e.g. here's the use of the kubernetes codec along with 2 little helper functions to get the ObjectMeta or TypeMeta for the objects so you can modify labels/annotations/type/APIVersion etc
https://github.com/fabric8io/helm/blob/61c8ca7b0ea2a45ff82bf4dd1823196adf54640d/action/install.go#L331-L341

as you need to modify the APIVersion to be able to do a `kubectl apply` from a chart

**Comment by jstrachan** [comment]
I just submitted a fresh PR for #282 after rebasing and cherry picking the secrets changes from PR https://github.com/helm/helm/pull/323 as they were fairly simple. I'll close this PR now

**Pull request closed without merging**
