### PR TITLE
Move expansion types out of common

### PR DESCRIPTION
**Pull request by sparkprime**
@jackgr

### CODE REVIEW

**Comment by jackgr** [comment]
OK, we're starting to overlap, which is a good sign. I have a commit with exactly this title that does exactly this, with one difference... I went with expansion as the package name, rather than expander because the latter collides in manager/expander.

**Comment by jackgr** [comment]
Let's sync tomorrow.

**Comment by jackgr** [comment]
See #446

**Comment by sparkprime** [comment]
No worries, this was a simple find / replace job.  I'll wait for your changes.

**Pull request closed without merging**
