### PR TITLE
allow setting TLS flags from environment variables

### LINKED ISSUE #3456: Error: unknown flag: --tls
Including the TLS command-line options on every call is tedious so I created a wrapper script that does:

    #!/bin/bash
    exec helm \
      --tls \
      --tls-verify \
      --tls-ca-cert=/path/to/ca.pem \
      --tls-cert=/path/to/cert.pem \
      --tls-key=/path/to/key.pem \
      "$@"
 
This works fine for commands like "helm ls" or "helm install" that communicate with Tiller but fails with *Error: unknown flag: --tls* with "helm", "helm search" or "helm repo list" for those that don't.  

Could this be changed to that these command-line options are allowed for all helm commands, but are ignored  when not communicating with Tiller?

Another alternative would be to add support for for a TILLER_TLS_* environment variables that are used like HELM_HOST or TILLER_NAMESPACE.  Then we could set the environment variables:

    export HELM_TLS_ENABLE=true
    export HELM_TLS_VERIFY=true
    export HELM_TLS_CA_CERT=/path/to/ca.pem
    export HELM_TLS_CERT=/path/to/cert.pem
    export HELM_TLS_KEY=/path/to/key.pem

and all helm commands would work without lots of command-line options.  Perhaps doing both would make sense.

Thoughts?

### PR DESCRIPTION
**Pull request by bacongobbler**
supercedes #4392 

closes #3456

### CODE REVIEW

**Comment by bacongobbler** [comment]
hold up; manual testing is showing that this isn't working as intended.

```
><> HELM_TLS_VERIFY=1 ./bin/helm list
><> ./bin/helm list --tls-verify
could not read x509 key pair (cert: "/home/bacongobbler/.helm/cert.pem", key: "/home/bacongobbler/.helm/key.pem"): can't load key pair from cert /home/bacongobbler/.helm/cert.pem and key /home/bacongobbler/.helm/key.pem: open /home/bacongobbler/.helm/cert.pem: no such file or directory
```

**Comment by bacongobbler** [comment]
okay fixed. It had to do with the `settings.Init` flag only working on top-level flags rather than when we're parsing those flags. Should be good to go now.

**Comment by bacongobbler** [comment]
```
><> make
GOBIN=/home/bacongobbler/code/go/src/k8s.io/helm/bin go install  -tags '' -ldflags '-w -s -X k8s.io/helm/pkg/version.GitCommit=efb60983cb0cf5d397f7ba81669010681fb4ab37 -X k8s.io/helm/pkg/version.GitTreeState=clean' k8s.io/helm/cmd/...
><> HELM_TLS_VERIFY=true ./bin/helm list
could not read x509 key pair (cert: "/home/bacongobbler/.helm/cert.pem", key: "/home/bacongobbler/.helm/key.pem"): can't load key pair from cert /home/bacongobbler/.helm/cert.pem and key /home/bacongobbler/.helm/key.pem: open /home/bacongobbler/.helm/cert.pem: no such file or directory
```

**Review by thomastaylor312 — APPROVED** [review]
Code looks good and manually validated functionality

**Pull request merged**
