### PR TITLE
Fixing pkg->cmd call by moving helmpath under /pkg

### PR DESCRIPTION
**Pull request by libesz**
When downloader package moved to under /pkg, helmpath functions got called still from it, while it is under /cmd. This commit fixes the issue by moving helmpath after the downloader to have only cmd->pkg and pkg->pkg calls.

### CODE REVIEW

**Comment by technosophos** [comment]
Thank you for noticing that. It's something we've been talking about fixing since we moved the downloader library.

**Comment by bacongobbler** [comment]
Perhaps this should live under `pkg/helm/helmpath` similar to `pkg/helm/portforwarder`? This client package is only relevant to users of the helm client, so the same argument could be applied here as well.

**Comment by technosophos** [comment]
I agree with @bacongobbler on that one. We probably should put it under `pkg/helm` since it is very specifically client-oriented logic.

**Comment by libesz** [comment]
Thanks for the review! I am preparing the move right now.

To be complete: downloader and resolver package also uses helmpath. Although these are also fully client related, they live outside of pkg/helm.

**Review by technosophos — APPROVED** [review]
Looks fabulous. Thanks.

**Review by adamreese — APPROVED** [review]

**Pull request merged**
