### PR TITLE
Modify spelling mistakes

### PR DESCRIPTION
**Pull request by yuxiaobo96**
Signed-off-by: yuxiaobo <yuxiaobogo@163.com>

**What this PR does / why we need it**:
Modify spelling mistakes
**Special notes for your reviewer**:

**If applicable**:
- [ ] this PR contains documentation
- [ ] this PR contains unit tests
- [ ] this PR has been tested for backwards compatibility

### CODE REVIEW

**Comment by hickeyma** [comment]
Tests failing seem to be due to the build env. I have kicked off a few runs now. Will wait until the test pass to merge.

**Comment by bacongobbler** [comment]
These aren't really typos. These were intentional to express excitement ("something's happening!"). Given these are internal unit tests and not customer facing, I think these should be kept as-is.

**Pull request closed without merging**
