### PR TITLE
set $HOME in tiller container to /tmp

### LINKED ISSUE #1951: Helm fails when podsecuritypolicy is on
I was doing some testing of Helm under OpenShift and Kube with pod security policy to flush out any assumptions that don't make sense in a multi-tenant environment.  One of the first ones I hit was that it looks like the helm assumes that it can run containers as root on the cluster:

```
$ helm install stable/redis
Error: release eager-jackal failed: error validating "": error validating data: mkdir /.kube: permission denied
```

A restrictive pod security policy (that doesn't allow running as root) will catch this - since I assume tiller doesn't actually need root in the pods it sets up, it might be good to craft the tiller image so that it doesn't assume it is running as UID 0 in the image.  Since tiller will have access to high level credentials, it's also somewhat dangerous that the tiller image expands the code inside its own container (any escape from the template environment will root the cluster).

### PR DESCRIPTION
**Pull request by bacongobbler**
closes #1951... I think. @smarterclayton if you can try this image on your setup that'd be appreciated.

### CODE REVIEW

**Comment by technosophos** [comment]
If this fixes it (and we get confirmation fast enough), I'll squeeze this into 2.2.0 tomorrow

**Comment by bacongobbler** [comment]
Sounds like we got confirmation that this fixes things.

**Comment by smarterclayton** [comment]
Yes this fixed the issue.

**Review by wilkers-steve — COMMENTED** [review]
Looks good to me 👍

**Pull request merged**
