### PR TITLE
Return err when search chart failed

### PR DESCRIPTION
**Pull request by FengyunPan**
None

### CODE REVIEW

**Comment by technosophos** [comment]
In testing other package managers, I can't find any that return an error if no matching package is found. Is there a reason to change this to an error?

**Comment by FengyunPan** [comment]
@technosophos Hi, thank for your review. I just want to return error if regexp.Compile() is failed.
I think we should return error when 'helm search' meet errror, and just return 'No results found' when 'helm search' is nil. Do you think so?

**Comment by FengyunPan** [comment]
@technosophos Sorry, I have understanded it. I close this pr.

**Comment by technosophos** [comment]
I agree.

Get Outlook for Android<https://aka.ms/ghei36>

________________________________

**Pull request closed without merging**
