### PR TITLE
UPT: tutorial to latest helm

### PR DESCRIPTION
**Pull request by AlphaWong**
Relataed: https://github.com/helm/helm/pull/4808

### CODE REVIEW

**Comment by mattfarina** [comment]
@AlphaWong Can you please signoff on the commit? You can alter this commit with signoff using the command `git commit --signoff --amend`. The force push the change. This is for DCO signoff.

**Comment by AlphaWong** [comment]
Sure. Let me do it monday. thx man

**Comment by bacongobbler** [comment]
ping

**Comment by bacongobbler** [comment]
I'm going to close this ticket due to inactivity, but please re-open if this still needs to be addressed. Thanks!

**Pull request closed without merging**
