### PR TITLE
feat(lint): separate errors and warnings

### PR DESCRIPTION
**Pull request by lanej**

### CODE REVIEW

**Comment by sgoings** [comment]
Love this change, @lanej!

```
 ~/go/src/github.com/helm/charts  ⑂ master +    helm lint ./nginx
[WARN] A README file was not found in nginx
[WARN] Chart name nginx already exists in charts repository [github.com/helm/charts]. If you're planning on submitting this chart to the charts repo, please consider changing the chart name.
[WARN] Chart [nginx] failed some checks
 ~/go/src/github.com/helm/charts  ⑂ master +    rm nginx/Chart.yaml
 ~/go/src/github.com/helm/charts  ⑂ master +    helm lint ./nginx
[WARN] A README file was not found in nginx
[WARN] Chart name nginx already exists in charts repository [github.com/helm/charts]. If you're planning on submitting this chart to the charts repo, please consider changing the chart name.
[ERROR] A Chart.yaml file was not found in nginx
[ERROR] open nginx/Chart.yaml: no such file or directory
[ERROR] Chart [nginx] failed some checks
Exiting with errors
```

One question though... are you ok with having 2 lines of errors re: Chart.yaml being nonexistent?

**Comment by lanej** [comment]
@sgoings fine ... for now.  the messages themselves need some refactoring.

**Comment by sgoings** [comment]
Aw yeah. That's better:

```
 ~/go/src/github.com/helm/charts  ⑂ master +    helm lint nginx
[WARN] A README file was not found in nginx
[WARN] Chart name nginx already exists in charts repository [github.com/helm/charts]. If you're planning on submitting this chart to the charts repo, please consider changing the chart name.
[ERROR] A Chart.yaml file was not found
[ERROR] Chart [nginx] failed some checks
Exiting with errors
```

**Comment by sgoings** [comment]
LGTM2 from @iancoffey via Slack

**Pull request merged**
