### PR TITLE
Removing the stable repository

### PR DESCRIPTION
**Pull request by mattfarina**
The stable repository provides a quick on-boarding with a set of
community curated charts. Two problems with the community stable
repository has lead to its need to be removed.

1. The URL is hard coded to a Google Cloud bucket under Google's
   control. This was setup when Helm was part of Kubernetes and
   Kubernetes was a Google project. The bucket cannot be
   transferred to another non-Google controlled project. And,
   the bucket is not accessible in some parts of the world
   (e.g., China).
2. The number of charts in the stable repository has grown
   generally unmaintainable. The repository maintainers cannot
   manage the number of PRs coming it cauing delays in response
   or no response and PRs are automatically closed. This is
   a poor experience.

The alternative is the Helm Hub that provides a central point of
search for many Helm repositories. Different people and organizations
can maintain their own charts. A central server is not needed as
Helm is setup to be distributed.

cc @helm/charts-maintainers

### CODE REVIEW

**Comment by maorfr** [comment]
This looks good to me. Do we already have a deprecation plan for the charts repository? Is there a doc maybe?

**Review by bacongobbler — APPROVED** [review]
LGTM.

**Comment by bacongobbler** [comment]
The v3 docs may need an update as well since the stable repository is a commonly used example. Would you be willing to update helm-www as well, or would you mind filing a ticket for that?

**Comment by mattfarina** [comment]
@maorfr When helm v2 is deprecated at the earliest. That timeline is up for discussing in the next Helm Dev Call.

@bacongobbler I noticed that. I wanted one PR to land at a time. I have a few in flight. I'll get to that unless someone else wants to.

**Review by hickeyma — APPROVED** [review]
LGTM, thanks.

**Comment by norrs** [comment]
What happens with the existing charts that A LOT of users depends on? Will they be migrated to Helm Hub? Where is Helm Hub? ( https://hub.helm.sh/ I assume? )

Please make follow up issues for chart owners to migrate their charts before you remove anything please, to avoid chaos and angry helm users.

cc @helm/charts-maintainers

**Comment by prydonius** [comment]
@norrs this just removes `stable` as a default repository, it can still be added manually with `helm repo add stable https://kubernetes-charts.storage.googleapis.com`

**Pull request merged**
