### PR TITLE
helm plugin subcommands aliases - helm3

### PR DESCRIPTION
**Pull request by Efrat19**
**What this PR does / why we need it**:

**Special notes for your reviewer**:

**If applicable**:
- [ ] this PR contains documentation
- [ ] this PR contains unit tests
- [ ] this PR has been tested for backwards compatibility

this pr address the following feature-request: #6558

### CODE REVIEW

**Review by bacongobbler — APPROVED** [review]
LGTM! Thanks.

**Comment by marckhouzam** [comment]
NIce.  Now every "remove" subcommand is matched to an "rm" alias.

To be fully consistent, there are two more aliases missing:
1. `helm repo ls`
1. `helm plugin up`  which exists for `helm repo update` and `helm dependency update`

If @bacongobbler agrees that it makes sense to add these, @Efrat19 are you interested in doing a second PR?

**Comment by bacongobbler** [comment]
I don't see why not

**Comment by Efrat19** [comment]
@marckhouzam  with great pleasure. ill handle this tonight

**Comment by Efrat19** [comment]
@bacongobbler  @marckhouzam 
pr submitted https://github.com/helm/helm/pull/6589
that was fun, I 💖you product

**Pull request merged**
