### PR TITLE
feat(helm): add --app-version flag to 'helm install/upgrade'

### LINKED ISSUE #3555: Add 'helm install --app-version' command/versioning a chart against an app version
As far as I'm aware, `helm install` currently only supports specifying the `--version` flag to specify a chart version to install.

I'm unsure how the 'appVersion' field in a Chart.yaml is supposed to be used, but it seems generally useful to add support for versioning your application against a specific version (or version set) of a Chart.

Am I mis-using the `appVersion` field here? Should I instead be constantly building my chart to be backward compatible with previous version, or otherwise how can I infer to my users which chart version to specify when running `helm install` if they want a particular version (this becomes even more complex when you consider a user can also change the version deployed with something like `--set image.tag`, which often results in a version change of an application).

### PR DESCRIPTION
**Pull request by eraac**
When 'helm install/upgrade --app-version 1.0.0' is run, this will override the chart app version

Closes #3555

Signed-off-by: Kevin Labesse <kevin@labesse.me>

Waiting for your feedback, not 100% sure is the most efficient way do to that

### CODE REVIEW

**Comment by bacongobbler** [comment]
Hey, would you mind rebasing to ensure that the windows tests work? We fixed them up in #4897. Sorry for the trouble!

**Comment by benlangfeld** [comment]
It would be awesome to see this in the next version of Helm!

**Comment by thunder-spb** [comment]
+1 for this feature.
That's very useful for me, that will allow me to use same chart for several services which has only difference in name, application version, image and configs. Whole deployment procedure is the same...

**Comment by Eraac** [comment]
Any update? That really needed for our workflow

**Comment by Eraac** [comment]
@damienpuig resolve, thanks

**Comment by Eraac** [comment]
Running `helm ls` and see app version actually running can be very useful (visibility and easy to understand). But when you publish a chart (ex. mysql or any other public chart), changing app version has no sense

My use case (our? i guess, seeing reactions) is when you create private chart and don't want to package the same helm chart for one metadata 

Maybe we can found another way, obviously I am open to other solutions

**Comment by thunder-spb** [comment]
My case, I have common chart for all my apps. So all applications deployed via that one chart and the only differences between apps (from deployment perspective) are image name, application version. And since Chart kept separately I don't have ability or want change AppVersion with CI. I believe that .Chart.appVersion should have ability to be overriden via CLI.
I don't really want to create/put chart for each application :)

**Comment by Stono** [comment]
We have exactly the above use case, common chart for 100s of app deployment, want this feature mucho

**Comment by dhavalc26** [comment]
We too have the exact same case where we want to separate our docker image builds and helm charts...So that only when our code changes should result in change in docker image and not helm chart. It would be very great to see this feature

**Comment by Eraac** [comment]
@bacongobbler I understand initially `Chart.yaml` is immutable and my change will break this. Maybe we can add new field into `Chart.yaml`, allowing or not to override appVersion (or any other fields?) that can by false by default

**Review by bacongobbler — APPROVED** [review]
I have no alternative proposals on how to fix this, so I don't think we should be blocking the pragmatic solution from going forward.

@technosophos or @adamreese when either of you have a minute, would you mind taking a look at this and see if this seems like an okay approach to move forward?

**Comment by Eraac** [comment]
My bad ... destroying git history, i will create new pull request

**Pull request closed without merging**
