### PR TITLE
feat(dm install): use template to generate manifest

### LINKED ISSUE #306: Inject install.yaml into the helm binary prior to build

### PR DESCRIPTION
**Pull request by technosophos**
Closes #306.

### CODE REVIEW

**Comment by adamreese** [comment]
:heart: it

**Comment by jackgr** [comment]
LGTM

**Comment by technosophos** [comment]
Missed a dependency in the glide.yaml file. Fixed and pushed. Waiting for Travis now.

**Comment by runseb** [comment]
yep, much better than zipping the .yaml with the binary.

+1 LGTM

**Pull request merged**
