### PR TITLE
#8854 Reuse kube-client

### PR DESCRIPTION
**Pull request by janario**
Signed-off-by: Janario Oliveira <janario.oliveira@gmail.com>

**What this PR does / why we need it**:

Reuse kubeclient instance instead of creating a new connection each time

Fix for https://github.com/helm/helm/issues/8854

**Special notes for your reviewer**:

**If applicable**:
- [ ] this PR contains documentation
- [ ] this PR contains unit tests
- [ ] this PR has been tested for backwards compatibility

### CODE REVIEW

**Comment by bacongobbler** [comment]
Is there a risk where the client connection can go invalid in the time it's created to the time it's used? In other words, should there be a check to refresh the client connection?

**Comment by janario** [comment]
> Is there a risk where the client connection can go invalid in the time it's created to the time it's used? In other words, should there be a check to refresh the client connection?

That's a very nice point, I went to test it to make sure

So, I know my AWS EKS token lives for 15min

```
$ date
Do 15. Okt 20:40:44 CEST 2020
$ aws eks --region eu-central-1 get-token --cluster-name eks-cluster | jq
{
  "kind": "ExecCredential",
  "apiVersion": "client.authentication.k8s.io/v1alpha1",
  "spec": {},
  "status": {
    "expirationTimestamp": "2020-10-15T18:54:45Z",
    ...
}
```

So my scenario test:

* pre-install hook-1 blocks for 16min
* pre-install hook-2 blocks for 16min
* deployment
* post-install hook-3 blocks for 16min
* post-install hook-4 blocks for 16min

To make sure, I've built my helm binary with some logs when it is creating/reusing the client

```
$ /home/janario/go/src/github.com/helm/helm/bin/helm upgrade --install long-client --atomic -n janario --timeout 3h /home/janario/tmp/helm-bug/wait-reuse-client/
Create client 2020-10-15 20:44:46.262856095 +0200 CEST m=+0.039056608 
Reuse client 2020-10-15 20:44:46.262887628 +0200 CEST m=+0.039088100 
Release "long-client" does not exist. Installing it now.
Reuse client 2020-10-15 20:44:46.758814297 +0200 CEST m=+0.535014864 
Reuse client 2020-10-15 21:16:55.847978306 +0200 CEST m=+1929.624178818 
NAME: long-client
LAST DEPLOYED: Thu Oct 15 20:44:47 2020
NAMESPACE: janario
STATUS: deployed
REVISION: 1
TEST SUITE: None

$ date
Do 15. Okt 21:50:03 CEST 2020
```

And it worked fine :+1:

**Review by bacongobbler — APPROVED** [review]

**Review by mattfarina — APPROVED** [review]
lgtm

**Comment by cartucciam** [comment]
Can we revert this? by using the factory we'd be able to inject a token refresh. We are hitting a 20 minutes timeout with EKS while using this library in Go

**Comment by janario** [comment]
@cartucciam 

I guess the proper way would to understand it better and refresh the session under the same connection. 🤔

**Comment by janario** [comment]
We have been using it for the last 2 years as a library and as a normal helm cli. In both cases no issue.

So I guess it might have something specific with your scenario that would be great to be reported and fixed separately.

**Comment by cartucciam** [comment]
> We have been using it for the last 2 years as a library and as a normal helm cli. In both cases no issue.
> 
> So I guess it might have something specific with your scenario that would be great to be reported and fixed separately.

Thanks, have you got any open source code I can refer to? All I can think off is using the rest.Config.ExecProvider to shell out to aws cli but there must be a better way I am ignoring

**Pull request merged**
