### PR TITLE
Remove unneeded public APIs before going beta

### PR DESCRIPTION
**Pull request by thomastaylor312**
After talking with some of the other maintainers, we decided to move any libraries in `pkg` that were unlikely to be used by those consuming the SDK. This allows us more flexibility to refactor and expose those APIs later as needs arise without breaking backwards compatibility. This is a good first pass at moving things to `internal`. Let me know if there are any that shouldn't be there or if there are any I could move over.

The following packages were moved to internal:
- ~chartutil (consumers of the SDK should be using the `chart` package to load charts)~ (reverted)
- ignore
- resolver
- ~strvals~ (reverted)
- sympath
- tlsutil
- urlutil

In addition `pkg/version` has been removed. This package was a weird hodgepodge of old Helm 2 logic and a function that had been co-opted for chart use. The only used function has been moved to chartutil and the version build info has been moved to the internal version package.

Please note that most of these are renames, with a few small "campfire rule" changes I found along the way

### CODE REVIEW

**Comment by thomastaylor312** [comment]
Other possibilities for packages in internal:
- The storage drivers
- Releaseutil (if we think people won't be managing the actual release objects themselves)
- helmpath (since it is mostly used internally)

**Comment by bacongobbler** [comment]
From searching on github:

`pkg/chartutil` is [used fairly commonly across multiple use cases](https://github.com/search?q=k8s.io%2Fhelm%2Fpkg%2Fchartutil&type=Code), so it should probably be restored.

`pkg/ignore` is used mostly during custom chart loading, which I agree that users should use `pkg/chart` for that. I think we can get away with making it private. It does appear to be a useful package for others to use for writing their own ignore files, though, so I'm kinda torn about making this private.

`pkg/strvals` is used on occasion by several projects.

sympath was designed to be used by others as an more open alternative to facebookgo/symwalk so it should be made public. See https://github.com/helm/helm/pull/2938 for more context.

`tlsutil` and `urlutil` are useful packages so I don't see why we need to make them private.

I guess the question begs why do we need to make these packages private? They're being used by third parties in production so I don't see why they need to be made private. If anything users have been asking us to make packages MORE public (like in https://github.com/helm/helm/issues/5311).

**Comment by thomastaylor312** [comment]
So for sympath, {tls,url}util, and strvals, my question would be do we want to support APIs that are not directly related to Helm? That was my justification for many of those that I moved to internal. I guess that would also apply to these packages.

However, I am not in anyway attached to these ideas. We had just mentioned moving some things in to internal to keep the API surface more manageable

**Comment by thomastaylor312** [comment]
Please note I will squash all my commits before merge

**Review by bacongobbler — APPROVED** [review]

**Comment by bacongobbler** [comment]
nice refactors!

**Review by mattfarina — APPROVED** [review]
If we document charts v2 as a spec (something we have been asked to do) than the `ignore`  and  `resolver` packages may be useful for those who decide to develop other tools to interact with charts.  We can always move things out of internal after the v3 release if this becomes requested.

**Pull request merged**
