### PR TITLE
ref(repo): client uses public repo.Repo struct

### PR DESCRIPTION
**Pull request by michelleN**

### CODE REVIEW

**Comment by adamreese** [comment]
We should have a friendly message for no repositories.

```
% ./bin/helm repo list
Chart Repositories:
```

**Comment by adamreese** [comment]
Need to check arg count

```
% ./bin/helm repo show
panic: runtime error: invalid memory address or nil pointer dereference
```

**Comment by adamreese** [comment]
How do I add a repo?

``% ./bin/helm repo add --cred token-foo https://example.com/charts
panic: unexpected type string
```

**Comment by michelleN** [comment]
1. agreed on the friendly message. I'll edit that
2. repo show is not on MVP so I didn't implement it but I'll change the message to reflect that
3. We don't do credential management yet on repos. We're only supporting public ones.

**Pull request closed without merging**
