### PR TITLE
fix(tunnel): allow tunneling to non-default namespace

### PR DESCRIPTION
**Pull request by adamreese**
- remove `helm` as the default namespace
- support kubeconfig default namespace
- refactor install client

### CODE REVIEW

**Comment by technosophos** [comment]
This is good!

```console
☃ @ENG001590.local ~/Code/Go/src/k8s.io/helm «/Users/mattbutcher/Code» ‹fix/namespace-tunnel*›
⇒  helm init --namespace cheese
$HELM_HOME has been configured at /Users/mattbutcher/Code/helm_home.

Tiller (the helm server side component) has been installed into your Kubernetes Cluster.
Happy Helming!
☃ @ENG001590.local ~/Code/Go/src/k8s.io/helm «/Users/mattbutcher/Code» ‹fix/namespace-tunnel*›
⇒  k --namespace cheese get po
NAME              READY     STATUS    RESTARTS   AGE
tiller-rc-f0bjc   1/1       Running   0          8s
☃ @ENG001590.local ~/Code/Go/src/k8s.io/helm «/Users/mattbutcher/Code» ‹fix/namespace-tunnel*›
⇒  k --namespace helm get po
NAME                                             READY     STATUS    RESTARTS   AGE
oldfashioned-salamander-nginx-2735090007-ddwh0   1/1       Running   0          1h
tiller-rc-qzk14                                  1/1       Running   0          1h
☃ @ENG001590.local ~/Code/Go/src/k8s.io/helm «/Users/mattbutcher/Code» ‹fix/namespace-tunnel*›
⇒  helm install --namespace cheese docs/examples/alpine
/Users/mattbutcher/Code/Go/src/k8s.io/helm/docs/examples/alpine/.helmignore
intentional-turtle
☃ @ENG001590.local ~/Code/Go/src/k8s.io/helm «/Users/mattbutcher/Code» ‹fix/namespace-tunnel*›
⇒  k --namespace cheese get po
NAME                        READY     STATUS    RESTARTS   AGE
intentional-turtle-alpine   1/1       Running   0          5s
tiller-rc-f0bjc             1/1       Running   0          57s
```

**Comment by technosophos** [comment]
Would be nice to have a better error for this:

```
⇒  helm delete intentional-turtle                                                                                                                                                                       1 ↵
Error forwarding ports: error upgrading connection: the server could not find the requested resource
^C
☃ @ENG001590.local ~/Code/Go/src/k8s.io/helm «/Users/mattbutcher/Code» ‹fix/namespace-tunnel*›
⇒  helm delete --namespace cheese intentional-turtle
```

**Comment by technosophos** [comment]
Since that error is not part of the namespace change, marking this as LGTM

**Comment by errordeveloper** [comment]
Excellent, thanks @adamreese! I was just about to submit a PR doing a similar, yet more basic thing, but failed to rebase as you've just fixed exactly what I needed :)

**Pull request merged**
