### PR TITLE
Feature: allow custom description after helm release upgrade

### LINKED ISSUE #3581: Feature Request: Support for custom description after helm release upgrade
First of all, I would like to thank you all maintainers of Helm. Helm is really great and awesome in many ways.   👍   

------ 
Currently, after an upgrade for a release, Helm update the release description with : 
`updatedRelease.Info.Description = "Upgrade complete"`
> source : https://github.com/kubernetes/helm/blob/d6da76f3cfe0dae5a01fd5fec29ce7d6f57a1a52/pkg/tiller/release_update.go .   

While this behaviour is fine for most use cases, I suggest that we should enable users to choose their own description, so that the output of `helm history....` in the future may be more informative rather than the hard coded string `Upgrade complete`.  

By the way, this also makes the documentation look outdated. Intially, this string was `Upgraded successfully` (https://github.com/kubernetes/helm/blob/master/docs/helm/helm_history.md). To sum up, my wish is that this string could be more flexible.

### PR DESCRIPTION
**Pull request by adshmh**
Feat(helm): allow custom description after helm release upgrade. Fixes #3581 

 Signed-off-by: Arash Deshmeh <adeshmeh@ca.ibm.com>

### CODE REVIEW

**Review by thomastaylor312 — COMMENTED** [review]
This is really well done! I am thinking that for feature parity, we will want to add description to `rollback` and `delete` as well. Thoughts?

**Comment by adshmh** [comment]
@thomastaylor312  Thank you for the review. I can submit PRs for those two commands as well if needed.

**Comment by thomastaylor312** [comment]
@adshmh I think it would belong in this PR since it is the same feature. Are you ok with pushing another commit adding this for the two other commands?

**Comment by adshmh** [comment]
@thomastaylor312 sure, I just updated the PR to include `delete` and `rollback` commands as well.

**Review by thomastaylor312 — APPROVED** [review]
I apologize for the delay on this. I lost track of it. This is good to go pending another review

**Comment by adshmh** [comment]
Rebased the PR to resolve the conflicts. 
@bacongobbler would appreciate it if you could take a look.

**Review by luong-komorebi — APPROVED** [review]
Thank you. The code looks good and shall solve my issue.

**Review by bacongobbler — APPROVED** [review]
nice!

**Pull request merged**
