### PR TITLE
helm create all defined template names should be namespaced …

### PR DESCRIPTION
**Pull request by dhilipkumars**
As mentioned [here](https://docs.helm.sh/chart_best_practices/#names-of-defined-templates), the default chart created by `helm create` should contian namespaced template functions. 

```
$helm create foo
Creating foo
```

The helper function now looks like this
```
$cat foo/templates/_helpers.tpl
{{/* vim: set filetype=mustache: */}}
{{/*
Expand the name of the chart.
*/}}
{{- define "foo.name" -}}
{{- default .Chart.Name .Values.nameOverride | trunc 63 | trimSuffix "-" -}}
{{- end -}}

{{/*
Create a default fully qualified app name.
We truncate at 63 chars because some Kubernetes name fields are limited to this (by the DNS naming spec).
*/}}
{{- define "foo.fullname" -}}
{{- $name := default .Chart.Name .Values.nameOverride -}}
{{- printf "%s-%s" .Release.Name $name | trunc 63 | trimSuffix "-" -}}
{{- end -}}
```

[ref 1](https://github.com/kubernetes/charts/issues/1785)
[ref 2](https://github.com/kubernetes/helm/issues/2216)

### CODE REVIEW

**Comment by jascott1** [comment]
@dhilipkumars Thanks for doing this one. Im getting an error while testing:

```
$ helm create foo
Creating foo
$ helm install foo --dry-run --debug
[debug] Created tunnel using local port: '50990'

[debug] SERVER: "localhost:50990"

[debug] Original chart version: ""
[debug] CHART PATH: /Users/jascott1/projects/helmPR/2845/foo

Error: render error in "foo/templates/NOTES.txt": template: foo/templates/NOTES.txt:16:94: executing "foo/templates/NOTES.txt" at <{{template "name" .}...>: template "name" not defined
```

**Comment by dhilipkumars** [comment]
Hi @jascott1, Sorry for the delay in responding.  Could you please check now?

**Comment by bacongobbler** [comment]
Would you mind updating the documentation to match?

**Comment by dhilipkumars** [comment]
@bacongobbler Sure, i will. In a follow-up PR or this one?

**Comment by bacongobbler** [comment]
I think it'd be best to ahve the docs updated in this PR if it isn't too much trouble.

**Comment by dhilipkumars** [comment]
@bacongobbler PTAL or is there some other document i should be updating?

**Comment by bacongobbler** [comment]
Anywhere "fullname" is defined would be a good start.

https://github.com/kubernetes/helm/search?utf8=✓&q=fullname

**Comment by dhilipkumars** [comment]
@bacongobbler updated nginx example.

**Comment by unguiculus** [comment]
There's another example here: https://github.com/dhilipkumars/helm/tree/master/docs/examples/alpine

**Comment by dhilipkumars** [comment]
@unguiculus Done now. Sorry to have missed it.

**Review by bacongobbler — APPROVED** [review]
Considering that this doesn't break existing charts, this looks fine to me but I'd like someone else on the team to review as well. I don't feel confident enough that this PR is backwards-incompatible (someone may be writing tooling around `helm create`). Perhaps someone else would have a stronger opinion.

**Comment by dhilipkumars** [comment]
@bacongobbler could you `cc` those , that may be interested in this PR?

**Comment by unguiculus** [comment]
I'd love to see this merged soon so it can make it into the 2.7 release. Since all charts in the charts repo are currently being migrated to namespaced templates, this would increase the chance that new charts will already have this in the future. I don't see any backwards compatibility issues at all because it only affects newly created charts.

**Comment by dhilipkumars** [comment]
cc @technosophos , @adamreese and @michelleN.  Would be great to get some feedback on this long pending PR.

**Comment by bacongobbler** [comment]
I'll slate this for 2.7 discussion.

**Review by technosophos — APPROVED** [review]
As "formal defender of backwards compatibility", I'm stating for the record that this does NOT violate our backward compatibility guidelines since it only changes new charts (and changes them to what we've been telling people to do all along). :ship:

**Comment by davidkarlsen** [comment]
Should there be logic in the linter to make people aware of the change and move their charts forward?

**Comment by bacongobbler** [comment]
Yes, that would be a great feature request. Mind filing a new ticket for that? :)

**Pull request merged**
