### PR TITLE
#6013 Adding flag for helm search json output

### LINKED ISSUE #6013: Feature Request: JSON support for helm search
Presently, json is not supported by helm-search. Would like to be able to parse json to select/list versions of a particular chart.

### PR DESCRIPTION
**Pull request by artbegolli**
**What this PR does / why we need it**:

closes #6013 

**Special notes for your reviewer**:

**If applicable**:
- [ ] this PR contains documentation
- [x] this PR contains unit tests
- [ ] this PR has been tested for backwards compatibility

### CODE REVIEW

**Review by artbegolli — COMMENTED** [review]
- [x] Fix failing test

**Comment by mattfarina** [comment]
@artbegolli Thanks for the PR. Can you please sign your commits. We use a DCO. The checks tab at the top will provide instructions on signing the existing commits.

**Comment by artbegolli** [comment]
Will do, will have some time to resolve the failing test in the next couple of days as well

**Comment by artbegolli** [comment]
Closing - replaced with https://github.com/helm/helm/pull/6204

**Pull request closed without merging**
