### PR TITLE
Update RBAC best practices

### PR DESCRIPTION
**Pull request by unguiculus**
This revises our RBAC best practices based on a discussion that came up there: https://github.com/jetstack/cert-manager/pull/229.

cc @kubernetes/charts-maintainers @omkensey

### CODE REVIEW

**Comment by omkensey** [comment]
I don’t like using the “default” service account if `rbac.create` is false and no service account is specified — we should still generate a name then.  Our assumption in that case is that the user is either not using RBAC at all, or self-managing it.  In the latter case it doesn’t matter for RBAC purposes what service account name is used; in the former, a newly-generated account will be easier to manage later — a user wanting to give a chart-installed app specific permissions would have to either patch it to use a different account (that they have to generate themselves to boot), or grant the desired permissions to the default account (potentially dangerous).

If users *do* want to self-manage and use the default service account, that’s still easily done by setting `rbac.create` to false and the account name to “default”.

**Comment by omkensey** [comment]
Ah, you’re right.  That’s what I get for reading on mobile while distracted :)  Yes, this looks good to me.

**Comment by prydonius** [comment]
Thanks for writing this up @unguiculus!

/lgtm

**Comment by prydonius** [comment]
Thought this was in the charts repo and would automerge, my bad!

**Pull request merged**
