### PR TITLE
Wait for at least 1 replica for Deployments and Daemonsets

### LINKED ISSUE #8660: Wait logic doesn't wait for all deployment and daemonset pods to be updated/ready
I'm hitting a couple issues with the helm install/upgrade/rollback wait logic:

1. maxUnavailable is subtracted from the amount of pods that need to be ready when waiting for deployments and daemonsets. It seems to me that maxUnavailable is only about how to accomplish the update, and should not dictate when the update is considered complete. If there is only 1 replica and the default maxUnavailable of 1 is in place, then it will wait for 1-1 == 0 pods to be ready, which is not ideal.

2. status.observedGeneration is not accounted for, so this can lead to race conditions where the wait logic sees the pods from the old generation of the deployment or daemonset rather than the new one.
 
It looks like 1. came out of #5219 and a similar issue to 2. is mentioned there as well though it doesn't specifically mention observedGeneration ( cc @thomastaylor312 )

Since the wait logic does not reliably wait for all pods to be updated/ready it seems to be of limited use, and gives a false impression that the release is good to go. Would there be any interest in removing the maxUnavailable subtraction and/or adding a status.observedGeneration check?

### PR DESCRIPTION
**Pull request by seaneagan**
The wait logic for Deployments and Daemonsets subtracts their maxUnavailable
value from the amount of replicas they should have ready. This can lead to
waiting for 0 pods to be ready. This change ensures at least 1 replica is ready,
unless there are 0 total desired replicas.

Fixes #8660.

### CODE REVIEW

**Comment by bridgetkromhout** [comment]
Hi, @seaneagan! Thanks for working on this PR. I realize it is a work in progress, but please sign the DCO as explained in https://github.com/helm/helm/pull/8671/checks?check_run_id=1043117851 - thanks!

**Comment by bacongobbler** [comment]
Hi @seaneagan. We ask that contributors please either write a unit test to cover this scneario, or write up a set of steps maintainers can use to verify and test the behaviour is working as intended. This saves both us time having to write test cases for each incoming PR, and it saves you time waiting for us to write said test case.

**Comment by seaneagan** [comment]
@bacongobbler I don't see any automated tests for the wait logic, if I missed them let me know.

Below is a test case where the wait should fail due to none of the pods becoming ready due to `faults.unready=true`, but currently it doesn't as the [maxUnavailable is set to 1](https://github.com/stefanprodan/podinfo/blob/master/charts/podinfo/templates/deployment.yaml#L17) and replicaCount is set to 1, so it waits for 1-1=0 pods to be ready. With this PR the wait fails as it waits for 1 pod to become ready.

```
kubectl create ns test
helm repo add podinfo https://stefanprodan.github.io/podinfo
helm upgrade --install \
--wait \
--timeout 10s \
--namespace test \
--set replicaCount=1 \
--set faults.unready=true \
--debug \
podinfo \
podinfo/podinfo
```

**Comment by jon-depop** [comment]
Bump for this PR. @bacongobbler if you're satisfied with the test steps mentioned, it would be great to see this PR get merged. Thanks both!

**Comment by jon-depop** [comment]
@seaneagan do you have a PR for the observedGeneration race condition?

**Comment by seaneagan** [comment]
@bacongobbler Is there anything else I can do to move this PR along? Thanks!

**Comment by cbf123** [comment]
Just wondering if anyone was planning on ever merging this?  Last update was from a year ago.

**Comment by mattfarina** [comment]
@seaneagan I'm sorry it's taken so long for us to really look at this. Yikes. Is there any way you can rebase? There's a merge conflict.

**Comment by cbf123** [comment]
> @seaneagan I'm sorry it's taken so long for us to really look at this. Yikes. Is there any way you can rebase? There's a merge conflict.

Hi, I'm the guy that joined the weekly call.  I've rebased this change under https://github.com/helm/helm/issues/8660 after checking whether Sean was interested in reviving it or not.

**Comment by mattfarina** [comment]
Closing this PR as https://github.com/helm/helm/pull/10831 is where current work is at.

**Pull request closed without merging**
