### PR TITLE
fix occurences typo in charts.md

### PR DESCRIPTION
**Pull request by yanc0**

### CODE REVIEW

**Comment by bacongobbler** [comment]
hey @yanc0, for any contribution we ask that the user signs the CLA for legal reasons. Would you be able to do so? Thanks!

**Comment by yanc0** [comment]
I've already done that but I never received the confirmation email :(

image

**Comment by bacongobbler** [comment]
hmm. If you're having troubles, I'd shoot an email over to helpdesk@rt.linuxfoundation.org. They should be able to help sort you out.

**Comment by yanc0** [comment]
It seems ok now

**Review by bacongobbler — APPROVED** [review]

**Comment by bacongobbler** [comment]
thanks!

**Pull request merged**
