### PR TITLE
Added more output when `helm init`.

### PR DESCRIPTION
**Pull request by gyliu513**
Add more info for the repos that will be added when `helm init`.

Fixed issue https://github.com/kubernetes/helm/issues/2810

### CODE REVIEW

**Comment by gyliu513** [comment]
Anyone from helm team can help review? It has been pending for one week!

**Comment by jascott1** [comment]
@gyliu513 This PR is failing automated tests. It needs to be fixed before a final review.

**Comment by bacongobbler** [comment]
@sharno's PR at https://github.com/kubernetes/helm/pull/2928 seems to fix the issues present in this one (no io.Writer was passed into the functions). Shall we close this PR in favour of that one?

**Pull request closed without merging**
