### PR TITLE
[WIP] Fix lint in windows

### PR DESCRIPTION
**Pull request by karuppiah7890**
**What this PR does / why we need it**:
Fixes #6418 
Twin of #6523 which got closed due to branch renaming

**If applicable**:
- [ ] this PR contains documentation
- [ ] this PR contains unit tests
- [ ] this PR has been tested for backwards compatibility

### CODE REVIEW

**Comment by karuppiah7890** [comment]
@bacongobbler I'm not able to build the code due to the presence of `syscall.Umask` in the code, which is not available in windows.

```
pkg/plugin/installer/http_installer_test.go
217:    syscall.Umask(0000)
```

What do we do about this now?

**Comment by bacongobbler** [comment]
> What do we do about this now?

This is only in a unit test. We can probably skip the test when in a Windows environment, or make it Windows-compatible. your choice.

**Comment by karuppiah7890** [comment]
I've paused work on this, since it has been quite a bit of work, with windows VMs. I'll get back to this soon, and when I do, I'll post here, but if someone else is picking it up, that's fine too 😄

**Comment by karuppiah7890** [comment]
Currently, I'm working on #6155

**Comment by jdolitsky** [comment]
Closing as a duplicate of https://github.com/helm/helm/pull/6757

**Comment by karuppiah7890** [comment]
@jdolitsky this fix is actually for v2 and #6757 is for v3 😅

**Comment by jdolitsky** [comment]
whoops- reopening!

**Comment by karuppiah7890** [comment]
I'm closing this PR. For reasons similar to why I closed #6757 - https://github.com/helm/helm/pull/6757#issuecomment-652759452 

And one more thing to note is, this fix is for v2.x.y and the timeline for v2 support (bug fixes/security fixes) is small. If someone is creating a PR for this, do check if v2 is still supported by the maintainers and then do check this comment - https://github.com/helm/helm/pull/6757#issuecomment-652759452

**Pull request closed without merging**
