### PR TITLE
fix(helm): fix flag parsing during plugin loading

### PR DESCRIPTION
**Pull request by adamreese**

### CODE REVIEW

**Comment by bacongobbler** [comment]
does this fix an issue somewhere? I'm assuming that $HELM_HOME and --home when running plugins isn't working in certain cases?

**Comment by technosophos** [comment]
Yeah -- there is a case where invoking a plugin with flags is generating a spurious error

**Comment by technosophos** [comment]
@areese

```
⇒  helm plugin list
NAME    	VERSION	DESCRIPTION
gh      	0.1.0  	This plugin provides GitHub services to Helm.
last    	0.1.0  	get the last release name
template	2.4.1+2	Render templates on the local client.
☃ @ts ~/Code/Go/src/k8s.io/helm «/Users/technosophos/Code» ‹adamreese-fix/helm-home-plugins-again*›
⇒  helm gh
Error: unknown command "gh" for "helm"

Did you mean this?
	get

Run 'helm --help' for usage.
☃ @ts ~/Code/Go/src/k8s.io/helm «/Users/technosophos/Code» ‹adamreese-fix/helm-home-plugins-again*›
⇒  helm last                                                                                                                                                      1 ↵
Error: unknown command "last" for "helm"

Did you mean this?
	lint
	list
	test

Run 'helm --help' for usage.
```

Note that my Helm Home is 
```
⇒  helm home
/Users/technosophos/hh
```

**Comment by technosophos** [comment]
Oddly enough:

```
⇒  helm last --home $(helm home)
Error: unknown command "last" for "helm"

Did you mean this?
	lint
	list
	test

Run 'helm --help' for usage.
```

Also, I tested on a plugin that is in both $HELM_HOME and $HOME/.helm. That one worked because it launched the copy in $HOME/.helm

**Comment by technosophos** [comment]
Retested, and it's working with the following plugin scenarios:

- helm plugin list|install are working fine
- helm help is showing the plugins
- `helm PLUGIN SUBCOMMAND` works
- `helm PLUGIN --FLAG` works
- `helm PLUGIN SUBCOMMAND --FLAG` works

BUT....

- `helm --home $OTHERDIR PLUGIN` does not work. $HELM_HOME overrides `--home`.

```
⇒  helm --home fake last
maudlin-quokka
```

**Comment by adamreese** [comment]
closing in favor of #2690

**Pull request closed without merging**
