### PR TITLE
fix docs of DeployedAll

### PR DESCRIPTION
**Pull request by dastrobu**
**What this PR does / why we need it**:

Makes the docs conform to the implementation.

**Special notes for your reviewer**:

--

**If applicable**:
- [x] this PR contains documentation
- [ ] this PR contains unit tests
- [x] this PR has been tested for backwards compatibility

### CODE REVIEW

**Comment by sabre1041** [comment]
@dastrobu It appears that there are other instances in that file which need to be updated. Would you be able to update all occurrences that have misalignment between the documentation and the contents within each method?

Please advise if you would like each misalignment to be noted in detail

**Comment by dastrobu** [comment]
@sabre1041 thanks for your feedback. Let's hope I got all places this time (PR updated). Let me know if you find other occurrences that I still overlooked.

**Review by sabre1041 — APPROVED** [review]
LGTM

**Review by robertsirc — APPROVED** [review]
LGTM

**Review by mattfarina — APPROVED** [review]

**Pull request merged**
