### PR TITLE
Dejargonize "semver" in CONTRIBUTING.md

### PR DESCRIPTION
**Pull request by ghost**
Hi. I would like to elaborate the "Semver" jargon in this file. I am using `helm` at my job and would also like to craft `man helm`, to integrate the cloud with FOSS OS environments. I earned/have/purchased (naturally, I discover a variety of opinions) a Masters Degree in computer science, but there are still many principles unfamiliar to me, but jargon obfuscates. Thank you for reading.

### CODE REVIEW

**Review by bacongobbler — APPROVED** [review]

**Comment by bacongobbler** [comment]
hey @manglano! Thanks for the PR. Once you sign the CLA we'd be more than happy to merge this one in.

**Comment by bacongobbler** [comment]
Ping, any update on signing the CLA?

**Comment by manglano** [comment]
Sorry about that; the last few days were quite busy. I will sign the CLA
and ping you later today.

**Comment by sameersbn** [comment]
ping @manglano

**Comment by jstoja** [comment]
ping @manglano , for the CLA :)

**Comment by bacongobbler** [comment]
Closing as #3739 was merged.

**Pull request closed without merging**
