### PR TITLE
Walk symbolic link directories

### LINKED ISSUE #1639: Support symbolic directory links
To use different charts together as subcharts, it would be good to "import" their folders via symbolic directory links. Currently Helm returns: `Error: error reading charts/grafana read /Users/.../charts/grafana: is a directory`

### PR DESCRIPTION
**Pull request by balboah**
Continue walking symlinks to be able to use them
for sub-charts. Useful when not specifying requirements
but still want to share charts locally.

Closes #1639 and #3108

### CODE REVIEW

**Comment by balboah** [comment]
@k8s-ci-robot CLA signed

**Comment by balboah** [comment]
@k8s-ci-robot CLA signed

**Review by thomastaylor312 — APPROVED** [review]
I validated that this worked as well. Thank you for adding this back @balboah (and the unit test 😄)

**Comment by thomastaylor312** [comment]
@bacongobbler Before I merge I wanted to check if we wanted to include this in 2.7.1 since it was functionality we had to remove from 2.7

**Comment by vainikkaj** [comment]
It seems that 2.7.1 is already out. Hopefully there will be another bug fix release before 2.8.

**Comment by bacongobbler** [comment]
There are a few edge cases in this code that I'd like to take a closer look at. I'm confident that this works when the chart directory is a symlink, but I'd like to write a few unit tests first before we go ahead and merge this.

**Comment by bacongobbler** [comment]
I would slate this for v2.8 given that it's "old but new" functionality and given the confidence I have with the lack of unit tests around this function. Sorry!

I would also love to have this functionality polished up so that it's fleshed out in a separate package like `pkg/symwalk`. That way others can take advantage of this code in non-facebook codebases.

**Comment by technosophos** [comment]
I would really love to see this land for 2.8.0. Any possibility of getting it rebased and tested?

**Comment by balboah** [comment]
@technosophos @bacongobbler I already added the `TestDependentChartsWithSubChartsSymlink` which failed before changing the code. I read the previous code that was imported and I would expect it to behave the same. Are you suggesting to add a more functional test around the `symWalk` logic?
Moving it into a separate package is simple enough if that's a requirement.

**Comment by balboah** [comment]
@technosophos rebase and passed local `make test`

**Review by bacongobbler — APPROVED** [review]

**Comment by bacongobbler** [comment]
I've punted the refactoring work into #3195.

**Pull request merged**
