### PR TITLE
Fix helm plugins behavior another way

### LINKED ISSUE #9814: Confusing behavior between HELM_PLUGIN and HELM_DATA_HOME
Output of `helm version`: 3.5.2

A recent project required me to run Helm in a container with a persistent volume. My plan was to put `HELM_*_HOME` on the persistent volume and put `HELM_PLUGIN` to a file system in the image. I thought this would allow me create a Docker image with all the plugins preinstalled. Then, anything related to "transient" data like the added repos and their charts would be kept in `HELM_*_HOME` thus on the persistent volume. 

This did not work. `helm plugin install` writes plugins to `HELM_DATA_HOME/plugins`. This is unexpected because:

> $HELM_PLUGINS | set the path to the plugins directory

I assumed that `helm install` would write files to `HELM_PLUGINS`. That is not the case.

I dug around one of the plugins I'm using and found a [reference](https://github.com/jkroepke/helm-secrets/blob/main/plugin.yaml#L7) to `HELM_PLUGIN_DIR`. That led me to the [plugin docs](https://helm.sh/docs/topics/plugins/) which state:

> Plugins are installed using the $ helm plugin install <path|url> command. You can pass in a path to a plugin on your local file system or a url of a remote VCS repo. The helm plugin install command clones or copies the plugin at the path/url given into $HELM_PLUGINS

So my question is: what is the expected behavior here? If `HELM_PLUGINS` is set, then should all plugin installations go into that directory? If so, then why would files be written to `HELM_DATA_HOME`. 

I was able to reproduce this problem using a simple `Dockerfile`:

```Dockerfile
FROM alpine/helm:3.5.2

# uncomment this to fix the build
ENV HELM_PLUGINS=/var/lib/helm/plugins

RUN apk add git ncurses bash curl

RUN helm plugin install https://github.com/jkroepke/helm-secrets

# Fails with command not found
RUN helm secrets --version
```

The `docker build` fails with:

```
 => ERROR [4/4] RUN helm secrets --version                                                                                                                                                                      0.3s
------
 > [4/4] RUN helm secrets --version:
#7 0.257 Error: unknown command "secrets" for "helm"
#7 0.257 Run 'helm --help' for usage.
```

### PR DESCRIPTION
**Pull request by yxxhero**
Signed-off-by: yxxhero <aiopsclub@163.com>

**What this PR does / why we need it**:
fix: https://github.com/helm/helm/issues/9814 https://github.com/helm/helm/issues/9942
**Special notes for your reviewer**:

**If applicable**:
- [ ] this PR contains documentation
- [x] this PR contains unit tests
- [ ] this PR has been tested for backwards compatibility

### CODE REVIEW

**Review by technosophos — APPROVED** [review]
This looks correct to me.

**Review by mattfarina — COMMENTED** [review]
By using `cli.New()` is means other applications cannot use this package. It will them be coupled to helm environment variable names. The locations cannot be programmatically passed in.

I don't like this but I think it's a design issue we can't fix prior to Helm v4. I'll look a little more at it.

**Comment by yxxhero** [comment]
@mattfarina thanks very much. if you need me do some thing. please tell me.

**Comment by mattfarina** [comment]
I've added the topic of how we got here to the agenda for Thursdays meeting. If there are no other ideas in the short term, I think we can merge this.

**Comment by yxxhero** [comment]
ok. Thanks very much.

**Comment by mattfarina** [comment]
We talked about this is this past Helm developer call. We could not come up with a better way to fix this issue.

We also think we need to use a context or dependency injection in Helm v4 as a way to handle passing around some of the details in the future.

**Review by mattfarina — APPROVED** [review]

**Pull request merged**
