### PR TITLE
add bootstrap target when running make/make all

### PR DESCRIPTION
**Pull request by tariq1890**
For better DX.

### CODE REVIEW

**Comment by tariq1890** [comment]
Looks like a CircleCI. Requesting a re-run :).

**Review by hickeyma — CHANGES_REQUESTED** [review]
This is looking good to me, thanks. Just two small nits:
- Need an update on make in [install](https://github.com/helm/helm/blob/master/docs/install.md#from-source-linux-macos)
- In developers doc: "This will build both Helm and Tiller. make bootstrap will attempt to install certain tools if they are missing." Needs an update to something like "This will build both Helm and Tiller, and will attempt to install certain tools if they are missing."

**Comment by bacongobbler** [comment]
We intentionally did not add make bootstrap to the default make target because it's a one-off target. It doesn't need to be called every time you rebuild the client.

In dev-v3 we added it there because we have smarter detection for when make bootstrap was called and dependencies an update. If we had the same thing in place here then I'd be open to consist this.

**Comment by hickeyma** [comment]
@bacongobbler I had the same thinking.

I thought about this a bit more and a there are a number of usability errors caused by not calling `make bootstrap build`. I then thought the user will not want it to be called all the time but for this they could call `make build`. I suppose doing the `bootstrap` each time for a `make` call is inconvenient but does it balance out in favour of  dependency issues?

**Comment by tariq1890** [comment]
I agree with @hickeyma on this. By instinct I would call `make` or `make all` when I run a project for the first time. Any subsequent rebuilds would be done by a `make build`. That's pretty much the convention if I am not mistaken.

**Pull request closed without merging**
