### PR TITLE
Use kube libraries v0.20.4

### PR DESCRIPTION
**Pull request by sbose78**
Use kube libraries v0.20.4

### CODE REVIEW

**Review by hickeyma — COMMENTED** [review]
@sbose78 Thanks for updating. I am always little unsure of using beta versions.  Why not just use the last v0.20.x version?

**Comment by bacongobbler** [comment]
Agreed. Generally we wait until a stable release is available before updating.

**Comment by sbose78** [comment]
Makes sense! moved to 0.20.4.

**Review by hickeyma — APPROVED** [review]
LGTM, thanks @sbose78. Needs another maintainer to merge.

**Review by mattfarina — APPROVED** [review]

**Pull request merged**
