### PR TITLE
allow newer clients to talk to older tiller instances

### LINKED ISSUE #4547: Error: incompatible versions client[v2.9.1] server[v2.8.2]
Output of `helm version`: client - v2.9.1, server v2.8.2

Output of `kubectl version`: client :- v1.11.2, server:- v1.9.7
Cloud Provider/Platform (AKS, GKE, Minikube etc.): AKS

when I am trying with `helm ls --tiller-namespace=<namespace>` getting error like `Error: incompatible versions client[v2.9.1] server[v2.8.2]`. I am a mac book user (installed via brew) and not sure how to downgrade my client version of helm since could not get much help onto it through online. Kindly advise.

### PR DESCRIPTION
**Pull request by bacongobbler**
See discussion in #1523
Closes #4547

### CODE REVIEW

**Comment by technosophos** [comment]
So here's the deal with our relatively constrained version compatibility system: When we start getting different Kubernetes core libraries involved in the same validation/installation logic, things can get weird.

As we all well know, every single version of Kubernetes breaks compatibility with the previous version. Core APIs change, but so does validation logic, names of resources, apis, versions, and kinds, and all sorts of seemingly arbitrary bits of logic.

To protect ourselves from having disagreements between client and server as to what is "valid", we have forced client and server to have both the same major and minor version number.

We are 💯 sure, for example, that the "core" of Helm (gRPC, message formats, templates) are _backward_ compatible. They are not _forward_ compatible, though. It is possible that an additive change, which is allowed by SemVer on minor increment, could "pass" on the client and fail on the server. (Example: New template function, or the introduction of CRD support in 2.10)

So the nuanced answer is:

- We could allow cross-talk if the client's minor is `>=` Tillers, and that would be _somewhat risky_
- We could require only a major version match, and that would be _substantially risky_
- We could allow a client/Tiller minor version distance of, say, 2 (one must be within two minor releases of the other, in either direction), and that would be somewhat risky

Keep in mind that the result of removing the requirement introduces a substantial stability risk, and introduces combinatoric complexity to Helm environments. All of this will directly translate to support issues of the form "X is not working, and I'm running client version P and server version Q." 

If we want to accept the liability (increased workload, diminished stability), we can do that. I would prefer, though, to at _least_ emit a warning if the versions are different. Then it will show up in logs.

**Comment by bacongobbler** [comment]
We support older clients talking to newer versions of tiller, which is part of that backwards-compatible guarantees we make. The template function change/CRD support cases are very valid cases, so thank you for demonstrating an example that shows why we cannot support this.

I'm in favour of closing this out and not fixing this issue given that we have not made any guarantees towards maintaining forwards-compatibility.

**Comment by Overbryd** [comment]
Still an issue here, I am new to helm and **ran straight into that**:

```
Error: incompatible versions client[v2.10.0] server[v2.9.1]
Error: incompatible versions client[v2.10.0] server[v2.9.1]
```

This is definitely a big issue. A `minor` version should allow a newer client to interact with an older server.
I reckon everybody here is a sensible developer, but the current state of the cli does not follow sensible rules of software development. Backwards compatibility could be taken a little bit more seriously.

**Comment by Overbryd** [comment]
And I am going to explain my pain further:

So I have a small task to do, install a "chart" onto the cluster.
Ok, I need to downgrade my local version to match the `major.minor` version of whatever is running in my clients cluster.

I cannot (yet) upgrade the server, since I have not throughly checked the changes and I would probably need to force all my colleagues to upgrade their toolchain (maybe, because as I read you have compatibility the other way round figured out).

So I thought, hej, lets just drop the binary into its own folder and symlink the version that should be active.

And turns out the binary cannot execute if it symlinked or at least if it is not the same as in $PATH.

```
$ helm init
-bash: /usr/local/bin/helm: cannot execute binary file: Exec format error
$ readlink /usr/local/bin/helm
/usr/local/lib/helm/2.9.1/bin/helm
$ which helm
/usr/local/bin/helm
$ /usr/local/lib/helm/2.9.1/bin/helm
```

**Comment by bacongobbler** [comment]
> Regardless of the lengthy explanation, more care should be taking in favor of compatibility.

I can't help but feel pretty upset about this comment. Backwards compatibility is taken *very* seriously in Helm, which is why older versions of the client can talk to newer instances of Tiller. We take great care in ensuring that the client APIs are fully backwards compatible. You could've written a Javascript GRPC client library to interact with Tiller in Helm 2.0.0 and it would still work today.

What @technosophos is pointing out boils down to the fact that Kubernetes makes breaking API changes every minor release, and we cannot control that. The core message to take away from this is *loosening the restriction means we can no longer always guarantee compatibility*. If that is acceptable to the community (which I highly doubt), then we can loosen the restriction.

We can only begin to guarantee forwards compatibility once Kubernetes stops breaking core APIs.

**Comment by Overbryd** [comment]
> I can't help but feel pretty upset about this comment.

Sorry, didn't mean to upset you. Forgive my ignorance.

> Backwards compatibility is taken very seriously in Helm, which is why older versions of the client can talk to newer instances of Tiller.

That is what I might need to learn to accept, my expectation is the other way around.

**Pull request closed without merging**
