### PR TITLE
ref(*): update to Kubernetes 1.4

### PR DESCRIPTION
**Pull request by technosophos**
This starts with #1211 and does the other updates necessary for
bumping us to Kubernetes 1.4.

---

This change is [Reviewable](https://reviewable.kubernetes.io/reviews/kubernetes/helm/1236)

### CODE REVIEW

**Comment by technosophos** [comment]
This is currently broken because of conflicting `init()` methods in a few different packages.

**Comment by technosophos** [comment]
Switching to `glide install --strip-vendor` fixes most of the errors. Now I'm looking into something changed with the ConfigMap API.

**Comment by adamreese** [comment]
just need to delete line `pkg/kube/client_test.go:318` and it works

**Comment by technosophos** [comment]
OK. Manually testing this seems to work. I tried install, upgrade, delete, ls, and get.

**Pull request merged**
