### PR TITLE
Updated project governance

### PR DESCRIPTION
**Pull request by gabrtv**
This PR is designed to formalize a project governance structure. It is broken into two files:
- `MAINTAINERS.md` - outlining the types of maintainers on the project and their distinct responsibilities, including how the project is planned and prioritized
- `CONTRIBUTING.md` - outlining the process for for getting a PR merged into the project, including conventions and rules around standards and merge approval

It is important to point out the distinction between:
- Collaborators, developers who have commit access on the repo (including LGTM authority), and..
- Core maintainers, who help guide the project through planning and prioritization

Feedback much appreciated. /cc @jackgr @technosophos

Duplicate of #344.  Re-submitting PR to try and get past the CLA.

### CODE REVIEW

**Comment by jackgr** [comment]
Just need to solve the CLA issue.

**Comment by jackgr** [comment]
Closes #319.

**Comment by gabrtv** [comment]
@googlebot I signed it!

**Comment by jackgr** [comment]
Changing CLA to yes and merging per the CLA documentation, which states:
> It's okay to accept a contribution that you are certain is covered by a CLA

**Pull request merged**
