### PR TITLE
Fix: Ignore alias validation error for index load

### LINKED ISSUE #12735: helm dependency update failing to pull from JFROG but "helm pull" works just fine.
Output of `helm version`:
version.BuildInfo{Version:"v3.14.0", GitCommit:"3fc9f4b2638e76f26739cd77c7017139be81d0ea", GitTreeState:"clean", GoVersion:"go1.21.5"}

Output of `kubectl version`:
Client Version: v1.29.0

Cloud Provider/Platform (AKS, GKE, Minikube etc.): 
AWS

we just started seeing an issue this week with several of our helm charts when trying to build them our pipeline does a "helm dependency update"  We are pulling the images from a JFROG artifactory.

just this week we started getting errors saying:
Error: can't get a valid version for repositories external-secrets-refs, (..... other charts listed). Try changing the version constraint in Chart.yaml

but when I do a "helm dependency list" and "helm pull" I can manually pull each image individually with no issues.

I tried to see if this is an issue with JFROG and our IT department assures us that JFROG is working just fine and it appears so since I can pull all the images we need to get with "helm pull" commands.

I have tried multiple version of helm going back to version 3.10.2 and still we have issues with "helm dependency update" 

we are stuck at this point and don't understand why "helm dependency update" just started failing on most of our charts.

I don't know if there was some update to JFROG that changed the way that helm deals with it?

### LINKED ISSUE #12748: validation: more than one dependency with name or alias
With Helm `v3.14.0` the following use case is broken:

```
dependencies:
  - name: kube-rbac-proxy
    version: "0.9.1"
    repository: "<redacted>"
    alias: loki-query-proxy
    condition: loki-query-proxy.enabled
  - name: kube-rbac-proxy
    version: "0.9.1"
    repository: "<redacted>"
    alias: loki-ingestion-proxy
    condition: loki-ingestion-proxy.enabled
```

Various Helm commands (e.g. `helm dependency update`) now lead to the following error message:

`index.go:366: skipping loading invalid entry for chart "<redacted>" "1.3.0" from <redacted>: validation: more than one dependency with name or alias "kube-rbac-proxy"`

According to the [documentation for the Chart.yaml](https://helm.sh/docs/topics/charts/#the-chartyaml-file) using name twice with separate aliases seems to be valid:

> alias: (optional) Alias to be used for the chart. Useful when you have to add the same chart multiple times

The error was probably introduced with [this PR](https://github.com/helm/helm/pull/9176). With Helm `v3.13.2` it worked without any problems.

### PR DESCRIPTION
**Pull request by gjenkins8**
**What this PR does / why we need it**:

This PR skips the alias validation error introduced in https://github.com/helm/helm/pull/9176 when loading chart indexes. 
fixes: https://github.com/helm/helm/issues/12735
fixes: https://github.com/helm/helm/issues/12748

**Special notes for your reviewer**:
Checking the error type and string is super brittle. And IMHO super hacky. Happy for other suggestions. Without introducing a full "chart validation" type/interface, I didn't really see another (easy) option :(. But I do think we should attempt to not revert https://github.com/helm/helm/pull/9176 .

**If applicable**:
- [ ] this PR contains documentation
- [x] this PR contains unit tests
- [x] this PR has been tested for backwards compatibility

### CODE REVIEW

**Review by mattfarina — APPROVED** [review]

**Review by sabre1041 — APPROVED** [review]
LGTM. Confirmed contents of PR addresses error as described in this issue

**Review by mattfarina — APPROVED** [review]

**Comment by fad3t** [comment]
I see milestone was set to 3.14.2, but it was not released yet, right?

**Comment by Pobek** [comment]
> I see milestone was set to 3.14.2, but it was not released yet, right?

Milestone 3.14.2 is scheduled to be released by March 13, 2024. https://github.com/helm/helm/milestone/138

**Comment by erikgb** [comment]
> > I see milestone was set to 3.14.2, but it was not released yet, right?
> 
> 
> 
> Milestone 3.14.2 is scheduled to be released by March 13, 2024. https://github.com/helm/helm/milestone/138

Then what is this https://github.com/helm/helm/releases/tag/v3.14.2? 🧐

**Pull request merged**
