### PR TITLE
Add Helm/Tiller code

### PR DESCRIPTION
**Pull request by technosophos**
This mega-PR overwrites the older Helm (tagged 1.999.0) with the new Helm/Tiller codebase. While the Tiller codebase is still very much in development, all of the tests should be passing. Because the codebase is highly divergent, you may find it easier to review by simply going to the branch itself and looking at the code there. The GitHub diff view won't be too helpful.

### CODE REVIEW

**Comment by technosophos** [comment]
@adamreese @fibonacci1729 @michelleN -- can ya'll offer your sacrifice to the CLA bot so it will let us merge.

**Comment by adamreese** [comment]
CLA bot, you have my blessing.

**Comment by michelleN** [comment]
CLA bot, go forth with my permission.

**Comment by fibonacci1729** [comment]
CLA bot, permission granted.

**Comment by runseb** [comment]
@technosophos you merged a PR with 133 commits and 422 files changed in 16 hours ?
Might be good to have a community discussion somewhere, mailing list, hangout ?
explain what changed, what's the design ?

cc// @adamreese @michelleN @sparkprime @vaikas-google

**Pull request merged**
