### PR TITLE
fix `helm get manifest` context deadline exceeded error

### LINKED ISSUE #2409: "Error: context deadline exceeded" on GKE
I tried to install latest Helm (v2.4.1) on my fresh created GKE cluster (with k8s 1.5.7). and it give out error whenever I install any chart. Attached are the logging of my previous command execution.

```
~ gcloud container clusters get-credentials minidock --zone xxxxxx --project xxxxxx
Fetching cluster endpoint and auth data.
kubeconfig entry generated for minidock.
~ helm init
$HELM_HOME has been configured at /home/dick/.helm.

Tiller (the helm server side component) has been installed into your Kubernetes Cluster.
Happy Helming!
~ kubectl get po --namespace kube-system
NAME                                                            READY     STATUS    RESTARTS   AGE
fluentd-cloud-logging-gke-minidock-default-pool-9b0813ac-3zdz   1/1       Running   0          21m
heapster-v1.2.0.1-1244163626-jmtpv                              2/2       Running   0          21m
kube-dns-3475745875-ngw5q                                       4/4       Running   0          22m
kube-dns-autoscaler-2835134359-1z3hg                            1/1       Running   0          22m
kube-proxy-gke-minidock-default-pool-9b0813ac-3zdz              1/1       Running   0          22m
kubernetes-dashboard-3968242289-t3gpk                           1/1       Running   0          22m
l7-default-backend-2001230086-vt3n0                             1/1       Running   0          22m
tiller-deploy-3210876050-4p7sx                                  1/1       Running   0          20m
~ kubectl --namespace kube-system logs tiller-deploy-3210876050-4p7sx 
Starting Tiller v2.4.1 (tls=false)
GRPC listening on :44134
Probes listening on :44135
Storage driver is ConfigMap
~ helm install --debug stable/wordpress 
[debug] Created tunnel using local port: '34772'

[debug] SERVER: "localhost:34772"

[debug] Fetched stable/wordpress to wordpress-0.6.0.tgz

[debug] CHART PATH: /home/dick/wordpress-0.6.0.tgz

Error: context deadline exceeded
```

### PR DESCRIPTION
**Pull request by bacongobbler**
closes #2409

### CODE REVIEW

**Comment by xiangpengzhao** [comment]
Verified this patch in https://github.com/kubernetes/helm/issues/2409#issuecomment-374459782

:+1: :100:

**Comment by furuholm** [comment]
@bacongobbler Any hope to get this merged into 2.9.0?

**Comment by bacongobbler** [comment]
Yes this definitely needs to make it into 2.9. thanks for the ping.

**Review by thomastaylor312 — APPROVED** [review]
:shipit:

**Comment by benlangfeld** [comment]
Could this be cherry-picked and released as v2.8.3 also? v2.8.x hasn't had a working release yet.

**Comment by benlangfeld** [comment]
@bacongobbler Any word on this making progress. Helm 2.7 is the latest stable release at this point.

**Comment by bacongobbler** [comment]
No, we're not going to cut a 2.8.3 with this patch. We're currently testing the release candidates for v2.9 and it'll be available in v2.9.0

**Comment by benlangfeld** [comment]
The risk with that strategy is that 2.9.0 will include other breakage like each 2.8.x release did, preventing an upgrade. I don't understand what the reason for avoiding another 2.8.x release is, since none of the existing 2.8.x releases are functional.

Do you have a timeline for 2.9.0, or indeed an RC with this fix included?

**Comment by bacongobbler** [comment]
I'm in the process of releasing rc4. It should be available in an hour or so depending on CI.

**Comment by bacongobbler** [comment]
You can also test the canary releases which are cut from master: https://docs.helm.sh/using_helm/#from-canary-builds

**Comment by bacongobbler** [comment]
https://github.com/kubernetes/helm/releases/tag/v2.9.0-rc4

**Pull request merged**
