### PR TITLE
don't mark issues as stale where a PR is in progress

### PR DESCRIPTION
**Pull request by joejulian**
**What this PR does / why we need it**:

PR reviews take much longer than 90 days. Let's not nag issues that are labeled "in progress"

**Special notes for your reviewer**:

### CODE REVIEW

**Comment by marckhouzam** [comment]
I like the idea but what's the workflow difference between the "in progress" label compared to "keep open".

**Comment by joejulian** [comment]
It's mostly for convenience when I'm doing triage and support. There are things that you folks mark "keep open" as things you've found important for the project. I mark things "in progress" when there's a PR open so I can manage the help-wanted/good-first-issue labels as appropriate.

**Review by marckhouzam — APPROVED** [review]
Sounds good to me.

**Review by hickeyma — APPROVED** [review]
Nice idea @joejulian

**Pull request merged**
