### PR TITLE
fix(helm): filter helm list to print latest release

### LINKED ISSUE #3208: helm upgrade --install no longer works
As of helm v2.7.1, after updating tiller, running helm upgrade --install flag no longer works. The following error is displayed: Error: UPGRADE FAILED: "${RELEASE}" has no deployed releases. Downgrading to v2.7.0 or v2.6.2 does not produce the error.

### PR DESCRIPTION
**Pull request by adamreese**
`helm list` should only list latest release

fixes #3208

### CODE REVIEW

**Review by technosophos — APPROVED** [review]
LGTM. Adam and I discussed this solution at length, and I think this is the best way to fix 3208.

**Comment by rcorre** [comment]
This doesn't resolve the [inability to upgrade a deleted release](https://github.com/kubernetes/helm/issues/3208#issuecomment-356081377) mentioned in #3208. Should a separate issue be opened for that?

**Comment by AmazingTurtle** [comment]
@technosophos who are you to close #3208 based on your discussion with your colleague? At least provide information on how you came to that conclusion. Because @rcorre is right, the inabilities have not been fixed with that. Please consider reopening the issue #3208

**Comment by michelleN** [comment]
@technosophos is the founder of this project and @adamreese is a founding engineer. Both are also Helm org maintainers have been working on this project for years since and since its inception. Feel free to see our [governance](https://github.com/helm/community/tree/master/governance) document and our [MAINTAINERS](https://github.com/helm/community/blob/master/MAINTAINERS.md) document.

If you have a problem or would like further information, you can open a new issue. I'd also suggest you state your issues in a more respectful manner as our [code of conduct](https://github.com/cncf/foundation/blob/master/code-of-conduct.md#contributor-code-of-conduct) dictates.

**Pull request merged**
