### PR TITLE
Create new resource policy, "no-upgrade-existing"

### PR DESCRIPTION
**Pull request by michaelfig**
Signed-off-by: Michael FIG <michael@fig.org>

**What this PR does / why we need it**:

refs [charts #5167](https://github.com/helm/charts/issues/5167)

This annotation can be added to existing charts that created random passwords, and they will no longer modify the passwords on upgrade.

See the sample `secret.yaml` below for usage.

**Special notes for your reviewer**:

**If applicable**:
- [X] this PR contains documentation
- [ ] this PR contains unit tests
- [X] this PR has been tested for backwards compatibility

Not sure how to create a unit test: this is what I used for testing on my machine, after running `helm create helm-random-secret`

helm-random-secret/templates/secret.yaml
```yaml
apiVersion: v1
kind: Secret
metadata:
  name: {{ template "helm-random-secret.fullname" . }}
{{- if not .Values.somePassword }}
  annotations:
    "helm.sh/resource-policy": no-upgrade-existing
{{- end }}
  labels:
    app: {{ template "helm-random-secret.name" . }}
    chart: {{ template "helm-random-secret.chart" . }}
    release: {{ .Release.Name }}
    heritage: {{ .Release.Service }}
data:
  {{- if .Values.somePassword }}
  some-password: {{ .Values.somePassword | b64enc | quote }}
  {{- else }}
  some-password: {{ randAlphaNum 10 | b64enc | quote }}
  {{- end }}
```

t.sh:
```sh
RELEASE=t
CHART=helm-random-secret
PATH="$HOME/go/src/k8s.io/helm/bin:$PATH"
helm version
helm delete --purge $RELEASE
echo "=== Expect deleted"
kubectl get secret $RELEASE-$CHART -oyaml | sed -ne 's/^ *some-password: //p' | base64 -D
echo; read
helm upgrade -i $RELEASE ./$CHART
echo "=== Expect secret"
kubectl get secret $RELEASE-$CHART -oyaml | sed -ne 's/^ *some-password: //p' | base64 -D
echo; read
helm upgrade -i $RELEASE ./$CHART
echo "=== Expect same"
kubectl get secret $RELEASE-$CHART -oyaml | sed -ne 's/^ *some-password: //p' | base64 -D
echo; read
helm upgrade -i $RELEASE --set somePassword='mystring' ./$CHART
echo "=== Expect mystring"
kubectl get secret $RELEASE-$CHART -oyaml | sed -ne 's/^ *some-password: //p' | base64 -D
echo; read
helm delete --purge $RELEASE
echo "=== Expect missing"
kubectl get secret $RELEASE-$CHART -oyaml | sed -ne 's/^ *some-password: //p' | base64 -D
```

### CODE REVIEW

**Comment by bacongobbler** [comment]
Hey there. Thanks for the PR.

I'm curious to know what's the difference between this and wrapping the whole object in a `{{ if .Release.IsInstall }}`? I'm pretty sure this capability is already possible today without needing to make any changes to Helm.

**Comment by michaelfig** [comment]
I tried that, but helm will delete the resource on upgrade.

**Comment by msvticket** [comment]
As a curious bystander I have a question:
Do this PR have any effect when running "helm template"?

**Comment by michaelfig** [comment]
@msvticket, `helm template --help` says:

> This does not require Tiller. However, any values that would normally be
looked up or retrieved in-cluster will be faked locally.

The `no-upgrade-existing` needs to find resources by looking them up in-cluster, and I haven't implemented any "local faking" for it, so no, there is no effect when running `helm template`.

**Comment by bacongobbler** [comment]
Ah yes, forgot about that. Sorry!

What about a pre-install hook instead? If I recall, this should work without an issue (and solve the same use case as described):

```
apiVersion: v1
kind: Secret
metadata:
  name: {{ template "helm-random-secret.fullname" . }}
{{- if not .Values.somePassword }}
  annotations:
    "helm.sh/hook": "pre-install"
{{- end }}
  labels:
    app: {{ template "helm-random-secret.name" . }}
    chart: {{ template "helm-random-secret.chart" . }}
    release: {{ .Release.Name }}
    heritage: {{ .Release.Service }}
data:
  {{- if .Values.somePassword }}
  some-password: {{ .Values.somePassword | b64enc | quote }}
  {{- else }}
  some-password: {{ randAlphaNum 10 | b64enc | quote }}
  {{- end }}
```

That hook will render the secret before any resources are created in Kubernetes, and will not be updated during a `helm upgrade`.

Have you tried that before, and if so, what difference does this annotation provide vs. the pre-install hook?

**Comment by michaelfig** [comment]
@bacongobbler The difference between `no-upgrade-existing' and the pre-install hook is that the user can explicitly set the password at any time in my example, and that will upgrade the secret (and a subsequent upgrade will not touch the secret unless it is manually deleted or again explicitly set), as well as automatically deleting the secret on a helm delete.

**Comment by bacongobbler** [comment]
I'm confused about the use case...

> the user can explicitly set the password at any time in my example

The use cases provided in https://github.com/helm/charts/issues/5167 has been

1. When I install a chart, I want a password generated for me, which is then persisted and should not change.
2. As a chart user, I want to be able to set that password during `helm install`, which is then persisted and should not change.

Both the examples shown with `pre-install/hook-delete-policy` and `no-upgrade-existing` solve that use case. What I don't understand is why would you want to install a chart with a password that gets changed every time you call `helm upgrade`, then override and lock it in place? Why wouldn't you want to just lock it in place the first time the chart is installed?

**Comment by bacongobbler** [comment]
Okay, I'm starting to see the use case now. So essentially it's kind of "pinning" an object to its state. Thank you. I'll have another look.

**Comment by michaelfig** [comment]
Would `pin-existing` be a better name?  
Also, what if the chart wants both this policy and also `keep`?  Should resource policies be comma-separated?

**Comment by bacongobbler** [comment]
`pin` might be a better name. It's a common term used in package management to pin an object at a certain point in time.

**Comment by michaelfig** [comment]
I think `pin` is counterintuitive, as it doesn't pin the resource you add the annotation to, rather just prevents the annotated resource from overriding the existing one, just for this particular helm run.

**Comment by bacongobbler** [comment]
related discussion: https://github.com/helm/helm/issues/3053#issuecomment-422945888

**Comment by michaelfig** [comment]
Okay, I can get behind this.  So to solve my use case, a new chart could have a pre-upgrade hook to add the "pin" annotation to existing secrets that it doesn't want to upgrade.

**Review by FrenchBen — APPROVED** [review]
LGTM! Can't wait to see this in the next release.

**Comment by michaelfig** [comment]
@FrenchBen, @bacongobbler will this be merged?

Thanks,
Michael.

**Comment by bacongobbler** [comment]
Right now I'm focusing on getting 2.13.0 out the door and primarily focusing on Helm 3 core development work. When I have more time I will get back to this, but for now I don't have the time to review. Sorry!

@FrenchBen's input is appreciated but he is not a core maintainer. It needs an LGTM from a core maintainer before it can be merged. :)

**Comment by cgetzen** [comment]
Would this work if we wanted to update one field in the resource, but not another (say a randomly generated ID or password)?

**Comment by michaelfig** [comment]
@cgetzen, sorry but no, subsets of a resource are not kept.

The current patch is all-or-nothing.

**Comment by asychev** [comment]
Is there any ETA for merging this?

**Comment by bacongobbler** [comment]
No ETA. I've been focusing more recently on security fixes for Helm 2 as well as ongoing development for Helm 3 so I have not been able to give this PR the time to think through the design.

If others could actually test this PR out and give it some feedback, that would be very helpful. I'm concerned that it might not solve the use cases in helm/charts#5167, so feedback from users running this in staging/production would be more helpful moving this forward.

**Comment by bacongobbler** [comment]
It only checks the "target" (the chart you are upgrading to) for the "pin" annotation. As soon as the annotation is removed from the template on a `helm upgrade`, the "pin" is lifted. A very simple use case where this won't work is with rollbacks. If you roll back to an older release that did not have that pin annotation, it will roll back rather than pinning to the old template. That probably isn't the desired behaviour.

**Comment by bacongobbler** [comment]
IMO it should be a "set and forget" setting that occurs outside of the update logic. Helm should mark the *existing* resource as "pinned", and no updates will change it. The user must manually intervene (i.e. remove the annotation from the resource) to allow updates.

**Comment by bacongobbler** [comment]
Closing as this is [not the right approach](https://github.com/helm/helm/pull/5290#issuecomment-526988334) for the problem. If someone wants to implement a PR as well as the supporting documentation that covers the approach described [here](https://github.com/helm/helm/pull/5290#issuecomment-526988755) for Helm 3, that'd be great. Helm 2.15.0 is the last feature release for Helm 2 so we are no longer accepting new features in Helm 2.

**Pull request closed without merging**
