### PR TITLE
Fixing linter typos

### LINKED ISSUE #913: "templates" vs "Templates"
The linter says it cannot find the "Templates" (uppercase) directory. We should make that "templates" since file systems can be case sensitive.

```
helm [master]$ bin/helm create mychart
Creating mychart
mychart [master*]$ ls
Chart.yaml	charts		templates	values.yaml
helm [master*]$ bin/helm lint mychart
Lint OK
helm [master*]$ rm -rf mychart/templates/
helm [master*]$ bin/helm lint mychart
[WARNING] Templates directory not found
helm [master*]$

helm [master*]$ cd mychart/
mychart [master*]$ ls
Chart.yaml	charts		values.yaml
mychart [master*]$ mkdir Templates
mychart [master*]$ cd ..
helm [master*]$ bin/helm lint mychart
Lint OK
```

cc/ @migmartri @technosophos

### PR DESCRIPTION
**Pull request by migmartri**
Closes #913

### CODE REVIEW

**Comment by migmartri** [comment]
For some reason the tests are failing. Adnan and I might have added a regression when we landed two overlapping features.

**Comment by migmartri** [comment]
It seems that tests are failing even in master. 

```
=== RUN   TestBadValues
--- FAIL: TestBadValues (0.00s)
panic: assignment to entry in nil map [recovered]
        panic: assignment to entry in nil map

**Comment by migmartri** [comment]
Tests failing in master. Discussing it here https://github.com/kubernetes/helm/issues/918

**Comment by technosophos** [comment]
Okay, I got #918 fixed, so if you rebase and push this change it should pass CI

**Comment by migmartri** [comment]
Thanks, it passed. Waiting for review now.

**Pull request merged**
