### PR TITLE
Fix curl error Failed writing body

### LINKED ISSUE #2802: curl: (23) Failed writing body
The `curl` call within the script *sometimes* (not always) throws an error:
```
# curl -sSLO https://raw.githubusercontent.com/kubernetes/helm/master/scripts/get
# chmod +x get
# ./get
curl: (23) Failed writing body (0 != 1370)
Downloading https://kubernetes-helm.storage.googleapis.com/helm-v2.5.1-linux-amd64.tar.gz
```
Due to curl writing to a pipe that is closed by `head -n 1` before all content is written:
```
TAG=$(curl -SsL $release_url | awk '/\/tag\//' | head -n 1 | cut -d '"' -f 2 | awk '{n=split($NF,a,"/");print a[n]}')
```

The curl maintainer [suggests to silence the error](http://thread.gmane.org/gmane.comp.web.curl.general/14941) due to the closing pipe with `curl -sL`, but this has the side effect of removing all error output.

Another suggestion of the `--no-buffer` option does not work.
Ignoring the content length with `--ignore-content-length` does not work.

### PR DESCRIPTION
**Pull request by hobti01**
Do not close the pipe early, output only the first version found.  wget command changed for consistency.
Fixes #2802

### CODE REVIEW

**Comment by thomastaylor312** [comment]
@hobti01 This looks like a pretty simple fix, but I am not sure how to duplicate the issue for testing based on #2802. Is there anything you were able to do to get you a consistent error?

**Comment by hobti01** [comment]
@thomastaylor312 No, I could not get 100% reproduction unfortunately.  The error seemed to happen about 1/3 of the time.

**Comment by technosophos** [comment]
Oh, that's an interesting one. I would be fine with merging this PR, since it can't hurt. But since @thomastaylor312 started the review, I'll leave it up to him.

**Comment by thomastaylor312** [comment]
I am going to run a quick sanity check test tonight and merge

**Review by thomastaylor312 — APPROVED** [review]
This looks good. Thank you for the fix!

**Pull request merged**
