### PR TITLE
fix: plugin does not load when helm base dir contains space

### LINKED ISSUE #10884: If $HELM_DATA_HOME contains spaces, plugins stop working
Output of `helm version`:
version.BuildInfo{Version:"v3.8.1", GitCommit:"5cb9af4b1b271d11d7a97a71df3ac337dd94ad37", GitTreeState:"clean", GoVersion:"go1.17.8"}

If `HELM_DATA_HOME` contains spaces, like `/Users/My Name/Library/helm` or `C:\Users\My Name\AppData\Roaming\helm`, no plugins can be executed.

Error:

> Error: fork/exec /Users/My: no such file or directory

> 'C:\Users\My' is not recognized as an internal or external command,
operable program or batch file.

Helm manually splits the command by space:

https://github.com/helm/helm/blob/699ea6dcef302d7ded608bc8a1ab6c404de81685/pkg/plugin/plugin.go#L152
https://github.com/helm/helm/blob/699ea6dcef302d7ded608bc8a1ab6c404de81685/pkg/plugin/plugin.go#L124-L129

### PR DESCRIPTION
**Pull request by sureshdsk**
Signed-off-by: Suresh Kumar <sureshdsk91@gmail.com>

**What this PR does / why we need it**:
closes #10884 
bug: plugin does not work when HELM_DATA_HOME directory path contains spaces
solution:
existing method expands env variable and then splits command sequence by space. if the path contains space, results in error. so expanding just before executing the command fixes the issue. 

**If applicable**:
- [ ] this PR contains documentation
- [x] this PR contains unit tests
- [ ] this PR has been tested for backwards compatibility

### CODE REVIEW

**Comment by jkroepke** [comment]
Did you forget 

https://github.com/helm/helm/blob/699ea6dcef302d7ded608bc8a1ab6c404de81685/pkg/plugin/plugin.go#L152

?

I guess, someone would ask for unit tests here.

**Comment by yxxhero** [comment]
@sureshdsk Thanks very much. need some unittest for this pr.

**Comment by sureshdsk** [comment]
@yxxhero I've added tests. can you take a look?

**Comment by sureshdsk** [comment]
@yxxhero its been a while. just following up. do you want review it or assign the code review to someone?

**Review by joejulian — APPROVED** [review]
This looks good to me, but I'm not a maintianer.

**Review by mattfarina — APPROVED** [review]

**Pull request merged**
