### PR TITLE
Added List mode for Role, ClusterRole and Bindings

### PR DESCRIPTION
**Pull request by sebosp**
Install and Uninstall Order for List Kinds
**What this PR does / why we need it**:
Kubernetes supports RoleList, RoleBindingList, ClusterRoleList and ClusterRoleBindingList, in order for a Role to be bound, it must already exist, for the List references, see: https://github.com/kubernetes/kubernetes/blob/master/pkg/apis/rbac/types.go

@hickeyma @SlickNik refs #5267 #5268

### CODE REVIEW

**Review by hickeyma — CHANGES_REQUESTED** [review]
This is looking good @sebosp, thanks. Do you mind adding tests to https://github.com/helm/helm/blob/master/pkg/tiller/kind_sorter_test.go ?

**Comment by sebosp** [comment]
Sure @hickeyma , lemme know if anything else is missing.

**Review by hickeyma — COMMENTED** [review]
Thanks @sebosp for adding the tests. Would you be able to provide examples of manifests using different 'List' resources like 'RoleList' etc.? I was unable to find any when I wanted to do some manual testing.

**Comment by sebosp** [comment]
Hmm I started adding them because prometheus-operator used them, but I don't see them as used anymore...
Some examples:

```
apiVersion: rbac.authorization.k8s.io/v1
kind: RoleBindingList
items:
- apiVersion: rbac.authorization.k8s.io/v1
  kind: RoleBinding
  metadata:
    name: prometheus-k8s
    namespace: monitoring
  roleRef:
    apiGroup: rbac.authorization.k8s.io
    kind: Role
    name: prometheus-k8s
  subjects:
  - kind: ServiceAccount
    name: prometheus-k8s
    namespace: monitoring
```

```
apiVersion: rbac.authorization.k8s.io/v1
items:
kind: RoleList
- apiVersion: rbac.authorization.k8s.io/v1
  kind: Role
  metadata:
    name: prometheus-k8s
    namespace: monitoring
  rules:
  - apiGroups:
    - ""
    resources:
    - nodes
    - services
    - endpoints
    - pods
    verbs:
    - get
    - list
    - watch
```

Apparently they were removed 21 days ago from prometheus-operator:
- https://github.com/helm/charts/blob/d891e2571360a3e5a42b5d3ad936fd008fd61b90/stable/prometheus-operator/templates/prometheus/rolebinding-specificNamespace.yaml
- https://github.com/helm/charts/blob/d891e2571360a3e5a42b5d3ad936fd008fd61b90/stable/prometheus-operator/templates/prometheus/role-specificNamespace.yaml

**Review by hickeyma — APPROVED** [review]
@sebosp LGTM, thanks for your efforts. Before I merge, can you squash the changes?

**Comment by sebosp** [comment]
I have tried to squash them @hickeyma please let me know if anything else, thanks for your patience and guidance :)

**Comment by hickeyma** [comment]
@sebosp Do you mind doing a PR for the `dev-v3` branch for this?

**Comment by sebosp** [comment]
Sure @hickeyma, please take a look at #6100

**Pull request merged**
