### PR TITLE
Add tests to `helm/pkg/kube/client_test.go` to cover `wait.go`

### LINKED ISSUE #13417: Increase unit test coverage for wait.go
Increase unit test coverage of helm/pkg/kube/wait.go

Output of `helm version`: 3.16.2

Output of `kubectl version`: N/A

Cloud Provider/Platform (AKS, GKE, Minikube etc.):  N/A

### PR DESCRIPTION
**Pull request by alex-kattathra-johnson**
**What this PR does / why we need it**:
fixes: #13417

**Special notes for your reviewer**:

**If applicable**:
- [ ] this PR contains user facing changes (the `docs needed` label should be applied if so)
- [x] this PR contains unit tests
- [ ] this PR has been tested for backwards compatibility

### CODE REVIEW

**Comment by robertsirc** [comment]
Why is this in client_test.go rather than creating a wait_test.go?

**Comment by robertsirc** [comment]
I am ok with it being done at the client level. I am looking for test coverage for every func in this whole folder because I want to refactor it when helm 4 development starts.

**Comment by alex-kattathra-johnson** [comment]
The coverage for the `helm.sh/helm/v3/pkg/kube` module goes from  47.6% to 57.1% with these added tests!

**Review by robertsirc — APPROVED** [review]
LGTM

**Pull request merged**
