### PR TITLE
Add constructor for setting ValueOptions.rawValues from map

### PR DESCRIPTION
**Pull request by rudoi**
**What this PR does / why we need it**:

This PR adds a constructor function that allows a ValueOptions object to be created from a map.

**Special notes for your reviewer**:

**If applicable**:
- [ ] this PR contains documentation
- [ ] this PR contains unit tests
- [ ] this PR has been tested for backwards compatibility

### CODE REVIEW

**Review by thomastaylor312 — APPROVED** [review]
LGTM

**Review by hickeyma — COMMENTED** [review]
@rudio what is the use case for the function?

**Comment by rudoi** [comment]
@hickeyma I believe this provides a way to build ValueOptions that is more friendly for those consuming Helm packages as libraries. I would like to deploy charts from within a CRD controller. Right now, the interfaces provided allow me to pass in a slice of file paths or a slice of key=value strings.

It would be preferable if I could supply an unstructured map[string]interface{} and build a ValueOptions from that.

**Review by hickeyma — APPROVED** [review]
@rudoi LGTM, thanks.

**Pull request merged**
