### PR TITLE
Fix packaging of multiple versions of same dependency

### PR DESCRIPTION
**Pull request by jpninanjohn**
Signed-off-by: Ninan John <jninan@thoughtworks.com>

**What this PR does / why we need it**:
Closes this issue -> https://github.com/helm/helm/issues/5866
Fix:
Added a flag that appends the version to the filename when packaging into a tarball for dependencies.

**Special notes for your reviewer**:
I have added a test to check if the tarball has all the versions of the same dependencies. 

**If applicable**:
- [ ] this PR contains documentation
- [x] this PR contains unit tests
- [ ] this PR has been tested for backwards compatibility

### CODE REVIEW

**Comment by tamalsaha** [comment]
@jpninanjohn , please see the relevant discussion here: https://kubernetes.slack.com/archives/C51E88VDG/p1561059858120100

It seems that you need to target this for Helm 3 and handle various cases that @bacongobbler  mentioned in slack.

**Comment by bacongobbler** [comment]
With this fix, does it allow you to install both versions in one `helm install`? What's the use case for having two versions of the same dependency managed in a single release object? Won't the objects from both charts collide with each other?

**Comment by karuppiah7890** [comment]
@bacongobbler about the use case for two versions - our team works with lot of charts to deploy components needed for a service. So, for example, for service A, there will be a chart with no templates but multiple dependencies in requirements yaml, like redis chart, postgres chart. And if the service needs more than one redis or postgres, we will have multiple redis and postgres charts, with different aliases. It also usual where a team creating the service wants to add another new redis for some new feature and when we add it to requirements, if the latest redis chart has changed with some new features, possibly breaking too, we still have to add it. The reason for not upgrading the chart version of existing redis dependencies when adding a latest version redis chart - well, it depends, based on the effects of the upgrade. For example
1. If the upgrade is a breaking change, it's quite some work and we might want to put it off for later to upgrade all the old chart versions in all the service components charts and make necessary changes for the breaking change, and possibly try to automate it
2. If the change causes changes in the K8s resources that it will cause a restart of pods. We might want to not do this - as it will cause some downtime which we may want to postpone it for the night based on need.

With the current issue of having only one version of a chart in all the instances in the dependencies, we are forced to use only one version (either old or new). I feel the users should not be forced to do so

**Comment by bacongobbler** [comment]
> And if the service needs more than one redis or postgres, we will have multiple redis and postgres charts, with different aliases

Aliases only change the name of the package on-disk but doesn't affect the templates themself when being rendered as far as I remember. redis-1 and redis-2 will still collide as far as I can remember.

I need to do some testing first to bring myself back up to speed; it's been a while since I've played with chart aliases.

**Comment by karuppiah7890** [comment]
And that's the issue. Currently the different versions of the same chart
are put together in a single folder inside the charts dir and like you said
they collide. Instead we want them to be separate

**Comment by jpninanjohn** [comment]
@bacongobbler I tried a `helm install` with the fix and it does install 2 different versions of the specified chart. The usecase is as @karuppiah7890 mentioned.

**Comment by hickeyma** [comment]
@jpninanjohn Thanks for your work on this PR. 

I am unsure that the changes are in alignment with how dependencies are designed to work. I understand that it fixes a use case you have but not sure of the side effects of such a change. 

Taking into account that Helm 2.15 is near to release, it might be better considering this for Helm 3 instead? That way there would be more time to review the change and any consequences.

@bacongobbler @thomastaylor312 What do you think?

**Comment by bacongobbler** [comment]
I agree, @hickeyma. After closer review, I noticed that this is actually introducing a new use case that originally was not accounted for, hence the change from `bug` to `feature`. The dependency resolver has not before had to resolve two identical dependencies with differing versions before, and I'm concerned that the use case described here is not something we've carved out a good story for.

I am +1 on pushing this out to Helm 3. That way we can give this use case a more properly thought-out review and determine if there are edge cases we may be missing.

**Comment by bacongobbler** [comment]
Closing as we've cut Helm 2.15 and will no longer be accepting feature requests for Helm 2. Thanks!

**Pull request closed without merging**
