### PR TITLE
docs(governance): add maintainers.md and modify contributing guidelines

### PR DESCRIPTION
**Pull request by gabrtv**
This PR is designed to formalize a project governance structure.  It is broken into two files:
1. `MAINTAINERS.md` - outlining the types of maintainers on the project and their distinct responsibilities, including how the project is planned and prioritized
2. `CONTRIBUTING.md` - outlining the process for for getting a PR merged into the project, including conventions and rules around standards and merge approval

It is important to point out the distinction between:
- **Collaborators**, developers who have commit access on the repo (including LGTM authority), and..
- **Core maintainers**, who help guide the project through planning and prioritization

Feedback much appreciated. /cc @jackgr @technosophos

### CODE REVIEW

**Comment by gabrtv** [comment]
I signed it!

**Comment by jackgr** [comment]
Looks great. Thanks, @gabrtv!

One thing that would be helpful to add to the first document is a section that contains something like the following:

## Order of Development
The team uses a combination of milestones and priority labels on Github issues to help development flow smoothly. While exceptions may be required on occasion, the team observes the following guidelines:
* PRs should only be submitted for issues in the current milestone. PRs for other milestones will not be reviewed or merged until the milestone for the issue(s) they address has started.
* PRs should be submitted more or less in issue priority order, with the caveat that because different issues may take different amounts of time to work, PRs may arrive out of order at times. However, lower priority PRs may not be reviewed or merged until higher priority PRs have been processed, and the review or merging of lower priority PRs may be interrupted by the arrival of higher priority PRs.

**Comment by gabrtv** [comment]
@jackgr good call.  Added that language to contributing guidelines above "How to Contribute a Patch".  Only change was `s/team/project/`.

**Comment by jackgr** [comment]
@gabrtv Wondering why the close. Are you resubmitting w/EngineYard email address for googlebot CLA check?

**Pull request closed without merging**
