### PR TITLE
refactor: use os instead of ioutil's ReadDir

### LINKED ISSUE #9926: refactor all use of ioutil.ReadDir
From the Go docs on ioutil.ReadDir:

> As of Go 1.16, os.ReadDir is a more efficient and correct choice: it returns a list of fs.DirEntry instead of fs.FileInfo, and it returns partial results in the case of an error midway through reading a directory.

There are a few places in Helm relying on ioutil.ReadDir that would be good candidates to switch to os.ReadDir instead.

https://golang.org/pkg/os/#DirEntry

### PR DESCRIPTION
**Pull request by kallydev**
Signed-off-by: Kally Fox <kallydev@gmail.com>

**What this PR does / why we need it**:
Resolved #9926.

**Special notes for your reviewer**:

**If applicable**:
- [ ] this PR contains documentation
- [x] this PR contains unit tests
- [x] this PR has been tested for backwards compatibility

### CODE REVIEW

**Review by cndoit18 — COMMENTED** [review]
If we want to migrate, can we migrate all the ioutil to os or io?

**Comment by kallydev** [comment]
> If we want to migrate, can we migrate all the ioutil to os or io?

Yes, I have migrated all ioutil.ReadDir to os.ReadDir. Since this PR specifies binding to Issue, if we need to migrate other ioutil code to os or io, I suggest to do it in another PR.

**Comment by cndoit18** [comment]
> > If we want to migrate, can we migrate all the ioutil to os or io?
> 
> Yes, I have migrated all ioutil.ReadDir to os.ReadDir. Since this PR specifies binding to Issue, if we need to migrate other ioutil code to os or io, I suggest to do it in another PR.

That looks great too.

**Review by bacongobbler — APPROVED** [review]
LGTM. Thanks!

**Review by cndoit18 — APPROVED** [review]

**Review by yxxhero — APPROVED** [review]
LGTM

**Review by hickeyma — APPROVED** [review]
LGTM, thanks for the update @kallydev

**Pull request merged**
