### PR TITLE
chore: `make protoc`

### PR DESCRIPTION
**Pull request by bacongobbler**
#5210 updated golang/protobuf but the protocol buffer package was not updated. Calling `make protoc` against master with protoc 3.2.0 results in these changes.

cc @technosophos, was there any technical reason why we didn't do this in #5210?

Signed-off-by: Matthew Fisher <matt.fisher@microsoft.com>

### CODE REVIEW

**Comment by mortent** [comment]
@bacongobbler I am working on #5532 and it requires a small change to the release proto. Are you planning to update this PR so it can be merged? If not, I'm happy to pick up this effort and make sure the test failures are addressed.

**Comment by bacongobbler** [comment]
Hi @mortent! Thanks for the ping.

I'm sorry that I haven't been able to get back to this sooner. I'll see what I can do about updating this PR in between flights tomorrow. If I'm unable to pick this up by EOD tomorrow then please feel free to pick this one up. :)

**Comment by hickeyma** [comment]
Issue raised #5658

**Comment by hickeyma** [comment]
@bacongobbler It would seem that you are also generating the 'XXX_' fields when you try to generate the Go files from definitions. FYI, @mortent has a suggestion in https://github.com/helm/helm/issues/5658#issuecomment-487662719

**Comment by hickeyma** [comment]
@bacongobbler Does the merge of https://github.com/helm/helm/pull/5669 make this PR redundant?

**Comment by bacongobbler** [comment]
Yes.

**Pull request closed without merging**
