### PR TITLE
Fix 'helm template' to also print invalid yaml

### PR DESCRIPTION
**Pull request by unguiculus**
Signed-off-by: Reinhard Naegele <unguiculus@gmail.com>

### CODE REVIEW

**Comment by unguiculus** [comment]
As mentioned in https://github.com/helm/helm/pull/7094#issuecomment-583562707, this is an alternative solution for #7094.

**Comment by mattfarina** [comment]
Over on #7094 it was suggested by @bacongobbler that this should be behind the `--debug` flag. Any thoughts on that?

**Comment by bacongobbler** [comment]
Yeah, same feedback as @mattfarina provided. The code looks good, but I'm interested in the CLI design. Would users want the full template output displayed when a rendering error occurs, or should it only be displayed when `--debug` is provided?

My concern is that if we display the full template output, the error message will be lost in the noise. For example, CI/CD pipelines probably don't want their templates rendered out in the log. By placing this under the `--debug` flag, users can opt into that functionality to gain a better understanding why their templates failed.

**Comment by unguiculus** [comment]
The way I implemented it basically follows what Helm 2 does. Was YAML parsing introduced on purpose here or is this just an unintentional side effect of the refactoring? Anyways I'm open to placing it under the `--debug` flag. Might be the better option but I don't really have a strong opinion on that.

**Comment by rimusz** [comment]
+1 for the `--debug` flag

**Comment by unguiculus** [comment]
So I went ahead and placed it under the `--debug` flag.

**Review by bacongobbler — APPROVED** [review]

**Pull request merged**
