### PR TITLE
feat(ci): add doc validation script

### PR DESCRIPTION
**Pull request by adamreese**

### CODE REVIEW

**Comment by k8s-oncall** [comment]
This change is [Reviewable](https://reviewable.kubernetes.io/reviews/kubernetes/helm/1611)

**Comment by technosophos** [comment]
I feel like someone just ran find-and-replace against me. :-)

**Comment by technosophos** [comment]
One option would be to remove the generated documentation, and just let individuals run `helm doc` themselves if they want the documentation.

**Comment by adamreese** [comment]
closing  ...for now

**Pull request closed without merging**
