### PR TITLE
Fix(helm): Fix the bug of dependency update deleting subcharts

### LINKED ISSUE #2830: Dependency update deletes subcharts
In Helm 2.6.0, the new delete feature that deletes old versions of charts is deleting subcharts that aren't in `requirements.yaml`. Output of what this looks like is below:

```shell
$ ls charts/subchart 
Chart.yaml  charts      templates   values.yaml
$ helm dep up
Hang tight while we grab the latest from your chart repositories...
...Unable to get an update from the "local" chart repository (http://127.0.0.1:8879/charts):
	Get http://127.0.0.1:8879/charts/index.yaml: dial tcp 127.0.0.1:8879: getsockopt: connection refused
...Successfully got an update from the "stable" chart repository
Update Complete. ⎈Happy Helming!⎈
Saving 1 charts
Downloading heapster from repo https://kubernetes-charts.storage.googleapis.com
Deleting outdated charts
$ ls charts
heapster-0.1.0.tgz
```

### PR DESCRIPTION
**Pull request by rocky-nupt**
In Helm 2.6.0, the new delete feature that deletes old versions of charts is deleting subcharts that aren't in requirements.yaml.
In this patch, I move subcharts not included in requirements.yaml to charts dir before remove tmpcharts.

Closes #2830

### CODE REVIEW

**Comment by jascott1** [comment]
@rocky-nupt Thanks for taking this on! I am getting an error from the move.
For my manual testing setup I have a charts dir with 2 charts, one is in requirements.yaml and one is not. 
```
$ ll
total 36
drwxr-xr-x  4 ubuntu ubuntu 4096 Aug 24 23:38 ./
drwxr-xr-x 13 ubuntu ubuntu 4096 Aug 24 22:32 ../
drwxr-xr-x  2 ubuntu ubuntu 4096 Aug 24 23:38 charts/
-rw-r--r--  1 ubuntu ubuntu   87 Aug 16 05:14 Chart.yaml
-rw-r--r--  1 ubuntu ubuntu  333 Aug 16 05:14 .helmignore
-rw-r--r--  1 ubuntu ubuntu  225 Aug 24 22:32 requirements.lock
-rw-rw-r--  1 ubuntu ubuntu  104 Aug 24 22:32 requirements.yaml
drwxr-xr-x  2 ubuntu ubuntu 4096 Aug 16 05:14 templates/
-rw-r--r--  1 ubuntu ubuntu 1135 Aug 16 05:14 values.yaml
```
```
$ ll charts/
total 32
drwxr-xr-x 2 ubuntu ubuntu 4096 Aug 24 23:38 ./
drwxr-xr-x 4 ubuntu ubuntu 4096 Aug 24 23:38 ../
-rw-rw-r-- 1 ubuntu ubuntu 8771 Aug 24 23:38 ceph-admin-pod-0.7.0-1.tgz
-rw-r-xr-x 1 ubuntu ubuntu 8991 Aug 24 23:38 ceph-rbd-daemonset-0.7.0-1.tgz*
```
When I run `helm dep up` I get an error 
```
$ ~/helm dep up
Hang tight while we grab the latest from your chart repositories...
...Successfully got an update from the "local" chart repository
...Successfully got an update from the "stable" chart repository
Update Complete. ⎈Happy Helming!⎈
Saving 1 charts
Downloading ceph-rbd-daemonset from repo http://127.0.0.1:8879/charts
Deleting outdated charts
Error: Unable to move local charts to charts dir: rename /home/ubuntu/testchart/charts/ceph-admin-pod-0.7.0-1.tgz /home/ubuntu/testchart/tmpcharts/ceph-admin-pod-0.7.0-1.tgz: no such file or directory
```
When testing against master I didn't get this behavior.

**Comment by rocky-nupt** [comment]
Oh, sorry for my carelessness. I mistake tmpfile and destfile in the move. I have fix it now. If there is any other error, please tell me. Thank you for your review! @jascott1

**Comment by jascott1** [comment]
@rocky-nupt Im not sure your fix was pushed. I re-tested and get the same result.

**Comment by rocky-nupt** [comment]
Really? I will test it again next week. Thank you anyway,:) @jascott1

**Comment by rocky-nupt** [comment]
I test it again without any errors. Can you show me your error. @jascott1

**Review by jascott1 — APPROVED** [review]

**Comment by jascott1** [comment]
@rocky-nupt re-tested and looks good. Sorry I must have gotten my helm builds confused last time. Thanks for the fix!

**Comment by thomastaylor312** [comment]
@jascott1 Since you got to this before me, feel free to merge.

**Pull request merged**
