### PR TITLE
codefresh ci

### PR DESCRIPTION
**Pull request by verchol**
**What this PR does / why we need it**:

**Special notes for your reviewer**:

**If applicable**:
- [ ] this PR contains documentation
- [ ] this PR contains unit tests
- [ ] this PR has been tested for backwards compatibility

### CODE REVIEW

**Review by hickeyma — CHANGES_REQUESTED** [review]
@verchol Thanks for submitting the PR.

A few things before we start reviewing this:
- Can you add [DCO](https://helm.sh/blog/helm-dco/#what-if-i-forget-to-sign-off-on-a-commit) to fix the check?
- Do you mind adding a description for the reason for this PR? Maybe create an issue and reference it?

**Comment by bacongobbler** [comment]
ping

**Comment by verchol** [comment]
Sorry , created PR  by mistake, now  working on full ci for helm 3 flow including integration tests and will apply according to the submit rules

**Comment by hickeyma** [comment]
That's ok @verchol. Can this PR be closed then?

**Comment by bacongobbler** [comment]
Closing due to inactivity. Please feel free to reopen once comments have been addressed and you ahve something ready to show. Thanks!

**Pull request closed without merging**
