### PR TITLE
Feature add 'any/every/this/in-any-case' policy to hook-delete-policy

### PR DESCRIPTION
**Pull request by lentil1016**
# What this pull request do
#3714 
> If any hook failed, tiller will delete this single hook then return at L372. Which makes previous succeeded hooks' delete policy trivial. It means if any `hook-delete-policy: hook-failed` is being triggered, then all other `hook-delete-policy` in this hook stage will be ignored.

Inspired by @consideRatio, I've implement this patch, and I think it's ready to be reviewed now.

## In summary

|Annotation|Policy|Master Behavior|PR Behavior|
|-|-|-|-|
|`"hook-succeeded"`|SUCCEEDED|Delete this hook if all hooks succeed|Delete this hook if this hook succeed|
|`"hook-failed"`|FAILED|Delete this hook if this hook failed|Same to master|
|`"this-hook-succeeded"`|SUCCEEDED|-|Delete this hook if this hook succeed|
|`"this-hook-failed"`|FAILED|-|Delete this hook if this hook failed|
|`"all-hooks-succeeded"`|ALL_SUCCEED|-|Delete this hook if all hooks succeed|
|`"any-hook-failed"`|ANY_FAILED|-|Delete this hook if any hook failed|
|`"in-any-case"`|IN_ANY_CASE|-|Delete this hook in any case above|

### Proto Changes

In the consideration of compatibility, I didn't rename `SUCCEEDED` and `FAILED`. So the development based on them will still work, if there is any. However, the behavior of `SUCCEEDED` **will changed** a little bit. It used to indicate "delete this hook if all hooks succeed", now it indicate **"delete this hook if this hook succeed"**. I believe this change will be more intuitive, for it's behavior will be the opposite of `FAILED`: `"delete this hook if this hook failed"`

Additionally, I add `ALL_SUCCEED` `ANY_FAILED` `IN_ANY_CASE` to the enum `DeletePolicy`:
- `ALL_SUCCEED`: Delete this hook if all hooks succeed.
- `ANY_FAILED`: Delete this hook if any hook failed.
- `IN_ANY_CASE`: No matter what happened, just delete this hook when process the hook deletion.

``` diff
diff --git a/_proto/hapi/release/hook.proto b/_proto/hapi/release/hook.proto
index cf7e25b..51e9af7 100644
--- a/_proto/hapi/release/hook.proto
+++ b/_proto/hapi/release/hook.proto
@@ -36,10 +36,15 @@ message Hook {
         RELEASE_TEST_FAILURE = 10;
         CRD_INSTALL = 11;
        }
+
+       // SUCCEEDED represents 'this hook succeed', FAILED represents 'this hook failed'
        enum DeletePolicy {
            SUCCEEDED = 0;
            FAILED = 1;
            BEFORE_HOOK_CREATION = 2;
+           ALL_SUCCEED = 3;
+           ANY_FAILED = 4;
+           IN_ANY_CASE = 5;
        }
        string name = 1;
        // Kind is the Kubernetes kind.
```

### Policy annotation definition Changes

In the consideration of compatibility. The `"hook-succeeded"` and `"hook-failed"` annotations are marked as `deprecated` . they will be shift to `"this-hook-succeeded"` and `"this-hook-failed"` when tiller is sorting the manifests, so the legacy charts will still work, for now. Tiller will print a warning log when shifting deprecated annotations.

https://github.com/helm/helm/blob/d47d86abbcc1db82f1493d25ea264cff9e6fd3a4/pkg/tiller/hooks.go#L198-L212

- `"hook-succeeded"` is deprecated, will be shifted to `"this-hook-succeeded"`.
- `"hook-failed"` is deprecated, will be shifted `"this-hook-failed"`.

In additional, I add `"this-hook-succeeded"` `"this-hook-failed"` `"all-hooks-succeeded"` `"any-hook-failed"` and `"in-any-case"`.
* `"before-hook-creation"` specifies Tiller should delete the previous hook before the new hook is launched. Deletion happened before any execution.
* `"this-hook-succeeded"` specifies Tiller should delete the hook after the hook is successfully executed. Deletion happened after all hooks succeeded or any hook failed.
* `"this-hook-failed"` specifies Tiller should delete the hook if the hook failed during execution. Deletion happened after all hooks succeeded or any hook failed.
* `"all-hooks-succeeded"` specifies Tiller should delete the hook after all hook in its execution stage executed successfully. Deletion happened after all hooks succeeded.
* `"any-hook-failed"` specifies Tiller should delete the hook if any hook in its execution stage failed during execution, including when itself failed. Deletion happened after any hook failed.
* `"in-any-case"` specifies Tiller should delete the hook in any case listed above.

### Other changes

- Add documents
- Add test cases
- Fix some typo

### CODE REVIEW

**Comment by consideRatio** [comment]
@Lentil1016 excellent PR! One less Helm issue for me to worry about.

**Comment by consideRatio** [comment]
@Lentil1016 any news about this via other sources or similar? I'm hoping to get a confirmation that this is indeed a bug and wait to have it fixed or start using the #3540 solution as a workaround.

**Comment by Lentil1016** [comment]
@jascott1 sorry for bothering. Any chance of getting some eyes on this? If this fix is not interested, I'll close it.

**Comment by Lentil1016** [comment]
@consideRatio I'm also tired of this waiting. And suggest you to start using the workaround if possible. This whole hook concept is wonderful but its implementation is a little bit plain. Hope a better hook in helm 3.0.

**Comment by bacongobbler** [comment]
Sorry, we've been heads down nailing down 2.9 bugs so haven't had the time to take a look into new features. Perhaps writing a unit test would be helpful here as a good next step to ensure the code works as intended.

**Comment by jascott1** [comment]
@Lentil1016 

Thanks for the submission. Would you consider updating the [docs](https://github.com/kubernetes/helm/blob/master/docs/charts_hooks.md) and possibly writing a test?

**Comment by consideRatio** [comment]
@Lentil1016 would you like to keep working on this?

## Suggested actions
- [ ] Clarify and document expected behavior of higher priority resource hooks with a failure deletion policy if a higher priority resource execution fails. An example situation to consider would be a Pod with a with a weight of -5 (higher priority) and a Job with a weight of 0 (lower priority) that fails.
__Action: clarify expected behavior__
@bacongobbler / @jascott1, perhaps you could assist by suggesting the expected behavior to make it easier to be actionable regarding this? Currently, a resource created before a failing job-hook will not be deleted even though deletion policies are set. This seems like a bug to me as I supposed the hooks would execute in sequence until one failed, and that would cause all previously created resources with deletion policies triggering on failure to to be deleted. I supposed this since that is how it works for the success hook as far as I can tell.

- [ ] `hook-succeeded`: Document and test that all the resources are deleted when all hooks have entered the Ready state.
  __Action: update docs__
  > `"hook-succeeded"` specifies Tiller should delete the hook after **all** the hook**s** **have** successfully executed.

- [ ] `hook-failed`: Document and test that all the resources are deleted when one of the hooks failed.
  __Action: update docs__
  > `"hook-failed"` specifies Tiller should delete the hook if some hook failed during execution.

**Comment by consideRatio** [comment]
### Related warning...
In Kubernetes 1.10.0-1.10.4 Jobs pod that fails will restart for eternity and the Job will not end up failed, see [kubernetes#62382](https://github.com/kubernetes/kubernetes/issues/62382).

**Comment by consideRatio** [comment]
@bacongobbler @Lentil1016 I've considered this a lot now, with some input I could build on @Lentil1016 commits and make it all the way to the finish line with documentation and tests.

## Question 1
Am I correct in thinking that a ConfigMap, DaemonSet, Deployment or other non-Job resource can't fail in a manner that later require it to be deleted, and it only make sense to have `"hook-failure"` on Job's?

> For all other kinds, as soon as Kubernetes marks the resource as loaded (added or updated), the resource is considered "Ready".
> --- [The docs regarding success](https://github.com/kubernetes/helm/blob/master/docs/charts_hooks.md#hooks-and-the-release-lifecycle)

## Question 2
Consider the options below. Do you agree that both deletion policies make intuitive sense in the new way below? If so, would you like me to augment this PR with that approach together with documentation and tests?

Code|Hook|Actual behavior|Description
-|-|-|-
master| `"hook-success"`|`"every-hook-success"`|Trigger deletion *if **all hook resources** are successful*.
master|`"hook-failure"`|`"this-hook-failure"`|Trigger deletion *if **this Job hook resource** fail*.
PR|`"hook-success"`|`"this-hook-success"`|Trigger deletion *if **this hook resource** is successful and the others have executed*.
PR|`"hook-failure"`|`"this-hook-failure"`|
New|`"hook-success"`|`"every-hook-success"`|
New|`"hook-failure"`|`"any-hook-failure"`|Trigger deletion *if **any hook resource** fails*.

**Comment by Lentil1016** [comment]
It seems this PR is getting to far from its first purpose and getting too heavy to be merged, I'll close it. sorry.

**Comment by consideRatio** [comment]
:'( It was an important PR i would say, the logic of the current helm hooks isnt good i think, it does not make sense.

**Pull request closed without merging**
