### PR TITLE
Add issue templates

### PR DESCRIPTION
**Pull request by cdrage**
**What kind of PR is this?**

Enhancement to GitHub issue templates

**What does does this PR do / why we need it**:

In order to streamline / enhance GitHub bug submission and to direct
users, we must create issue templates to appropriately submit issues.

This PR:
  - Adds descriptions with regards where to ask for support
  (StackOverflow, Slack, documentation) before submitting asking
  developers
  - Adds improvement to the bug report process

**Which issue(s) this PR fixes**:

N/A

**How to test changes / Special notes to the reviewer**:

Yes. Before merging, it's suggested to create the `enhancement` label in
order to appropriately label all incoming enhancement issues.

Signed-off-by: Charlie Drage <charlie@charliedrage.com>

### CODE REVIEW

**Comment by cdrage** [comment]
The inspiration for this comes from:
https://github.com/kubernetes/kubernetes/tree/master/.github/ISSUE_TEMPLATE

**Comment by bacongobbler** [comment]
similar to #7179, can you use the issue template in the Helm 2 branch instead? https://github.com/helm/helm/blob/dev-v2/.github/ISSUE_TEMPLATE.md

once that's in place, we can discuss the limitations with that template in an issue and go from there. It's best to bring up the discussion first so others can chime in before coming to a solution.

**Comment by cdrage** [comment]
I've opened up https://github.com/helm/helm/issues/7190 with regards to having a discussion with regards to issue templating @bacongobbler

**Comment by bacongobbler** [comment]
Thanks.

**Pull request closed without merging**
