### PR TITLE
ref(create): app version should be 0.1.0

### PR DESCRIPTION
**Pull request by bacongobbler**
When creating a Helm chart for the first time, the assumption should be that the app version is also 0.1.0, implying this is for a new application.

Signed-off-by: Matthew Fisher <matt.fisher@microsoft.com>

### CODE REVIEW

**Review by thomastaylor312 — APPROVED** [review]

**Comment by adamreese** [comment]
What do you think about setting it to a TODO?  "TODO: Put the application's version here."
I think bundler does this when scaffolding out a gemspec

**Comment by bacongobbler** [comment]
I like that idea. I'll see what I can do.

**Comment by bacongobbler** [comment]
done. Chart.yaml created with `helm create` now adds some commentary. This resulted in changing some behaviour within chartutil to accomodate the change, as `chartutil.Create` no longer takes chart metadata and writes it to a Chart.yaml. Instead, `chartutil.Create` accepts a chart name and creates the chart with the default values.

Let me know if that design looks too invasive and I can back that out.

**Review by adamreese — APPROVED** [review]

**Comment by maver1ck** [comment]
Hi Guys,
Why we remove image.tag here ?
App Version cannot be set from values.yaml which mean that you need to modify chart on every deploy.

**Pull request merged**
