### PR TITLE
feat(repo): validate repo url

### PR DESCRIPTION
**Pull request by michelleN**

### CODE REVIEW

**Comment by jackgr** [comment]
So, we have https://github.com/kubernetes/helm/blob/master/pkg/repo/repoprovider.go#L246 and associated tests.

How is this functionality different?

**Comment by michelleN** [comment]
They're not similar at all. ParseChartReference takes in a reference to a chart and returns a chart.Locator where as ValidateRepoURL checks to make sure a repo url you're trying to add has a valid prefix and is a valid url. @jackgr

**Comment by michelleN** [comment]
Resolves #501

**Comment by jackgr** [comment]
Sorry I wasn't thinking clearly. Yes, we did talk about that. 

The concern is that we already have and use a regex for validating repo URLs. See https://github.com/kubernetes/helm/blob/master/pkg/repo/gcs_repo.go#L36. 

Having a second regex seems incorrect. URL validity checks will differ if the regexes differ, since some URLs may pass one but not the other. If the regexes don't differ, then we don't need a new one.

What am I missing?

**Comment by jackgr** [comment]
Likewise, the chart component of the URL in gcs_repo.go should either replace or be replaced by the one at https://github.com/kubernetes/helm/blob/master/pkg/chart/locator.go#L46.

**Comment by michelleN** [comment]
@jackgr I went ahead and used the GCSRepoURLMatcher for validation on creating a repo so we can reuse some code.

**Comment by jackgr** [comment]
Nice.

**Pull request merged**
