### PR TITLE
oci: Add flag --plain-http to enable working with HTTP registries

### LINKED ISSUE #11682: How can I push chart to an insecure OCI registry with helm v3
helm 3.10.0 and after version

Upload a chart to a registry.

If the chart has an associated provenance file,
it will also be uploaded.

Usage:
helm push [chart] [remote] [flags]

Flags:
-h, --help help for push

Global Flags:
--burst-limit int client-side default throttling limit (default 100)
--debug enable verbose output
--kube-apiserver string the address and the port for the Kubernetes API server
--kube-as-group stringArray group to impersonate for the operation, this flag can be repeated to specify multiple groups.
--kube-as-user string username to impersonate for the operation
--kube-ca-file string the certificate authority file for the Kubernetes API server connection
--kube-context string name of the kubeconfig context to use
--kube-insecure-skip-tls-verify if true, the Kubernetes API server's certificate will not be checked for validity. This will make your HTTPS connections insecure
--kube-tls-server-name string server name to use for Kubernetes API server certificate validation. If it is not provided, the hostname used to contact the server is used
--kube-token string bearer token used for authentication
--kubeconfig string path to the kubeconfig file
-n, --namespace string namespace scope for this request
--registry-config string path to the registry config file (default "/root/.config/helm/registry/config.json")
--repository-cache string path to the file containing cached repository indexes (default "/root/.cache/helm/repository")
--repository-config string path to the file containing repository names and URLs (default "/root/.config/helm/repositories.yaml")

but not find -insecure-skip-tls-verify

### PR DESCRIPTION
**Pull request by aryan9600**
**What this PR does / why we need it**:
Add a new flag `--plain-http` to the following commands:
* `helm install`
* `helm pull`
* `helm push`
* `helm template`
* `helm upgrade`
* `helm show`

This flag instructs the registry client to use plain HTTP connections,
thus enabling upload/download of charts from OCI registries served at
an HTTP endpoint.

closes https://github.com/helm/helm/issues/11682

**Special notes for your reviewer**:

**If applicable**:
- [ ] this PR contains documentation
- [x] this PR contains unit tests
- [x] this PR has been tested for backwards compatibility

### CODE REVIEW

**Review by sabre1041 — CHANGES_REQUESTED** [review]
@aryan9600 Thank you so much for this much needed enhancement. Started to test various different scenarios. Unfortunately, the following fails:

```shell
helm upgrade -i  --plain-http -n plain-http --create-namespace plain-http oci://<registry>/helm/plain-http

Error: Get "https://<registry>/v2/helm/plain-http/tags/list": tls: failed to verify certificate: x509: certificate signed by unknown authority
```

Specifying the version of the chart does work

**Comment by aryan9600** [comment]
@sabre1041 this should be fixed, the call to fetch tags also respect this flag now.

**Comment by sabre1041** [comment]
@aryan9600 indeed the tags listing is working, however unit test `Test_3_Tags` is failing locally. Can you confirm you are seeing similar results on your end?

**Review by sabre1041 — APPROVED** [review]
LGTM

**Comment by aryan9600** [comment]
ping @scottrigby

**Comment by lindhe** [comment]
I would like to suggest naming this flag something else to make the security implications clearer, e.g. `--use-insecure-registry` 🙃

This has precedence:
 ```
--kube-insecure-skip-tls-verify   if true, the Kubernetes API server's certificate will not be checked for validity. This will make your HTTPS connections insecure
```

**Comment by scottrigby** [comment]
> I would like to suggest naming this flag something else to make the security implications clearer, e.g. `--use-insecure-registry` 🙃
> 
> This has precedence:
> 
> ```
> --kube-insecure-skip-tls-verify   if true, the Kubernetes API server's certificate will not be checked for validity. This will make your HTTPS connections insecure
> ```

Hi @lindhe `--insecure-skip-tls-verify` was already added for OCI registries in #11711. 

Just to be clear, `--insecure-skip-tls-verify` skips validation of a certificate behind HTTPS, self-signed or otherwise. This is different from using an OCI registry behind plain HTTP, which is what `--plain-http` in this PR allows.

**Comment by rstribrn** [comment]
> > I would like to suggest naming this flag something else to make the security implications clearer, e.g. `--use-insecure-registry` upside_down_face
> > This has precedence:
> > ```
> > --kube-insecure-skip-tls-verify   if true, the Kubernetes API server's certificate will not be checked for validity. This will make your HTTPS connections insecure
> > ```
> 
> Hi @lindhe `--insecure-skip-tls-verify` was already added for OCI registries in #11711.
> 
> Just to be clear, `--insecure-skip-tls-verify` skips validation of a certificate behind HTTPS, self-signed or otherwise. This is different from using an OCI registry behind plain HTTP, which is what `--plain-http` in this PR allows.

Just added comment to #11167 that "--insecure-skip-tls-verify" doesn't work either for "helm dep update":
https://github.com/helm/helm/pull/11711#issuecomment-1651515590

And of course:
**helm dependency update --insecure-skip-tls-verify**
`Error: unknown flag: --insecure-skip-tls-verify`

**Review by scottrigby — APPROVED** [review]
@aryan9600 Thanks so much, this PR looks and works great 👏  

Without this PR, plain HTTP registries - except for localhost - fail with a message:
> http: server gave HTTP response to HTTPS client

With this PR, passing `--plain-http` flag allows this to succeed.

This PR is good to go 👍 

I suggest as a follow-up we update the Helm website/docs to clarify the purpose of `--plain-http` and `--insecure-skip-tls-verify` since these seem to get confused.

**Pull request merged**
