### PR TITLE
fix: rollback from uninstalled release with no error message

### PR DESCRIPTION
**Pull request by liuming-dev**
**helm version**
```bash
~/.kube » helm version
version.BuildInfo{Version:"v3.1.2", GitCommit:"d878d4d45863e42fd5cff6743294a11d28a9abce", GitTreeState:"clean", GoVersion:"go1.13.8"}
```

**situation**
I have a deployed release
```
~/.kube » helm list -n testzy
NAME           	NAMESPACE	REVISION	UPDATED                             	STATUS  	CHART                        	APP VERSION
helm-app-test-a	testzy   	3       	2020-03-27 17:45:02.329406 +0800 CST	deployed	helm-app-sample-1.0.0        	1.0.3
```

uninstall release
```
~/.kube » helm uninstall helm-app-test-a -n testzy --keep-history
release "helm-app-test-a" uninstalled

~/.kube » helm list -n testzy -a
NAME           	NAMESPACE	REVISION	UPDATED                             	STATUS     	CHART                        	APP VERSION
helm-app-test-a	testzy   	3       	2020-03-27 17:45:02.329406 +0800 CST	uninstalled	helm-app-sample-1.0.0        	1.0.3
```

rollback to former revision, get a error message, and the current release status is set to `pending-rollback`
```
~/.kube » helm rollback helm-app-test-a 1 -n testzy
Error: "helm-app-test-a" has no deployed releases

~/.kube » helm list -n testzy -a
NAME           	NAMESPACE	REVISION	UPDATED                             	STATUS          	CHART                        	APP VERSION
helm-app-test-a	testzy   	4       	2020-03-27 18:52:45.08371 +0800 CST 	pending-rollback	helm-app-sample-1.0.0        	1
```

but the resources of the release has been created, and their's status are ok
```
~/.kube » kubectl -n testzy get deployment helm-app-test-a
NAME              READY   UP-TO-DATE   AVAILABLE   AGE
helm-app-test-a   1/1     1            1           5m1s
```

therefore, i think helm allows user to rollback from uninstalled release, this is a bug

this PR fixs the bug, and it will rollback successfully without error message.

fixs #6978, #7366 

Please help to review the code, thanks.

### CODE REVIEW

**Comment by liuming-tech** [comment]
@adamreese @hickeyma @jdolitsky

**Comment by technosophos** [comment]
I left a few notes on #7913 that would also relate to this issue. I am concerned that the solution proposed here will break the 3-way-diff algorithm in interesting ways. I described this in more detail there.

I think this PR will also need some tests.

**Comment by liuming-dev** [comment]
> I left a few notes on #7913 that would also relate to this issue. I am concerned that the solution proposed here will break the 3-way-diff algorithm in interesting ways. I described this in more detail there.
> 
> I think this PR will also need some tests.

It seems #7913 has solved this issue.

**Comment by hickeyma** [comment]
@liuming-dev Closing this out in favour #7653 which now supersedes #7913

**Pull request closed without merging**
