### PR TITLE
Rename index.md to README.md

### PR DESCRIPTION
**Pull request by pierreozoux**
If you browse documentation from GitHub it makes more sense.

### CODE REVIEW

**Comment by technosophos** [comment]
There's an effort underway to re-work the documentation. So I'd like to hold off on a rename. The docs team is trying to take the contents of this directory and turn it into a Hugo site. We're sorta waiting for some guidance from that team about how things will need to be structured. But my understanding is that index.md becomes the index.html for that site.

That said, I think it would be fine (and useful) to add a README.md that provided some generic info and pointed to the index. Then we can adjust accordingly as things progress.

**Comment by technosophos** [comment]
Related to #2501

**Comment by flynnduism** [comment]
Having a README makes sense for easier viewing on Github - I tested and this won't impact on the Hugo site at all, so this is a win-win.

**Comment by technosophos** [comment]
Okay. Merging it, then.

**Review by technosophos — APPROVED** [review]
Thanks for your patience on this one.

**Pull request merged**
