### PR TITLE
feat(checksum): Generate shasum/sha256sum -c compatible sha256 file

### LINKED ISSUE #4968: sha256 file is not understood by sha256sum command
The sha256 checksum files on the release page, e.g., <https://storage.googleapis.com/kubernetes-helm/helm-v2.11.0-linux-amd64.tar.gz.sha256> have just the checksum. That is OK, but the Linux sha256sum command has the -c option, which allows it to check signatures, which is handy, as it avoids having to manually and visually check the checksum. If the file had two spaces and the filename appended to the line with the checksum, -c would work. Like this:

    02a4751586d6a80f6848b58e7f6bd6c973ffffadc52b4c06652db7def02773a1  helm-v2.11.0-linux-amd64.tar.gz

### PR DESCRIPTION
**Pull request by t2sa**
Commands shasum -a 256 -c (or) sha256sum -c can read the SHA sum and validate the TAR/ZIP archive
Example:
  Download helm-v3.0.2-darwin-amd64.tar.gz.sha256 and helm-v3.0.2-darwin-amd64.tar.gz and running below will result in
    shasum -a 256 -c helm-v3.0.2-darwin-amd64.tar.gz.sha256
    helm-v3.0.2-darwin-amd64.tar.gz: OK

Closes #4968

### CODE REVIEW

**Comment by bacongobbler** [comment]
Hi @t2sa. At this point, other systems have come to expect the format from the .sha256 file. For example, the `get` script relies on the output from here. Can you instead change this to write to a new file?

**Comment by bacongobbler** [comment]
For reference:

https://github.com/helm/helm/blob/12e0ab7e44eb02738e1128ac01ee0843e47b4e79/scripts/get#L135-L144

**Comment by t2sa** [comment]
Hello, thanks for taking the time to review. The get /get-helm-3 change is backwards compatible with the existing format and the proposed format. So this change should be good if those are the only two users of the checksum file. 

However if there are other productions dependencies on the checksum I see your point. Is there an option to test out this commit and ensure all systems are green? I am happy to review/update if one of you can point me to a list of dependencies.

**Comment by bacongobbler** [comment]
Unfortunately no. Helm is downloaded nearly 1,000,000 times per month, so any backwards-incompatible changes can impact a significant number of users. I can't really point you to a list of systems to check; it's based more on past experiences dealing with backwards-incompatible changes.

**Comment by t2sa** [comment]
Totally understand, have updated logic to add an extra file at the same location that ends with sha256sum. While releasing kindly point the checksum link to the new file.
example: https://get.helm.sh/helm-v3.0.2-darwin-amd64.tar.gz.sha256sum

**Comment by bacongobbler** [comment]
> While releasing kindly point the checksum link to the new file.

The release is completely automated. This will be uploaded as part of the [CI script](https://github.com/helm/helm/blob/9e4d42e18c995fd2e1eb308aecaa8e1b5ec706e5/.circleci/deploy.sh#L49).

If you want to update the [release checklist](https://github.com/helm/helm-www/blob/master/content/docs/community/release_checklist.md#8-write-the-release-notes), then the next release maintainer can incorporate that link into the release document.

**Comment by t2sa** [comment]
> If you want to update the [release checklist](https://github.com/helm/helm-www/blob/master/content/docs/community/release_checklist.md#8-write-the-release-notes), then the next release maintainer can incorporate that link into the release document.

Updated the release checklist [helm-www/PR#466](https://github.com/helm/helm-www/pull/466)

**Comment by bacongobbler** [comment]
[The proposal](https://github.com/helm/helm/issues/4968#issuecomment-442812685) in #4968 asked for a single file containing all of the checksums into one file. e.g.

shasums.txt

```
2f39c118b07679de853f88e62982e8840ccf518f7feb7274430ff2ca89b37033  helm-v3.1.0-darwin-amd64.tar.gz
0e2681caeadae47ea05d698c96a30f0ac002b76421e9d5893132e9158865b457  helm-v3.1.0-darwin-amd64.zip
4abb57f216e4b86a6f2c77f1b16148c96f555fa2818a36dea2d7c88f9e5b9cfb  helm-v3.1.0-linux-386.tar.gz
1123cec84c5936ce21e2ea047d64414bbd65964bbb09e8c1955a243e8c5084f6  helm-v3.1.0-linux-386.zip
```

This way, any file can be checked with

```
><> shasum -a 256 -c shasums.txt
helm-v3.1.0-darwin-amd64.tar.gz: OK
helm-v3.1.0-darwin-amd64.zip: OK
helm-v3.1.0-linux-386.tar.gz: OK
helm-v3.1.0-linux-386.zip: OK
```

Can you please look further into the requirements as per what was proposed in the original ticket? Thanks.

**Comment by t2sa** [comment]
Hi @bacongobbler, I took the approach keeping user experience in mind. Lets take for example an OSX user downloading only helm-v3.0.2-darwin-amd64.tar.gz along with the shasums.txt and running shasum command (Perl) available by default.

```
$ shasum -c shasums.txt -s
shasum: helm-v3.0.2-linux-386.tar.gz:
shasum: helm-v3.0.2-linux-amd64.tar.gz: No such file or directory
shasum: helm-v3.0.2-linux-arm.tar.gz: No such file or directory
shasum: helm-v3.0.2-linux-arm64.tar.gz: No such file or directory
shasum: helm-v3.0.2-linux-ppc64le.tar.gz: No such file or directory
shasum: helm-v3.0.2-windows-amd64.zip: No such file or directory
$ echo $?
1
```
Though the `-s` option is turned on, user sees these errors plus status code gets set to 1.
The GNU sha256sum (found on Linux distros) have `--ignore-missing` option which can be used to circumvent this issue.

The current implementation of having an individual *.sha256sum keeps the OSX and Linux community satisfied. Users see a proper exit code and can wrap scripts around shasum/sha256sum. Let me know your thoughts and if you feel the need for one shasums.txt then I can make the necessary change.

Thanks

**Comment by bacongobbler** [comment]
As per [the OP's comment](https://github.com/helm/helm/issues/4968#issuecomment-442812685), it was mentioned

> Not sure having a parallel file is worth it. Just having a single file with the checksums of all files seems like the simpler approach

Having a single shasums.txt with all the checksums in one file would be good. Should users want to verify a single checksum, they can either use `shasum -a 256 --ignore-missing shasums.txt` or just compare the output of `shasum -a 256 helm-v3.0.3-linux-amd64.tar.gz | awk '{ print $1 }' to `cat helm-v3.0.3-linux-amd64.tar.gz.sha256`.

Can you please change this PR to write out one `shasums.txt` file containing all of the checksums? Thanks.

**Comment by bacongobbler** [comment]
`sha256sum` is also available on macOS via `brew install coreutils`, FYI, so this tool can be used on other operating systems.

**Review by bacongobbler — APPROVED** [review]
LGTM!

**Pull request merged**
