### PR TITLE
Support the convention for multiple images, BOM and re-location in the chart template

### PR DESCRIPTION
**Pull request by jhvhs**
See https://github.com/helm/helm/issues/7154 for more context

Signed-off-by: Konstantin Semenov <ksemenov@pivotal.io>

### CODE REVIEW

**Comment by thomastaylor312** [comment]
This looks pretty nice. Pinging @helm/charts-maintainers to take a look at this to make sure it matches up with current best practices

**Comment by jhvhs** [comment]
@thomastaylor312  I'd be more than happy to organise a pull request for the documentation website repo to update the best practices section.

**Comment by prydonius** [comment]
cc @carrodher

**Review by jlegrone — COMMENTED** [review]
The issue of how to reference images by digest has been brought up in https://github.com/helm/charts/issues/13449. I think I prefer the simplicity of that proposal over this, especially as the default "helm create" experience.

I also think Helm should provide a first-class type for image references, much like CNAB does, but that's beyond the scope of this PR. Perhaps this would make sense to trial as a library chart first?

**Comment by jhvhs** [comment]
> The issue of how to reference images by digest has been brought up in [helm/charts#13449](https://github.com/helm/charts/issues/13449). I think I prefer the simplicity of that proposal over this, especially as the default "helm create" experience.

Are you suggesting that we comment out the digest, leaving it in as an optional possibility?

**Comment by jlegrone** [comment]
> Are you suggesting that we comment out the digest, leaving it in as an optional possibility?

I am against specifying digest as a separate field and then appending it to the tag, eg. `my/image:tag@digest`. If we do this without building image validation directly into Helm, then users will frequently end up confused as to why updating the tag override has no effect (this will be a non-obvious problem to detect as well).

I'm also wary of adding ~100 lines of helper templates to the default Helm starter chart. I'd much rather see this complexity handled directly in Helm rather than user templates which can start from conventions but are also subject to entropy.

**Comment by jhvhs** [comment]
> The more desirable behavior would be for Helm to check that a tag resolves to a digest before deploying, and _then_ update image references in rendered resources to use that digest. This ensures that if either tag OR digest change, users will know (as opposed to digest silently always taking precedence).

It would be great to have helm verify the image, but unfortunately, the fact that the helm cli  can communicate with the k8s cluster doesn't necessarily mean it can also communicate with the registry - for example, it has no knowledge of the pull secrets, or there might be a firewall in place preventing any connections apart from the clusters themselves.

The only reason we have to involve digests is that, unfortunately, tags are mutable. Referencing the image with the same tag does not guarantee that the exact same binary blob will be pulled down. Because of that, I believe that the digest should be used for stricter blob identification, while the tag should be be used as a visual version reference for the operator.

**Comment by jhvhs** [comment]
> I also think Helm should provide a first-class type for image references, much like CNAB does...

We have filed a proposal https://github.com/helm/helm/issues/7754 for the first-class type support

**Comment by joejulian** [comment]
Is this abandoned?

**Comment by joejulian** [comment]
closing this as abaondoned

**Pull request closed without merging**
