### PR TITLE
feat(values): support YAML streams in values files (closes #10125)

### LINKED ISSUE #10125: Support streams in values files
It would be useful if single values files could contain multiple documents. This way, a single file with multiple hashes could be provided.

This would be useful for example when passing ad-hoc values to ArgoCD Applications, as they are passed as a single string.

When implemented, passing a single values files containing:

```
---
image: "foo"
---
image: "overridden-foo"
```

should result in ` .Values.image` with value `overridden-foo`.

### PR DESCRIPTION
**Pull request by raphink**
Signed-off-by: Raphaël Pinson <raphael.pinson@camptocamp.com>

**What this PR does / why we need it**:

This simple PR allows to consider values files as streams of multiple documents. This is useful to pass multiple value documents as one file, as required for example by ArgoCD applications (when passing verbatim values), without having to merge the values beforehand.

As a result, a single values files such as:

```
---
image: "foo"
---
image: "overridden-foo"
```

will now set `.Values.image` to `overridden-foo`.

Note: this does not apply to the default values file, only the additional files passed to the CLI.

**Special notes for your reviewer**:

**If applicable**:

- [x] this PR has been tested for backwards compatibility

### CODE REVIEW

**Comment by zonggen** [comment]
Could you link/create the corresponding issue to this PR, thank you :)

Reference: [CONTRIBUTING.md#how-to-contribute-a-patch](https://github.com/helm/helm/blob/main/CONTRIBUTING.md#how-to-contribute-a-patch)

**Comment by raphink** [comment]
@zonggen Do I need to create a HIP for this, or just open an issue?

**Comment by zonggen** [comment]
Just an issue should be sufficient, then it would be triaged by one of the maintainers.

**Comment by raphink** [comment]
Opened #10125 for that

**Comment by yxxhero** [comment]
@raphink You should [warrants a HIP](https://github.com/helm/helm/blob/main/CONTRIBUTING.md#proposing-an-idea). And add unittest. Thanks very much.

**Pull request closed without merging**
