### PR TITLE
feat(helm): support namespace and additional values in lint

### PR DESCRIPTION
**Pull request by jmastr**

### CODE REVIEW

**Comment by jmastr** [comment]
CLA signed!

**Comment by jmastr** [comment]
@k8s-ci-robot please check

**Comment by jmastr** [comment]
@technosophos could you trigger the CLA check?

**Comment by bacongobbler** [comment]
Looks like it’s fixed now. :)

**Comment by jmastr** [comment]
hi @technosophos can you review my patch? shall i spilt it into multiple patch sets to make review easier?

**Comment by bacongobbler** [comment]
We’re currently busy cutting v2.6.2. We will get to this or eventually. Thanks!

**Review by bacongobbler — CHANGES_REQUESTED** [review]
What are the implications of this when a user runs `helm lint` without specifying any values? I think by flipping the engine's templating strictness on (as seen in https://github.com/kubernetes/helm/pull/2972/commits/4e5432f5ffd5ab6bcda597a02c0c9f5643a721ca) goes against all other uses of the engine and might be considered a breaking change. Would it be possible to pull this commit out and propose as a separate feature request?

Rest of this looks great!

**Comment by jmastr** [comment]
@bacongobbler 

> I think by flipping the engine's templating strictness on (as seen in 4e5432f) goes against all other uses of the engine and might be considered a breaking change.

Without that patch the `lint`ing is quite useless in my opinion. I want to see helm fail, if not every value, that I use in the templates is set (via `values.yaml`, `--set`, or `--values`), because I don't want to have keys with empty values in my e.g. `ConfigMap` (imagine a username with empty password combination makes it to production)... Maybe we should change the default behavior of `helm install` etc. to be strict (I also was wondering, why I could not enable strict mode for `helm install`, at least in 2.4.2. Did not see the source code for that.)? 

> What are the implications of this when a user runs helm lint without specifying any values?

All `.yaml` files in `/`(, where `values.yaml`) lives are taken into consideration for the lint process (7a2e158). If all template variables can be filled with values, lint passes. Thinking about that, this could lead to unexpected and definitely is not like `helm install`. If it is okay for you, I will remove 7a2e158.

**Comment by jmastr** [comment]
Hey @bacongobbler 

I took out 7a2e158, because in my opinion it was just wrong to take all top level `yaml` files. one can pass additional `yaml` files via the command line.

How to proceed with the `strict` mode? Like I said, I think the patch is quite useless, if the engine does not warn about missing values for the templates.

**Comment by bacongobbler** [comment]
If you could make that toggle-able with a feature flag, that might be useful. I'll let other core maintainers chime in here and see if my assumptions are correct or not though :)

**Comment by jmastr** [comment]
@bacongobbler lint had already a `--strict` parameter, so I reused that in 
bb4c16f

```diff
-       renderedContentMap, err := engine.New().Render(chart, valuesToRender)
+       e := engine.New()
+       if strict {
+               e.Strict = true
+       }
+       renderedContentMap, err := e.Render(chart, valuesToRender)
```

**Review by bacongobbler — APPROVED** [review]
this looks much better, thank you! I'd love to get another maintainer to take a look at this change since it is a relatively large change to `helm lint`.

**Comment by jmastr** [comment]
@bacongobbler could you ping another maintainer then?

**Comment by jmastr** [comment]
@thomastaylor312 can you review this PR?

**Comment by thomastaylor312** [comment]
@jmastr Sure thing. I'll take a look

**Comment by jmastr** [comment]
@thomastaylor312 @bacongobbler anything?

**Comment by thomastaylor312** [comment]
@jmastr Sorry, this slipped through the cracks. I'll take a look tonight

**Review by thomastaylor312 — COMMENTED** [review]
This is looking good, but because it is a big change to lint, could you add some unit tests to test the new functionality?

**Comment by jmastr** [comment]
hey @thomastaylor312 

could you give me a hint what exactly you think of. I "just" add new command line parameters. I don't know how to test that.

But I adapted the existing unit tests already:
```
$ git diff origin/master --stat | grep test.go
 cmd/helm/lint_test.go                              |  7 ++-
 pkg/lint/lint_test.go                              | 13 ++++--
 pkg/lint/rules/template_test.go                    |  9 +++-
```

**Comment by thomastaylor312** [comment]
@jmastr Actually, now that I go back and read this again, I think you are good. There is already a test that passes in values to a template to make sure it works. Sorry for the confusion on my part. I'll go ahead and merge.

**Review by thomastaylor312 — APPROVED** [review]

**Comment by thomastaylor312** [comment]
@bacongobbler This is good to merge when you would like

**Pull request merged**
