### PR TITLE
Added List mode for Role, ClusterRole and Bindings

### PR DESCRIPTION
**Pull request by sebosp**
refs #5267 

**What this PR does / why we need it**:
Kubernetes supports RoleList, RoleBindingList, ClusterRoleList and ClusterRoleBindingList, in order for a Role to be bound, it must already exist, for the List references, see: https://github.com/kubernetes/kubernetes/blob/master/pkg/apis/rbac/types.go

### CODE REVIEW

**Review by hickeyma — CHANGES_REQUESTED** [review]
Thanks for this.

A few things:

- You will also need to add them to the uninstall order (reverse order to install): https://github.com/helm/helm/blob/master/pkg/tiller/kind_sorter.go#L62
- Can you also sign the DCO: https://helm.sh/blog/helm-dco/index.html

**Comment by sebosp** [comment]
Thanks @hickeyma ,

I have added it to the UninstallOrder and signed the commits.

**Review by hickeyma — CHANGES_REQUESTED** [review]
Thanks for the update. The uninstall order is the inverse of the install order. For example,
"RoleBindingList",
"RoleBinding"
Do you mind updating the uninstall order?

**Review by hickeyma — APPROVED** [review]
LGTM, thanks. I'll let @mattfarina to have a look at this one before merge.

**Review by SlickNik — COMMENTED** [review]
Thanks @sebosp! The diff looks good to me, but there seem to be some extraneous commits in the PR not related to this change. Can we rebase and clean this up so that it's just the commits related to this change?

**Comment by sebosp** [comment]
Closing in favor of #5748

**Pull request closed without merging**
