### PR TITLE
feat(tiller) add -prometheus-histograms flag

### PR DESCRIPTION
**Pull request by mynameiswhm**
By default, `github.com/grpc-ecosystem/go-grpc-prometheus` [doesn't export latency distribution](https://github.com/grpc-ecosystem/go-grpc-prometheus#histograms) for API methods.

I've added `-prometheus-histograms` flag to Tiller, which uses `goprom.EnableHandlingTimeHistogram()` call to enable it.

### CODE REVIEW

**Comment by bacongobbler** [comment]
I think this should be hidden behind a feature flag if go-grpc-Prometheus explicitly disables this feature by default. How about `--enable-prometheus-histograms` set to false by default?

**Comment by mynameiswhm** [comment]
@bacongobbler fair enough! Quick search shows that [istio/mixer](https://github.com/istio/mixer/blob/master/cmd/server/cmd/server.go#L392) and [docker/swarmkit](https://github.com/docker/swarmkit/blob/master/cmd/swarmd/main.go#L213) enables it by default, while [coreos/etcd](https://github.com/coreos/etcd/blob/master/etcdmain/etcd.go#L183) enables it with a flag.

There's two boolean flags in Tiller right now, none of which has prefix `enable`. How about `-prometheus-histograms`?

And then there's question about how to better document this. Should I also add a flag to `helm init` or leave it for power users like `-experimental-release`, `-trace` and `-storage` are right now?

**Comment by mynameiswhm** [comment]
@bacongobbler added flag to Tiller, updated initial comment. The question about documentation/`helm init` still stands :)

**Comment by mynameiswhm** [comment]
After using this patch internally for some time, I've found out that `go-grpc-prometheus`s default histogram buket sizes does not suit very well for Tiller's purposes.

For example, here's histogram of 17 `InstallRelease` requests:

```
grpc_server_handling_seconds_bucket{grpc_method="InstallRelease",grpc_service="hapi.services.tiller.ReleaseService",grpc_type="unary",le="0.005"} 0
grpc_server_handling_seconds_bucket{grpc_method="InstallRelease",grpc_service="hapi.services.tiller.ReleaseService",grpc_type="unary",le="0.01"} 0
grpc_server_handling_seconds_bucket{grpc_method="InstallRelease",grpc_service="hapi.services.tiller.ReleaseService",grpc_type="unary",le="0.025"} 0
grpc_server_handling_seconds_bucket{grpc_method="InstallRelease",grpc_service="hapi.services.tiller.ReleaseService",grpc_type="unary",le="0.05"} 0
grpc_server_handling_seconds_bucket{grpc_method="InstallRelease",grpc_service="hapi.services.tiller.ReleaseService",grpc_type="unary",le="0.1"} 0
grpc_server_handling_seconds_bucket{grpc_method="InstallRelease",grpc_service="hapi.services.tiller.ReleaseService",grpc_type="unary",le="0.25"} 0
grpc_server_handling_seconds_bucket{grpc_method="InstallRelease",grpc_service="hapi.services.tiller.ReleaseService",grpc_type="unary",le="0.5"} 0
grpc_server_handling_seconds_bucket{grpc_method="InstallRelease",grpc_service="hapi.services.tiller.ReleaseService",grpc_type="unary",le="1"} 0
grpc_server_handling_seconds_bucket{grpc_method="InstallRelease",grpc_service="hapi.services.tiller.ReleaseService",grpc_type="unary",le="2.5"} 0
grpc_server_handling_seconds_bucket{grpc_method="InstallRelease",grpc_service="hapi.services.tiller.ReleaseService",grpc_type="unary",le="5"} 0
grpc_server_handling_seconds_bucket{grpc_method="InstallRelease",grpc_service="hapi.services.tiller.ReleaseService",grpc_type="unary",le="10"} 0
grpc_server_handling_seconds_bucket{grpc_method="InstallRelease",grpc_service="hapi.services.tiller.ReleaseService",grpc_type="unary",le="+Inf"} 17
```

All 17 of them took longer than `10`, but (obviously) less than `+Inf` seconds to complete.
Going to experiment with different bucket sizes today, will update PR accordingly later.

**Comment by bacongobbler** [comment]
> Should I also add a flag to helm init or leave it for power users like -experimental-release, -trace and -storage are right now?

I think for now it's better to leave this up for power users and document how you would go about enabling it via `kubectl edit` or by rolling your own custom tiller deployment. We did the same for #2721, too. :)

**Comment by mynameiswhm** [comment]
Pre-defined bucket sizes are not really working, so I've added support for Prometheus' Summaries in https://github.com/grpc-ecosystem/go-grpc-prometheus/pull/27

**Comment by bacongobbler** [comment]
the code looks good to me, though we should add some documentation to support this feature at the very least so users know how to enable/use this feature. Would you mind going ahead and writing some docs for this? Thank you so much!

**Comment by mynameiswhm** [comment]
@bacongobbler as I've mentioned before, histograms are not very useful with varying release install times, so summaries will be better fit, but my PR with summaries support https://github.com/grpc-ecosystem/go-grpc-prometheus/pull/27 is still not merged :(

**Pull request closed without merging**
