### PR TITLE
Updating to Kubernetes client libraries for 1.31.0

### PR DESCRIPTION
**Pull request by mattfarina**
**What this PR does / why we need it**:

**Special notes for your reviewer**:

**If applicable**:
- [ ] this PR contains user facing changes (the `docs needed` label should be applied if so)
- [ ] this PR contains unit tests
- [ ] this PR has been tested for backwards compatibility

### CODE REVIEW

**Review by robertsirc — APPROVED** [review]
LGTM: this is just a version bump.

**Review by sabre1041 — APPROVED** [review]
LGTM

**Review by harshsingh32 — COMMENTED** [review]
lgtm

**Comment by sabre1041** [comment]
@mattfarina can you address the conflicting files?

**Review by sabre1041 — APPROVED** [review]
LGTM

**Pull request merged**
