### PR TITLE
Add Syself to ADOPTERS.md

### PR DESCRIPTION
**Pull request by janiskemper**
**What this PR does / why we need it**:
Adding Syself to ADOPTERS.md because we are happy users of helm!

**If applicable**:
- [ ] this PR contains documentation
- [ ] this PR contains unit tests
- [ ] this PR has been tested for backwards compatibility

### CODE REVIEW

**Review by robertsirc — APPROVED** [review]
LGTM.

**Review by scottrigby — APPROVED** [review]
Hi @janiskemper 👋 

As you can see, not many people have added to this adopters list, even though Helm is so widely used. But that's what this file is for, so thanks!  I see you at https://www.linkedin.com/in/janis-kemper/ 👍

**Comment by scottrigby** [comment]
non-functional, merging per [size labels](https://github.com/helm/helm/blob/main/CONTRIBUTING.md#size-labels).

**Comment by janiskemper** [comment]
thanks @scottrigby :) I was actually feeling a bit awkward because of that :sweat_smile: I'm glad to increase the number of "official" adopters a little ;)

**Pull request merged**
