### PR TITLE
Remove symwalk printing

### PR DESCRIPTION
**Pull request by carlbordum**

### CODE REVIEW

**Review by hickeyma — COMMENTED** [review]
@carlbordum what is the reason for removing this message?

**Comment by carlbordum** [comment]
It's just spammy for us whenever we `helm upgrade` because our repo is filled with unrelated symlinks.

**Comment by hickeyma** [comment]
@bacongobbler You added the message in #6822, do you think the message is necessary?

**Comment by hickeyma** [comment]
@carlbordum I am going to close this PR as per @bacongobbler response in https://github.com/helm/helm/pull/11026#issuecomment-1149932898.

**Pull request closed without merging**
