### PR TITLE
(fix) Handle caFile alone being set for repos

### PR DESCRIPTION
**Pull request by mparry**
Previously it was only respected if `certFile` and `keyFile` were also
specified. However, these are independent features.

This addresses #3074. (The main motivation was that `caFile` appears to be a necessary workaround on, for example, MacOS due to https://github.com/golang/go/issues/16532.)

### CODE REVIEW

**Review by bacongobbler — COMMENTED** [review]
Generally speaking, we try to retain backwards compatibility in public-facing packages where possible. Is there any way we can retain NewClientTLS and introduce NewTLSConfig as a function that calls NewClientTLS instead?

I'd also add some unit tests to `pkg/tlsutil`, otherwise this looks good.

**Comment by mparry** [comment]
I have tweaked the change such that `NewClientTLS()` is reinstated and should work as before. I have also slightly expanded `httpgetter_test` so that it exercises the new code path at least.

I didn't add any tests directly at the `tls` level only because there was nothing existing to base them upon, and I didn't want to spend a lot of time inventing some. If you think that the above is still insufficient, I can take another look.

**Comment by javefang** [comment]
/LGTM, @bacongobbler what do we need before this can be merged?

**Comment by mparry** [comment]
Rebased against master

**Comment by nazarewk** [comment]
should also fix #3792 , what is the status of this?

**Review by bacongobbler — APPROVED** [review]

**Pull request merged**
