### PR TITLE
Limits need to call tag API when explicit version specified

### LINKED ISSUE #10557: v3.8.0-rc.1: helm pull OCI chart fails if tag listing endpoint not available
On Helm v3.7.2:
```
$ export HELM_EXPERIMENTAL_OCI=1
$ helm pull oci://public.ecr.aws/aws-controllers-k8s/apigatewayv2-chart --version v0.0.8
Pulled: public.ecr.aws/aws-controllers-k8s/apigatewayv2-chart:v0.0.8
Digest: sha256:299d8b520291ade6d136a7529b7fd44338d58b5b8239813aed97e8fd81ca1f00
```

On Helm v3.8.0-rc.1:
```
$ helm pull oci://public.ecr.aws/aws-controllers-k8s/apigatewayv2-chart --version v0.0.8
Error: GET "https://public.ecr.aws/v2/aws-controllers-k8s/apigatewayv2-chart/tags/list": unable to retrieve credentials
```

Not sure the proper behavior here, but I'm not sure we need to list tags if `--version` is explicit.

cc @scottrigby @sabre1041

### PR DESCRIPTION
**Pull request by sabre1041**
Reduces the need to call the OCI tag API when explicit versions are specified

fixes https://github.com/helm/helm/issues/10557

### CODE REVIEW

**Review by scottrigby — APPROVED** [review]
this is exactly what I was thinking. 

lgtm, given the caveat that I can not actually test this right now. See https://github.com/helm/helm/issues/10557#issuecomment-1015554818

**Review by jdolitsky — APPROVED** [review]
tested, works 👍

**Comment by marckhouzam** [comment]
Does this need to be part of 3.8?

**Comment by jdolitsky** [comment]
I think so @marckhouzam - ive just placed into milestone

**Comment by marckhouzam** [comment]
> I think so @marckhouzam - ive just placed into milestone

So this will need to be cherry-picked into the `release-3.8` branch.  I didn't do it myself because I felt the release manager should give his ok.  I think it's @mattfarina ?

**Pull request merged**
