### PR TITLE
Change Update to Upgrade in context of helm release

### PR DESCRIPTION
**Pull request by nebril**
This commit aims to stop using Update and Upgrade as synonyms in context
of changing Helm Releases.

Upgrade was chosen as the correct word, as the user facing command for
changing the release is `helm upgrade`.

### CODE REVIEW

**Comment by technosophos** [comment]
Unfortunately, we can't do this change until Helm 3. It breaks our API compatibility commitment for gRPC (no named fields on proto files can be removed or modified).

**Comment by nebril** [comment]
Sure thing.

**Comment by bacongobbler** [comment]
Go 1.9 was just released with [type aliases](https://blog.golang.org/go1.9) as a headliner feature. Would that be something we could use in this PR to migrate over in prep for a major release? We can just document all the deprecated objects and point users in the right direction.

**Comment by bacongobbler** [comment]
closing as stale

**Pull request closed without merging**
