### PR TITLE
Bump Cobra to 1.3.0

### PR DESCRIPTION
**Pull request by marckhouzam**
**What this PR does / why we need it**:

Move to the latest Cobra release.
It keeps us up-to-date but also brings two fixes of value to Helm:
- https://github.com/spf13/cobra/pull/1509 which is the fix for #10438
- https://github.com/spf13/cobra/pull/1161 which allows plugins to do better completion for flags in some scenarios

**Special notes for your reviewer**:

I don't know why dependabot didn't trigger in this case.

### CODE REVIEW

**Review by mattfarina — APPROVED** [review]
lgtm. Merge when ready.

**Comment by mattfarina** [comment]
@marckhouzam merged a different PR that created a conflict. Sorry about that.

**Comment by marckhouzam** [comment]
@mattfarina Rebased

**Comment by marckhouzam** [comment]
Let's instead use the PR that dependabot finally opened: #10491 10491

**Pull request closed without merging**
