### PR TITLE
fix(*): update import paths for helm repo naming

### PR DESCRIPTION
**Pull request by adamreese**
https://github.com/kubernetes/deployment-manager/issues/285

### CODE REVIEW

**Comment by technosophos** [comment]
Hmm... the longer we wait to rename the repo, the further this will get out of date. I've already added new files that will need to be fixed.

**Comment by jackgr** [comment]
@adamreese please rebase.

**Comment by jackgr** [comment]
We need to coordinate the renaming of the repo with the path updates. 

There's nothing holding us back on renaming the repo, except reaching a point of stability, where renaming makes sense. So, here's a proposal for identifying the point of stability: 

one person confirms that both client and server are working correctly, then adds a comment to #285 to indicate that it's time to rename and sends a note that we're frozen until the rename is completed. 

My vote would be for @adamreese to be that person and to do it this weekend, so that the freeze blocks as little work as possible.

@vaikas-google is Monday morning a good time for you to rename the repo, or do we need to do this later in the week?

**Comment by jackgr** [comment]
:+1:

**Comment by michelleN** [comment]
lgtm

**Pull request merged**
