### PR TITLE
Add support for weights for non-hook artifacts

### LINKED ISSUE #8439: Openshift SCC should be installed before any resource which creates a pod
When creating a [SCC](https://docs.openshift.com/enterprise/3.0/admin_guide/manage_scc.html) and service account as part of a helm chart, since it is not ordered to be created before deployment and other resources, the scc does not have an effect on the pods. 

The simplest fix might be to just add kind "SecurityContextConstraints" just after "ServiceAccount" in the kind_sorter.go file.

https://github.com/helm/helm/blob/release-3.0/pkg/releaseutil/kind_sorter.go

Output of `helm version`:
version.BuildInfo{Version:"v3.1.2", GitCommit:"d878d4d45863e42fd5cff6743294a11d28a9abce", GitTreeState:"clean", GoVersion:"go1.13.8"}

Output of `kubectl version`:
Client Version: version.Info{Major:"1", Minor:"18", GitVersion:"v1.18.0", GitCommit:"9e991415386e4cf155a24b1da15becaa390438d8", GitTreeState:"clean", BuildDate:"2020-03-26T06:16:15Z", GoVersion:"go1.14", Compiler:"gc", Platform:"darwin/amd64"}
Server Version: version.Info{Major:"1", Minor:"16+", GitVersion:"v1.16.2+18cfcc9", GitCommit:"18cfcc9", GitTreeState:"clean", BuildDate:"2020-05-25T09:09:52Z", GoVersion:"go1.12.12", Compiler:"gc", Platform:"linux/amd64"}

Cloud Provider/Platform (AKS, GKE, Minikube etc.): 
ROKS (RedHat Openshift Kubernetes service - IBM Cloud)

### PR DESCRIPTION
**Pull request by ashokponkumar**
closes #8439 #3635

**What this PR does / why we need it**:
It adds the capability to order manifests. It uses a functionality very similar to helm.io/hook-weight. It adds helm.io/order-weight.

Ueses the following logic to support any CR.

Have an annotation by the name "helm.sh/weight", which takes an Integer value (-ve or +ve). This a concept that Helm anyway uses for hooks ("helm.sh/hook-weight").
We retain the InstallOrder. We install CRs which have a negative weight in ascending order before those in InstallOrder. Then those with InstallOrder, and then Install those with +ve weights in ascending order.
If anyone specifies a weight for a resource in Install order, which is +ve or -ve, it goes with that batch.
If the weight is 0, then it happens just before those in the install order. So if there is a resource which in InstallOrder, but has a weight of 0, it will be applied before any other resource.

**Special notes for your reviewer**:

**If applicable**:
- [ ] this PR contains documentation
- [ ] this PR contains unit tests
- [ ] this PR has been tested for backwards compatibility

### CODE REVIEW

**Comment by liuming-dev** [comment]
I like this PR, it gives users more flexibilities to define resources install/uninstall order. 


> If the weight is 0, then it happens just before those in the install order. So if there is a resource which in InstallOrder, but has a weight of 0, it will be applied before any other resource.

 How can I differ setting the weight=0 from not setting weight hook(`Weight` default value is 0)?

**Comment by ashokponkumar** [comment]
@liuming-dev Thanks! Good point. While implementing I realised that hook-weight does not differentiate between weight 0 and no weight. So modelled order-weight too same way. Will modify the proposal above.

**Review by hickeyma — CHANGES_REQUESTED** [review]
@ashokponkumar Do you mind rebasing with master? You seem to be out of sync and pulling in changes to this PR which are already merged.

**Comment by ashokponkumar** [comment]
> @ashokponkumar Do you mind rebasing with master? You seem to be out of sync and pulling in changes to this PR which are already merged.

sure @hickeyma. Am new to this process. Guess I am messing things up a bit. I tried following the suggestions by DCO tool. Now am trying to follow [this](https://github.com/kubernetes/community/blob/master/contributors/guide/github-workflow.md). Do you have any document on how to pull changes after a PR is raised without adding the new commits in master being shown as part of the pull request. Am trying myself too and will try to create a new pull request.

**Comment by hickeyma** [comment]
@ashokponkumar Have a look at GitHub docs on git rebase: https://docs.github.com/en/github/using-git/about-git-rebase

**Comment by ashokponkumar** [comment]
> @ashokponkumar Have a look at GitHub docs on git rebase: https://docs.github.com/en/github/using-git/about-git-rebase

Thanks! Will look into it.

**Comment by ashokponkumar** [comment]
Have created a new pull request #8446 . Hence closing this. @hickeyma Would much appreciate if you can have a look at #8446 and let me know if more changes are required.

**Pull request closed without merging**
