### PR TITLE
Add test for subchart coalesce null values

### LINKED ISSUE #5184: Nested `null` values don't remove keys as expected
<https://github.com/helm/helm/pull/2648> allows for deletion of keys by setting `null` values in a `values.yaml` file. However it doesn't work for nested values, e.g.:

```yaml
web:
  livenessProbe:
    httpGet: null
    exec:
      command:
      - curl
      - -f
      - http://localhost:8080/api/v1/info
```

Will not remove `web.livenessProbe.httpGet` from the original values, rather it just overrides the value with `null` and prints the warning:

```
2019/01/18 11:30:07 Warning: Merging destination map for chart 'concourse'. Cannot overwrite table item 'httpGet', with non table value: map[path:/api/v1/info port:atc]
```

Ironically, above is a small variant on the example given in the docs, which I'm pretty sure does not actually do what it claims to: <https://docs.helm.sh/chart_template_guide/#deleting-a-default-key>

I suspect that since the template rendering doesn't seem to differentiate much between a null value and a value not being specified, that this warnings are being ignored and not having much effect.

Output of `helm version`:

```
Client: &version.Version{SemVer:"v2.12.1", GitCommit:"02a47c7249b1fc6d8fd3b94e6b4babf9d818144e", GitTreeState:"clean"}
Server: &version.Version{SemVer:"v2.12.1", GitCommit:"02a47c7249b1fc6d8fd3b94e6b4babf9d818144e", GitTreeState:"clean"}
```

Output of `kubectl version`:

```
Client Version: version.Info{Major:"1", Minor:"13", GitVersion:"v1.13.1", GitCommit:"eec55b9ba98609a46fee712359c7b5b365bdd920", GitTreeState:"clean", BuildDate:"2018-12-13T10:39:04Z", GoVersion:"go1.11.2", Compiler:"gc", Platform:"linux/amd64"}
Server Version: version.Info{Major:"1", Minor:"11+", GitVersion:"v1.11.5-eks-6bad6d", GitCommit:"6bad6d9c768dc0864dab48a11653aa53b5a47043", GitTreeState:"clean", BuildDate:"2018-12-06T23:13:14Z", GoVersion:"go1.10.3", Compiler:"gc", Platform:"linux/amd64"}
```

Cloud Provider/Platform (AKS, GKE, Minikube etc.): 

EKS

### PR DESCRIPTION
**Pull request by aeijdenberg**
Since coalesce can sometimes be called more than once, make sure
that we don't drop keys until right at the end, else they can lose
their meaning (and allow the original value to come through).

More tests would be welcome.

Signed-off-by: Adam Eijdenberg <adam@continusec.com>

Closes #5184 (at least hopefully improves the situation)

**What this PR does / why we need it**:

#5184 caused a regress for subchart values. This attempts to fix it.

**Special notes for your reviewer**:

**If applicable**:
- [ ] this PR contains documentation
- [x] this PR contains unit tests
- [ ] this PR has been tested for backwards compatibility

### CODE REVIEW

**Comment by aeijdenberg** [comment]
(I had to force push with slightly amended commit message a few times until I managed to get the build to past - it seems there might be some unrelated flaky tests or builds?)

**Comment by bacongobbler** [comment]
@sgillespie would you mind testing to seee if this fix works for you?

**Comment by sgillespie** [comment]
This does not seem to fix it for me.

Consider a default value in a subchart:
```
livenessProbe:
  tcpSocket:
    port: 5000
```
Overridden with:
```
livenessProbe:
    tcpSocket: null
```
The result (2.14.2):
```
livenessProbe:                    
  tcpSocket: null
```
And this patch:
```
 livenessProbe:            
   tcpSocket:
     port: 5000
```

**Comment by sgillespie** [comment]
FWIW I'm testing with `helm template`

**Comment by aeijdenberg** [comment]
@sgillespie is right - this still doesn't fix the `demo.zip` example in the linked issue. 

I've had another look today - sadly I don't think I'm going to be able to fix this easily - and I don't have the capacity available to learn the code base to fully fix it.

The underlying problem so far as I can tell is that `chartutil.CoalesceValues()` is called many times, and there seems to be an assumption that it's safe to call more than once, passing the previous output as input a 2nd time.

However with the behavior now of removing `nil` keys, that means that if it's called a second time with a `nil` key removed, then there's no value value to override the source value and thus it comes back again.

I think the right way to fix is likely to stop removing `nil` keys at all inside of that function, and instead remove them much closer to wherever the final values files are rendered. And that's the part of the code base I'm not going to have the capacity in the near future to tease apart and figure out.

**Comment by sgillespie** [comment]
This looks to have been fixed in #6080.

**Comment by aeijdenberg** [comment]
#6080 does appears to have fixed this, which is great!  I've amended this PR to just add the test that I'd already written (which #6080 also fixes), as we can never have enough tests. :)

**Review by hickeyma — APPROVED** [review]
In conjunction with PR #6080 and validation in https://github.com/helm/helm/pull/6146#issuecomment-521787139, LGTM.

**Pull request merged**
