### PR TITLE
feat(helm): Add the --kubeconfig flag

### PR DESCRIPTION
**Pull request by rohancme**
Adds the ability to specify a kubeconfig file that overrides $KUBECONFIG
Issue: #2219

### CODE REVIEW

**Comment by rchakra3** [comment]
There was also an error check that I noticed was missing in `version.go` that I've added

**Review by technosophos — APPROVED** [review]
LGTM. Just needs a rebase, then we can merge.

**Comment by rchakra3** [comment]
@technosophos rebased, thanks for the review!

**Comment by technosophos** [comment]
Thank you very much for that quick turn-around, @rchakra3 . And thank you for the PR.

**Pull request merged**
