### PR TITLE
added option --insecure-skip-tls-verify for helm pull, install and upgrade, addresses #7875

### LINKED ISSUE #7875: Use HELM behind proxy: support insecure repositories when charts get downloaded
### Version info
Output of **helm version**: v3 canary build 4/4/2020
Output of **kubectl version**: 1.16.2
Cloud Provider/**Platform** (AKS, GKE, Minikube etc.): Minishift

---

### Context
Recently support for insecure registries has been added:

- Initial ticket: https://github.com/helm/helm/issues/5434
- Pull request: https://github.com/helm/helm/pull/7254

Although adding the insecure registries works perfectly, we cannot pull/install/upgrade images due to TLS verification still being done.

### Configuration:
Helm 'repositories.yaml' configuration:
```
apiVersion: ""
generated: "0001-01-01T00:00:00Z"
repositories:
- caFile: ""
  certFile: ""
  insecure_skip_tls_verify: true
  keyFile: ""
  name: fluxcd
  password: ""
  url: https://<helm-repository>/repository/helm-fluxcd/
  username: ""
```

### Problem
When pulling the chart we get following error:
```
bamboo@app-bamboo-agent-5:~$ helm pull fluxcd/flux
Error: Get https://<helm-repository>/repository/helm-fluxcd/flux-1.3.0.tgz: x509: certificate signed by unknown authority
```
Just making sure by specyfing the repo directly:
```
bamboo@app-bamboo-agent-5:~$ helm pull fluxcd/flux --repo https://repo.crelan-int.be/repository/helm-fluxcd/
Error: looks like "https://<helm-repository>/repository/helm-fluxcd/" is not a valid chart repository or cannot be reached: Get https://<helm-repository>/repository/helm-fluxcd/index.yaml: x509: certificate signed by unknown authority
```
### Fix
Current `pull`, `install` and `upgrade` commands should keep into account that TLS verification is not required if the repository is marked as insecure.

### PR DESCRIPTION
**Pull request by xvzf**
Signed-off-by: Matthias Riegler <matthias.riegler@taotesting.com>
**What this PR does / why we need it**:
Fixes https://github.com/helm/helm/issues/7875

### CODE REVIEW

**Comment by xvzf** [comment]
Fixes #7875

**Comment by technosophos** [comment]
Any way we can add tests for this? Otherwise, it looks good. It will be a relief to have this flag consistent across commands

**Comment by xvzf** [comment]
@technosophos Wanted to have tests for this but I couldn't figure out how to do it. If you have an input, let me know!

**Comment by xvzf** [comment]
@technosophos any update here?

**Review by bacongobbler — APPROVED** [review]
LGTM

**Pull request merged**
