### PR TITLE
ref(pkg/plugin): create clean path for extracting files

### PR DESCRIPTION
**Pull request by michelleN**

### CODE REVIEW

**Comment by technosophos** [comment]
This issue should be fixed, as we don't really want to suggest that this behavior is a good practice. But unlike the other reported cases, it is not a security issue here because it doesn't allow a user to do anything that the plugin system does not already allow a plugin to do.

As always, users should only install trusted plugins because by design they give broad permissions. (The same really goes for any case where you install applications onto your system.) https://github.com/kubernetes/helm/blob/master/docs/plugins.md

**Comment by bacongobbler** [comment]
do we have a unit test we can add to explain what we are trying to protect against here? If not, should we add an action item to implement one as a follow-up?

**Comment by michelleN** [comment]
@bacongobbler good call. I added a unit test here.

**Review by bacongobbler — APPROVED** [review]

**Comment by michelleN** [comment]
thnx for the lgtm @bacongobbler ! I'm going to do some more manual tests before merging this.

**Pull request merged**
