### PR TITLE
Fix a typo in helm_install.md

### PR DESCRIPTION
**Pull request by ivuk**
Just a typo fix.

Hope you're having a great day! :)

### CODE REVIEW

**Comment by bacongobbler** [comment]
Hi! Thank you for the docs fix, and I hope you're having a great day yourself. :)

Would you mind running `make docs` and push that change as well? Once that's done we can merge this one in.

**Comment by ivuk** [comment]
Thanks for the help, Matthew! I've learned a bit about Godoc today. :)

I've rebased the patch on top of the latest commits to the `master` branch, since there was a conflict. Hope that's OK. Cheers! :)

**Comment by bacongobbler** [comment]
Hmm, looks like this wasn't cleanly rebased against master. @ivuk if you want to do the following, it should clean up this branch to make it merge properly:

```
git remote add upstream https://github.com/kubernetes/helm
git fetch upstream master
git checkout upstream/master
git checkout -b fix-3194
git cherry-pick 6322c95
git cherry-pick a884def
git cherry-pick e7695ea
git cherry-pick 985e76f
git push origin fix-3194:fix-typo --force
```

**Comment by ivuk** [comment]
Thanks for the input, I've opened #3197 which should apply cleanly on top of current `master`.

Thank you for trying to help, I appreciate it! :)

**Pull request closed without merging**
