### PR TITLE
bug(tiller): sort unknown but different kinds alphabetically based on kind name

### PR DESCRIPTION
**Pull request by jascott1**
Adds additional manifest sorting logic so that different unknown kinds
are sorted alphabetically so that manifest order is more deterministic.

### CODE REVIEW

**Comment by jascott1** [comment]
@thomastaylor312 I tested this manually with some "unknown" kinds and it works as expected.

**Review by thomastaylor312 — APPROVED** [review]
This looks good to go!

**Comment by thomastaylor312** [comment]
Let's pull this in to 2.6.2 as well. @jascott1 can you add the "needs pick" label after you merge?

**Comment by jascott1** [comment]
@thomastaylor312 Thanks and done!

**Pull request merged**
