### PR TITLE
Fixed a typo in docs

### PR DESCRIPTION
**Pull request by skozlov**
Replaced `chart` command by `helm`.

### CODE REVIEW

**Comment by hickeyma** [comment]
Good catch, thanks.

One thing, you need to sign DCO.  For example, `$ git commit --amend -s`
Have a look at [Helm DCO](https://helm.sh/blog/helm-dco/) for more information..

**Comment by skozlov** [comment]
Sorry about that, I just was reading docs, fixed the typo and moved on. Now I've read [CONTRIBUTING.md](https://github.com/helm/helm/blob/master/CONTRIBUTING.md).

**Review by hickeyma — APPROVED** [review]
LGTM, thanks.

**Comment by skozlov** [comment]
NP, thank you for the project.

**Review by bacongobbler — APPROVED** [review]

**Pull request merged**
