### PR TITLE
bump version to v2.8.0

### PR DESCRIPTION
**Pull request by bacongobbler**
(cherry picked from commit 14af25f1de6832228539259b821949d20069a222)

### CODE REVIEW

**Comment by paolomainardi** [comment]
Should this file be updated too ? https://github.com/kubernetes/helm/blob/v2.8.0/pkg/version/version.go

**Comment by bacongobbler** [comment]
That file is auto-generated at compile time, which CI handles. All good :)

**Comment by bacongobbler** [comment]
Actually it looks like that file is indeed updated manually as seen in https://github.com/kubernetes/helm/commit/08c1144f5eb3e3b636d9775617287cc26e53dba4. I’ll update that, and the release checklist. We may need to release a v2.8.1.

**Review by thomastaylor312 — APPROVED** [review]

**Comment by bacongobbler** [comment]
will file a new PR.

**Pull request merged**
