### PR TITLE
Add schema validation for the linter 

### PR DESCRIPTION
**Pull request by wilreichert**
Addresses #2575

**Problem:**

Currently the error messages returned from kubernetes are woefully vague with regards to the exact cause an invalid schema. For example, this [commit](https://github.com/openstack/openstack-helm/commit/161170bf96c1a63505c128439d9b93d39d85f7fe) in openstack-helm had a minor indentations issue in the cinder chart. The resulting error from the server was

```
03:05:49 Error: release cinder88 failed: Deployment in version "v1beta1" cannot be handled as a Deployment: [pos 1127]: json: expect char '"' but got char '['
```

That chart has 4 deployments with a fair amount of templating and the message provides no insight as to what or where the problem might be. Identifying the exact cause took way too much of time.

**Solution:**

`kubectl create` has a `--validate` option which performs a client side schema validation. That validation also provide specific error messages as to the exact elements causing failures. That validation code can easily be used as part of the `helm lint` command.

**Caveats:**

The schema must be obtained from somewhere, currently it uses whatever kubernetes cluster helm uses. To ensure the kubernetes server is available the code performs a test connect with a 5 second timeout. If that fails a warning is added to the linter output and the tests continue normally.

### CODE REVIEW

**Comment by thomastaylor312** [comment]
Put this in the 2.6 milestone because 2.5 is releasing soon

**Comment by wilreichert** [comment]
Unsure exactly how to write tests for this. Schema validation is server version specific & the Validation Factory method assumes connectivity. Possible to work around but it seems like you'd just end copying a bunch of code from kubectl and adding needless complexity. Theres a check if the configured Kubernetes server is responding with a relatively short timeout. In the event there's no reply a warning linter message is generated and no more attempts to connect are done. Seemed like a reasonable behavior.

**Comment by chancez** [comment]
You can potentially avoid querying an API for the schema, since kubectl store's the schema in `~/.kube`:

```
ls ~/.kube/schema/
v1.4.3+coreos.0 v1.6.2+coreos.0 v1.6.4          v1.6.4+coreos.0
```

**Comment by technosophos** [comment]
I've used the kubectl .kube/schema strategy before (like in the VS Code Helm extension).  I guess we could do something similar on our own and drop the schemata into $HELM_HOME/cache/schemas

**Comment by technosophos** [comment]
I am not sure if this meets the "stability/security enhancements only" mandate for 2.6. I guess we could say any improvement to linter is a stability improvement, though. Other maintainers: any thoughts on that? Do we meed to push this to 2.7?

**Comment by technosophos** [comment]
I'm sorry... I'd lost track of this issue. Is the open item that we need to figure out how to make this work in offline mode? Perhaps we could just change lint to add a `--skip-schema-validation` flag and solve it that way?

**Comment by technosophos** [comment]
It's been a while with no update, so moving to 2.7.

**Comment by thomastaylor312** [comment]
Bumping this to the backlog milestone for now

**Comment by bacongobbler** [comment]
bumping an old bug, but yes I do believe that the open item on this PR is how to make this work in offline mode. @wilreichert how do you feel about rebasing this to write out the client schema on `helm init` to `$(helm home)/linter/schema` and running those files against the linter?

Potentially related to this work: #3051 (since we probably want to store `helm lint` rulesets in a config file
somewhere.

**Comment by bacongobbler** [comment]
#2694 is the original issue, actually. :)

**Comment by bacongobbler** [comment]
Closing this PR due to inactivity. If someone is interested in pushing this along the finish line, please write a PR against Helm 3. As per [the announcement on the mailing list](https://lists.cncf.io/g/cncf-helm/topic/last_v2_feature_release/34301238), Helm 2.15.0 is the last release where we will be merging new features for Helm 2. Thanks!

**Pull request closed without merging**
