### PR TITLE
fix(helm): Display debug release info when upgrade failed because of timeout. Closes #3020

### LINKED ISSUE #3020: Using --wait suppresses debug logs
This makes it very hard to investigate what is going on with a bad helm upgrade

### PR DESCRIPTION
**Pull request by splisson**
Display debug release info when upgrade failed because of timeout. 
Signed-off-by: Sebastien Plisson <sebastien.plisson@gmail.com>

### CODE REVIEW

**Comment by splisson** [comment]
@bacongobbler this is the new PR for #3020

**Comment by bacongobbler** [comment]
thanks! I'll have a look later today.

**Comment by timm088** [comment]
@bacongobbler @splisson any ETA on getting this out for the next helm release? The output here is quite useful for feedback on deployment issues.

**Comment by bridgetkromhout** [comment]
Hi, @timm088 - We appreciate your work on this feature! As per [the September 26th, 2019 announcement on the mailing list](https://lists.cncf.io/g/cncf-helm/topic/last_v2_feature_release/34301238), Helm 2.15.0 is the last release where we will be merging new features for Helm 2. If you'd like to re-target this to Helm 3 we'd be happy to work on it with you. Thanks.

**Pull request closed without merging**
