### PR TITLE
Fix/missing ssl params

### PR DESCRIPTION
**Pull request by technosophos**
Fix several issues with SSL, including:

- Add parameters back to `helm get *`
- Correctly process params for `helm list`
- Fix security issue that allows self-signed certs to auth
- Add documentation

### CODE REVIEW

**Review by bacongobbler — APPROVED** [review]
reviewed in a pairing session, LGTM

**Review by bacongobbler — CHANGES_REQUESTED** [review]
docs need updating :)

> helm docs are out of date. Please run "make docs"

**Comment by bacongobbler** [comment]
mind rebasing your PR as well? looks like a merge commit strayed in here. Sorry!

**Review by bacongobbler — APPROVED** [review]

**Comment by technosophos** [comment]
Ah! Yes, I rebased off the wrong commit. I think I fixed it.

**Review by adamreese — APPROVED** [review]

**Pull request merged**
