### PR TITLE
fix silent lint ignore for non existing packaged charts

### LINKED ISSUE #6537: Helm v2: lint silently ignores non existing packaged charts
Related issue: #6428 

```
$ helm lint blah.tgz
==> Skipping blah.tgz
open blah.tgz: no such file or directory

0 chart(s) linted, no failures
```

And it also doesn't throw errors for corrupted charts

```
$ touch blah.tgz

$ helm lint blah.tgz
==> Skipping blah.tgz
EOF

0 chart(s) linted, no failures
```

Output of `helm version`:
```
Client: &version.Version{SemVer:"v2.14.3", GitCommit:"0e7f3b6637f7af8fcfddb3d2941fcc7cbebb0085", GitTreeState:"clean"}
```

### PR DESCRIPTION
**Pull request by karuppiah7890**
**What this PR does / why we need it**:
Fixes #6537 

**If applicable**:
- [ ] this PR contains documentation
- [x] this PR contains unit tests
- [ ] this PR has been tested for backwards compatibility

### CODE REVIEW

**Comment by karuppiah7890** [comment]
Have to incorporate changes from #6536 PR

**Comment by karuppiah7890** [comment]
@bacongobbler @thomastaylor312 ^ I have made changes to the PR based on #6536 

Just one question - currently charts with errors are not considered in the total, but show up as failed though. Like `0 chart(s) linted, 1 chart(s) failed` , is that okay?

**Comment by karuppiah7890** [comment]
My guess on the failing test - I think it's due to a race condition I mentioned here https://github.com/helm/helm/pull/6060#issuecomment-539310230 . Gotta dig more to be sure. Should we fix it in this PR? Or in #6060 may be? In different commit of course. Or separate PR? let me know!

**Comment by bacongobbler** [comment]
the race condition was fixed in #6654.

**Comment by karuppiah7890** [comment]
I'll rebase :)

**Comment by karuppiah7890** [comment]
@bacongobbler I have rebased and pushed the changes. Please review and do check this comment where I have a question - https://github.com/helm/helm/pull/6538#issuecomment-539350783

**Comment by bacongobbler** [comment]
We just switched branches over. Helm 2 development is on the `dev-v2` branch, and Helm 3 development is on the `master` branch. Would you mind re-opening this PR against the correct branch once this is ready for review again? Thanks.

**Pull request closed without merging**
