### PR TITLE
Updating charts.md file

### PR DESCRIPTION
**Pull request by Sagar2366**
Signed-off-by : Sagar2366 sagarutekar2366@gmail.com

### CODE REVIEW

**Comment by bacongobbler** [comment]
Again, if you wouldn't mind signing the DCO that would be great. Thanks.

**Comment by Sagar2366** [comment]
How to add DCO signing off, I am directly raising pr from Github site and not from command line, It would be great if you guide me for same :)

**Comment by bacongobbler** [comment]
You'll have to use the CLI rather than the site, unfortunately.

**Comment by thomastaylor312** [comment]
Closed by #5011

**Pull request closed without merging**
