### PR TITLE
Improve chart examples

### PR DESCRIPTION
**Pull request by unguiculus**

### CODE REVIEW

**Review by thomastaylor312 — APPROVED** [review]
This is great! Thank you for submitting this. It all looks good to me and I tested the charts just to make sure they worked. I am going to let one of the chart maintainers have the final word before merging in case I missed anything

**Review by prydonius — APPROVED** [review]
lgtm, thanks again for updating these @unguiculus

**Comment by prydonius** [comment]
@thomastaylor312 will leave the merge to you :)

**Pull request merged**
