### PR TITLE
Ordered charts

### PR DESCRIPTION
**Pull request by zadoryzsolt**
**What this PR does / why we need it**:
Adds order weight to manifests and charts. This extends sorting by kind, where heavier charts get deployed first. It makes the final order [chart weight] > [manifest weight] > [kind].

When used with the --wait flag, helm waits for equally weighted objects before proceeding to the next subset. By default everything has a default weight of (0, 0), so currents charts work as before.

Charts are handled independently, so if one is heavier than it's dependency, it will still be deployed first regardless of the parent-child relation.

refs #3635 

**Special notes for your reviewer**:

**If applicable**:
- [x] this PR contains documentation
- [x] this PR contains unit tests
- [ ] this PR has been tested for backwards compatibility

### CODE REVIEW

**Comment by zadoryzsolt** [comment]
it is ready for review

**Comment by libesz** [comment]
Do we have any initial thoughts on this PR?

**Comment by CsatariGergely** [comment]
@bacongobbler do you have any comments to this?

**Comment by bacongobbler** [comment]
Two thoughts:

- this needs a DCO sign-off
- this needs documentation so users know how to use this, it's behaviour, etc.

Once those are covered we can take a deeper look.

**Comment by libesz** [comment]
I believe both thoughts are fixed now.

**Comment by CsatariGergely** [comment]
@bacongobbler Yes, both the DCO is signed now and the documentation added.

**Comment by CsatariGergely** [comment]
@bacongobbler can you please check this?

**Comment by bacongobbler** [comment]
Sorry for not getting back to you sooner. The team has been focusing for the past few months on getting Helm 3 out the door, and that has meant it's been harder to find time to review feature additions for Helm 2.

Helm 2.15 is soon to be released, and will be the last feature release for Helm 2. Because of the time commitment required to review and test this, we won't be able to find the time to review this. That being said, if you want to try again by implementing this for Helm 3, that would be much appreciated. I'd hold off for a few weeks until 2.15 is out as we are planning to move the dev-v3 branch over to be the new master branch, so there will be some shuffling around for a bit, but once that's done we'd be happy to consider this for the 3.1.0 release.

Thanks again!

**Comment by tomcruise81** [comment]
@libesz / @CsatariGergely - has any work been done to port this PR to Helm 3?

**Comment by libesz** [comment]
@tomcruise81 Nothing on my side (also not planned currently). Probably @zadoryzsolt has something.

**Comment by zadoryzsolt** [comment]
We dropped the feature for now, and currently I don't have private time to port this to helm3.

**Pull request closed without merging**
