### PR TITLE
fix(helm): Accept dependency in requirements.yaml from charts directory

### LINKED ISSUE #3221: Helm should allow easier "management" of child charts placed manually in `charts`
I have a PR (kubernetes/charts#1719) that uses two subcharts, with a `requirements.yaml` to make it easy to choose whether one or the other is not deployed.  Currently the acceptance test is failing because it does `helm dep up` before trying to install the chart, and with no `repository` line in requirements.yaml `helm dep up` fails.  Declaring the "local" repository causes `helm dep up` to fail a la #2887.  I could eliminate the use of `requirements.yaml` but then I'd have to wrap every template in an `{{- if foo.enabled }}` block, which seems inelegant at best.

It may seem nonsensical to have the source repo be the `charts` directory but in my case it's the direct result of these constraints:

* using subcharts
* wanting to allow subcharts to be turned on or off independently
* wanting that to be easy to maintain

I propose one of the following two fixes:

* `helm dep up` ignores dependencies that have no repo declared instead of throwing an error
* if `helm dep up` sees a dependency source URL that resolves to the `charts` directory of the installing chart, it does not try to download the dependency but checks that it is already present and meets any declared constraints like version requirements, erroring only if those checks fail.

### PR DESCRIPTION
**Pull request by splisson**
This change allow the use of charts from the charts sub-directory of the current chart in requirements.yaml. It checks the version. It leaves the chart in place.

Closes #3221

### CODE REVIEW

**Comment by jascott1** [comment]
HI @splisson 

Thanks for the PR! Can you update this to specify which bug or feature proposal this is related to? See the format here https://github.com/kubernetes/helm/blob/master/docs/developers.md#git-conventions

**Comment by bacongobbler** [comment]
ping @splisson ^^

**Comment by bacongobbler** [comment]
Hey @splisson, thanks again for the PR. I noticed there are a ton of changes being made to existing function signatures but no unit tests to cover these cases. Would you mind writing these such that we can ensure the code works the way it should? Thanks!

**Comment by splisson** [comment]
Sure

**Comment by sgandon** [comment]
I wonder if this is not similar to this PR that I made a while ago.
https://github.com/kubernetes/helm/pull/3987

**Comment by YingjunHu** [comment]
@sgandon Any updates on this PR? Is the problem fixed? I'm still seeing the problem in 2019. I'd appreciate if you can still see this comment..

**Comment by sgandon** [comment]
It too one year for someone to review my PR #3987, and a few days to fixed proposed changes. Let's hope it does not take another year to have it merged.

**Comment by YingjunHu** [comment]
It's pretty frustrated to see this happen.. Although I've also found the way to work around it, it would be great if they can merge it... Been tracing this issue for half a year already. Thanks @sgandon. 
Happy helming?? Lol

**Comment by bacongobbler** [comment]
Hi @splisson, sorry for leaving this one dangling for so long. This PR seems much cleaner than the proposed solution in #3987. If you would be willing to rebase this PR, that would be great. If not, pleas elet us know and someone else can carry this PR forwards. Thanks!

**Comment by bacongobbler** [comment]
it looks like a few stray commits snuck in here (like fca5c6b). Let me know once this has been fixed up and I'll be happy to review again.

**Comment by splisson** [comment]
I reverted 2 of them
Is that what you meant?

Sébastien

**Comment by bacongobbler** [comment]
Sorry @splisson, but a `git revert` is slightly different than removing the commit from the history.

What I suggest you could do is run a `git rebase --interactive master`. It will open a new window which you can remove commits from the branch history entirely by removing them from the timeline.

More info here: https://thoughtbot.com/blog/git-interactive-rebase-squash-amend-rewriting-history#interactive-rebase

**Comment by bacongobbler** [comment]
fixed up in https://github.com/helm/helm/pull/6578. Thanks @splisson! :)

**Comment by splisson** [comment]
Thanks matt

Sébastien

**Pull request closed without merging**
