### PR TITLE
Clean up residual file

### PR DESCRIPTION
**Pull request by jayonlau**
**What this PR does / why we need it**:
The soft link file has been deleted, This pr cleans up the redundant files.

**Special notes for your reviewer**:

**If applicable**:
- [ ] this PR contains documentation
- [ ] this PR contains unit tests
- [ ] this PR has been tested for backwards compatibility

### CODE REVIEW

**Comment by jayonlau** [comment]
anyone help me review it?

**Comment by jayonlau** [comment]
@mattfarina

**Comment by jayonlau** [comment]
@cndoit18

**Review by cndoit18 — CHANGES_REQUESTED** [review]
These two files cannot be deleted, they are useful

**Comment by cndoit18** [comment]
See: https://app.circleci.com/pipelines/github/helm/helm/2713/workflows/ee452681-b55a-4962-8280-37807795a06e/jobs/14283/parallel-runs/0/steps/0-104

**Pull request closed without merging**
