### PR TITLE
fix a few function names on comments

### PR DESCRIPTION
**Pull request by cuishuang**
fix a few function names on comments

### CODE REVIEW

**Comment by yxxhero** [comment]
@cuishuang Please add some descriptions. Thanks very much.

**Review by yxxhero — APPROVED** [review]
LGTM

**Review by hickeyma — CHANGES_REQUESTED** [review]
Looks good @cuishuang, thanks.

Just missed to change https://github.com/helm/helm/blob/main/pkg/plugin/installer/http_installer.go#L171 as well.

**Comment by cuishuang** [comment]
> Looks good @cuishuang, thanks.
> 
> Just missed to change https://github.com/helm/helm/blob/main/pkg/plugin/installer/http_installer.go#L171 as well.

Thanks for pointing out. Has been completed

**Review by yxxhero — APPROVED** [review]
LGTM

**Review by hickeyma — APPROVED** [review]
LGTM, thanks @cuishuang

**Review by mattfarina — APPROVED** [review]

**Pull request merged**
