### PR TITLE
Feature/repo url trailing slash

### PR DESCRIPTION
**Pull request by fiunchinho**
Repository url should be normalized to always be without trailing slashes to avoid confusing behaviour like

```
$ helm repo add --debug schip http://helm.company.io/
"schip" has been added to your repositories

$ helm dependency update
Error: no repository definition for http://helm.company.io, http://helm.company.io. Try 'helm repo add'

$ helm repo list
NAME                 URL
kubernetes-charts    http://storage.googleapis.com/kubernetes-charts
schip                http://helm.company.io/

$ helm repo remove schip
"schip" has been removed from your repositories

$ helm repo add --debug schip http://helm.company.io
"schip" has been added to your repositories

$ helm repo list
NAME                 URL
kubernetes-charts    http://storage.googleapis.com/kubernetes-charts
schip                http://helm.company.io

$ helm dependency update
Hang tight while we grab the latest from your chart repositories...
...Successfully got an update from the "schip" chart repository
...Successfully got an update from the "kubernetes-charts" chart repository
Update Complete. ⎈Happy Helming!⎈
Saving 2 charts
Downloading schip/helmtest from repo http://helm.company.io
```

It's my first PR, so any feedback would be appreciated.

### CODE REVIEW

**Comment by k8s-oncall** [comment]
This change is [Reviewable](https://reviewable.kubernetes.io/reviews/kubernetes/helm/1607)

**Comment by fiunchinho** [comment]
I just signed the CLA

**Comment by technosophos** [comment]
This same issue might now be resolved by two different fixes, but I am inclined to merge this one as a safeguard.

**Comment by technosophos** [comment]
Thanks! Reviewed it and am merging it!

**Pull request merged**
