### PR TITLE
fix(*): handle unreleased versioning

### LINKED ISSUE #2110: canary image results in confusing version number
we recently tried to upgrade to master on our tiller instance via:

```
> helm init --upgrade --canary
Tiller (the helm server side component) has been upgraded to the current version.
Happy Helming!
> helm version
Client: &version.Version{SemVer:"v2.2.2", GitCommit:"1b330722aafcb8123114ae51f69d1e884a326f3e", GitTreeState:"clean"}
Server: &version.Version{SemVer:"v2.2.0", GitCommit:"3844b53bbb6c0bb98519255ec84e702a94fde268", GitTreeState:"clean"}
```

This resulted in a version of 2.2.0, which seemed to be a downgrade from what we were running on our clients (2.2.2). We had to check the source code to verify that our labeled 2.2.0 was a newer version than 2.2.2.

### PR DESCRIPTION
**Pull request by adamreese**
Adds an `unreleased` flag to the version if not building from HEAD of a
tag. The compatibility check is bypassed if the client or server are
unreleased.

fixes #2110

### CODE REVIEW

**Comment by technosophos** [comment]
Could we change it from `+unreleased` to `-unreleased`? That has an added advantage of telling SemVer clients that this version is not equal to `2.3.x`.

**Comment by adamreese** [comment]
`2.3.x` is not a valid semver so it won't match either way

**Review by technosophos — APPROVED** [review]

**Comment by adamreese** [comment]
@technosophos PTAL, I updated to be backwards compatible

**Comment by technosophos** [comment]
Yeah, I like this better with using `2.3` instead of `2.3.x`. 🚢

**Comment by libesz** [comment]
Hello Guys!
 We just realized that this PR is reverted my [previous contribution](https://github.com/kubernetes/helm/pull/2198). Since the 4 ? marks [disappeared](https://github.com/kubernetes/helm/commit/2e819e014d78b83c15252571f7bcac75cd226ab7#diff-b242e373bdad475032fb107fa23c1e9eL3) from the `versioning.mk`, I cannot fake the original git version information if the code is eventually building in the scope of another git repo. In that case e.g. the build is marked as dirty.
Can we somehow get both use case working? 😄 
Thanks!

**Comment by adamreese** [comment]
I think it would be easier to just run `go install ...` rather than try to munge the makefile with fake values.

**Pull request merged**
