### PR TITLE
feature(helm): print resource keeped when uninstall

### LINKED ISSUE #7733: Meaningless uninstall command output when annotated with "helm.sh/resource-policy:keep"
if  a resource annotated with "helm.sh/resource-policy:keep", the output is meaningless when excuting uninstall command.
```
➜  myappone helm uninstall myapp1
manifest-1  # keeped resource name which is  generated by program

release "myapp1" uninstalled
```
Obviously,that's not what we want need. output like this will be fun:
```
➜  myappone helm uninstall myapp1
service/myapp1-service

release "myapp1" uninstalled
```

Output of `helm version`:
version.BuildInfo{Version:"v3.0.1", GitCommit:"7c22ef9ce89e0ebeb7125ba2ebf7d421f3e82ffa", GitTreeState:"clean", GoVersion:"go1.13.4"}
Output of `kubectl version`:
Client Version: version.Info{Major:"1", Minor:"15", GitVersion:"v1.15.1", GitCommit:"4485c6f18cee9a5d3c3b4e523bd27972b1b53892", GitTreeState:"clean", BuildDate:"2019-07-18T14:25:20Z", GoVersion:"go1.12.7", Compiler:"gc", Platform:"darwin/amd64"}
Server Version: version.Info{Major:"1", Minor:"17", GitVersion:"v1.17.2", GitCommit:"59603c6e503c87169aea6106f57b9f242f64df89", GitTreeState:"clean", BuildDate:"2020-01-18T23:22:30Z", GoVersion:"go1.13.5", Compiler:"gc", Platform:"linux/amd64"}
Cloud Provider/Platform (AKS, GKE, Minikube etc.):

### PR DESCRIPTION
**Pull request by donggangcj**
Close #7733

Signed-off-by: Dong Gang <dong.gang@daocloud.io>

### CODE REVIEW

**Review by jdolitsky — APPROVED** [review]
LGTM, other maintainers to weigh in here - is a change in stdout like this considered breaking change?

**Comment by technosophos** [comment]
Per policy, this needs a regression test.

**Comment by donggangcj** [comment]
@technosophos  How can i begin a regression test?

**Comment by bacongobbler** [comment]
>  How can i begin a regression test?

Start by writing a unit test that covers the case described in #7733. If written correctly, the test case should fail if this patch is not present or working as expected.

**Comment by donggangcj** [comment]
👌ok! I see. Thanks

**Comment by donggangcj** [comment]
@bacongobbler I add some simple unit test beause minor changes have been made. Is it necessary to add more unit tests？Thanks!

**Comment by djsly** [comment]
@donggangcj  / @bacongobbler  is this is ready to be merged , should we merge this ?

**Review by SoulPancake — APPROVED** [review]

**Comment by joejulian** [comment]
@donggangcj  Are you still willing to work on this? It needs rebased.

**Comment by joejulian** [comment]
Closing as abandoned

**Pull request closed without merging**
