### PR TITLE
First cut of handling NOTES.txt file

### PR DESCRIPTION
**Pull request by vaikas**
I've been testing manually, but please take a look at the proposed changes.
@technosophos @prydonius #993

---

This change is [Reviewable](https://reviewable.kubernetes.io/reviews/kubernetes/helm/1090)

### CODE REVIEW

**Comment by vaikas-google** [comment]
Ok, should be now ready for review. Not sure what the earlier snafu with circleci was, appears to have been fixed somehow.

**Comment by technosophos** [comment]
@prydonius You want to give this a test run? If not, I'll do it.

**Comment by prydonius** [comment]
This is really sweet!!

```
$ helm install .
mottled-molly

$ helm status mottled-molly
Last Deployed: Thu Aug 25 11:45:24 2016
Status: DEPLOYED

Resources:
==> v1/Secret
NAME                    TYPE      DATA      AGE
mottled-molly-mariadb   Opaque    2         11s
mottled-molly-redmine   Opaque    2         10s

==> extensions/Deployment
NAME                    DESIRED   CURRENT   UP-TO-DATE   AVAILABLE   AGE
mottled-molly-mariadb   1         1         1            0           11s
mottled-molly-redmine   1         1         1         0         10s

==> v1/Service
NAME                    CLUSTER-IP      EXTERNAL-IP   PORT(S)    AGE
mottled-molly-mariadb   10.11.245.127   <none>        3306/TCP   10s
mottled-molly-redmine   10.11.241.181   <pending>   80/TCP    10s


Notes:
To access Redmine, execute the following command to retrieve the external IP:

$ kubectl get svc mottled-molly-redmine

Visit the application in your browser: http://EXTERNAL_IP
```

Looks like there's an extra new line between the services print-out and `Notes:`. Otherwise looks great!

Are you going to implement running `status` after `install/upgrade` in a separate PR?

**Comment by migmartri** [comment]
This is awesome.

I am wondering if we should add the namespace in which the chart is running as part of the output as well.

**Comment by technosophos** [comment]
I'd vote for doing status-after-install in a separate PR. If namespace is simple to add, I think that'd be great. If it's an ordeal, though, maybe a separate PR for that?

**Comment by vaikas-google** [comment]
Added namespace, I'll do the status after install/update in a follow on CR.
vaikas@vaikas-glaptop:~/projects/go/src/k8s.io/helm$ ./bin/helm --host localhost:44134 status wondering-duck
Last Deployed: Fri Aug 26 02:59:48 2016
Namespace: jimmybob
Status: DEPLOYED

PTAL

**Pull request merged**
