### PR TITLE
Removing legacy completions.bash file

### LINKED ISSUE #8186: Remove completions.bash file?
`scripts/completions.bash` used to be used for shell completions but it has been replaced in how completions work and are documented to be used. Can we remove it now?

### PR DESCRIPTION
**Pull request by mattfarina**
This file was previously used for shell completions but is
no longer in use as there is a new completions system in place
and there has been for some time.

The contents of this file were out of date and reflect Helm v2.

Closes #8186

### CODE REVIEW

**Review by bacongobbler — APPROVED** [review]

**Comment by mattfarina** [comment]
@marckhouzam can you take a look at this?

**Review by marckhouzam — APPROVED** [review]
Thanks for doing this!

**Comment by marckhouzam** [comment]
Oh and sorry for not seeing it earlier. Please don't hesitate to tag me as you just did because I'm having trouble paying attention to all the PRs that come in. Thanks!

**Comment by hickeyma** [comment]
@mattfarina This is reviewed and ready to merge.

**Pull request merged**
