### PR TITLE
Helm v3: Stream Job Output

### PR DESCRIPTION
**Pull request by nickschuch**
This is a very early pull request for streaming Job logs to developers.

I have pushed to get some early feedback.

Some items to work out:
* How should the output appear to a developer?
* Should Job output be on by default? Now that `helm` is a pure CLI, it feels like a nice step giving.

### CODE REVIEW

**Comment by bacongobbler** [comment]
Hey @nickschuch, thank you for the PR!

Currently we are not accepting any PRs against the Helm 3 branch until all of the main refactoring work is done. Only core maintainers are committing to that branch until we get to that point. This is to avoid any problems with interfering with in-flight refactors and to make sure we have a stable foundation on which to build/accept PRs against. I'll go ahead and keep this open for now and we can come back and revisit it when we are done with the refactor. Thanks!

**Comment by nickschuch** [comment]
Hey @bacongobbler! Completely understand. Happy to keep them open and revisit at a later date.

**Comment by bacongobbler** [comment]
if you want to take another stab at this, the main refactoring has been done. You may want to go through the codebase to re-orient yourself a bit now that Tiller's been removed. Let me know if you have any questions.

I'd also suggest that along with the code that's already in here, I'd write unit tests and documentation to cover this use case. Thanks!

**Comment by distorhead** [comment]
Hi!

Don't you want to use https://github.com/flant/kubedog library to enable logs and other clever features out of the box (tracking multiple resources at the same time with decorated realtime output, tracking modes, early failures detection with different modes, logs filtration, logs of kubernetes events)?

This library initially emerged from this old issue https://github.com/helm/helm/issues/3481 and already being used in many production environments.

**Comment by bacongobbler** [comment]
I'm going to close this ticket due to inactivity, but please re-open if this still needs to be addressed. Thanks!

**Pull request closed without merging**
