### PR TITLE
test(linter): switch from golint to revive and fix lint errors

### LINKED ISSUE #10205: "make test" has linter errors and a warning to use revive in place of golint(deprecated)
Output of `helm version`:  version.BuildInfo{Version:"v3.7+unreleased", GitCommit:"993040d15897cfabd1e4a4b8b0e6a49c2045fdcc", GitTreeState:"dirty", GoVersion:"go1.17.1"}

Output of `kubectl version`: N/A

Cloud Provider/Platform (AKS, GKE, Minikube etc.): N/A

I cloned the repository on my mac and ran ```make test``` - the build fails quickly with linter errors including, for example:
- ```pkg/helmpath/lazypath_darwin.go:13: File is not `gofmt`-ed with `-s` (gofmt)```
- ```cmd/helm/install.go:258:2: sigchanyzer: misuse of unbuffered os.Signal channel as argument to signal.Notify (govet)```

I also got a warning:
- ```WARN [runner] The linter 'golint' is deprecated (since v1.41.0) due to: The repository of the linter has been archived by the owner.  Replaced by revive.```

As a result of the warning I changed the build to use revive instead of golint and then got a few more lint errors including, for example:
- ```cmd/helm/repo_update.go:136:10: errorf: should replace errors.New(fmt.Sprintf(...)) with fmt.Errorf(...) (revive)```

I have also created a branch which switches to use revive and  fixes all of the linter problems and can make a pull request if wanted.

### PR DESCRIPTION
**Pull request by mmulholla**
Signed-off-by: Martin Mulholland <mmulholl@redhat.com>

**What this PR does / why we need it**: 
It does 2 things:
- changes from the golint linter, which is deprecated, to the replacment revive
- fixes all of the linting errors including existing ones from gofmt, and govet, and new ones from revive

without these changes ```make test``` fails and does not run any tests. 

**Special notes for your reviewer**:

I fixed all of the gofmt errors by running ```gofmt -s -w <file>```, for example:
```gofmt -s -w cmd/helm/root_unix.go```

**If applicable**:
- [ ] this PR contains documentation
- [ ] this PR contains unit tests
- [ ] this PR has been tested for backwards compatibility

closes #10205

### CODE REVIEW

**Comment by mmulholla** [comment]
The ci/circleci build failed because revive was added in golang_cli version 1.37.0 and the build was using 1.36.0. As a result I updated the golang_cli version to the newest which is 1.42.1. Hope that version is OK, not sure how else to determine a best for. 

Here is the info on golang_cli versions: https://github.com/golangci/golangci-lint/releases

**Comment by mmulholla** [comment]
The ci/circleci build failed  again for linter errors on files that are nor=t included in make test. Fixed them by running:
```gofmt -s -w ./..``` from the root directory.

**Comment by dperaza4dustbit** [comment]
LGTM, this fix works for me see details:

dperaza@dperaza-mac helm % git checkout fixLintErrors
Branch 'fixLintErrors' set up to track remote branch 'fixLintErrors' from 'mmulholla'.
Switched to a new branch 'fixLintErrors'
dperaza@dperaza-mac helm % make test-style
GO111MODULE=on golangci-lint run
dperaza@dperaza-mac helm % go version
go version go1.17 darwin/amd64
dperaza@dperaza-mac helm % golangci-lint version
golangci-lint has version 1.42.1 built from 54f4301 on 2021-09-04T14:39:09Z

**Review by FrenchBen — APPROVED** [review]
LGTM - It would be nice to move to Go 1.17 to remove the `// +build` syntax in favor of `//go:build`
>prep in Go 1.16, landing the main functionality in Go 1.17, and finishing the transition in Go 1.18. https://github.com/golang/go/issues/25348#issuecomment-685766625

**Review by bacongobbler — COMMENTED** [review]
most of this looks good to me. Thanks for taking this on. Just had one comment.

**Comment by hickeyma** [comment]
@mmulholla Do you mind rebasing with latest?

**Review by jdolitsky — APPROVED** [review]
This lgtm.

If we dont hear from submitter (@mmulholla) perhaps we can resolve conflicts and merge?

**Comment by hickeyma** [comment]
Ping @mmulholla, do you mind rebasing to move the PR along?

**Comment by hickeyma** [comment]
ping @mmulholla

**Comment by hickeyma** [comment]
@mmulholla I had a look at rebasing this and it ended up getting awkard. I have pushed #10575 instead to supersede this. I hope this is ok with you?

**Comment by joejulian** [comment]
Superseded with #10575. Closing.

**Pull request closed without merging**
