### PR TITLE
Revert "toYaml - Fix #3470 and #3410's trailing \n issues"

### LINKED ISSUE #3470: Extra newline generated from 'toyaml' function which is not removed even by an {{- end }}
Created a values.yaml file with the following:
```
labels:
  tier: frontend
  foo: bar
  foo3: bar3
```

and a template with the following:
```
apiVersion: v1
kind: ConfigMap
metadata:
  name: "bug bug"
data:
{{- if .Values.labels }}
{{ toYaml .Values.labels | indent 2 }}{{- end }}
  bug: yes
```

When I run a dry run it returns:
```
[debug] Created tunnel using local port: '41519'

[debug] SERVER: "127.0.0.1:41519"

[debug] Original chart version: ""
[debug] CHART PATH: /home/me/bug

NAME:   eponymous-whale
REVISION: 1
RELEASED: Wed Feb  7 13:35:39 2018
CHART: bug-0.1.0
USER-SUPPLIED VALUES:
{}

COMPUTED VALUES:
labels:
  foo: bar
  foo3: bar3
  tier: frontend

HOOKS:
MANIFEST:

---
# Source: bug/templates/bug-configmap.yaml
apiVersion: v1
kind: ConfigMap
metadata:
  name: "bug bug"
data:
  foo: bar
  foo3: bar3
  tier: frontend

  bug: yes
```

The empty line above `bug: yes` has the 2 spaces from the indent but the `{{- end }}` should have removed them (or better yet not passed back the extra line from the toyaml function
```
helm version
Client: &version.Version{SemVer:"v2.8.0", GitCommit:"14af25f1de6832228539259b821949d20069a222", GitTreeState:"clean"}
Server: &version.Version{SemVer:"v2.8.0", GitCommit:"14af25f1de6832228539259b821949d20069a222", GitTreeState:"clean"}
```

### LINKED ISSUE #3981: stable/prometheus broken on helm release 2.9.0
Output of `helm version`:
```
Client: &version.Version{SemVer:"v2.9.0", GitCommit:"f6025bb9ee7daf9fee0026541c90a6f557a3e0bc", GitTreeState:"clean"}
Server: &version.Version{SemVer:"v2.9.0", GitCommit:"f6025bb9ee7daf9fee0026541c90a6f557a3e0bc", GitTreeState:"clean"}
```

Output of `kubectl version`:
```
Client Version: version.Info{Major:"1", Minor:"10", GitVersion:"v1.10.1", GitCommit:"d4ab47518836c750f9949b9e0d387f20fb92260b", GitTreeState:"clean", BuildDate:"2018-04-12T14:26:04Z", GoVersion:"go1.9.3", Compiler:"gc", Platform:"linux/amd64"}
Server Version: version.Info{Major:"1", Minor:"10", GitVersion:"v1.10.1", GitCommit:"d4ab47518836c750f9949b9e0d387f20fb92260b", GitTreeState:"clean", BuildDate:"2018-04-12T14:14:26Z", GoVersion:"go1.9.3", Compiler:"gc", Platform:"linux/amd64"}
```

Cloud Provider/Platform (AKS, GKE, Minikube etc.): bare metal

Installing `stable/prometheus` chart is broken on helm `2.9.0`. Works fine in helm `2.8.2`
The prometheus configMap entry contains broken yaml for the `prometheus.yml` key.

Specifically, the `alerting:` section that is added by `templates/server-configmap.yml` is missing a new line and results in the following snippet being generated

```
      - action: replace
        source_labels:
        - __meta_kubernetes_pod_name
        target_label: kubernetes_pod_namealerting:
      alertmanagers:
      - kubernetes_sd_configs:
```

which should actually be like this

```
      - action: replace
        source_labels:
        - __meta_kubernetes_pod_name
        target_label: kubernetes_pod_name
    alerting:
      alertmanagers:
      - kubernetes_sd_configs:
```

Possibly related to #3410 #3470 as referenced in the 2.9.0 release notes

This results in the prometheus server pod failing to starts as it complains about malformed yaml as shown below

```
level=error ts=2018-04-27T04:41:05.546416253Z caller=main.go:582 err="Error loading config couldn't load configuration (--config.file=/etc/config/prometheus.yml): parsing YAML file /etc/config/prometheus.yml: yaml: line 202: mapping values are not allowed in this context"
level=info ts=2018-04-27T04:41:05.546496152Z caller=main.go:584 msg="See you next time!"
```

### PR DESCRIPTION
**Pull request by bacongobbler**
Reverts kubernetes/helm#3837

closes #3981

### CODE REVIEW

**Comment by bacongobbler** [comment]
@georgepapas would you mind giving this a test and see if this fixes your issue? Thanks!

**Review by technosophos — APPROVED** [review]

**Comment by georgepapas** [comment]
@bacongobbler Sure, what is the best way to get a distribution that has this change? Is there a tag I can use, or should I build locally?

**Comment by bacongobbler** [comment]
@georgepapa you can test using the canary releases for now: https://docs.helm.sh/using_helm/#from-canary-builds

**Comment by consideRatio** [comment]
#### Explanation of error

The following template code with #3837 was problematic I'm confident.

```yaml
{{- range $key, $value := .Values.serverFiles }}
  {{ $key }}: |
{{ toYaml $value | default "{}" | indent 4 }}
{{- if eq $key "prometheus.yml" -}}
{{- if $root.Values.alertmanager.enabled -}}
    alerting:
```

Note that all whitespace in between the `{{ toYaml ...` output and the `alerting:` line is chomped by the backward and forward comping by lines in between. As #3837 caused `toYaml` to no longer generate an un-chompable new line in the end, `alerting:` is suddenly overlapping on top of the output from `toYaml`.

https://github.com/kubernetes/charts/blob/9667722aba5b1d5e823385db0b3c1d0bfeea2904/stable/prometheus/templates/server-configmap.yaml#L14-L19

---

Sorry for the trouble caused by my PR!

**Pull request merged**
