### PR TITLE
Fix value precedence

### LINKED ISSUE #9940: Value files precedence behaviour changes when custom values file is used
Edit: The issue can be reproduced and outputs can be seen here - https://github.com/ankitabhopatkar13/helm-values-issue

Output of `helm version`: `version.BuildInfo{Version:"v3.6.1", GitCommit:"61d8e8c4a6f95540c15c6a65f36a6dd0a45e7a2f", GitTreeState:"dirty", GoVersion:"go1.16.5"}`

I have 3 kind of charts -

- Library Chart
- App Chart (Uses Library Chart as dependecy)
- Umbrella Chart (Has all the app charts as dependencies)

Library chart has value structure like -
----- templates/
----- values.yaml
```
- exports:
     service:
       type: ClusterIP
       port: 9090
```

App Chart has value structure like -
----- templates/
----- values.yaml
```
service:
  type: ClusterIP
  port: 1234
```

Umbrella Chart has value structure like -
----- values/
------- aws/
--------- test.yaml
--------- accp.yaml
              
`helm upgrade --install release release --values aws/test.yaml`, the service port is still used as 9090 and not 1234.

But if I don't pass the custom values file and just use values.yaml in the umbrella chart, the port is getting set to 1234 which is what should be the case even when custom values file(test.yaml) is used.

### PR DESCRIPTION
**Pull request by zegerius**
Fix value precedence when importing values from child, as described in issue https://github.com/helm/helm/issues/9940

**What this PR does / why we need it**:

 Closes https://github.com/helm/helm/issues/9940

**If applicable**:
- [ ] this PR contains documentation
- [x] this PR contains unit tests
- [ ] this PR has been tested for backwards compatibility

### CODE REVIEW

**Comment by bacongobbler** [comment]
Can you please provide a test case to confirm #9940 has been fixed?

**Comment by zegerius** [comment]
@bacongobbler sure, I'll do that tomorrow together with my colleague @ankitabhopatkar13. This was tested against this repository https://github.com/ankitabhopatkar13/helm-values-issue. AFAIK no tests broke, I am not sure how often this code block is hit.

**Comment by zegerius** [comment]
@bacongobbler - @ankitabhopatkar13 and I finalized the test. Output before and after the fix below:

Before fix

```
Running tool: /opt/homebrew/opt/go/libexec/bin/go test -timeout 30s -run ^TestProcessDependencyImportValuesMultiLevelPrecedence$ helm.sh/helm/v3/pkg/chartutil

--- FAIL: TestProcessDependencyImportValuesMultiLevelPrecedence (0.00s)
    /Users/aram/projects/helm/pkg/chartutil/dependencies_test.go:263: failed to match imported float value 9090 with expected 8080
FAIL
FAIL	helm.sh/helm/v3/pkg/chartutil	0.216s
FAIL
```

After fix

```
Running tool: /opt/homebrew/opt/go/libexec/bin/go test -timeout 30s -run ^TestProcessDependencyImportValuesMultiLevelPrecedence$ helm.sh/helm/v3/pkg/chartutil

ok  	helm.sh/helm/v3/pkg/chartutil	0.243s
```

**Comment by zonggen** [comment]
Tested manually with chart from linked issue: https://github.com/ankitabhopatkar13/helm-values-issue

<details><summary>Before fix:</summary>
<p>

```shell
$ helm upgrade --install umbrella umbrella --debug --dry-run

MANIFEST:
---
# Source: umbrella/charts/app1/templates/service.yaml
apiVersion: v1
kind: Service
metadata:
  name: umbrella-app1
  labels:
    helm.sh/chart: app1-0.1.0
    app.kubernetes.io/name: app1
    app.kubernetes.io/instance: umbrella
    app.kubernetes.io/version: "1.16.0"
    app.kubernetes.io/managed-by: Helm
spec:
  type: ClusterIP
  ports:
    - port: 1234
      targetPort: http
      protocol: TCP
      name: http
  selector:
    app.kubernetes.io/name: app1
    app.kubernetes.io/instance: umbrella
---
# Source: umbrella/charts/app2/templates/service.yaml
apiVersion: v1
kind: Service
metadata:
  name: umbrella-app2
  labels:
    helm.sh/chart: app2-0.1.0
    app.kubernetes.io/name: app2
    app.kubernetes.io/instance: umbrella
    app.kubernetes.io/version: "1.16.0"
    app.kubernetes.io/managed-by: Helm
spec:
  type: ClusterIP
  ports:
    - port: 8080
      targetPort: http
      protocol: TCP
      name: http
  selector:
    app.kubernetes.io/name: app2
    app.kubernetes.io/instance: umbrella

$ helm upgrade --install umbrella umbrella --debug --dry-run --values umbrella/values.yaml

MANIFEST:
---
# Source: umbrella/charts/app1/templates/service.yaml
apiVersion: v1
kind: Service
metadata:
  name: umbrella-app1
  labels:
    helm.sh/chart: app1-0.1.0
    app.kubernetes.io/name: app1
    app.kubernetes.io/instance: umbrella
    app.kubernetes.io/version: "1.16.0"
    app.kubernetes.io/managed-by: Helm
spec:
  type: ClusterIP
  ports:
    - port: 9090
      targetPort: http
      protocol: TCP
      name: http
  selector:
    app.kubernetes.io/name: app1
    app.kubernetes.io/instance: umbrella
---
# Source: umbrella/charts/app2/templates/service.yaml
apiVersion: v1
kind: Service
metadata:
  name: umbrella-app2
  labels:
    helm.sh/chart: app2-0.1.0
    app.kubernetes.io/name: app2
    app.kubernetes.io/instance: umbrella
    app.kubernetes.io/version: "1.16.0"
    app.kubernetes.io/managed-by: Helm
spec:
  type: ClusterIP
  ports:
    - port: 9090
      targetPort: http
      protocol: TCP
      name: http
  selector:
    app.kubernetes.io/name: app2
    app.kubernetes.io/instance: umbrella
```
</p>
</details>

<details><summary>After fix:</summary>
<p>

```shell
$ helm upgrade --install umbrella umbrella --debug --dry-run

MANIFEST:
---
# Source: umbrella/charts/app1/templates/service.yaml
apiVersion: v1
kind: Service
metadata:
  name: umbrella-app1
  labels:
    helm.sh/chart: app1-0.1.0
    app.kubernetes.io/name: app1
    app.kubernetes.io/instance: umbrella
    app.kubernetes.io/version: "1.16.0"
    app.kubernetes.io/managed-by: Helm
spec:
  type: ClusterIP
  ports:
    - port: 1234
      targetPort: http
      protocol: TCP
      name: http
  selector:
    app.kubernetes.io/name: app1
    app.kubernetes.io/instance: umbrella
---
# Source: umbrella/charts/app2/templates/service.yaml
apiVersion: v1
kind: Service
metadata:
  name: umbrella-app2
  labels:
    helm.sh/chart: app2-0.1.0
    app.kubernetes.io/name: app2
    app.kubernetes.io/instance: umbrella
    app.kubernetes.io/version: "1.16.0"
    app.kubernetes.io/managed-by: Helm
spec:
  type: ClusterIP
  ports:
    - port: 8080
      targetPort: http
      protocol: TCP
      name: http
  selector:
    app.kubernetes.io/name: app2
    app.kubernetes.io/instance: umbrella

$ helm upgrade --install umbrella umbrella --debug --dry-run --values umbrella/values.yaml

MANIFEST:
---
# Source: umbrella/charts/app1/templates/service.yaml
apiVersion: v1
kind: Service
metadata:
  name: umbrella-app1
  labels:
    helm.sh/chart: app1-0.1.0
    app.kubernetes.io/name: app1
    app.kubernetes.io/instance: umbrella
    app.kubernetes.io/version: "1.16.0"
    app.kubernetes.io/managed-by: Helm
spec:
  type: ClusterIP
  ports:
    - port: 1234
      targetPort: http
      protocol: TCP
      name: http
  selector:
    app.kubernetes.io/name: app1
    app.kubernetes.io/instance: umbrella
---
# Source: umbrella/charts/app2/templates/service.yaml
apiVersion: v1
kind: Service
metadata:
  name: umbrella-app2
  labels:
    helm.sh/chart: app2-0.1.0
    app.kubernetes.io/name: app2
    app.kubernetes.io/instance: umbrella
    app.kubernetes.io/version: "1.16.0"
    app.kubernetes.io/managed-by: Helm
spec:
  type: ClusterIP
  ports:
    - port: 8080
      targetPort: http
      protocol: TCP
      name: http
  selector:
    app.kubernetes.io/name: app2
    app.kubernetes.io/instance: umbrella
```

</p>
</details>

Notice the `helm upgrade --install umbrella umbrella --debug --dry-run --values umbrella/values.yaml` does not set to library default port `9090` after the fix.

I think this fixes the issue and test case passed during local run.

**Comment by zegerius** [comment]
I'll simplify the test data directory. There's a bit too many adjacent things going on there.

**Comment by zegerius** [comment]
Simplified test data. I think it can be merged @bacongobbler @zonggen

**Comment by zonggen** [comment]
Ran the test case and with `helm upgrade`. Looks good from my side.

**Comment by ankitabhopatkar13** [comment]
Hi @mattfarina,

I see this has been marked to 3.8.1 milestone instead of the 3.8.0. Is there anything pending on this MR?

We have to workaround a lot because of this bug and would appreciate it released as soon as possible.

Thanks!

**Review by hickeyma — APPROVED** [review]
LGTM, thanks for the fix @zegerius.

**Review by mattfarina — APPROVED** [review]

**Pull request merged**
