### PR TITLE
tiller grpc message size opt

### LINKED ISSUE #3322: `helm list`error maximum size exceeded
## Problem:
After installing kolla-kubernetes (a collection of helm charts resulting in many releases) and attempting to do a `helm list` from a remote client I receive the following error:

```
Error: grpc: received message larger than max (6645791 vs. 4194304)
```
This problem does not manifest when performing `helm list` on the server.
Currently the count of releases is 16 although I presume it also has to do with release size. Each release is composed of multiple sub-charts.

## Version:
```
Client: &version.Version{SemVer:"v2.7.2", GitCommit:"8478fb4fc723885b155c924d1c8c410b7a9444e6", GitTreeState:"clean"}
Server: &version.Version{SemVer:"v2.7.2", GitCommit:"8478fb4fc723885b155c924d1c8c410b7a9444e6", GitTreeState:"clean"}
```

## Solutions:
Should I look into "chunking" the results as to not exceed the maximum or does someone have a better of idea of how to resolve this issue?

### PR DESCRIPTION
**Pull request by makhov**
We have a lot of releases and in our cluster `helm ls` fails yet:
```
✗ helm ls 
Error: trying to send message larger than max (30334253 vs. 20971520)
✗ helm ls -m 10
	next: api-gateway
NAME                 	REVISION	UPDATED                 	STATUS  	CHART           	NAMESPACE
.... <list of releases>
```

We need to make maxMsgSize configurable.
Fixes #3322

### CODE REVIEW

**Comment by makhov** [comment]
CLA signed

**Comment by bacongobbler** [comment]
This handles server-side, but what about client-side as well?

**Comment by ultimateboy** [comment]
See https://github.com/kubernetes/helm/pull/3782

**Comment by bacongobbler** [comment]
fixed in https://github.com/helm/helm/pull/3782

**Pull request closed without merging**
