### PR TITLE
Adds data processing example

### PR DESCRIPTION
**Pull request by LeendersR**
Adds a data processing example.

Adds rabbitmq and storm templates.

### CODE REVIEW

**Comment by bmelville** [comment]
Hey, the template registry has moved to https://github.com/kubernetes/application-dm-templates, so can you PR the template/ stuff into there instead?

**Comment by bmelville** [comment]
Hey Robert!

Are you going to follow up on this to get it in?

Thanks, and hope all is well,
B.

**Comment by LeendersR** [comment]
Thanks for the reminder!

**Comment by sgoings** [comment]
This should probably be closed, eh @jackgr + @LeendersR?

**Comment by jackgr** [comment]
Actually, it should become a chart. It's been sitting here waiting for
attention, but no need to kill it.

**Pull request closed without merging**
