### PR TITLE
Adding --devel to helm inspect

### PR DESCRIPTION
**Pull request by bridgetkromhout**
Fixes https://github.com/helm/helm/issues/7667

**What this PR does / why we need it**:

When merged, this should resolve the issue opened by @mattfarina requesting that we clarify the v2 docs around `helm inspect`, including the `--devel` flag.

**Special notes for your reviewer**:

Happy to adjust this PR if this is not the correct way to update v2 docs (I know they're a bit of a corner case). Note that I had to add another chart since the mariadb one did not have a devel version available. I also noticed the output for the mariadb one was very outdated so I updated it.

- [X] this PR contains documentation

Signed-off-by: Bridget Kromhout <bridget@kromhout.org>

### CODE REVIEW

**Comment by bridgetkromhout** [comment]
I seem to be getting an error with the linter:

https://app.circleci.com/pipelines/github/helm/helm/834/workflows/ff2db140-a805-4a5e-9728-1485e50e43b8/jobs/12359/steps

```
--- FAIL: TestInvalidYaml (0.00s)
    lint_test.go:84: All didn't fail with expected errors, got []support.Message(nil)
FAIL
FAIL	k8s.io/helm/pkg/lint	0.307s
```

**Comment by bridgetkromhout** [comment]
(I haven't had the bandwidth to get back to this, but I am aware that I have work to do here.)

**Comment by bridgetkromhout** [comment]
I replicated the build locally with this fork/branch, and it does not produce this error (it builds without errors). I get no errors running https://github.com/helm/helm/blob/dev-v2/.circleci/bootstrap.sh locally followed by https://github.com/helm/helm/blob/dev-v2/.circleci/test.sh (which errors on circleci).

Could someone with circleci access see if a re-run helps? Or let me know where my error lies? Thanks!

**Comment by mattfarina** [comment]
@bridgetkromhout I re-ran the tests and they passed. The issue was with gometalinter phoning back to GitHub and that breaking. It wasn't with the content of the PR.

**Review by bacongobbler — APPROVED** [review]

**Pull request merged**
