### PR TITLE
Fix coalesce globals to prevent subchart globals to leak upstream

### LINKED ISSUE #9749: Chart dependencies, erroneous `global` values rendering
I came across a potential bug around `global` values rendering.
I managed to reproduce it with a simple umbrella chart structure  :

```
├── charts
│   ├── helm-inner-one
│   │   ├── charts
│   │   ├── Chart.yaml
│   │   ├── templates
│   │   │   └── test.yaml
│   │   └── values.yaml
│   └── helm-inner-two
│       ├── charts
│       ├── Chart.yaml
│       ├── templates
│       │   └── test.yaml
│       └── values.yaml
├── Chart.yaml
└── values.yaml
``` 

Both *inner* charts have the exact same `test.yaml` file

```yaml
name: {{ .Values.global.common.someValue }}
```

*inner-one* values
```yaml
global:
  common:
    someValue: "inner-one"
```
*inner-two* values
```yaml
global:
  common:
    someValue: "inner-two"
```

*root* chart values
```yaml
global:
  test:
    key: val
  # common:
  #   other: foo
```

Rendering is fine assuming the *root* chart does **NOT** have a `global.common` node
```bash
$ helm template .
---
# Source: test/charts/helm-inner-one/templates/test.yaml
name: inner-one
---
# Source: test/charts/helm-inner-two/templates/test.yaml
name: inner-two
```

If I uncomment *root* chart's `global.common` node, even if it is **NOT** overridding `.Values.global.common.someValue`  but rather `.Values.global.common.other`, values seem conflicting resulting in erroneous rendering

```bash
$ helm template .
---
# Source: test/charts/helm-inner-one/templates/test.yaml
name: inner-one
---
# Source: test/charts/helm-inner-two/templates/test.yaml
name: inner-one
```

Output of `helm version`:
version.BuildInfo{Version:"v3.6.0", GitCommit:"7f2df6467771a75f5646b7f12afb408590ed1755", GitTreeState:"clean", GoVersion:"go1.16.3"}

Output of `kubectl version`: N/A

Cloud Provider/Platform (AKS, GKE, Minikube etc.):  N/A

### PR DESCRIPTION
**Pull request by codeJack**
Signed-off-by: Giacomo Margaria <giacomo.margaria@gmail.com>

**What this PR does / why we need it**:
fixes: #9749
Make sure tables are copied *by value* and NOT *by reference* within `coalesceGlobals`.

**Special notes for your reviewer**:

**If applicable**:
- [ ] this PR contains documentation
- [x] this PR contains unit tests
- [ ] this PR has been tested for backwards compatibility

### CODE REVIEW

**Review by cndoit18 — APPROVED** [review]

**Review by bacongobbler — APPROVED** [review]
Thanks for the tests. Code LGTM. Will need another maintainer's approval as making changes to how Helm coalesces values has introduced many bugs in the past.

**Review by hickeyma — CHANGES_REQUESTED** [review]
@codeJack I tested this with the Helm CLI using the chart example in the description of the issue (https://github.com/helm/helm/issues/9749#issue-905999475) but it seems to be returning unpredictable results every time it is run.

Here is the output from a test I did:

```console
$ for (( c=1; c<=10; c++ )) \
do
echo "———————— Run: $c ————————"
helm template . | grep "Source: test/charts/helm-inner-one/templates/test.yaml" -B 1 -A 5
done

———————— Run: 1 ————————
---
# Source: test/charts/helm-inner-one/templates/test.yaml
name: inner-one
---
# Source: test/charts/helm-inner-two/templates/test.yaml
name: inner-one
---
———————— Run: 2 ————————
---
# Source: test/charts/helm-inner-one/templates/test.yaml
name: inner-one
---
# Source: test/charts/helm-inner-two/templates/test.yaml
name: inner-one
---
———————— Run: 3 ————————
---
# Source: test/charts/helm-inner-one/templates/test.yaml
name: inner-one
---
# Source: test/charts/helm-inner-two/templates/test.yaml
name: inner-one
---
———————— Run: 4 ————————
---
# Source: test/charts/helm-inner-one/templates/test.yaml
name: inner-two
---
# Source: test/charts/helm-inner-two/templates/test.yaml
name: inner-two
---
———————— Run: 5 ————————
---
# Source: test/charts/helm-inner-one/templates/test.yaml
name: inner-one
---
# Source: test/charts/helm-inner-two/templates/test.yaml
name: inner-one
---
———————— Run: 6 ————————
---
# Source: test/charts/helm-inner-one/templates/test.yaml
name: inner-two
---
# Source: test/charts/helm-inner-two/templates/test.yaml
name: inner-two
---
———————— Run: 7 ————————
---
# Source: test/charts/helm-inner-one/templates/test.yaml
name: inner-one
---
# Source: test/charts/helm-inner-two/templates/test.yaml
name: inner-one
---
———————— Run: 8 ————————
---
# Source: test/charts/helm-inner-one/templates/test.yaml
name: inner-one
---
# Source: test/charts/helm-inner-two/templates/test.yaml
name: inner-one
---
———————— Run: 9 ————————
---
# Source: test/charts/helm-inner-one/templates/test.yaml
name: inner-two
---
# Source: test/charts/helm-inner-two/templates/test.yaml
name: inner-two
---
———————— Run: 10 ————————
---
# Source: test/charts/helm-inner-one/templates/test.yaml
name: inner-one
---
# Source: test/charts/helm-inner-two/templates/test.yaml
name: inner-one
---
```

Do you mind testing it in a loop and see if the results are consistent as expected?

**Comment by hickeyma** [comment]
My apologises @codeJack. I realized that I was referencing an old `helm` binary and not using your fix. My bad. This looks good to me.

**Review by hickeyma — APPROVED** [review]
LGTM, thanks for the fix @codeJack

**Comment by codeJack** [comment]
Thanks @hickeyma

**Comment by bacongobbler** [comment]
@codeJack would you mind looking into #10154 and see if your commit introduced a regression? If not, can you please provide the user a solution? Thanks.

**Pull request merged**
