### PR TITLE
fix(scripts): fix kube-dns

### PR DESCRIPTION
**Pull request by adamreese**

### CODE REVIEW

**Comment by michelleN** [comment]
fixes the dns issue?

**Comment by adamreese** [comment]
@michelleN needs testing

**Comment by michelleN** [comment]
```
helm [fix/kube-dns*]$ ./scripts/kube-up.sh
Verifying Prerequisites....
You are golden, carry on...
Adding iptables hackery for docker-machine...
Getting the party going...
8057577b11bd1705b4579104174aff732bb31e5ea3104f121dab77fc6a87a85d
Waiting for Kubernetes cluster to become available...
Kubernetes cluster is up.
Creating kube-system namespace...
namespace "kube-system" created
Setting up internal dns...
replicationcontroller "kube-dns-v10" created
service "kube-dns" created
cluster "docker" set.
context "docker" set.
switched to context "docker".
Wrote config for docker
Kubernetes master is running at 192.168.99.100:8080
KubeDNS is running at 192.168.99.100:8080/api/v1/proxy/namespaces/kube-system/services/kube-dns
helm [fix/kube-dns*]$ docker ps
CONTAINER ID        IMAGE                                             COMMAND                  CREATED             STATUS                  PORTS               NAMES
fb3f5ed33240        gcr.io/google_containers/exechealthz:1.0          "/exechealthz '-cmd=n"   3 seconds ago       Up Less than a second                       k8s_healthz.ded80efe_kube-dns-v10-9n5vp_kube-system_9e6ee632-fcf3-11e5-be30-4a4477cac450_9dd5888e
780d9cc68be9        quay.io/adamreese/resourcifier:latest             "/bin/resourcifier --"   7 seconds ago       Up 6 seconds                                k8s_resourcifier.4bbb3ca6_resourcifier-rc-r9leo_helm_0b220c23-fc34-11e5-aa54-4a4477cac450_f28a4907
fbb7b6a40adf        quay.io/adamreese/resourcifier:latest             "/bin/resourcifier --"   9 seconds ago       Up 8 seconds                                k8s_resourcifier.4bbb3ca6_resourcifier-rc-crbd1_helm_0b2204ad-fc34-11e5-aa54-4a4477cac450_de2ec009
30b3fe696d1b        quay.io/adamreese/expandybird:latest              "/bin/expandybird -ex"   11 seconds ago      Up 10 seconds                               k8s_expandybird.a9e53b3e_expandybird-rc-guhpe_helm_0b150088-fc34-11e5-aa54-4a4477cac450_0b89090e
9fa953676641        quay.io/adamreese/manager:latest                  "/bin/manager --kubec"   12 seconds ago      Up 12 seconds                               k8s_manager.71223601_manager-rc-f71se_helm_0b468531-fc34-11e5-aa54-4a4477cac450_ccb7af19
9869947d0282        quay.io/adamreese/expandybird:latest              "/bin/expandybird -ex"   14 seconds ago      Up 13 seconds                               k8s_expandybird.a9e53b3e_expandybird-rc-jt84z_helm_0b150e8d-fc34-11e5-aa54-4a4477cac450_f25f6fc1
7b2b99832beb        gcr.io/google_containers/pause:2.0                "/pause"                 16 seconds ago      Up 15 seconds                               k8s_POD.e2764897_kube-dns-v10-9n5vp_kube-system_9e6ee632-fcf3-11e5-be30-4a4477cac450_9684abf3
a5a0614f6469        gcr.io/google_containers/pause:2.0                "/pause"                 17 seconds ago      Up 16 seconds                               k8s_POD.a71a056f_expandybird-rc-guhpe_helm_0b150088-fc34-11e5-aa54-4a4477cac450_0c7fd258
d63fde97b555        gcr.io/google_containers/pause:2.0                "/pause"                 17 seconds ago      Up 16 seconds                               k8s_POD.e60d05e7_resourcifier-rc-r9leo_helm_0b220c23-fc34-11e5-aa54-4a4477cac450_60ec07c1
30b5566d521c        gcr.io/google_containers/pause:2.0                "/pause"                 17 seconds ago      Up 16 seconds                               k8s_POD.e60d05e7_resourcifier-rc-crbd1_helm_0b2204ad-fc34-11e5-aa54-4a4477cac450_1ffe2d42
1df0c46017fa        gcr.io/google_containers/pause:2.0                "/pause"                 17 seconds ago      Up 16 seconds                               k8s_POD.f48203b0_manager-rc-f71se_helm_0b468531-fc34-11e5-aa54-4a4477cac450_cf84bd12
1db59e4dba0e        gcr.io/google_containers/pause:2.0                "/pause"                 17 seconds ago      Up 16 seconds                               k8s_POD.a71a056f_expandybird-rc-jt84z_helm_0b150e8d-fc34-11e5-aa54-4a4477cac450_1c09aaf2
889469907f02        gcr.io/google_containers/hyperkube-amd64:v1.2.0   "/hyperkube controlle"   20 seconds ago      Up 19 seconds                               k8s_controller-manager.69f14b63_k8s-master-127.0.0.1_default_a61437d0ef757ee8c4f6fcc7a34bdeaa_4b1bddf6
aa5c6b9413df        gcr.io/google_containers/hyperkube-amd64:v1.2.0   "/setup-files.sh IP:1"   20 seconds ago      Up 19 seconds                               k8s_setup.dfd03214_k8s-master-127.0.0.1_default_a61437d0ef757ee8c4f6fcc7a34bdeaa_65274dde
772fb66fcf4c        gcr.io/google_containers/hyperkube-amd64:v1.2.0   "/hyperkube scheduler"   21 seconds ago      Up 20 seconds                               k8s_scheduler.f758fcbc_k8s-master-127.0.0.1_default_a61437d0ef757ee8c4f6fcc7a34bdeaa_c3ba742c
001c2dccec9e        gcr.io/google_containers/etcd:2.2.1               "/usr/local/bin/etcd "   21 seconds ago      Up 20 seconds                               k8s_etcd.7e452b0b_k8s-etcd-127.0.0.1_default_1df6a8b4d6e129d5ed8840e370203c11_f671f126
fbab0abe37d0        gcr.io/google_containers/hyperkube-amd64:v1.2.0   "/hyperkube apiserver"   21 seconds ago      Up 20 seconds                               k8s_apiserver.fe8bc1dc_k8s-master-127.0.0.1_default_a61437d0ef757ee8c4f6fcc7a34bdeaa_73687088
07c5adf30e4b        gcr.io/google_containers/hyperkube-amd64:v1.2.0   "/hyperkube proxy --m"   21 seconds ago      Up 20 seconds                               k8s_kube-proxy.943d4851_k8s-proxy-127.0.0.1_default_5d1227af0f6b212c3e3877d336f3623b_550bb844
73e22aa789db        gcr.io/google_containers/pause:2.0                "/pause"                 21 seconds ago      Up 20 seconds                               k8s_POD.6059dfa2_k8s-master-127.0.0.1_default_a61437d0ef757ee8c4f6fcc7a34bdeaa_1df427ce
0fcebf14f7ca        gcr.io/google_containers/pause:2.0                "/pause"                 21 seconds ago      Up 20 seconds                               k8s_POD.6059dfa2_k8s-etcd-127.0.0.1_default_1df6a8b4d6e129d5ed8840e370203c11_d1a0ec54
832d3c8c8ff4        gcr.io/google_containers/pause:2.0                "/pause"                 21 seconds ago      Up 20 seconds                               k8s_POD.6059dfa2_k8s-proxy-127.0.0.1_default_5d1227af0f6b212c3e3877d336f3623b_9cb83268
8057577b11bd        gcr.io/google_containers/hyperkube-amd64:v1.2.0   "/hyperkube kubelet -"   29 seconds ago      Up 28 seconds                               helm_kubelet
```

**Comment by technosophos** [comment]
Pulled my LGTM because I figured @michelleN is already commenting. I don't see any issues on my end,

**Comment by michelleN** [comment]
All good from my end. :+1:

**Comment by adamreese** [comment]
made a few more fixes, give another try before I merge

**Comment by michelleN** [comment]
works! woot. 
```
helm [feat/e2e-test]$ kubectl exec -it alpine -- nslookup google.com
Server:    (null)
Address 1: ::1 localhost
Address 2: 127.0.0.1 localhost

Name:      google.com
Address 1: 172.217.2.46 nuq05s02-in-f14.1e100.net
Address 2: 2607:f8b0:4005:802::200e nuq05s02-in-x0e.1e100.net
```

**Pull request merged**
