### PR TITLE
Add App Version to the helm ls command.

### PR DESCRIPTION
**Pull request by derekbassett**

### CODE REVIEW

**Comment by derekbassett** [comment]
I'm talking to my company about getting me added to cncf for the CLA agreement.

**Comment by derekbassett** [comment]
This will add the feature requested https://github.com/kubernetes/helm/issues/3592

**Comment by bjornmagnusson** [comment]
Look great, I was the one requested that feature in the #3592.
Just tried this PR out, works according to my wish :)

**Comment by bacongobbler** [comment]
should we close this in favour of #3903?

**Comment by derekbassett** [comment]
When I rebased this something went wrong.  I have reapplied my changes and generated this https://github.com/kubernetes/helm/pull/3903 PR

**Pull request closed without merging**
