### PR TITLE
chore(deps): bump xstrings dependency

### PR DESCRIPTION
**Pull request by ivankatliarchuk**
While maintaining helm-unittest project, we reveal that there is a change in behaviour https://github.com/helm-unittest/helm-unittest/issues/359

**What this PR does / why we need it**:

current camelCase function is actually returns a PascalCase, so there is a fix for that and new function is added e.g. PascalCase

The dependency `github.com/huandu/xstrings` not being updated for 18 months.
Screenshot 2024-08-12 at 08 40 38

**Special notes for your reviewer**:

There is a breaking change. Release notes https://github.com/huandu/xstrings/releases. Might as well bump this now. We're gonna have to do it eventually, so why not get it over with sooner rather than later?

The documentation need to be updated. Pleas guide me what need to be done as well

Screenshot 2024-08-10 at 15 55 12

**If applicable**:
- [x] this PR contains user facing changes (the `docs needed` label should be applied if so)
- [ ] this PR contains unit tests
- [ ] this PR has been tested for backwards compatibility

### CODE REVIEW

**Comment by yxxhero** [comment]
@ivankatliarchuk any user case changed?

**Comment by ivankatliarchuk** [comment]
Apologies, I did not get that. The output of cameCase function has changed e.g. test -> `Test` now `test` and `test_this` -> `TestThis` when now `testThis`

**Comment by ivankatliarchuk** [comment]
No user case changed

**Comment by ivankatliarchuk** [comment]
Most likely there is a user-facing change as behavior of cameCase function changed

**Review by robertsirc — APPROVED** [review]
LGTM. For the maintainers [here](https://github.com/huandu/xstrings/releases/tag/v1.5.0) is the release of 1.5.0. I want to note this is a breaking change in this package. I searched helm for all of the contract changes and I was not able to find any with the search tools with both VSCode and GoLand.

**Review by robertsirc — CHANGES_REQUESTED** [review]
This dependency is within another project called sprig we would need to upgrade it there.

**Comment by ivankatliarchuk** [comment]
Sprig library is unmaintained, last release was 2+ years ago. I you have a look, helm does indirect dependency bump and original dependency version is `ithub.com/huandu/xstrings v1.3.3`. So there are two action items
1. Bump it here
2. And ideally migrate away

**Comment by mattfarina** [comment]
sprig is owned by maintainers of Helm. There isn't really an alternative to migrate to as most of the Helm template functions are provided by sprig. There will be an updated release coming soon.

**Comment by mattfarina** [comment]
Note, updating xstrings in place will cause a breaking change in the template functions that Helm provides to charts. What charts used to get as output will be different. We should not update xstrings until spring handles this situation.

**Comment by ivankatliarchuk** [comment]
Thanks for looking into this.

**Comment by ivankatliarchuk** [comment]
Shell I close this pull request?

**Comment by mattfarina** [comment]
Closing this issue as spig was updated which caused xstrings to be updated.

Sprig was updated in a way that the feature, as it is exposed to end users, has not changed. So, there is no breaking change for Helm.

**Comment by ivankatliarchuk** [comment]
Thanks we are testing it on our side

**Pull request closed without merging**
