### PR TITLE
chore(*): Re-enable style conformance test in circleci build

### PR DESCRIPTION
**Pull request by hickeyma**
Style conformance test was not enabled in v3. This PR enables it.

**What this PR does / why we need it**:
Tests Go style in circleci build to identify any breaking changes for dev unit test environment.  

**Special notes for your reviewer**:
Have added back in calling `.circleci/test.sh` for test as script calls `test-style`. @adamreese What was the reason for removing it? 

**If applicable**:
- [ ] this PR contains documentation
- [ ] this PR contains unit tests
- [ ] this PR has been tested for backwards compatibility

### CODE REVIEW

**Review by bacongobbler — CHANGES_REQUESTED** [review]
I still think we want coveralls integration as part of the CI build. This allows us to check how much of the codebase is covered by unit tests. Can we add back the conformance tests without removing coveralls support?

cc @adamreese as he was working on adding coveralls support to Helm 3 so we knew where our coverage gaps were.

**Comment by hickeyma** [comment]
@bacongobbler Is it because it won't call this as we are on the `dev-v3` branch:

```
if [[ "${CIRCLE_BRANCH-}" == "master" ]]; then
    echo "Running unit tests with coverage'"
    ./scripts/coverage.sh --coveralls
```

**Comment by bacongobbler** [comment]
that should probably be fixed, most likely just an oversight on our part.

**Comment by hickeyma** [comment]
@bacongobbler Gone with adding a step to circleci for test style. I removed the `test.sh` script to see if it is still used.

**Review by bacongobbler — APPROVED** [review]

**Review by adamreese — APPROVED** [review]

**Pull request merged**
