### PR TITLE
feat(comp): Dynamic completion for --output flag

### PR DESCRIPTION
**Pull request by marckhouzam**
**What this PR does / why we need it**:

This PR adds shell completion for the `--output` flag.  For example a user could now do:
```
helm repo list --output <TAB>
```
and will then be given the choices:
```
json   table  yaml
```
This works for the `--output` flag of any command that supports it.

**Special notes for your reviewer**:

I don't like that the three values `json table yaml` are hard-coded in the completion logic.  If a new format is ever added, it is likely that the completion code will be forgotten and not updated.  I would have preferred to create the list of choices by looping through the "enum" of formats.  However, I don't believe this is feasible with the current implementation of the output formats which are unrelated string contants.  Doing something with `iota` would be possible, but would require multiple changes in the output format code.

What I did instead is that the acceptance test will generate the expected completion (`json table yaml`  for now) output based on the help text of the `--output` flag.  I feel this help text has a better chance of being updated than the completion code.  So, if an extra format is added, the acceptance tests will fail if the completion code is not matching the help text for the `--output` flag.

**If applicable**:
- this PR has been tested for backwards compatibility through the acceptance-testing repo
- new tests for this feature have been prepared in https://github.com/helm/acceptance-testing/pull/51

### CODE REVIEW

**Review by hickeyma — COMMENTED** [review]
Thanks for this @marckhouzam. Can you squash your commits as it would help reviewing?

**Review by bacongobbler — APPROVED** [review]

**Comment by hickeyma** [comment]
Can we wait to merge until commits are squashed?

**Comment by bacongobbler** [comment]
Yes absolutely. Alternatively, github allows you to "squash and merge" pull requests if you wish.

image

**Comment by hickeyma** [comment]
sure do, just wanted to test against the the branch manually and having problems with the commits

**Comment by marckhouzam** [comment]
Squashed.

**Comment by bacongobbler** [comment]
thanks @marckhouzam! I'll let @hickeyma merge this one. :)

**Review by hickeyma — APPROVED** [review]
LGTM, thanks @marckhouzam

**Pull request merged**
