### PR TITLE
fix(helm): Fixed semantic version constraints on 'search' command

### PR DESCRIPTION
**Pull request by mparry**
This addresses #3115. I have illustrated the change in a comment there.

### CODE REVIEW

**Comment by thomastaylor312** [comment]
@mparry Thanks for the patch! We'll need you to sign the CLA before we move forward with this

**Comment by mparry** [comment]
Sorry, I'm just waiting for it to be approved for our organisation; shouldn't be long!

**Comment by mparry** [comment]
Bump to trigger CLA check

**Review by technosophos — APPROVED** [review]
LGTM. Thanks for the good test coverage, too.

**Comment by technosophos** [comment]
Note: This one was mis-labeled as a M because so many new tests were added. _That_ is the kind of problem I _like_ to have.

**Pull request merged**
