### PR TITLE
fix(repo/search): fix helm repo search command to display proper versions

### LINKED ISSUE #6712: Inconsistency between helm search and helm install
In the Service Catalog, one of our users reported inconsistency between the `helm search` and `helm install`: https://github.com/kubernetes-sigs/service-catalog/issues/2725

**TL;DR**

`helm search` shows version 0.3.0-beta.1 (the newest one), but `helm install` installs the 0.2.1 version (the old one).

**How to reproduce**
```
helm repo add svc-cat https://svc-catalog-charts.storage.googleapis.com

helm repo add svc-cat https://svc-catalog-charts.storage.googleapis.com
"svc-cat" has been added to your repositories

helm search service-catalog
NAME                     	CHART VERSION	APP VERSION	DESCRIPTION
svc-cat/catalog          	0.3.0-beta.1 	           	service-catalog webhook server and controller-manager hel...

helm install svc-cat/catalog \
>     --name catalog --namespace catalog

helm list
NAME                	REVISION	UPDATED                 	STATUS  	CHART                         	APP VERSION	NAMESPACE           
catalog             	1       	Mon Oct  7 09:55:27 2019	DEPLOYED	**catalog-0.2.1**                 	           	catalog             
```

**Investigation**

The `helm search` strategy just grabs the 0 entry from the index file:
https://github.com/helm/helm/blob/9668ad4d90c5e95bd520e58e7387607be6b63bb6/cmd/helm/search/search.go#L71-L73

but the `helm install` uses the `"github.com/Masterminds/semver"` lib to check which version should be installed:
https://github.com/helm/helm/blob/9668ad4d90c5e95bd520e58e7387607be6b63bb6/pkg/repo/index.go#L180-L188

the constraint is defined as `semver.NewConstraint("*")` so it will skip prereleases when looking at the list of releases while `>=0.0.0-0` will evaluate and find prereleases.

In `helm install` documentation there is this statement:
> (..)It will install the latest version of that chart unless you also supply a version number with the '--version' flag.

_source: https://github.com/helm/helm/blob/release-2.15/docs/helm/helm_install.md_

**Expected behavior**
The `helm search` and `helm install` should be consistent. Additionally, documentation should be adjusted to clearly say that pre-releases are skipped or alternatively the constraint in source code should be changed to match also the pre-release versions.
 
---

Output of `helm version`:

```
Client: &version.Version{SemVer:"v2.14.0", GitCommit:"05811b84a3f93603dd6c2fcfe57944dfa7ab7fd0", GitTreeState:"clean"}
```

Output of `kubectl version`:
`not applicable`

Cloud Provider/Platform (AKS, GKE, Minikube etc.): 
`not applicable`

### PR DESCRIPTION
**Pull request by mszostok**
**Description**
Fix the helm repo search command to display proper versions. 

Changes proposed in this pr:

- Adjust documentation to clearly state about installed/displayed versions.
- Introduce the `--devel` flag for `helm repo search` command.

**Current behavior:** 
```shell
# Searches only for stable releases, prerelease versions will be skipped
$ helm search repo
 
# Searches for releases and prereleases (alpha, beta, and release candidate releases)
$ helm search repo --devel

# Searches only for release in version 1.0.0
$ helm search repo --version 1.0.0
```
Signed-off-by: Mateusz Szostok <szostok.mateusz@gmail.com>

Fixes: https://github.com/helm/helm/issues/6712

### CODE REVIEW

**Review by bacongobbler — APPROVED** [review]

**Comment by bacongobbler** [comment]
thanks for the tests. LGTM.

**Comment by marckhouzam** [comment]
@mszostok It's hard to keep track but the command is actually `helm search repo`.  In the new help text your examples are reversed and say `helm repo search`.  I'd suggest a new PR to adjust.  Thanks.

**Comment by bacongobbler** [comment]
good catch, @marckhouzam. I'll go fix that up.

**Comment by mszostok** [comment]
@bacongobbler @marckhouzam, here is the PR with the fix: https://github.com/helm/helm/pull/6785

sorry for that 🤦‍♂

**Pull request merged**
