### PR TITLE
v2: fix(completion): --flag=val breaks zsh completion

### PR DESCRIPTION
**Pull request by marckhouzam**
**What this PR does / why we need it**:

zsh completion cannot handle the flag format --flag=val.

**Special notes for your reviewer**:

This is a bug I ran into when working on Helm completion.
I was surprised that it didn't happen when I was using
kubectl, so I investigated and found a PR that fixed this
bug in kubectl:
https://github.com/kubernetes/kubernetes/pull/48553

I've marked the original author, @superbrothers , as a co-author to this PR.

I duplicated the code in this commit which:

Removes __helm_declare, which is safe to do since
`declare -F` is already replaced to `whence -w` by
__helm_convert_bash_to_zsh().

The problem was that calling "declare" from inside a function
scopes the declaration to that function only.  So "declare"
should not be called through __helm_declare() but instead
directly.

To reproduce:
1- setup helm completion in zsh
2- helm --kubeconfig=$HOME/.kube/config statu\<TAB\>

you will get the error:
__helm_handle_flag:27: bad math expression: operand expected at end of string

Co-authored-by: Kazuki Suda <kazuki.suda@gmail.com>
Signed-off-by: Marc Khouzam <marc.khouzam@ville.montreal.qc.ca>

I realized that this bug was also the root of the problem of #5046.  With this PR
fixing the issue in the proper way,  I've added a commit to remove
the previous fix for #5046 (PR #5072 and #5406). 

However, for completely other reasons, we still need to remove the quotes from the aliashash associative array in zsh.  I've therefore put it back.

### CODE REVIEW

**Review by eddiezane — APPROVED** [review]
LGTM. Should be the actual fix. Same thing I did in https://github.com/digitalocean/doctl/pull/403 albeit I didn't quite understand it at the time.

**Comment by marckhouzam** [comment]
@eddiezane you may be interested in applying a similar commit as https://github.com/helm/helm/pull/5680/commits/48f0e3101d49a3de1466ff75fc786ce012f369cc for doctl if you use command aliases.

**Comment by hickeyma** [comment]
@marckhouzam Try doing a forced push to do a rebuild.

**Comment by allamand** [comment]
I run on this problem, would this fix be merged ?

**Comment by marckhouzam** [comment]
The https://github.com/helm/acceptance-testing repo can help maintainers get a feel that this change is safe.

If you run the completion tests on the master branch now they will pass.
If you run them again after applying this PR they will fail with an UNEXPECTED SUCCESS.
This is because this PR fixes a specific test that was marked as a known failure.
The PR to mark the test as expected to pass is ready here https://github.com/helm/acceptance-testing/pull/35

(I know this PASS -> FAIL after a PR is merged is not ideal, but with the tests being in a different repo, it is difficult to handle corresponding PRs).

For helm v2, to run the completion tests you can do the following.
(there is a PR to make it easier #6388 )

```
make && make build-cross && cd $GOPATH/src/helm.sh/acceptance-testing && \
ROBOT_RUN_TESTS=shells.robot ROBOT_HELM_PATH=$GOPATH/src/k8s.io/helm/bin make; cd -
```

**Comment by marckhouzam** [comment]
@mattfarina As discussed, this PR is important to eventually get v2 auto-complete to play well with v3 auto-complete during the migration period.
The change of this PR is the same as #6389 which was merged in v3

**Review by bacongobbler — APPROVED** [review]
Nice catch! LGTM

**Pull request merged**
