### PR TITLE
Document the HELM_TLS_HOSTNAME variable in 'helm --help'

### LINKED ISSUE #5120: Feature: TILLER_TLS_HOSTNAME environment variable for '--tls-hostname'
Thank you for [this handy patch](#4444) @bacongobbler. Quite often you don't know the domain name of Tiller until after it is deployed, so too late to easily change the certificate (though possible with a `cert-manager` private CA), and this option addresses that. The `--tls-hostname` option can be set at run time so that fixes that and enables tiller verification.

It would be helpful if there was a matching environment variable for `--tls-hostname` e.g. `TILLER_TLS_HOSTNAME`. That would allow the entire TLS configuration to be in the environment, without have to inject command line options in CI/CD tasks.

Output of `helm version`:
```
Client: &version.Version{SemVer:"v2.12.1", GitCommit:"02a47c7249b1fc6d8fd3b94e6b4babf9d818144e", GitTreeState:"clean"}
Server: &version.Version{SemVer:"v2.12.1", GitCommit:"02a47c7249b1fc6d8fd3b94e6b4babf9d818144e", GitTreeState:"clean"}
```
Output of `kubectl version`:
```
Client Version: version.Info{Major:"1", Minor:"12", GitVersion:"v1.12.4", GitCommit:"f49fa022dbe63faafd0da106ef7e05a29721d3f1", GitTreeState:"clean", BuildDate:"2018-12-14T07:10:00Z", GoVersion:"go1.10.4", Compiler:"gc", Platform:"linux/amd64"}
Server Version: version.Info{Major:"1", Minor:"11+", GitVersion:"v1.11.5-gke.5", GitCommit:"9aba9c1237d9d2347bef28652b93b1cba3aca6d8", GitTreeState:"clean", BuildDate:"2018-12-11T02:36:50Z", GoVersion:"go1.10.3b4", Compiler:"gc", Platform:"linux/amd64"}
```
Cloud Provider/Platform (AKS, GKE, Minikube etc.):  GKE

### PR DESCRIPTION
**Pull request by whereisaaron**
Closes #5120
Also adjusted order `ENABLE` -> `VERIFY` -> `HOSTNAME`

### CODE REVIEW

**Review by bacongobbler — APPROVED** [review]

**Review by michelleN — APPROVED** [review]

**Comment by michelleN** [comment]
@whereisaaron looks like CircleCI is failing. I wonder if we need to run a `make docs` before pushing. Could you try that? In the meantime, we can try re-running the build.

**Review by michelleN — COMMENTED** [review]
@whereisaaron looks like CircleCI is failing. I wonder if we need to run a make docs before pushing. Could you try that? In the meantime, we can try re-running the build.

**Comment by whereisaaron** [comment]
Thanks for checking it @michelleN. Shouldn't `make docs` be run as part of the build?

I checked, and in order to run `make docs` you need to build the entire application, and I don't have a whole existing environment for `helm`. It seems to me it should be CI's job to run `make docs`?

**Comment by bacongobbler** [comment]
CI just checks that the docs have been validated and the unit tests are passing. In an ideal world, we'd have CI auto-generate the docs and commit to master, but for now we ask the user to generate them beforehand.

If you're unable to do that, we can rebase this PR and do it from one of our machines. Just let us know how you'd like to proceed.

**Comment by bacongobbler** [comment]
ping @whereisaaron, are you able to commit the output of `make docs` or would you like us to take this over the finish line?

**Comment by whereisaaron** [comment]
Thanks, I'll take a look tomorrow, do it in a quick build container.

**Review by bacongobbler — APPROVED** [review]

**Pull request merged**
