### PR TITLE
ref(wait): consolidate switch cases

### LINKED ISSUE #6440: [Helm 3] I have a question about 'switch ... case ' syntax
- https://github.com/helm/helm/blob/5cb923eecbe80d1ad76399aee234717c11931d9a/pkg/kube/wait.go#L67
- https://github.com/helm/helm/blob/5cb923eecbe80d1ad76399aee234717c11931d9a/pkg/kube/wait.go#L80
- https://github.com/helm/helm/blob/5cb923eecbe80d1ad76399aee234717c11931d9a/pkg/kube/wait.go#L93
- https://github.com/helm/helm/blob/5cb923eecbe80d1ad76399aee234717c11931d9a/pkg/kube/wait.go#L106

Wondering why not use syntax as follow

```go
...
            switch value := AsVersioned(v).(type) {
            case *corev1.Pod:
              ...
            case *appsv1.Deployment, *appsv1beta1.Deployment, *appsv1beta2.Deployment, *extensionsv1beta1.Deployment:
              ...
              ...
            }
```

### PR DESCRIPTION
**Pull request by bacongobbler**
supersedes #6449 
closes #6440

### CODE REVIEW

**Review by hickeyma — CHANGES_REQUESTED** [review]
Refactor looks good so far, thanks @bacongobbler. I think some refactor could also be done here: https://github.com/helm/helm/blob/dev-v3/pkg/kube/wait.go#L377

**Comment by bacongobbler** [comment]
nicely caught, @hickeyma. I ignored it for the time being but I think it's worth looking at again now that we have a better understanding of how it's used. I'll see what I can do.

**Comment by bacongobbler** [comment]
@hickeyma so here's what the code would look like if we refactored that one:

```
	// ew ew ew ew ew ew
	_, isAppsv1ReplicaSet := object.(*appsv1.ReplicaSet)
	_, isAppsv1beta2ReplicaSet := object.(*appsv1beta2.ReplicaSet)
	_, isExtensionsv1beta1ReplicaSet := object.(*extensionsv1beta1.ReplicaSet)
	_, isAppsv1StatefulSet := object.(*appsv1.StatefulSet)
	_, isAppsv1beta1StatefulSet := object.(*appsv1beta1.StatefulSet)
	_, isAppsv1beta2StatefulSet := object.(*appsv1beta2.StatefulSet)
	_, isAppsv1DaemonSet := object.(*appsv1.DaemonSet)
	_, isAppsv1beta2DaemonSet := object.(*appsv1beta2.DaemonSet)
	_, isExtensionsv1beta1DaemonSet := object.(*extensionsv1beta1.DaemonSet)
	_, isAppsv1Deployment := object.(*appsv1.Deployment)
	_, isAppsv1beta1Deployment := object.(*appsv1beta1.Deployment)
	_, isAppsv1beta2Deployment := object.(*appsv1beta2.Deployment)
	_, isExtensionsv1beta1Deployment := object.(*extensionsv1beta1.Deployment)
	_, isBatchv1Job := object.(*batchv1.Job)
	_, isCorev1ReplicationController := object.(*corev1.ReplicationController)
	_, isCorev1Service := object.(*corev1.Service)

	switch {
		case isAppsv1ReplicaSet, isAppsv1beta2ReplicaSet, isExtensionsv1beta1ReplicaSet, isAppsv1StatefulSet, isAppsv1beta1StatefulSet, isAppsv1beta2StatefulSet, isAppsv1DaemonSet, isAppsv1beta2DaemonSet, isAppsv1beisExtensionsv1beta1DaemonSetta2DaemonSet
	}
```

Not much of a gain if we went that route :(

**Review by thomastaylor312 — APPROVED** [review]
Thanks for doing this. Been meaning to do this for a while

**Review by hickeyma — COMMENTED** [review]
Maybe I am reading this incorrectly but I thought this:

```
case *extensionsv1beta1.ReplicaSet:
		selector, err = metav1.LabelSelectorAsSelector(t.Spec.Selector)
case *appsv1.ReplicaSet:
		selector, err = metav1.LabelSelectorAsSelector(t.Spec.Selector)
case *appsv1beta2.ReplicaSet:
		selector, err = metav1.LabelSelectorAsSelector(t.Spec.Selector)
case *appsv1.StatefulSet:
		selector, err = metav1.LabelSelectorAsSelector(t.Spec.Selector)
case *appsv1beta1.StatefulSet:
		selector, err = metav1.LabelSelectorAsSelector(t.Spec.Selector)
case *appsv1beta2.StatefulSet:
		selector, err = metav1.LabelSelectorAsSelector(t.Spec.Selector)
case *extensionsv1beta1.DaemonSet:
		selector, err = metav1.LabelSelectorAsSelector(t.Spec.Selector)
case *appsv1beta2.DaemonSet:
		selector, err = metav1.LabelSelectorAsSelector(t.Spec.Selector)
case *extensionsv1beta1.Deployment:
		selector, err = metav1.LabelSelectorAsSelector(t.Spec.Selector)
case *batchv1.Job:
		selector, err = metav1.LabelSelectorAsSelector(t.Spec.Selector)
```

could be refactored to:

```
case *extensionsv1beta1.ReplicaSet, *appsv1.ReplicaSet, *appsv1beta2.ReplicaSet, *appsv1.StatefulSet, *appsv1beta1.StatefulSet, *appsv1beta2.StatefulSet, *extensionsv1beta1.DaemonSet, *appsv1beta2.DaemonSet, *extensionsv1beta1.Deployment, *batchv1.Job:
               selector, err = metav1.LabelSelectorAsSelector(t.Spec.Selector)
```

**Comment by bacongobbler** [comment]
I just tried that unfortunately. As mentioned in #6449, `t` would be casted to a `runtime.Object`, which does not have a way of accessing `.Spec`, so you'd run into a compiler error.

**Review by hickeyma — APPROVED** [review]
LGTM, thanks @bacongobbler

**Pull request merged**
