### PR TITLE
Fix rename for helm dep upgrade. For issue #2998

### PR DESCRIPTION
**Pull request by ghost**
helm dependency upgrade wasn't working on certain file system because it assumes that os.rename is available. Since rename isn't available for subfolders in docker containers, I ripped a fallback rename strategy from [dep](https://github.com/golang/dep/blob/5b1fe9e6d89372487d0aac78d9c5362a517857e7/internal/fs/fs.go#L103-L118) that works in docker. I wasn't able to reference this package as a dependency because it is an internal package in dep.

This is my first submission to the open source community, so please let me know if committing this fs package from golang/dep is the wrong approach, or if something in their license prohibits this.

https://github.com/golang/dep

### CODE REVIEW

**Comment by bacongobbler** [comment]
We might need CNCF's legal team to have a look at this. cc @michelleN

**Comment by bricerisingslalom** [comment]
I'm a little confused, I've fixed both of the gofmt issues locally with `gofmt -s -w file.go`, but circleci still says that they're failing the style check.

**Comment by bricerisingslalom** [comment]
I ran gofmt -s -w with the official golang docker image and managed to get the format that circleci is expecting. Now I'm getting the same licensing issue in my circleci build that I'm getting locally.

**Comment by bricerisingslalom** [comment]
Is there anything I can do to help get this merged? If there's a contact on the CNCF legal team that I can talk to, I would be happy to start communications

**Comment by bacongobbler** [comment]
Not much at this time other than getting the tests to pass. We have all been away at kubecon for the past week.

**Comment by bricerisingslalom** [comment]
Oh ok, I hope the conference was great!

The only thing that appears to be failing as far as I can tell is the linter that looks for the apache license. Should I commit that line to each file before we hear back about whether we're allowed to use this code?

**Comment by bricerisingslalom** [comment]
I noticed that this package also reuses code licensed under a BSD style license, I've copied the approach used in that package and now it's passing the linter

https://github.com/helm/helm/blob/master/pkg/sympath/walk.go

**Comment by bricerisingslalom** [comment]
Is there anything I can do to make progress on this PR?

**Comment by bacongobbler** [comment]
Since this is BSD-licensed code, it's fine to take it and re-license it as Apache 2. The question, though, is whether that practice follows the DCO. We're just waiting on a response on how we can move forward.

**Comment by bacongobbler** [comment]
Here's the response from the CNCF legal team:

> 1) Since Helm uses a DCO, the person who is making the contribution -- and including a DCO "Signed-off-by" message -- would need to be comfortable that they can sign off on one of the statements in the DCO. This would be https://developercertificate.org/, either (a), (b) or (c). In the context here, it looks like they're using (b).

> 2) Instead of pulling these forked files directly into the main Helm /pkg/ directory, I would recommend that this code be pulled into a separate directory, something like /third_party/forked/. That way it should be fully clear to downstream users that this code originated in part from outside the main project, and that different licenses may apply. This is the practice followed by Kubernetes when forking upstream projects: see https://github.com/kubernetes/kubernetes/tree/master/third_party/forked

> 3) Finally, I would also suggest putting the full BSD license text in the header comments of these couple of files, instead of the URL. E.g., in the new file pkg/fsutil/fs.go, instead of "https://github.com/golang/dep/blob/master/LICENSE", I would suggest including the actual text from that LICENSE file. This is because complying with BSD-style licenses is generally understood to require actually distributing the applicable license text.

> If they follow the steps described in 2 and 3 above, I don't see a problem with bringing in the code.

So in order to accept this PR:

1. Please move `pkg/fs` to `third_party/dep/fs` or something indicative that the code came from dep
2. Please put the full BSD license text in the header comments of the files being submitted

Once that's done this should be good to go from a legal perspective.

Thanks for your patience!

**Comment by bacongobbler** [comment]
ping

**Comment by bacongobbler** [comment]
due to inactivity, I'm going to go ahead and close this. If anyone else feels like taking this across the finish line, feel free!

**Pull request closed without merging**
