### PR TITLE
fix(helm): Don't crash on bad --values arg

### LINKED ISSUE #3679: Invalid --values argument results in segfault
For example, if you accidentally specify `--values` when you meant `--set` - which was what I did - then you get this rather unfriendly result:

```
panic: runtime error: invalid memory address or nil pointer dereference
[signal SIGSEGV: segmentation violation code=0x1 addr=0x8 pc=0x2139add]

goroutine 1 [running]:
main.readFile(0x7ffeefbff059, 0x2f, 0x7ffeefbff059, 0x2f, 0xc4200d01d8, 0x0, 0x0)
	/Users/m.parry/code/gocode/src/k8s.io/helm/cmd/helm/install.go:498 +0x8d
main.vals(0xc4204ae480, 0x5, 0x8, 0x34125f0, 0x0, 0x0, 0x2, 0xc420842600, 0x0, 0x23, ...)
	/Users/m.parry/code/gocode/src/k8s.io/helm/cmd/helm/install.go:337 +0x13a
main.(*installCmd).run(0xc4201f6000, 0x0, 0x27fe8c0)
	/Users/m.parry/code/gocode/src/k8s.io/helm/cmd/helm/install.go:210 +0x10e
...
```

### PR DESCRIPTION
**Pull request by mparry**
Closes #3679.

Note that I have also made a small fix in `init_test.go` to prevent a potential `index out of range` panic when `TestInitCmd` fails in a certain way. This was preventing me from running the full test suite locally on my Mac, where I have some certificate issues due to a proxy.

### CODE REVIEW

**Comment by mparry** [comment]
I don't think that the `cmd/tiller` test failure relates to my change, eg. https://circleci.com/gh/kubernetes/helm/5355 failed the same way.

**Comment by bacongobbler** [comment]
Yeah, it's due tosomething up in circle:

> /usr/local/go/pkg/tool/linux_amd64/link: signal: killed

**Review by bacongobbler — COMMENTED** [review]
Hey! can we add a unit test to check that remote values via -f still work? I noticed that wasn't added in #2769 but it'd be good to add in this PR just so we can make sure we're not making any regressions with this change. Thanks!

**Comment by mparry** [comment]
@bacongobbler - I've added some additional testing.

I have generally improved some of the surrounding test cases too: previously they were not checking that the specified values were actually being picked up properly. (It would also be good, I think, if the error cases were checking that the right error was reported - rather than any error at all - but I didn't go this far.)

**Review by bacongobbler — APPROVED** [review]
Hey @mparry. Sorry for taking so long to get back to you on this PR. The functionality here looks great! If you wouldn't mind rebasing, we can get this in for the next release. Thanks!

**Comment by bacongobbler** [comment]
I'm going to close this ticket due to inactivity, but please re-open if this still needs to be addressed for Helm 3. Thanks!

**Pull request closed without merging**
