### PR TITLE
Add darwin/arm64 (Apple Silicon) support

### LINKED ISSUE #9091: Provide Download for Helm on Apple Silicon
We will need to wait for a builder in Go for Apple Silicon. Issue for it is at https://github.com/golang/go/issues/39782

### PR DESCRIPTION
**Pull request by joelanford**
Signed-off-by: Joe Lanford <joe.lanford@gmail.com>

**What this PR does / why we need it**:
An increasing number of macOS users will be using Apple Silicon.

Closes #9091

### CODE REVIEW

**Comment by joelanford** [comment]
Interesting. Looks like something breaks due to the bump to Go 1.16. I've reproduced locally, so I'll dig into this a little more.

**Comment by joelanford** [comment]
I resolved the above issue I mentioned. It was a difference in the error text that `text/template` outputs when there's an unclosed template.

Anything else I'm missing?

**Review by bacongobbler — APPROVED** [review]
looks good to me. needs another maintainer's approval before it can be merged as per the PR merge policy.

**Comment by cagataygurturk** [comment]
Can we maybe push this PR forward?

**Review by mattfarina — APPROVED** [review]

**Comment by mattfarina** [comment]
This will go into 3.6.0 as the change updates the minor version of Go

**Pull request merged**
