### PR TITLE
ref(*): Refactors the history action to return releases

### PR DESCRIPTION
**Pull request by thomastaylor312**
Refactors the history action to return releases instead of formatted output

Output utilities have been moved to their own file and streamlined as well

### CODE REVIEW

**Comment by thomastaylor312** [comment]
I labeled this as a breaking change in case anyone was already using the `History` action as a library in alpha.1

**Review by bacongobbler — APPROVED** [review]
`MarshalTable` could probably use a refactor at some point, but I really like the rest of the refactor work done here. LGTM!

**Comment by thomastaylor312** [comment]
@bacongobbler I totally agree, I can back out the `MarshalTable` stuff if you'd think it would be cleaner. It isn't my favorite, but it felt weird being isolated in `cmd/history.go`

**Comment by bacongobbler** [comment]
yeah it's fine to merge as-is.

**Review by hickeyma — APPROVED** [review]
LGTM, thanks @thomastaylor312

**Pull request merged**
