### PR TITLE
fix(upgrade):Check the raw vals during an upgrade properly

### PR DESCRIPTION
**Pull request by kmala**
this got changed by this PR https://github.com/kubernetes/helm/pull/1656

### CODE REVIEW

**Comment by technosophos** [comment]
I think we might need both the empty string test and the test for `{}\n`, since we can't assume that the client will send `{}\n`.

**Comment by kmala** [comment]
I think it will always be `{}\n` as the client is using the yaml.marshal() https://github.com/kubernetes/helm/blob/master/cmd/helm/upgrade.go#L195 unless i am missing something. I can also add the empty string just to be extra careful.

**Comment by technosophos** [comment]
@kmala Because some people's tools are interacting with the gRPC API directly, and passing an empty string for that value.

**Comment by kmala** [comment]
@technosophos Updated.

**Comment by mboersma** [comment]
This issue has stalled some users of the [workflow-migration](https://github.com/deis/workflow-migration) tool, so if it's possible to get it merged for a patch release, that would be groovy. ☮️

**Comment by technosophos** [comment]
Backported to release-2.1 for 2.1.3

**Pull request merged**
