### PR TITLE
fix(pkg/kube/client.go): cannot upgrade release after upgrade release failed in a certain case

### PR DESCRIPTION
**Pull request by skydai**
In a certain case, if charts updates with add a new k8s resource, and upgrade release failed. The failed reason is upgrade other res- ources failed excepet the n ew k8s resource. In this case, results cannot upgrade success anymore, it would throw an error like that " no %s with the name %q found"(release not found)

### CODE REVIEW

**Comment by bacongobbler** [comment]
Hi @skydai. We ask that contributors please start by first filing an issue before filing a PR. This saves both you and us some time determining the correct fix for the problem. It also provides us with some context on how to test and verify the PR fixes the issue.

In addition, we also ask for unit tests along with any changes to the codebase. This ensures that

a) we are testing the fix, and
b) we can ensure no further regressions are introduced

Please point to an issue. If none exists, please file one. Thanks.

**Review by bacongobbler — CHANGES_REQUESTED** [review]
Hi @skydai. We ask that contributors please start by first filing an issue before filing a PR. This saves both you and us some time determining the correct fix for the problem. It also provides us with some context on how to test and verify the PR fixes the issue.

In addition, we also ask for unit tests along with any changes to the codebase. This ensures that

a) we are testing the fix, and
b) we can ensure no further regressions are introduced

Please point to an issue. If none exists, please file one. Thanks.

**Comment by skydai** [comment]
ok ， i would recommit it later with requested rules

**Comment by bacongobbler** [comment]
closing as inactive.

**Pull request closed without merging**
