### PR TITLE
fix(pkg/downloader): Resolve repo alias before checking digests on build

### LINKED ISSUE #6871: Helm 3.0.0-rc.2 dependency build does not allow aliases
With helm 3, `helm dependency update` followed by `helm dependency build` complains about `Chart.lock` being out of sync when a repository contains an alias.

```
$ helm version
version.BuildInfo{Version:"v3.0.0-rc.2", GitCommit:"82ea5aa774661cc6557cb57293571d06f94aff0c", GitTreeState:"clean", GoVersion:"go1.13.3"}
$ helm repo list
NAME    	URL
stable  	https://kubernetes-charts.storage.googleapis.com/
jetstack	https://charts.jetstack.io
$ cat Chart.yaml
name: alias
apiVersion: v2
version: 1.0.0

dependencies:
  - name: postgresql
    version: "6.5.5"
    repository: "@stable"
$ helm dependency update .
Hang tight while we grab the latest from your chart repositories...
...Successfully got an update from the "jetstack" chart repository
...Successfully got an update from the "stable" chart repository
Update Complete. ⎈Happy Helming!⎈
Saving 1 charts
Downloading postgresql from repo https://kubernetes-charts.storage.googleapis.com/
Deleting outdated charts
$ cat Chart.lock
dependencies:
- name: postgresql
  repository: https://kubernetes-charts.storage.googleapis.com/
  version: 6.5.5
digest: sha256:72394d61ae09dba4eb534de7c51a9285c2fe4ea6eb537c1593d593f06894ca68
generated: "2019-11-02T18:03:00.63001711+01:00"
$ helm dependency build .
Error: Chart.lock is out of sync with Chart.yaml
```

This is surprising since I just did the `update` to make sure the `Chart.lock` is in sync. If I resolve the alias, then everything works as expected.

```
$ cat Chart.yaml
name: alias
apiVersion: v2
version: 1.0.0

dependencies:
  - name: postgresql
    version: "6.5.5"
    repository: https://kubernetes-charts.storage.googleapis.com/
$ helm dependency update .
Hang tight while we grab the latest from your chart repositories...
...Successfully got an update from the "jetstack" chart repository
...Successfully got an update from the "stable" chart repository
Update Complete. ⎈Happy Helming!⎈
Saving 1 charts
Downloading postgresql from repo https://kubernetes-charts.storage.googleapis.com/
Deleting outdated charts
$ helm dependency build .
Hang tight while we grab the latest from your chart repositories...
...Successfully got an update from the "jetstack" chart repository
...Successfully got an update from the "stable" chart repository
Update Complete. ⎈Happy Helming!⎈
Saving 1 charts
Downloading postgresql from repo https://kubernetes-charts.storage.googleapis.com/
Deleting outdated charts
```

Are aliases not supported in this context? If so, I think the error messages should be improved :)

### PR DESCRIPTION
**Pull request by hangpark**
Fixes #6871 
Caused by #6736 

## What this PR does / why we need it:

`Update()` gets repo names before resolving a lock file by calling `resolveRepoNames(req)`. But that method changes aliased repo URLs into the actual URLs. That makes digests from `helm update` and `helm build` be different for each other.

To make them in sync, setting actual (resolved) repo URLs into the loaded chart during `helm build` is necessary. Thus, this commit adds an extra step in the `Build()` implementation.

For comments, this commit also changes the name of `getRepoNames()` into `resolveRepoNames()` to avoid misunderstanding since getters are expected to not mutate its input data in general.

~~Also, like `Update()`, `Build()` is changed to be finished immediately if there is no dependency.~~
(Edited: remove this feature since nil chart deps & non-nil lock deps should return out-of-sync error)

- [x] this PR contains unit tests

### CODE REVIEW

**Comment by bacongobbler** [comment]
@hangpark looks like there's only changes to the tests in this PR. Did you accidentally fail to commit code before pushing?

**Comment by hangpark** [comment]
@bacongobbler I was not sure whether CI runs for all pushed commits or for the latest only. I wanted to show a red X mark on the failing test, so I pushed two commits with a time gap :) And... now you can check my fix too!

**Review by bacongobbler — APPROVED** [review]
Thank you for the test as well as the fix. LGTM!

**Comment by bacongobbler** [comment]
Okay, after assessing the original issue, I've cherry-picked this into the release-3.0 branch. If we find more issues, we will cut another rc.5 with this fix, or just cut 3.0 with this fix in there. Thanks so much for looking into this!

**Pull request merged**
