### PR TITLE
ref(*): kubernetes v1.6

### PR DESCRIPTION
**Pull request by adamreese**
Rebase on kubernetes v1.6

### CODE REVIEW

**Comment by seh** [comment]
Is this the work you had mentioned during last week's developer meeting?

I was confused at first by the changes to _glide.yaml_, expecting to see movement from _kubernetes/kubernetes_ to _kubernetes/apimachinery_ and _kubertenes/client-go_, but now I see that you eliminated the "subpackages" mappings for the various Kubernetes dependencies.

**Comment by adamreese** [comment]
@seh This is what I was referring to on the developer call

**Comment by adamreese** [comment]
To test in cluster:
```
helm init --tiller-image quay.io/adamreese/tiller:kube-v1.6
```

**Review by technosophos — APPROVED** [review]
I manually reviewed this PR as follows:

1. I did a fresh install of Kube 1.6.1
2. I cloned this branch and did `make bootstrap build`
3. I ran `helm init`
4. I ran `kubectl get deployment -n kube-system tiller-deploy > tiller.yaml`
5. I destroyed the tiller deployment
6. I created a service account and role binding for 'tiller'
7. I added `serviceAccount: tiller` to the tiller.yaml, and also changed the image to the one @adamreese posted in the comments
6. I used `kubectl create` to load tiller.yaml
7. I installed a chart with `helm install`, tested list, status, history, delete, rollback (from deleted to undeleted), and then upgrade.

All worked as expected.

**Review by thomastaylor312 — APPROVED** [review]
This all looks good. I tested all of the same functionality as @technosophos. I also made sure `--wait` still functioned properly (good refactor on that by the way)

**Comment by seh** [comment]
@adamreese, for further reducing the remaining dependencies on kubernetes/kubernetes, there's still progress to watch in kubernetes/kubernetes#41331 and the recently closed kubernetes/kubernetes#41543.

**Pull request merged**
