### PR TITLE
fix(rollback): fix helm rollback doesn't have meta.helm.sh annotations

### LINKED ISSUE #9747: Resource created by `helm rollback` doesn't have `meta.helm.sh` annotations.
Output of `helm version`: 3.3.4

Output of `kubectl version`: v1.19.9

Cloud Provider/Platform (AKS, GKE, Minikube etc.): AWS EKS 

Resource created by `helm rollback` doesn't have `meta.helm.sh` annotations.

It seems `setMetadataVisitor` is executed by `upgrade` and `install` but not by `rollback`. Because of that resource created by `rollback` is not annotated and can't be "adopted" by helm if needed.

### PR DESCRIPTION
**Pull request by cndoit18**
Signed-off-by: cndoit18 <cndoit18@outlook.com>

**What this PR does / why we need it**:
fixes: #9747 

**Special notes for your reviewer**:
The current fakeKubeClient is not enough to support writing unit tests for it. I think it needs a new issue as its dependency

**If applicable**:
- [ ] this PR contains unit tests
- [x] this PR has been tested for backwards compatibility

### CODE REVIEW

**Comment by bacongobbler** [comment]
@cndoit18 you marked this as a draft. Is this ready for review?

**Comment by cndoit18** [comment]
> @cndoit18 you marked this as a draft. Is this ready for review?

Oh, sorry, I forgot, I should still need to verify it myself, if I can I will change it to ready

**Comment by cndoit18** [comment]
Thank you very much, I have checked it. @bacongobbler

**Review by joejulian — APPROVED** [review]
Thanks for this. This explains some issues we've hit and didn't know how we got there.

**Review by bacongobbler — APPROVED** [review]

**Comment by bacongobbler** [comment]
Short answer is no, this will not be ported to Helm 3.8.

**Pull request merged**
