### PR TITLE
Add optional check to restrict charts to target namespace

### PR DESCRIPTION
**Pull request by anguslees**
This change adds a new `RestrictToNamespace` option to gRPC calls.
When enabled, this will reject charts that attempt to install
resources outside the target namespace (either in another namespace,
or "global" non-namespaced resources).

This is intended as a simple namespace-scoped stop-gap permission
model, until helm/tiller becomes more RBAC-aware.  It implements a
simple binary mechanism that allows either "namespace local" or
"unrestricted/global" operations, and trusts the client to indicate
which operation was intended.  It would be reasonable to think of this
as "the sudo approach".

Notes:
- The gRPC interface and behaviour is backwards compatible.  Nothing
  in this change sets this option (other than test cases).
- This change does not (yet) expose this option through to the `helm`
  CLI tool.
- This change does not (yet) modify rudder.  Rudder continues to allow
  any namespace in chart resources.

### CODE REVIEW

**Comment by bacongobbler** [comment]
this is a compatibility breaker for pkg/kube and pkg/tiller though, as many function signatures have been changed to accommodate this feature. Is there any way to avoid that?

**Comment by bacongobbler** [comment]
It also looks like this PR is missing docs (in the form of a design doc/usage docs) as well as tests. Given the size and scope of this PR I don't think we should move forward until those are in place at the very least.

**Comment by bacongobbler** [comment]
ping

**Comment by anguslees** [comment]
Oops, failed to notice your replies in the kubecon/travel/holidays email backlog :stuck_out_tongue: 

Re pkg/kube and pkg/tiller compatibility: This is gRPC compatible.  What other interfaces are considered public?  Are you saying I need to avoid modifying existing public functions in these two go packages?  GIven the nature of the existing APIs, I think this means introducing new methods (that perhaps take an extensible options struct so we can avoid doing this again), or manipulating a mutable property in the `Client` struct.  Either of these seems to deviate from the existing code structure and the precedent set by other similar options, so advice is welcomed.

Re missing tests/docs: Yep.  I wanted to get some agreement on the approach before investing in the rest.

**Comment by anguslees** [comment]
Fwiw, I'm waiting on the answers to my above questions re compatibility (since that may require the PR to be rewritten) - and general "lgtm on the general concept" before embarking on docs.

**Comment by bacongobbler** [comment]
As per [the announcement on the mailing list](https://lists.cncf.io/g/cncf-helm/topic/last_v2_feature_release/34301238), Helm 2.15.0 is the last release where we will be merging new features for Helm 2. We don't plan to merge this in the 2.15 timeframe. The functionality proposed in this PR can be accomplished in Helm 3 through proper setup of role-based access controls for each user, so I don't believe there is a point to try and port this over.

Thanks!

**Pull request closed without merging**
