### PR TITLE
docs(helm): Document how to update a release idempotently

### LINKED ISSUE #3134: helm install --replace fails with "cannot re-use a name that is still in use"
Hi, I try to idempotently deploy a package with:
```
helm install --replace --tiller-namespace=system --namespace=system -n somepackage
```
(I use the `system` namespace, and tiller is deployed into it, so no mistake there), but the second time it fails with

`"Error: cannot re-use a name that is still in use"`

The first install runs flawless, it's the subsequent ones that fail. I am using helm version:
```
Client: &version.Version{SemVer:"v2.7.0-rc1", GitCommit:"1eff362941a349ab577c356f037ee093b23767a7", GitTreeState:"clean"}
Server: &version.Version{SemVer:"v2.7.0-rc1", GitCommit:"1eff362941a349ab577c356f037ee093b23767a7", GitTreeState:"clean"}
```

### PR DESCRIPTION
**Pull request by splisson**
To use the same command when installing and upgrading a release, using helm upgrade with '--install' works.

Closes #3134

### CODE REVIEW

**Comment by technosophos** [comment]
I know this is really nit-picky, but... can I ask for one small change? It should be "Upgrade a Release..."

We are trying to be careful to use the term "update" for `helm repo update` and "upgrade" for `helm upgrade`. I know it's really pedantic. We're just trying to make it easier for people to search/grep the docs for what they're interested in..

**Comment by splisson** [comment]
No problem, I'm all for consistency.

**Review by SlickNik — APPROVED** [review]
Looks good to me. Thanks @splisson 👍

**Review by technosophos — APPROVED** [review]
I second that. LGTM

**Pull request merged**
