### PR TITLE
Use import () way

### PR DESCRIPTION
**Pull request by xichengliudui**
**What this PR does / why we need it**:
Use import () way

**Special notes for your reviewer**:

**If applicable**:
- [x] this PR contains documentation
- [ ] this PR contains unit tests
- [ ] this PR has been tested for backwards compatibility

### CODE REVIEW

**Comment by mattfarina** [comment]
Because there is #5307 did you want to close this?

**Comment by xichengliudui** [comment]
What pr fixed is the _test file, which is different from #5307 . i am afraid it will cause confusion

**Comment by xichengliudui** [comment]
@mattfarina  If you need to close this pr, I'll close it

**Comment by hickeyma** [comment]
@xichengliudui Do you mind adding these changes into the 1 PR: #5307 ? You can then close this PR.

**Pull request closed without merging**
