### PR TITLE
WIP: Watch hooks logs in helm install/upgrade

### PR DESCRIPTION
**Pull request by distorhead**
Experiments with log streaming during install/upgrade operation.

Separate issue to describe what problems we aimed to solve: https://github.com/kubernetes/helm/issues/3481.

Related PRs: https://github.com/kubernetes/helm/pull/2386, https://github.com/kubernetes/helm/pull/2342, https://github.com/kubernetes/helm/pull/3263

### CODE REVIEW

**Comment by distorhead** [comment]
The main question for now is how to extend install/upgrade grpc requests in backward-compatible manner. 
Proposal is to make api version negotiation between `helm-client` and `tiller`. See https://github.com/kubernetes/helm/issues/3481#issuecomment-366248119 for details.

**Comment by distorhead** [comment]
Feedback needed https://github.com/kubernetes/helm/issues/3481#issuecomment-367444870

**Comment by bacongobbler** [comment]
Hi @distorhead. As per [the announcement on the mailing list](https://lists.cncf.io/g/cncf-helm/topic/last_v2_feature_release/34301238), Helm 2.15.0 is the last release where we will be merging new features for Helm 2. Because this PR is so large, I don't believe we will have the time to properly review this. Therefore, I'm going ahead and closing this as something we do not plan to implement for Helm 2. #3263 is very similar to this PR and was also closed for the same reason.

That being said, there may be value in streaming hook output back to `helm install/upgrade` if provided in a feature flag for Helm 3. I know you expressed interest in trying again in Helm 3 (source: https://github.com/helm/helm/issues/3481#issuecomment-442615100), so if you're still interested in moving this idea forward, please feel free to write a PR against Helm 3. Thanks!

**Comment by dudicoco** [comment]
@distorhead @bacongobbler what is the status regarding porting this PR to work with helm 3?
I think this is an amazing feature that everyone would find beneficial and it's a shame that work has stopped on this PR when it could totally improve the information we get from helm install/upgrade/test.

Thanks!

**Pull request closed without merging**
