### PR TITLE
Corrected a typo in Easy in-cluster installation

### PR DESCRIPTION
**Pull request by frederimandin**

### CODE REVIEW

**Comment by bacongobbler** [comment]
`kubectl get po` is actually a valid shortcut for `kubectl get pods`. Still a good change nonetheless. More users are probably aware of the long form.

**Comment by bacongobbler** [comment]
Can you please sign the CLA and get that figured out? Thanks!

**Comment by frederimandin** [comment]
OK, I did just sign the CLA.
And indeed I was not aware of the shortcut, my bad.

**Review by bacongobbler — APPROVED** [review]

**Comment by bacongobbler** [comment]
thanks!

**Pull request merged**
