### PR TITLE
update(env) Add env var for HELM_REGISTRY_CACHE

### LINKED ISSUE #7776: Incorrect RegistryConfig location and expose RegistryCache location via envVar
Output of `helm version`:
version.BuildInfo{Version:"v3.1+unreleased", GitCommit:"26830942d275b3a70edfdc32474230f3499a18e4", GitTreeState:"dirty", GoVersion:"go1.13.4"}

Output of `kubectl version`:
Client Version: version.Info{Major:"1", Minor:"15", GitVersion:"v1.15.0", GitCommit:"e8462b5b5dc2584fdcd18e6bcfe9f1e4d970a529", GitTreeState:"clean", BuildDate:"2019-06-19T16:40:16Z", GoVersion:"go1.12.5", Compiler:"gc", Platform:"linux/amd64"}                                                 
Server Version: version.Info{Major:"1", Minor:"17", GitVersion:"v1.17.3", GitCommit:"06ad960bfd03b39c8310aaf92d1e7c12ce618213", GitTreeState:"clean", BuildDate:"2020-02-11T18:07:13Z", GoVersion:"go1.13.6", Compiler:"gc", Platform:"linux/amd64"}

Cloud Provider/Platform (AKS, GKE, Minikube etc.): 
GKE

Output of `helm env` provides the following output.
```
$ helm env 
...
HELM_REGISTRY_CONFIG="/home/vbobade/.config/helm/registry.json"
...
```
I wasn't able to find the registry config and am guessing that this isn't created and also noticed that the registry location isn't exposed via an envVar. This should be done via env var.

The registry cache is located on my system at `/home/vbobade/.cache/helm/registry/cache`

### PR DESCRIPTION
**Pull request by waveywaves**
partly fixes https://github.com/helm/helm/issues/7776

### CODE REVIEW

**Review by jdolitsky — APPROVED** [review]
lgtm!

**Review by hickeyma — COMMENTED** [review]
Thanks for pushing this PR @waveywaves. I am going to ask @bacongobbler on this before reviewing as not sure if this is the approach after reading https://github.com/helm/helm/issues/7776#issuecomment-600750415.

**Comment by waveywaves** [comment]
@hickeyma That sounds good, I created this PR during the time of opening the issue. So I guess it would be good if he can take a look at this.

**Comment by waveywaves** [comment]
Closing this as this is not necessary atm

**Pull request closed without merging**
