### PR TITLE
Update helm_rollback.md

### PR DESCRIPTION
**Pull request by Ethan-Arrowood**
While deving at a Microsoft Open Hack my group discovered this useful piece of information in this issue comment: https://github.com/helm/helm/issues/1796#issuecomment-311385728

We found it very useful for our Blue Green CD pipeline and thought others might find it useful as well.

### CODE REVIEW

**Comment by bacongobbler** [comment]
Thanks @Ethan-Arrowood! It looks like two things need to be fixed up here:

1. It looks like you'll need to add this to [the rollback CLI docs](https://github.com/helm/helm/blob/e2a0e7fa545585a29c1e9602e6320479788eb9a6/cmd/helm/rollback.go#L32-L34) first, then call `make docs` to generate this piece of documentation. Anything in `docs/helm` is automatically generated off the CLI :)
2. Helm requires a DCO signoff on each commit. To fix this, please follow the instructions here: https://github.com/helm/helm/pull/4984/checks?check_run_id=36208136

Thanks!

**Comment by bacongobbler** [comment]
ping

**Comment by Ethan-Arrowood** [comment]
Oh oops! Lets this fall through my notification stack. I'll try to find time this afternoon to complete it 😄

**Comment by jascott1** [comment]
Hi @Ethan-Arrowood 

You might try `make bootstrap` and `make build` before running `make docs`.

**Comment by Ethan-Arrowood** [comment]
Still same error :(

**Comment by bacongobbler** [comment]
Thanks @Ethan-Arrowood! Based on your previous comment, I went ahead and amended your commit with the required changes to get it to pass and re-submitted it as https://github.com/helm/helm/pull/5228. You're still the commit author so you'll still receive credit for the contribution. Thanks so much for your PR!

**Comment by Ethan-Arrowood** [comment]
Awesome!

**Pull request closed without merging**
