### PR TITLE
Move oci out experimental

### LINKED ISSUE #9188: Move `internal/experimental/registry` out of `internal` package
I would like to know whether it's possible to move https://github.com/helm/helm/tree/master/internal/experimental/registry out of the `internal` package so that project like https://github.com/hashicorp/terraform-provider-helm can implement OCI registry support by using Helm as a library.

Ref: https://github.com/hashicorp/terraform-provider-helm/issues/633

Output of `helm version`:

```
version.BuildInfo{Version:"v3.4.2", GitCommit:"23dd3af5e19a02d4f4baa5b2f242645a1a3af629", GitTreeState:"dirty", GoVersion:"go1.15.5"}
```

Output of `kubectl version`:

```
Client Version: version.Info{Major:"1", Minor:"20", GitVersion:"v1.20.1", GitCommit:"c4d752765b3bbac2237bf87cf0b1c2e307844666", GitTreeState:"clean", BuildDate:"2020-12-19T08:38:20Z", GoVersion:"go1.15.5", Compiler:"gc", Platform:"darwin/amd64"}
Server Version: version.Info{Major:"1", Minor:"18", GitVersion:"v1.18.9", GitCommit:"94f372e501c973a7fa9eb40ec9ebd2fe7ca69848", GitTreeState:"clean", BuildDate:"2020-09-16T13:47:43Z", GoVersion:"go1.13.15", Compiler:"gc", Platform:"linux/amd64"}
```

Cloud Provider/Platform (AKS, GKE, Minikube etc.): 

N/A

### PR DESCRIPTION
**Pull request by dperaza4dustbit**
Moving all registry package out of experimental, and removing all checks and gates.

closes #9188

refs #10393

### CODE REVIEW

**Review by scottrigby — CHANGES_REQUESTED** [review]
Thanks @dperaza4dustbit !

- Since `pkg/action` already exists, the 3 files in `internal/experimental/action` should be moved inside `pkg/action` and references updated
- All other package dirs in `internal/experimental` should we moved to `pkg/action`
- The experimental directory should no longer exist after this

Thanks @mattfarina for noticing this ☝️

**Comment by dperaza4dustbit** [comment]
> 

got it, I'm on it

**Comment by dperaza4dustbit** [comment]
@scottrigby done with all other experimental module

**Review by scottrigby — APPROVED** [review]
Thanks @dperaza4dustbit for the fixes

Looks good, passes tests, and manually tested the registry commands with semver, not specifying versions, etc 👌 Approving to unblock the RC release in the morning.

Extremely minor thing, I removed this one legacy comment, since it's non-functional and we want to release the RC in the morning. 
https://github.com/helm/helm/blob/7cab1a09e30edc3892edab5fd3a73811dbf1ec76/cmd/helm/root.go#L196

**Review by mattfarina — CHANGES_REQUESTED** [review]
Why is the `pusher` package within `action`? Shouldn't it be alongside `getter` and `action`? `pusher` is the opposite of `getter` in terms of packages and even has the same style.

This same idea applies to `uploader`. It's the opposite of `downloader`. It should be alongside `downloader` and `action` rather than within `action`.

**Review by mattfarina — APPROVED** [review]

**Review by scottrigby — APPROVED** [review]
Perf! Just did the same manual testing again, and all works as expected (can add more to test suite later). 💯

**Pull request merged**
