### PR TITLE
Serve charts from specified local repository path

### PR DESCRIPTION
**Pull request by joe2far**
- Add support for optionally providing a repository path (--repo-path) for the helm serve command
- Calulate the absolute path, allowing for relative paths to be provided
- Return an error if the local repository directory path does not exist

### CODE REVIEW

**Comment by technosophos** [comment]
Is this related to https://github.com/kubernetes/helm/issues/746?

**Comment by technosophos** [comment]
Oh! I see! It lets the HTTP server serve from an arbitrary path. Code looks good to me. I'll give @michelleN a chance to check it out, though, since she's the owner of the repo code.

**Comment by joe2far** [comment]
No, not related to #746, but does fix / resolves #698

**Comment by michelleN** [comment]
This looks great @joe2far. Thanks!

**Comment by technosophos** [comment]
Merging. Thanks @joe2far

**Pull request merged**
