### PR TITLE
github: add Asset Transparency action for GitHub releases

### PR DESCRIPTION
**Pull request by philips**
This adds a GitHub Action to have Helm release inserted into the Asset
Transparency log[1].

With these assets in the log it would be great to also recommend users
verify their download of helm using the Asset Transparency CLI like
this:

```
tl verify https://get.helm.sh/helm-v3.3.1-darwin-amd64.tar.gz helm-v3.3.1-darwin-amd64.tar.gz
```

[1] https://www.transparencylog.com

See kubernetes-dev discussion here:
https://groups.google.com/g/kubernetes-dev/c/iWr5FiOyU78

**What this PR does / why we need it**:

**Special notes for your reviewer**:

**If applicable**:
- [ ] this PR contains documentation
- [ ] this PR contains unit tests
- [ ] this PR has been tested for backwards compatibility

### CODE REVIEW

**Comment by philips** [comment]
I just noticed that get.helm.sh isn’t a redirection to the GitHub release assets. Do y’all have a shell script or something that generates those URLs from a git tag? Then I can use the [additionalURLs input](https://github.com/transparencylog/publish-releases-asset-transparency-action#action-to-publish-and-verify-release-assets-into-asset-transparency-log) to handle that.

**Comment by bacongobbler** [comment]
> I just noticed that get.helm.sh isn’t a redirection to the GitHub release assets.

get.helm.sh is the hsot for the release assets. Only the PGP signatures are hosted on Github.

https://helm.sh/blog/get-helm-sh/

> Do y’all have a shell script or something that generates those URLs from a git tag?

[get-helm-3](https://github.com/helm/helm/blob/master/scripts/get-helm-3) will generate the URL and fetch the content.

**Comment by bacongobbler** [comment]
@philips can you clarify how this differs from the approach being taken in https://github.com/helm/helm/pull/7944?

**Comment by philips** [comment]
It looks like #7944 is automating signature verification and doing trust on first use of a gpg signing key. This system is complementary to gpg signing. From the [FAQ](https://www.transparencylog.com/frequently-asked-questions/)

Why not use GPG keys or other public key signing?

This is complimentary to public key signing! Public key signing asserts that someone with access to the private key signed the exact content. But, the private key can be used to generate an unlimited number of signatures for different content. If the URLs contents are both signed and logged in the URL content record then there is a guarantee that both the owner of the private key signed the content AND the content being fetched is cryptographically identical to the content other people are fetching using tl.

**Comment by bridgetkromhout** [comment]
Hi, @philips! Thanks for adding this. We'll hopefully sort out any remaining details after the holiday weekend; meanwhile if you want to fix the DCO on that commit, then that blocker will be out of the way: https://github.com/helm/helm/pull/8697/checks?check_run_id=1072837057

**Comment by philips** [comment]
@bridgetkromhout done.

I will hold off on the additionalURLs generation for the get.helm.sh URLs until I hear back if this is something y’all are interested in having in your release process.

**Comment by bacongobbler** [comment]
I think it's always good to introduce more assistive tooling, especially when it's automated and complementary to the existing toolset. 

However, the statement made in tl's README seems concerning.

> Alpha Warning: tl works as described but has minimal testing, no peer review, and no load testing. Please test the tool and provide feedback.

Perhaps it'd be worth testing the viability of this project on smaller open source projects before suggesting to a community with a massive user base (read: large blast radius).

**Comment by philips** [comment]
@bacongobbler I can sympathize with the blast radius concern. However, there are two things to consider:

Adding this GitHub action simply registers Helm releases with Asset Transparency. In the worst case the GitHub action fails if there is an issue with the Asset Transparency service. In the “best” case if the Helm storage buckets or webservers are compromised you can rely on the Asset Transparency API to audit what files might have been compromised.

If you do recommend `tl` in helm install/download docs the effect of a “blast” is fairly minimal:

1. If the Asset Transparency service had an issue the user would experience a `tl verify` failure and likely file an issue, etc on this repo.
2. The Helm team could remove the recommendation to do `tl verify` from their download/install docs until the service was fixed.

**Comment by geokb** [comment]
Sorry folks for this off-topic comment but this is the only way for me to contact @philips directly. Please don't remove it until he replies. Hi @philips, I have been searching for any email of yours to contact you but I could not find anything. Can you please post your email here, or just send me an empty email me to the email address in my Github profile in order to contact you? Sorry if this looks weird but I've been trying to reach out to you about a FOSS project within your area of expertise that I've been working on that I am about to release and just wanted some advice from you. Again I apologize for this weird and off-topic comment.

**Comment by jdolitsky** [comment]
Does this require any credentials to work?

**Comment by philips** [comment]
No it doesn't require credentials.

**Comment by mattfarina** [comment]
@philips I just noticed this PR. Thanks for pointing us at Asset Transparency and sending over the NYU blog post. I wasn't aware this had been created. The NYU blog post helps me to trust this project and org as I had no idea who Honesty Owl (the parent company behind the project) was prior to seeing this. Security is about trust and that's good link.

Helm uses CircleCI and a [deploy script](https://github.com/helm/helm/blob/master/.circleci/deploy.sh). This is something that would sit nicely in there after the deploy. You have both the local file and the file is in the remote location.

I'll take the action to discuss this with both the Helm client maintainers and the Helm security team.

**Comment by philips** [comment]
Just so we are clear: Honesty Owl, Inc is a public benefit company that was formed by me to create products like transparencylog.com.

**Comment by technosophos** [comment]
I am definitely good with adding this functionality to Helm's build pipeline. Given our size, structure, and existing involvement with other projects like in-toto and TUF, this would be a great fit and help us further our long term goal of exhibiting good software supply chain practices. And I feel better knowing this is one of @philips 's projects, and that Trishank (who wrote much of the CNAB security spec) has already looked at it.

**Review by jdolitsky — APPROVED** [review]
👍

**Comment by joejulian** [comment]
kicking CI

**Review by joejulian — APPROVED** [review]

**Pull request merged**
