### PR TITLE
Scanner buffer overwrite bug

### PR DESCRIPTION
**Pull request by givia**
`scanner.Bytes()` does no allocation. By appending its result to a new empty byte array, we're creating a copy to avoid the overwrite problem.

### CODE REVIEW

**Comment by technosophos** [comment]
Excellent catch! Thanks -- and thanks for improving the tests, too. As soon as we get an LGTM2, I'll merge.

We follow a consistent commit message format. Not a huge deal, but if you have a moment to amend the commits that would be awesome.

https://github.com/helm/helm/blob/master/CONTRIBUTING.md

**Comment by bacongobbler** [comment]
also, was @remohammadi working with you on this? We should probably ask for his permission to use his commit if he's not explicitly working with you. :)

**Comment by remohammadi** [comment]
I'm working with @givia :) The test data comes from the [etcd project](https://github.com/coreos/etcd/blob/master/hack/kubernetes-deploy/etcd.yml).

**Comment by bacongobbler** [comment]
perfect. thanks!

**Pull request merged**
