### PR TITLE
feat(*): add from and repo for dependency resolve

### PR DESCRIPTION
**Pull request by technosophos**
This addresses #209 and #213, and adds ability to constrain
dependencies based on repo, not just name and version.

### CODE REVIEW

**Comment by gabrtv** [comment]
One problem I forsee is the need to normalize the repo representation, since the repo URI can vary depending on protocols. For example, these should be equivalent:

 * `https://github.com/gabrtv/charts(.git)?`
 * `git://github.com/gabrtv/charts(.git)?`
 * `git+ssh://github.com/gabrtv/charts(.git)?`

.. all should map to `github.com/gabrtv/charts`.  Anyway, that's a separate issue. This LGTM!

**Comment by technosophos** [comment]
Added repo name normalization as suggested by @gabrtv.

**Comment by mboersma** [comment]
Do from: and repo: need some docs, or does this close #209 and #213?

**Comment by technosophos** [comment]
I should probably add something explaining how these get generated and what they're used for.

**Comment by technosophos** [comment]
@mboersma would you mind doing a quick review of the docs on this one? It's only a few paragraphs. But I don't want to merge without at least one person eyeballing my changes.

**Comment by carmstrong** [comment]
Docs LGTM.

**Pull request merged**
