### PR TITLE
Add toToml template function

### PR DESCRIPTION
**Pull request by jackzampolin**
This pr adds a `toToml` template function that is modeled on `toYaml` and `toJson`.

### CODE REVIEW

**Comment by technosophos** [comment]
TOML IS BACK!!!!

(I first wanted to encode chart value files in TOML because I think it's much prettier than YAML.)

Ought we also do a fromToml function? I guess that's probably of limited value, since charts tend not to have base TOML data, but I could imagine users wanting to do something like this: `{{ $params := .Files.Get "my.toml" | fromToml }}`. If that's a lot of work, we can punt until later.

**Comment by jackzampolin** [comment]
@technosophos I thought about it but as you mention the usage would be limited. Also the two main TOML libraries (BurntSushi, naoina) require struct tags for the unmarshall which looked difficult to implement so I avoided it.

**Comment by technosophos** [comment]
Alright, in spite of what GitHub is reporting, CircleCI is indeed passing the tests. So I am merging this.

**Review by technosophos — APPROVED** [review]
LGTM

**Pull request merged**
