### PR TITLE
ref(pkg/repo): rename RepoFile to File

### PR DESCRIPTION
**Pull request by imroc**
To resolve the linter warning: name start with package name.

### CODE REVIEW

**Comment by imroc** [comment]
appveyor failure was not related

**Comment by imroc** [comment]
@adamreese @adshmh @bacongobbler PTAL 🤔

**Review by bacongobbler — CHANGES_REQUESTED** [review]
These makes changes to helm's SDK so therefore we cannot accept this as-is. I recall there being an issue where we were discussing changing these names for Helm 3 but not for Helm 2. I'll see if I can pull that up in the morning.

**Comment by imroc** [comment]
@bacongobbler but this is a PR for Helm 3 (dev-v3 branch) not Helm 2

**Comment by bacongobbler** [comment]
Ah so GitHub on mobile doesn't show you what branch it's targeting. My bad

**Review by bacongobbler — APPROVED** [review]

**Comment by bacongobbler** [comment]
needs another maintainer to sign off since this is a `size/L`

**Review by adamreese — APPROVED** [review]

**Pull request merged**
