### PR TITLE
Fix for vbom.ml bootstrap

### PR DESCRIPTION
**Pull request by redbaron**
[WARN]	Unable to checkout vbom.ml/util
[ERROR]	Update failed for vbom.ml/util: Cannot detect VCS
[ERROR]	Failed to install: Cannot detect VCS
Makefile:120: recipe for target 'bootstrap' failed

### CODE REVIEW

**Comment by unguiculus** [comment]
You seemed to have fixed the same problem I just had, but in a different way.
See #2343, #2344.

**Comment by unguiculus** [comment]
Well, I guess I was to quick to judge. Seems to be a different problem.

**Comment by technosophos** [comment]
The `glide.lock` file is auto-generated by `glide up` from the `glide.yaml` file. So this won't fix the issue permanently.

What you'll need to do is move that entire `package:` section to the `glide.yaml` file and then re-run `glide up`. After that, run `make bootstrap` to make sure everything is working.

**Comment by technosophos** [comment]
Did you re-run `glide up`? That should have generated a new `glide.lock` file that should also be committed.

**Comment by redbaron** [comment]
@technosophos no,I didn't add `glide up`,all I am doing is fixing `glide cc && make bootstrap` case. I updated `glide.yaml` as you asked so that whoever does `glide up` next preserves `vcs: git` in `glide.lock`

**Review by technosophos — APPROVED** [review]
LGTM. Thanks for fixing that last commit.

**Comment by jnaulty** [comment]
I am running into this issue for helm `v2.15.2`
```
[INFO] --> Fetching vbom.ml/util
[WARN] Unable to checkout vbom.ml/util
[ERROR] Update failed for vbom.ml/util: Cannot detect VCS
[ERROR] Failed to install: Cannot detect VCS
make: *** [Makefile:175: bootstrap] Error 1
```

**Comment by jnaulty** [comment]
To fix, I ended up running a `go get -u vbom.ml/util`

**Pull request merged**
