### PR TITLE
code-of-conduct: use the upstream language

### PR DESCRIPTION
**Pull request by philips**
Provide concrete information about who to contact about CoC issues. Having unambiguous people to contact is important to resolve issues in a timely manner.

This is the primary important change, having consistent and explicit
points of contact: https://github.com/kubernetes/kubernetes-template-project/commit/98749d6b8efc612fe05d1bc42b0e0bff89f30e0a

---

This change is [Reviewable](https://reviewable.kubernetes.io/reviews/kubernetes/helm/1165)

### CODE REVIEW

**Comment by technosophos** [comment]
@sarahnovotny Are you guys comfortable being points of contact for the Helm project's code of conduct?

**Comment by philips** [comment]
@technosophos Yes, this is the COC that is used for all Kubernetes projects moving forward. See https://github.com/kubernetes/community/blob/master/incubator.md#creation-of-the-incubator-project

@sarahnovotny will be slow to reply because she is traveling but she and Dan have agreed to do this for all projects.

**Comment by technosophos** [comment]
Is that in writing somewhere? I don't feel comfortable signing someone up  for that responsibility without knowing for sure that it's okay with them.

**Comment by philips** [comment]
@technosophos is this sufficient? https://github.com/kubernetes/kubernetes/pull/28242

**Comment by sarahnovotny** [comment]
LGTM :)

**Pull request merged**
