### PR TITLE
do not check YAML if nothing was parsed

### LINKED ISSUE #8621: Linting fails in 3.3.0 when a template file results in only a comment.
Output of `helm version`:
version.BuildInfo{Version:"v3.3.0", GitCommit:"8a4aeec08d67a7b84472007529e8097ec3742105", GitTreeState:"dirty", GoVersion:"go1.14.7"}

An error occurs when linting a chart that results in a template file containing only a comment:
```` 
# comment on first line
{{- if false }}
apiVersion: v1
kind: ConfigMap
metadata:
  name: mychart-configmap
data:
  myvalue: "Hello World"
{{- end }}
````

the resulting lint throws an error:
````
[ERROR] templates/configmap-false.yaml: object name does not conform to Kubernetes naming requirements: ""
````

Essentially an empty file with only a comment triggers this issue.

```` 
# comment on first line
{{- if true }}
apiVersion: v1
kind: ConfigMap
metadata:
  name: mychart-configmap
data:
  myvalue: "Hello World"
{{- end }}
````

results in a successful lint:
````
1 chart(s) linted, 0 chart(s) failed
````

### LINKED ISSUE #8909: Lint fails with empty rendered manifests
As a good practice to avoid unwanted processing of our files by our IDEs, we are used to set `#@formatter:off` at the beginning of our YAML manifests.

A lot of them are also surrounded by conditions that can be changed through provided values.yaml at chart installation, such as:
```
#@formatter:off
{{ if .Values.dbUpgrade }}
...
{{ end }}
```
Which means rendering can lead to YAML manifest only containing the `#@formatter:off` comment

Linting these kind of manifests was working "thanks to" #6418. But now this issue is fixed (enabling again linting all the manifests included in the chart), we get this error:

```
❯ helm lint exploded-chart/xxx
==> Linting exploded-chart/xxx
[ERROR] templates/job-migrate.yaml: object name does not conform to Kubernetes naming requirements: "": invalid metadata name, must match regex ^(([A-Za-z0-9][-A-Za-z0-9_.]*)?[A-Za-z0-9])+$ and the length must not longer than 253
```

I think we need [here](https://github.com/helm/helm/blob/a61ce5633af99708171414353ed49547cf05013d/pkg/lint/rules/template.go#L116) to prevent the YAML structure checks if we don't have any elements parsed, instead of considering the emptiness of the raw YAML string (once trimmed)

Hope this is clear :)

Output of `helm version`:
`version.BuildInfo{Version:"v3.3.4", GitCommit:"a61ce5633af99708171414353ed49547cf05013d", GitTreeState:"clean", GoVersion:"go1.14.9"}`

### PR DESCRIPTION
**Pull request by cvila84**
**What this PR does / why we need it**:
closes #8621

**Special notes for your reviewer**:
added a test to avoid lint rules to be applied on parsed empty object

**If applicable**:
- [ ] this PR contains documentation
- [X] this PR contains unit tests
- [X] this PR has been tested for backwards compatibility

### CODE REVIEW

**Comment by cvila84** [comment]
CircleCI build is failing because I don't have Azure environment for deployment (missing AZURE_STORAGE_CONNECTION_STRING)

**Comment by mattfarina** [comment]
@cvila84 This appears to be because you setup your own CircleCI for your fork of Helm. You should let the setup for the repo at github.com/helm/helm handle it.

When the CI run is for a pull request the deploy step is skipped. But, you ran it for a branch as setup in your own environment.

Does this make sense?

**Comment by cvila84** [comment]
@mattfarina This is crystal clear. I just don't remember to have setup myself a project in my circle CI dashboard. I suspect it was done automatically when I pushed for the first time the new 'fork-lint-bug' branch in my fork as it contained the .circleci/config.xml... Anyway, I removed it, as it does not make sense as you explained

**Comment by bacongobbler** [comment]
I noticed this branch is based on the `release-3.3` branch instead of `master`. Please re-target this PR against the master branch. That may also be the cause why the CI pipeline failed. Thanks.

**Comment by bacongobbler** [comment]
Okay. It looks like I was able to do that myself. Now it just looks like you need to rebase a0df4ba on top of master for CI to run correctly.

**Comment by cvila84** [comment]
@bacongobbler seems much better now !

**Comment by mattfarina** [comment]
@cvila84 could you please add a test for this situation. We want to make sure something in the future doesn't accidentally undo this causing a regression.

**Comment by cvila84** [comment]
@mattfarina I added 1 UT. I also tested that this UT fails against both 3.3.4 and 3.4.0 release.

**Review by mattfarina — APPROVED** [review]
lgtm

**Comment by hickeyma** [comment]
Is this PR to handle a yaml file:
- which contains a comment only
- which starts with `#@formatter:off`

For testing: 

I created a scaffold chart. I added a file with comment only and updated the `deployment.yaml` file with the `formatter` as follows:

```console
$ cat issue-8909/templates/empty.yaml
# This is an empty template

$ cat issue-8909/templates/deployment.yaml
#@formatter:off
apiVersion: apps/v1
kind: Deployment
metadata:
[...]
```

I tested as follows first without applying the patch:

```console
$ helm3 lint issue-8909
==> Linting issue-8909
[INFO] Chart.yaml: icon is recommended
[ERROR] templates/empty.yaml: object name must be between 0 and 253 characters: ""

Error: 1 chart(s) linted, 1 chart(s) failed
```

I then tested with the PR as follows:

```console
$ helm3 lint issue-8909
==> Linting issue-8909
[INFO] Chart.yaml: icon is recommended

1 chart(s) linted, 0 chart(s) failed
```

Is this the fix as expected? Does this PR fix #8621  and if so then is PR #8862 actually not fixing #8621?

**Comment by cvila84** [comment]
This PR is fixing for sure #8621. It is very likely PR #8862 also fixes this issue, but the updates of this other PR implies other changes (on YAML parser) that needs to be reviewed/accepted before whereas this one is just a simple fix

**Comment by hickeyma** [comment]
@cvila84 I agree that this looks like ti does. I am however unsure about the other PR at this moment. I have raised to discuss it today at the dev weekly.

**Comment by hickeyma** [comment]
Both #8913 and #8862 fix #8621. PR #8862 deals also with multi-doc yaml.

As discussed with @mattfarina at dev weekly meeting yesterday, it as agreed to merge both PRs as there are additional unit tests in this PR, and therefore adds value.

**Review by hickeyma — APPROVED** [review]
LGTM, thanks for the fix @cvila84

**Comment by cvila84** [comment]
you're welcome :)

**Pull request merged**
