### PR TITLE
Replace 'gopkg.in/yaml.v2' with 'github.com/ghodss/yaml'

### PR DESCRIPTION
**Pull request by lelenanam**
Fix issue #1192

Signed-off-by: Elena Morozova lelenanam@gmail.com

---

This change is [Reviewable](https://reviewable.kubernetes.io/reviews/kubernetes/helm/1216)

### CODE REVIEW

**Comment by technosophos** [comment]
Looks like this needs a rebase and then one more change to the imports.

**Comment by morelena** [comment]
@technosophos I wonder what is the process for updating glide.lock file? I've tried `glide up` and it hangs forever.

**Comment by technosophos** [comment]
I think @adamreese is looking at why it's hanging. Looks like there's a symlink in k8s that is causing that to happen.

**Comment by technosophos** [comment]
I'm debugging glide right now. Can you tell me which version of Glide you're running (and if it's from Homebrew)? `glide --version` should show that.

**Comment by morelena** [comment]
@technosophos  glide version 0.12.0-dev

**Comment by technosophos** [comment]
So I did some testing using `glide 0.12.2`

- There is definitely some delay fetching GitHub repos, and that's adding a lot of time. I'm on a very fast internet connection, and even small GitHub repos were taking 30 seconds to fetch.
- My aggregate time for a `glide up` was 6 minutes on an unwarmed cache
- If I tried to use k8s 1.4 instead of 1.3, things got a lot worse (8-20 minutes) and Helm won't build anyway b/c APIs changed
- There _might_ be a bug in the Glide caching algorithm, but I can't reproduce it.

Otherwise, I got things to fetch and build okay.

Would you mind giving it a shot again, and pasting glide's output if it gets stuck for more than 10 minutes? /cc @mattfarina

**Comment by technosophos** [comment]
I just looked at the output of the last test run... this is definitely not an easy issue. There seem to be some important differences in the way these two YAML parsers behave. Let me know if you get stuck on this, and I'll see if I can help test.

**Comment by morelena** [comment]
Seems I have no time for that

**Pull request closed without merging**
