### PR TITLE
helm install when resources already exist will fail

### PR DESCRIPTION
**Pull request by xchapter7x**
This is a PR to fix the issue described here: https://github.com/kubernetes/helm/issues/3319

- the intent here is to make the client smart enough to fail if a `Create` call is not able to complete successfully, due to a conflicting pre-existing resource.

I decided to implement this pre-existing resource check within the kubeclient. Reason being, if a `Create` call can not actually create the resource b/c the resource already exists, then one would expect the call to return an error.

This seemed more appropriate then implementing a check in the tiller package as part of the `InstallRelease` call, as tiller knows only about installing a release, and that it has a client interface upon which it can call `Create`. It shouldn't need to know anything about the expected behavior of the client Create call, and its handling of pre-existing resources.

The kubeclient Create implementation borrows the approach taken in the Update call on the kubeclient. Obvious difference being, update will skip pre-existing resources and create will now fail on pre-existing resources.

### CODE REVIEW

**Comment by xchapter7x** [comment]
hi @bacongobbler, @technosophos,

I just wanted to follow up and see if you had any thoughts about this PR? Feedback is be welcome and much appreciated. Thanks.

-John

**Comment by bacongobbler** [comment]
Hi @xchapter7x. Thanks for taking the time to write up a PR for this. At the time I did not have enough experience with `pkg/kube` to determine whether or not this was the right fix. Now that I'm more familiar with the codebase, this does seem like the right fix for the problem.

cc @thomastaylor312. What do you think about merging this one into Helm 2 and porting it over to Helm 3? Seems like it'd fix the issues we were discussing about the `--atomic` flag as well.

**Comment by thomastaylor312** [comment]
I implemented this using your handy function @xchapter7x in #6542 for v3. Based on what I see here with your PR, my one worry is that a release may still get created and cause issues when someone tries to delete it, but I've been going back and forth between the v2 and v3 codebase that I could be wrong.

**Comment by xchapter7x** [comment]
@thomastaylor312 @bacongobbler 
I'm glad this PR ended up adding some value for the community :)

Let me know if I can help with more contributions moving forward.

Keep up the great work 👍

**Comment by bacongobbler** [comment]
Thanks @xchapter7x! Given the complexity in this change we aren't planning on moving this through for Helm 2, however thank you for catalyzing the movement on Helm 3!

**Pull request closed without merging**
