### PR TITLE
Revert "feat(helm): adding kubeconfig flag"

### PR DESCRIPTION
**Pull request by bacongobbler**
This reverts commit 371ff8f26deaf57556b35dd6c0378950ae07422e.

This PR likely is what caused #3378. We'll have to test this PR manually to confirm.

cc @gardlt

### CODE REVIEW

**Comment by thomastaylor312** [comment]
This looks good to me, but I would like one of the people who reported the issue to test this and make sure

**Comment by DylanGraham** [comment]
Your branch:

    $ bin/helm version
    Client: &version.Version{SemVer:"v2.7+unreleased", 
    GitCommit:"f13c4d28b5d4b93e2b9f2586d78657e43b192311", GitTreeState:"clean"} Server: 
    &version.Version{SemVer:"v2.8.0", GitCommit:"14af25f1de6832228539259b821949d20069a222", GitTreeState:"clean"}

Standard 2.8.0:

    $ helm version
    Client: &version.Version{SemVer:"v2.8.0", GitCommit:"14af25f1de6832228539259b821949d20069a222", GitTreeState:"clean"}
    Error: cannot connect to Tiller

**Comment by bacongobbler** [comment]
thank you @DylanGraham for the vote of confidence. From testing it definitely does look like this was indeed the issue :)

**Comment by jascott1** [comment]
@bacongobbler  This is a breaking change for some people. Can you clarify how users specify kubeconfig location now? It appears its `$KUBECONFIG` or nothing.

**Comment by bacongobbler** [comment]
Technically speaking this PR fixes a regression introduced in v2.8.0. I’d be more than happy to get a PR running that fixes it while retaining this feature, but this was the quickest solution to fix v2.8.0 and get a release out the door so we can get feedback on other features introduced in v2.8.0.

In v2.7.2 users were using $KUBECONFIG, yes. This feature flag is new.

**Comment by jascott1** [comment]
Ok great, I didn't notice the feature was so new. Thanks!

**Review by mattfarina — APPROVED** [review]
/lgtm

**Comment by mattfarina** [comment]
@qrevel @torosent does this change fix your problem?

**Comment by qrevel** [comment]
/lgtm

Sorry I didn't check earlier, I only saw this PR when @mattfarina mentioned me.
Thanks for the fix.

**Comment by mattfarina** [comment]
@thomastaylor312 @jascott1 not that this has a thumbs up from the person who reported the issue can you do a review. This appears to be the last issue before cutting a 2.8.1 release.

**Review by SlickNik — APPROVED** [review]
/lgtm 👍

**Pull request merged**
