### PR TITLE
Return "unknown command" error for unknown subcommands

### LINKED ISSUE #6998: [helm3] unknown subcommand should return error
The output of `helm version`:

```
version.BuildInfo{Version:"v3.0.0", GitCommit:"e29ce2a54e96cd02ccfce88bee4f58bb6e2a28b6", GitTreeState:"clean", GoVersion:"go1.13.4"}
```

There is no error raised if I passed an unknown subcommand to Helm 3, no error message and the exit code is 0.
It's really hard to find out what is going wrong when I was debugging a helm 2 plugin. there supposed to be an error message to tell me which subcommand does not exist.

### PR DESCRIPTION
**Pull request by nauxliu**
Fix #6998

### CODE REVIEW

**Review by marckhouzam — COMMENTED** [review]
Could you add a test to check that an invalid subcommand does fail?

**Comment by marckhouzam** [comment]
/cc @adamreese who had refactored the arguments handling.

The change in behaviour is that an invalid command (e.g., `helm bad`) will now show an error message, not show the help, and have an error return code.

Is returning an error code when it used to not do so considered a breaking change?

**Comment by marckhouzam** [comment]
I've put @adamreese as a reviewer as this one-liner reverts a change he had made.  He may have some concerns about this.

**Comment by hickeyma** [comment]
@nauxliu Do you mind rebasing to fix the conflicts?

**Comment by adamreese** [comment]
@nauxliu I used the web interface to rebase for you but the last newline got lost.  Just needs to be formatted

**Comment by nauxliu** [comment]
@adamreese @hickeyma I've rebased and resolved conflicts.

**Review by hickeyma — APPROVED** [review]
LGTM, thanks for this fix @nauxliu

**Pull request merged**
