### PR TITLE
Fix watcher may have nil

### PR DESCRIPTION
**Pull request by lou-lan**

### CODE REVIEW

**Review by technosophos — APPROVED** [review]

**Comment by technosophos** [comment]
This needs to be tied to an issue before it can be merged.

**Comment by mattfarina** [comment]
@lou-lan can you please create an issue for this that describes the reason for the change.

**Comment by technosophos** [comment]
Having thought about his, I am a little worried that this may result in an unintended behavior change. Are we sure we want to short-circuit the watch in this case?

**Comment by bacongobbler** [comment]
closing. Multiple maintainers have asked for changes and longer explanations on the reason for this change.

When you are ready, please open a new PR following the guidelines suggested by the other maintainers, and link back to this PR for reference. Thanks.

**Pull request closed without merging**
