### PR TITLE
Revert "Fix for existing CRDs are deleted when crd-install hook is in…

### LINKED ISSUE #5054: helm fails installing CRDs using crd-install hook
This happens only with version `2.12.0` with version `2.11.0` works fine.

When trying to install a chart that installs CRDs with `crd-install` hook installation fails with the following error:
```
$ helm repo add presslabs https://presslabs.github.io/charts
"presslabs" has been added to your repositories

$ helm install presslabs/mysql-operator --name oper                                                                                                                                             
Error: customresourcedefinitions.apiextensions.k8s.io "mysqlbackups.mysql.presslabs.org" already exists
```
The chart crds template can be found [here](https://github.com/presslabs/mysql-operator/blob/master/hack/charts/mysql-operator/templates/crds.yaml#L13).

The CRDs are installed but the release is failed:
```
$ kubectl get crds                                                                                                                                                                                    
NAME                                    CREATED AT
mysqlbackups.mysql.presslabs.org        2018-12-13T16:17:52Z
mysqlclusters.mysql.presslabs.org       2018-12-13T16:17:52Z

$ helm ls
NAME	REVISION	UPDATED                 	STATUS	CHART               	APP VERSION	NAMESPACE
oper	1       	Thu Dec 13 18:17:51 2018	FAILED	mysql-operator-0.2.1	v0.2.1     	default 
```

After deleting the release the CRDs will be deleted too:
```
$ helm delete --purge oper                                                                                                                                                                      
release "oper" deleted

$ kubectl get crds
No resources found.
```
The CRD description:
```
$ kubectl describe crd mysqlclusters.mysql.presslabs.org                                                                                                                                              
Name:         mysqlclusters.mysql.presslabs.org
Namespace:    
Labels:       app=mysql-operator
              chart=mysql-operator-0.2.1
              controller-tools.k8s.io=1.0
              heritage=Tiller
              release=oper
Annotations:  helm.sh/hook=crd-install
API Version:  apiextensions.k8s.io/v1beta1
Kind:         CustomResourceDefinition
Metadata:
  Creation Timestamp:  2018-12-13T16:32:29Z
  Generation:          1
  Resource Version:    5047801
  Self Link:           /apis/apiextensions.k8s.io/v1beta1/customresourcedefinitions/mysqlclusters.mysql.presslabs.org
  UID:                 aebf3973-fef4-11e8-811a-42010a9c0035
Spec:
  Additional Printer Columns:
    JSON Path:    .metadata.creationTimestamp
    Description:  CreationTimestamp is a timestamp representing the server time when this object was created. It is not guaranteed to be set in happens-before order across separate operations. Clients may not set this value. It is represented in RFC3339 form and is in UTC.

Populated by the system. Read-only. Null for lists. More info: https://git.k8s.io/community/contributors/devel/api-conventions.md#metadata
    Name:  Age
    Type:  date
  Group:   mysql.presslabs.org
  Names:
    Kind:       MysqlCluster
    List Kind:  MysqlClusterList
    Plural:     mysqlclusters
    Short Names:
      mysql
    Singular:  mysqlcluster
  Scope:       Namespaced
  Subresources:
    Scale:
      Spec Replicas Path:    .spec.replicas
      Status Replicas Path:  .status.readyNodes
    Status:
  Version:  v1alpha1
  Versions:
    Name:     v1alpha1
    Served:   true
    Storage:  true
Status:
  Accepted Names:
    Kind:       MysqlCluster
    List Kind:  MysqlClusterList
    Plural:     mysqlclusters
    Short Names:
      mysql
    Singular:  mysqlcluster
  Conditions:
    Last Transition Time:  2018-12-13T16:32:29Z
    Message:               no conflicts found
    Reason:                NoConflicts
    Status:                True
    Type:                  NamesAccepted
    Last Transition Time:  <nil>
    Message:               the initial names have been accepted
    Reason:                InitialNamesAccepted
    Status:                True
    Type:                  Established
  Stored Versions:
    v1alpha1
Events:  <none>
```

Output of `helm version`:
```
Client: &version.Version{SemVer:"v2.12.0", GitCommit:"d325d2a9c179b33af1a024cdb5a4472b6288016a", GitTreeState:"clean"}
Server: &version.Version{SemVer:"v2.12.0", GitCommit:"d325d2a9c179b33af1a024cdb5a4472b6288016a", GitTreeState:"clean"}
```

Output of `kubectl version`:
```
Client Version: version.Info{Major:"1", Minor:"11", GitVersion:"v1.11.0", GitCommit:"91e7b4fd31fcd3d5f436da26c980becec37ceefe", GitTreeState:"clean", BuildDate:"2018-06-27T20:17:28Z", GoVersion:"go1.10.2", Compiler:"gc", Platform:"linux/amd64"}
Server Version: version.Info{Major:"1", Minor:"11+", GitVersion:"v1.11.2-gke.18", GitCommit:"5796233393d7bc034428de15191ad3d2eaff95fb", GitTreeState:"clean", BuildDate:"2018-11-08T20:49:08Z", GoVersion:"go1.10.3b4", Compiler:"gc", Platform:"linux/amd64"}
```

Cloud Provider/Platform (AKS, GKE, Minikube etc.): GKE, Digital Ocean

### PR DESCRIPTION
**Pull request by bacongobbler**
…troduced (#4709)"

This reverts commit e2a0e7fa545585a29c1e9602e6320479788eb9a6.

Signed-off-by: Matthew Fisher <matt.fisher@microsoft.com>

closes #5054

### CODE REVIEW

**Comment by philoserf** [comment]
Since this is a BUG that interferes with chart installation when there is a CRD shouldn't we expedite this and cut a patch release?

**Review by adamreese — APPROVED** [review]

**Comment by Stono** [comment]
Can anyone answer @philoserf question above?  I've come to upgrade helm today and noticed this revert (I'm currently on 2.11.0).  I'm now worried that with 2.12.1; the original bug present in 2.12.0 will cause CRD's to be deleted (which would be a disaster for us).

**Comment by philoserf** [comment]
The release was cut @Stono 

https://github.com/helm/helm/releases/tag/v2.12.1

**Comment by Stono** [comment]
Sorry, I missread @philoserf - but even so - this is: `Revert "Fix for existing CRDs are deleted`, so what about the original bug, where existing CRDs are deleted?

**Comment by tim-beatson** [comment]
@philoserf, this bug is again present in 2.12.2

**Pull request merged**
