### PR TITLE
Strict file permissions for repository.yaml

### LINKED ISSUE #11451: Repository configuration file permissions too wide
Output of `helm version`: `version.BuildInfo{Version:"v3.10.1", GitCommit:"9f88ccb6aee40b9a0535fcc7efea6055e1ef72c9", GitTreeState:"clean", GoVersion:"go1.18.7"}`

Output of `kubectl version`:
```console
Client Version: version.Info{Major:"1", Minor:"23", GitVersion:"v1.23.13", GitCommit:"592eca05be27f7d927d0b25cbb4241d75a9574bf", GitTreeState:"clean", BuildDate:"2022-10-12T10:57:16Z", GoVersion:"go1.17.13", Compiler:"gc", Platform:"linux/amd64"}
Server Version: version.Info{Major:"1", Minor:"23", GitVersion:"v1.23.13", GitCommit:"592eca05be27f7d927d0b25cbb4241d75a9574bf", GitTreeState:"clean", BuildDate:"2022-10-12T10:50:48Z", GoVersion:"go1.17.13", Compiler:"gc", Platform:"linux/amd64"}
```

Cloud Provider/Platform (AKS, GKE, Minikube etc.): `kubeadm`

I just noticed that Helm creates `~/.config/helm/repositories.yaml` with POSIX file permissions `0644`, which is probably not appropriate considering that it can contain credentials. Even if Helm derives the file permissions from the umask, world-readability is probably always too wide. Can we change the default permissions?

### PR DESCRIPTION
**Pull request by ksankeerth**
Closes #11451 

**What this PR does / why we need it**:
This PR remove read access of  "repository.yaml"  to world

**Special notes for your reviewer**:

**If applicable**:
- [ ] this PR contains documentation
- [ ] this PR contains unit tests
- [ ] this PR has been tested for backwards compatibility

### CODE REVIEW

**Comment by joejulian** [comment]
With secret data, shouldn't this be 600?

**Comment by ksankeerth** [comment]
> With secret data, shouldn't this be 600?

I initially started with 600. but later I changed to 640 as per the issue description. 

>  Even if Helm derives the file permissions from the umask, world-readability is probably always too wide

I'll change the permissions to 600 👍

**Review by joejulian — APPROVED** [review]
LGTM, but my review doesn't count. This needs a core maintainer to review.

**Review by yxxhero — COMMENTED** [review]
LGTM

**Review by mattfarina — APPROVED** [review]

**Review by joejulian — APPROVED** [review]

**Pull request merged**
