### PR TITLE
chore(docs): mv index.md to README.md

### PR DESCRIPTION
**Pull request by michelleN**
* Newcomers may not realize they have to look
for the index.md file when coming to the docs dir
* README.md makes the index easier to see

Is this going to break the helm.sh site? @flynnduism

### CODE REVIEW

**Comment by technosophos** [comment]
Yes, that will break helm.sh

**Comment by flynnduism** [comment]
This can be done, just need to update the docs site in tandem. I'll open a PR there.

**Comment by flynnduism** [comment]
Once [#88](https://github.com/helm/helm-www/pull/88) is merged and deployed, then this is 👍

**Comment by michelleN** [comment]
🙏 thank you Ronan!!

**Review by bacongobbler — APPROVED** [review]
looks like the work has been done upstream so this is good to go. Thanks @michelleN!

**Pull request merged**
