### PR TITLE
feat: update sprig to version 2.22

### PR DESCRIPTION
**Pull request by johanfleury**
`sprig` introduced some new interesting functions in 2.21 (`deepCopy` for instance).

I tried to update to `sprig` to version 3.0 (which is used on master) but couldn't: for some reason glide fails at finding `github.com/Masterminds/semver/v3` (I suppose this is due to their move to Go modules or something).

### CODE REVIEW

**Comment by karuppiah7890** [comment]
Thanks for the PR @johanfleury 😁 🎉 

Looks like @mattfarina helps maintain `sprig`. He might be able to help if you want to use v3 . I'll also check what's going wrong.

Also, on a side note, this PR looks like a feature addition to me. Looking at sprig changelog, yes, there were some fixes in v2.21.0 in sprig, v2.22.0 only has features. If you've been following the helm announcements, you might have noticed that we are doing only bug fixes for helm v2, and no more features. Not sure how to consider this PR 🙈 

If you notice, in `master`, helm v3 already has v3 sprig in this commit https://github.com/helm/helm/commit/967f4fed42d0347405aa71fb441b054f761ee8e2 by @mattfarina . Not sure if it was intentional to leave v2 as is.

ccing @mattfarina to help review.

**Comment by karuppiah7890** [comment]
Also, if you are looking to work on more PRs, you are always welcome 😄 

Do checkout https://github.com/helm/helm/#community-discussion-contribution-and-support for details about the mailing lists, discussions in slack and the developer calls on Thursdays 9:30 am -10 am Pacific time .

**Comment by mattfarina** [comment]
@johanfleury Can you please rebase from dev-v2. There was a change there.

**Comment by johanfleury** [comment]
@mattfarina done.

@karuppiah7890 thank you for the explanations.

**Comment by mattfarina** [comment]
> I'm not used to neither Golang nor glide, but is their a way to only update a single dependency without updating all the others? (I didn't meant to update github.com/pkg/errors, golang.org/x/sync or google.golang.org/genproto)

There is no method with Glide. To give a little history, Glide was superseded by dep which is in the process of being superseded by Go modules. Both dep and Go modules provide this ability. It was in the glide roadmap but was not implemented because of being overcome by events.

Helm v3 uses Go modules.

**Pull request closed without merging**
