### PR TITLE
Using const() defines constants together (part:1)

### PR DESCRIPTION
**Pull request by xichengliudui**
Signed-off-by: xichengliudui <1693291525@qq.com>

**What this PR does / why we need it**:

**Special notes for your reviewer**:

**If applicable**:
- [ ] this PR contains documentation
- [ ] this PR contains unit tests
- [ ] this PR has been tested for backwards compatibility

### CODE REVIEW

**Comment by xichengliudui** [comment]
here.

**Comment by bacongobbler** [comment]
Looks like there are formatting issues that need to be addressed.

> pkg/tiller/environment/environment.go:1::warning: file is not gofmted with -s (gofmt)

**Comment by xichengliudui** [comment]
I used `gofmt -w`, am I using it the wrong way?

**Comment by xichengliudui** [comment]
I just used `gofmt-s` and `gofmt-w` and then `git diff`, and nothing has changed between them

**Comment by xichengliudui** [comment]
@bacongobbler , has been updated, I just made a stupid question.

**Review by bacongobbler — APPROVED** [review]

**Pull request merged**
