### PR TITLE
feat(list-dependencies): Implement -with-dependencies args to list command (#8081)

### PR DESCRIPTION
**Pull request by Prims47**
**What this PR does / why we need it**:

Add arg `-with-dependencies` to list command.
See #8081 

**Special notes for your reviewer**:

**If applicable**:
- [ ] this PR contains documentation
- [ ] this PR contains unit tests
- [ ] this PR has been tested for backwards compatibility

### CODE REVIEW

**Review by bacongobbler — CHANGES_REQUESTED** [review]
Hi @Prims47. Based on the test output here, it looks like the output changed for `helm list --all`, `helm list --pending`. This would be considered a breaking change. Can you please look back and address these issues making sure that the output for existing feature flags remain the same. Thanks.

**Comment by bacongobbler** [comment]
For a refresher on our backwards compatibility guarantees: https://github.com/helm/helm/blob/master/CONTRIBUTING.md#semantic-versioning

**Comment by Prims47** [comment]
Hi @bacongobbler,

I completely understand what you're saying.

However I've tried not to break the existing flags.
Which is why if you look closely at the test `cmd/helm/list_test.go` line 179. I keep the same operation. In the following lines I have my order which does not output the same thing.

For command `list --pending`. It's because in my release fixture i create a it with status `StatusPendingInstall`.

**Comment by bacongobbler** [comment]
`helm list` implies that each name displayed marks a release name that I can interact with.

For example:

```
><> ./bin/helm list
NAME                	NAMESPACE	REVISION	UPDATED                                	STATUS  	CHART          	APP VERSION
wordpress-1590081299	default  	1       	2020-05-21 10:15:01.358417135 -0700 PDT	deployed	wordpress-7.5.4	5.2.4      
><> ./bin/helm get manifest wordpress-1590081299 | head -n 10
---
# Source: wordpress/charts/mariadb/templates/secrets.yaml
apiVersion: v1
kind: Secret
metadata:
  name: wordpress-1590081299-mariadb
  labels:
    app: "mariadb"
    chart: "mariadb-6.12.0"
    release: "wordpress-1590081299"
```

I cannot do that with `helm list --with-dependencies`.

```
><> ./bin/helm list --with-dependencies
NAME                                                                                         	NAMESPACE	REVISION	UPDATED                                	STATUS  	CHART          	APP VERSION
wordpress-1590081299                                                                         	default  	1       	2020-05-21 10:15:01.358417135 -0700 PDT	deployed	wordpress-7.5.4	5.2.4      
======== DEPENDENCIES ========                                                               
NAME                          	Version	Repository                                       	Enabled
mariadb                       	6.x.x  	https://kubernetes-charts.storage.googleapis.com/	true   
================                                                                             
><> ./bin/helm get manifest mariadb
Error: release: not found
```

We should probably put this under `helm get dependencies` instead, as that seems more fitting.

In addition, the output here differs from the rest of the Helm CLI's output. Can you please have a look at implementing [the output package](https://github.com/helm/helm/blob/master/pkg/cli/output/output.go) such that the output can be re-formatted depending on the user's needs. Have a look at [`helm get all`](https://github.com/helm/helm/blob/master/cmd/helm/get_all.go) for usage examples.

Hope this helps.

**Comment by bacongobbler** [comment]
See also https://github.com/helm/helm/issues/8066.

**Comment by Prims47** [comment]
Thanks 😄 

I close this PR because i create a new one => https://github.com/helm/helm/pull/8190

**Pull request closed without merging**
