### PR TITLE
feat(2063): Better 'helm list' visibility into state of pending upgrades

### PR DESCRIPTION
**Pull request by ata18**
This PR adds new statuses `PENDING_UPGRADE, PENDING_ROLLBACK, PENDING_INSTALL` to helm list. With this PR, `helm list --all` shows both the old release and the new release with a pending status while performing the upgrade/rollback and once the upgrade/rollback completes/fails, the new release's status gets updated accordingly. 

```
helm upgrade -f config.yaml excited-lamb stable/mariadb --wait
Release "excited-lamb" has been upgraded. Happy Helming!
```

```
--- k8s.io/helm ‹at-helm-list*➔ M?› » helm ls --all
NAME            REVISION        UPDATED                        STATUS                           CHART           NAMESPACE
excited-lamb    2               Tue Jul 11 16:55:44 2017        DEPLOYED                 mariadb-0.6.3   default
excited-lamb    3               Tue Jul 11 17:04:24 2017        PENDING_UPGRADE mariadb-0.6.3   default
```

```
--- k8s.io/helm ‹at-helm-list*➔ M?› » helm ls --all
NAME            REVISION        UPDATED                         STATUS          CHART           NAMESPACE
excited-lamb    3               Tue Jul 11 17:04:24 2017        DEPLOYED        mariadb-0.6.3   default

```

Fixes: https://github.com/kubernetes/helm/issues/2063

### CODE REVIEW

**Comment by at1012** [comment]
Hi @thomastaylor312, this is up for review.

**Comment by thomastaylor312** [comment]
Thank you @at1012. I'll take a look at this tomorrow night

**Comment by thomastaylor312** [comment]
@at1012 It looks like you had all of the protobuf definitions changed. What version of `protoc` are you using?

**Review by thomastaylor312 — APPROVED** [review]
I manually validated this as well and everything looks good. It also looks like the protobuf files are all just a comment change and when I regenerated them on my system it was the same with protoc 3.3.0. 

Thanks for the work on this, it is a very useful feature

**Comment by at1012** [comment]
Thanks to you, as well @thomastaylor312!

**Pull request merged**
