### PR TITLE
Migrate 'template' to 'include' in 'helm create' 

### PR DESCRIPTION
**Pull request by alexvicegrab**
...to conform to Helm best practices, as discussed in issue #4092

Signed-off-by: Alejandro Vicente Grabovetsky <sasha@aid.technology>

### CODE REVIEW

**Comment by alexvicegrab** [comment]
What is the best way of assigning reviewers here?

**Comment by alexvicegrab** [comment]
@bacongobbler ?

**Comment by bacongobbler** [comment]
This was recently changed in https://github.com/kubernetes/helm/pull/3337. @unguiculus and @prydonius are the undisputed "Charts Best Practices guru" 'round here so I'll defer to their experience. Looks like this was intended though.

**Comment by alexvicegrab** [comment]
Thanks @bacongobbler, as mentioned in the issue, I've updated the templates (rather than reverse any changes in 3337) to a recommendation by @technosophos to use `include` rather than `template`, which to me makes sense, as it's the more versatile of the two keywords and simplifies understanding Charts to newcomers.

**Review by prydonius — APPROVED** [review]

**Comment by bacongobbler** [comment]
awesome. Thanks @prydonius! I wanna give @unguiculus a chance to chime in here, but if there's no response by the end of the week I think we can go ahead with this change. Thanks @alexvicegrab :)

**Comment by alexvicegrab** [comment]
Good to merge? :)

**Comment by unguiculus** [comment]
@bacongobbler I did not change this in #3337. `template` had been used before. I kind of like this change, though. The only problem I see is that `template` is used almost exclusively in the charts repo, except for cases where piping is needed. @prydonius Maybe we should discuss the implications in the next charts call before merging this?

**Comment by bacongobbler** [comment]
@unguiculus I merged it prior to your response, sorry! If we need to back this out/tweak some things let us know.

**Pull request merged**
