### PR TITLE
create a relative path to the index file

### PR DESCRIPTION
**Pull request by bacongobbler**
refs dicsussion in #3595

cc @Stelminator

### CODE REVIEW

**Comment by bacongobbler** [comment]
Same output, but more portable in case we decide to change things in Helm 3.

**Comment by Stelminator** [comment]
Ah, glad to see something clean looking come out of the original mess.  I think the discussion on this was actually in https://github.com/kubernetes/helm/pull/3596.  I'm going to take a look at where else we need a similar change.

**Comment by bacongobbler** [comment]
thanks! yeah I meant to ref #3596

**Review by thomastaylor312 — APPROVED** [review]
Should be good to go. Looks like @Stelminator has already checked this to make sure it doesn't conflict with anything he is doing. 

If there is an easy way to add in a unit test for this before merging, that may be a good idea, but it is a small enough change that I don't see a need to block on it

**Review by SlickNik — APPROVED** [review]
Looks good to me. Thanks @bacongobbler 👍  -- adding a unit test for this scenario will be much appreciated.

**Pull request closed without merging**
