### PR TITLE
 fix(pkg/strvals): evaluate "null" values 

### LINKED ISSUE #3891: values_files.md indicates null for removing a key
This is a documentation issue about [values_files.md](https://github.com/kubernetes/helm/blob/master/docs/chart_template_guide/values_files.md).

Section [Deleting a default key](https://github.com/kubernetes/helm/blob/master/docs/chart_template_guide/values_files.md#deleting-a-default-key) indicates that you should set a value to `null` to delete a key. There is also an example about it:

    helm install stable/drupal ... --set livenessProbe.httpGet=null

Doing a test, it seems to set the variable to the literal string `"null"`.

When setting it to the *empty string*, I noticed that I could trigger a `default "..."` pipeline function, maybe indicating that an empty string should be used instead of `null` in the description and in the example.

Output of `helm version`:

    Client: &version.Version{SemVer:"v2.8.1", GitCommit:"6af75a8fd72e2aa18a2b278cfe5c7a1c5feca7f2", GitTreeState:"clean"}
    Server: &version.Version{SemVer:"v2.8.1", GitCommit:"6af75a8fd72e2aa18a2b278cfe5c7a1c5feca7f2", GitTreeState:"clean"}

### PR DESCRIPTION
**Pull request by michelleN**
resolves #3891

### CODE REVIEW

**Review by bacongobbler — APPROVED** [review]

**Comment by bacongobbler** [comment]
woah, guess the --author stuff we were messing around with earlier won't work here. Adding a `Co-Authored-By` header at the bottom is great though!

**Comment by royjs** [comment]
will this be part of a 2.9.x bugfix release? That would be really helpful

**Comment by bacongobbler** [comment]
Because it's a new feature, this will be part of the next minor release, so helm 2.10.0. :)

**Comment by royjs** [comment]
Unless I am mistaken it's a fix for a feature that was introduced a while ago ( See #2648)
I actually opened issue #3117  about this last November.

But if it's part of 2.10 I will still be happy :)

**Pull request merged**
