### PR TITLE
fix: fixed bug in Dependency.List()

### LINKED ISSUE #4431: Helm Dep List is returning "missing" for deps on packaged charts
Output of `helm version`:

```console
$ helm version --client
Client: &version.Version{SemVer:"v2.10.0-rc.2", GitCommit:"56154102a2f25ebf679c791907fd355bb0377f05", GitTreeState:"dirty"}
```

Output of `kubectl version`:

N/A -- this is client only

Cloud Provider/Platform (AKS, GKE, Minikube etc.):  N/A

Fetch the wordpress chart: `helm fetch stable/wordpress`

```console
$ helm dep list ./wordpress-2.1.5.tgz 
NAME   	VERSION	REPOSITORY                                       	STATUS
mariadb	4.x.x  	https://kubernetes-charts.storage.googleapis.com/	missing
```

Status is `missing`. But the dependency is in the tarball. Unpack the chart, and this is evident:

```console
$ tar -zxvf wordpress-2.1.5.tgz
x wordpress/Chart.yaml
x wordpress/values.yaml
x wordpress/templates/NOTES.txt
x wordpress/templates/_helpers.tpl
x wordpress/templates/deployment.yaml
x wordpress/templates/externaldb-secrets.yaml
x wordpress/templates/ingress.yaml
x wordpress/templates/pvc.yaml
x wordpress/templates/secrets.yaml
x wordpress/templates/svc.yaml
x wordpress/templates/tests/test-mariadb-connection.yaml
x wordpress/templates/tls-secrets.yaml
x wordpress/.helmignore
x wordpress/README.md
x wordpress/requirements.lock
x wordpress/requirements.yaml
x wordpress/charts/mariadb/Chart.yaml
x wordpress/charts/mariadb/values.yaml
x wordpress/charts/mariadb/templates/NOTES.txt
x wordpress/charts/mariadb/templates/_helpers.tpl
x wordpress/charts/mariadb/templates/initialization-configmap.yaml
x wordpress/charts/mariadb/templates/master-configmap.yaml
x wordpress/charts/mariadb/templates/master-statefulset.yaml
x wordpress/charts/mariadb/templates/master-svc.yaml
x wordpress/charts/mariadb/templates/secrets.yaml
x wordpress/charts/mariadb/templates/slave-configmap.yaml
x wordpress/charts/mariadb/templates/slave-statefulset.yaml
x wordpress/charts/mariadb/templates/slave-svc.yaml
x wordpress/charts/mariadb/templates/test-runner.yaml
x wordpress/charts/mariadb/templates/tests.yaml
x wordpress/charts/mariadb/.helmignore
x wordpress/charts/mariadb/OWNERS
x wordpress/charts/mariadb/README.md
x wordpress/charts/mariadb/files/docker-entrypoint-initdb.d/README.md

$ helm dep list wordpress
NAME   	VERSION	REPOSITORY                                       	STATUS
mariadb	4.x.x  	https://kubernetes-charts.storage.googleapis.com/	unpacked
```

### PR DESCRIPTION
**Pull request by technosophos**
A bug in Dependency.List() caused all compressed charts to flag their dependencies as "missing".

Also added tests, which probably should have been there all along.

Closes #4431

Signed-off-by: Matt Butcher <matt.butcher@microsoft.com>

### CODE REVIEW

**Review by adamreese — APPROVED** [review]

**Comment by adamreese** [comment]
This is marked XXL due to test fixtures.  Merge away!

**Review by hickeyma — COMMENTED** [review]
Thanks for pushing the fix @technosophos. Just wondering if it is possible to re-use some of the existing tests charts rather than adding such a large load of charts artefacts?

**Comment by technosophos** [comment]
There were no test charts in that `testdata` package.

**Comment by hickeyma** [comment]
> There were no test charts in that `testdata` package.

Good point. I was thinking of test dependency chart which I had forgotten now reside in `cmd/helm/testdata/testcharts/`! 😄   I am ok either way; just wanted to avoid loading similar files if we can avoid it.

**Review by hickeyma — APPROVED** [review]
Apart from whether can re-use test data, it LGTM. Thanks for the fix @technosophos

**Comment by technosophos** [comment]
My issue with re-using test data is that you tend to then unintentionally add dependencies on your tests. If Test A and Test B both use the same data, it is possible that a change you make on the data in order to alter a test on Test A will unintentionally alter Test B. If we start using the same test data across packages, it gets harder and harder to trace those test inter-dependencies. This, in my mind, defeats the purpose of isolating test cases in unit tests.

I will take a look, though, at reducing at least the number of files in this particular PR. I can probably cut a few.

**Pull request merged**
