### PR TITLE
Added a --wait flag to helm init

### LINKED ISSUE #2114: Feature request: `helm init --wait`
It's now possible in 2.2.x to use the `--wait` flag to [wait for deploys](https://github.com/kubernetes/helm/issues/1805) to be ready which is a great addition especially for various CI/CD scenarios.

How feasible would it be to add the same to `helm init` with reference specifically to Tiller and it being ready to serve? Same premise as waiting for Charts to be ready but with Tiller itself to be installed/upgraded.

### PR DESCRIPTION
**Pull request by ghost**
Added a --wait flag to helm init which pings the Tiller grpc server to ensure that it is ready to receive requests.
Fixes #2114

### CODE REVIEW

**Comment by TheOriginalAlex** [comment]
Bump to verify CLA.

**Comment by unguiculus** [comment]
To be consistent, I'd just call it `--wait`.

**Comment by TheOriginalAlex** [comment]
@unguiculus: `--wait` already exists for most of these things.  `--wait` and `--wait-for-ready` has different functionalities.  `--wait` blocks until the release chart is installed in the cluster, whereas `--wait-for-ready` blocks until the Tiller is ready.

**Comment by unguiculus** [comment]
In my eyes, it's the same thing. It all boils down to ready pods.

**Comment by TheOriginalAlex** [comment]
@unguiculus: Changed.

**Comment by TheOriginalAlex** [comment]
Bump.

**Comment by bacongobbler** [comment]
I disagree with what @unguiculus says. There can be two separate use cases here: failing fast for when the RPC request is attempted on broken or unreachable tiller instances, and waiting for the resources to come up. A user may want to wait for resources to come up on `helm install` but fail fast when the connection to tiller is broken. With this change, that won't be possible.

As far as I'm aware, this hasn't been discussed elsewhere so I'm a little oblivious as to what exactly this is supposed to fix. Can we get a bit of background context on how this bug arises, and how the proposed fix affects users of Helm? Thanks!

**Comment by bacongobbler** [comment]
As an aside, it would be nice if this flag was documented and covered by unit tests if possible. That way we can provide more information on what this feature flag does and how it affects the user.

**Comment by TheOriginalAlex** [comment]
That makes sense.  :)

**Comment by TheOriginalAlex** [comment]
@bacongobbler: Should I go ahead and make the change?

**Comment by bacongobbler** [comment]
I'm still unsure what the actual issue is (how it pops up, how it occurs). Once that's nailed down and we have a solid idea for the problem. #2114 is a separate feature request than what's proposed here as far as I can tell. :)

**Comment by TheOriginalAlex** [comment]
I have a bash script where I'm trying to automate creating a Tiller pod and deployed a chart with `helm install`, but I can't do that because `helm init` doesn't wait to finish installing and `helm install` doesn't have an option to not be fail fast.

**Comment by TheOriginalAlex** [comment]
`kubectl rollout status -w` is a work around, but there's a chance of a race condition there.  `rollout status` just waits for the pod to start IIRC.  But, there's a slight chance that the pod could start but the grpc server might have a delayed start and my subsequent `helm install` would fail.

**Comment by TheOriginalAlex** [comment]
I was trying to solve the same issue `helm init --wait` would.  I suppose I could just solve that instead since there already is an issue for it.

**Comment by bacongobbler** [comment]
Yeah. If we add --wait to `helm init` then this problem (and the need for turning off grpc's fail fast mode) will disappear.

**Review by bacongobbler — APPROVED** [review]

**Comment by bacongobbler** [comment]
Hey! Sorry I missed the notification when this was updated. This looks great! If you wouldn't mind rebasing the PR, we can merge this in. Thanks again!

**Comment by TheOriginalAlex** [comment]
Done!  Thank you!

**Pull request merged**
