### PR TITLE
feat(helm): add ability to sort release list by chart name

### LINKED ISSUE #4321: Feature Request: `helm ls` sort by chart name
Hello people! Thanks for a great tool in helm!

As [the documentation states](https://docs.helm.sh/helm/#helm-list), helm will by default sort by release name, and optionally (with the `-d` / `--date` flag) by release date.

**TL;DR**  
I would like to request the ability to sort releases by chart name.

**Background**  
Our use case, for completeness, is that we have a distributed computing system with ~30 systems. Releasing is a manual process, and when we look to make sure the versions are properly deployed, we use `helm ls` to check the versions.

Since we release every system (that has been updated) at the same time, sorting by date becomes meaningless to us, as well as sorting by release name. `mewing-billygoat` and `wishful-chinchilla` are most likely meaningless to other developers as well.

The alternative solution would be to name the releases, but as the charts are already named meaningfully, this becomes redundant.

Thanks for taking your time to read this.

### PR DESCRIPTION
**Pull request by adshmh**
Added the ability to sort the list of release by chart name. Fixes #4321 
 
Signed-off-by: Arash Deshmeh <adeshmeh@ca.ibm.com>

### CODE REVIEW

**Comment by adshmh** [comment]
@bacongobbler would appreciate it if you could take a look at this PR (if the changes look reasonable I can rebase to resolve the conflicts)

**Review by bacongobbler — APPROVED** [review]
This looks great! Would you mind rebasing this? Thanks so much.

**Comment by adshmh** [comment]
Thank you for the code review. Rebased.

**Comment by bacongobbler** [comment]
Thanks again :)

**Pull request merged**
