### PR TITLE
Add reference to text/template Go package doc

### PR DESCRIPTION
**Pull request by stapelberg**
…since people might not be familiar with Go templates.

### CODE REVIEW

**Comment by stapelberg** [comment]
I originally created the commit in GitHub’s web interface, hence it didn’t use my google.com email address. I’ve fixed this now. Let’s see if this works: @googlebot, I signed it

**Comment by stapelberg** [comment]
Also added my google.com email to GitHub. @googlebot, I signed it.

**Comment by stapelberg** [comment]
Further below in the doc (https://github.com/kubernetes/helm/blob/master/docs/charts.md#references), there’s actually already a reference to that page. Should I change my PR to refer to the references section?

**Comment by technosophos** [comment]
Thanks! This all looks fine. No need to change the PR for that.

**Pull request merged**
