### PR TITLE
chore(client): fix style errors

### LINKED ISSUE #482: Style error in pkg/client
```
==> Running golint...

pkg/client/deployments.go:103:1: comment on exported method Client.DescribeDeployment should be of the form "DescribeDeployment ..."
```

### PR DESCRIPTION
**Pull request by michelleN**
Fixes #482

### CODE REVIEW

**Comment by jackgr** [comment]
The changes to `pkg/client/client.go` don't look like style fixes or related to #482.

**Comment by michelleN** [comment]
There was an 'e' missing in DescribeDeployment which is why we were seeing the style error in #482, so that resolves #482. There was another style error being thrown in pkg/client/client.go about doing a return in an else statement so I moved the the return outside of the else block getting rid of another style error. The github highlighting makes the change look a little strange.

**Comment by jackgr** [comment]
Aha! Good catch!


-- 
Jack Greenfield | Google

**Comment by sparkprime** [comment]
Always fun when you break the diff algorithm :)

LGTM

**Comment by jackgr** [comment]
:+1:

**Pull request merged**
