### PR TITLE
Fix compile errors related to missing dependencies.

### PR DESCRIPTION
**Pull request by sparkprime**
I don't know if this is the correct fix but it worked for me.

### CODE REVIEW

**Comment by jackgr** [comment]
@technosophos PTAL.

**Comment by jackgr** [comment]
@sparkprime please rebase.

**Comment by technosophos** [comment]
Can you re-run as `GOOS=linux glide up`? I can't tell for sure, but it looks like some of the packages that are removed here are transient dependencies for Linux builds.

Otherwise, this looks good.

On a side note: we really need some tests on the manager. These dependencies slipped through the cracks because they are not (transient) dependencies for tests, so test coverage didn't fail locally or in CI/CD.

**Comment by technosophos** [comment]
*UPDATE:* The reason this is failing on Circle is because GOOS was not set to "linux" before. So it's not rebase-related; it's related to the glide.lock file. Simply re-running as I suggested will fix the CircleCI build.

**Comment by jackgr** [comment]
Thanks for catching, @technosophos.

**Comment by technosophos** [comment]
Should probably also install a newer version of Glide. The bug that caused this was fixed by 0.9.3, if not before.

**Comment by sgoings** [comment]
@sparkprime It looks like if you add `export GO15VENDOREXPERIMENT=1` into the Makefile, CircleCI will look at your vendor directory correctly (it's not).

**Comment by sparkprime** [comment]
This PR requires exhaustively adding all the DM dependencies to the glide.yaml file, which is mechanical work and not a good use of hackathon time, so will punt until later.

**Comment by technosophos** [comment]
Okay, so am attempting to reproduce locally. I cannot reproduce.

Glide version: `0.9.3-4-gd5fc6b6` (built off of master)
Go version: go version go1.5.1 darwin/amd64

Go env:

```
GOARCH="amd64"
GOBIN=""
GOEXE=""
GOHOSTARCH="amd64"
GOHOSTOS="darwin"
GOOS="darwin"
GOPATH="/Users/mattbutcher/Code/tmpGo"
GORACE=""
GOROOT="/usr/local/Cellar/go/1.5.1/libexec"
GOTOOLDIR="/usr/local/Cellar/go/1.5.1/libexec/pkg/tool/darwin_amd64"
GO15VENDOREXPERIMENT="1"
CC="clang"
GOGCCFLAGS="-fPIC -m64 -pthread -fno-caret-diagnostics -Qunused-arguments -fmessage-length=0 -fno-common"
CXX="clang++"
CGO_ENABLED="1"
```


Here's what I did:

```console
$ cd ~
$ mkdir -p Code/tmpGo
$ export GOPATH=$(pwd)/Code/tmpGo
$ cd $GOPATH
$ mkdir -p src/github.com/kubernetes
$ cd src/github.com/kubernetes
$ git clone git@github.com:kubernetes/helm.git
$ cd helm
```

So at this point, I have `$GOPATH` with _only_ this repo.

*Test 1:* Run `glide install` and rebuild from a known state.

This should pull all of the direct and transitive dependencies.

```
$ glide install
[WARN] Lock file may be out of date. Hash check of YAML failed. You may need to run 'update'
[INFO] Downloading dependencies. Please wait...
[INFO] Fetching updates for github.com/aokoli/goutils.
[INFO] Fetching updates for github.com/gorilla/mux.
[INFO] Fetching updates for github.com/Masterminds/httputil.
[INFO] Fetching updates for github.com/emicklei/go-restful.
[INFO] Fetching updates for github.com/google/go-querystring.
[INFO] Fetching updates for github.com/gorilla/handlers.
[INFO] Fetching updates for golang.org/x/net.
[INFO] Fetching updates for github.com/Masterminds/sprig.
[INFO] Fetching updates for github.com/Masterminds/semver.
[INFO] Fetching updates for golang.org/x/oauth2.
[INFO] Fetching updates for google.golang.org/api.
[INFO] Fetching updates for github.com/ghodss/yaml.
[INFO] Fetching updates for github.com/google/go-github.
[INFO] Fetching updates for google.golang.org/cloud.
[INFO] Fetching updates for github.com/codegangsta/cli.
[INFO] Fetching updates for github.com/gorilla/context.
[INFO] Fetching updates for gopkg.in/yaml.v2.
[INFO] Fetching updates for gopkg.in/mgo.v2.
[INFO] Downloading dependencies. Please wait...
[INFO] Setting references.
[INFO] Setting version for github.com/gorilla/mux to 26a6070f849969ba72b72256e9f14cf519751690.
[INFO] Setting version for github.com/Masterminds/semver to c4f7ef0702f269161a60489ccbbc9f1241ad1265.
[INFO] Setting version for github.com/Masterminds/sprig to 0199893f008a87287bf2b4e3e390e66bb074c659.
[INFO] Setting version for github.com/Masterminds/httputil to e9b977e9cf16f9d339573e18f0f1f7ce5d3f419a.
[INFO] Setting version for github.com/gorilla/context to 1c83b3eabd45b6d76072b66b746c20815fb2872d.
[INFO] Setting version for github.com/google/go-querystring to 2a60fc2ba6c19de80291203597d752e9ba58e4c0.
[INFO] Setting version for github.com/google/go-github to b8b4ac742977310ff6e75140a403a38dab109977.
[INFO] Setting version for github.com/ghodss/yaml to 73d445a93680fa1a78ae23a5839bad48f32ba1ee.
[INFO] Setting version for github.com/emicklei/go-restful to b86acf97a74ed7603ac78d012f5535b4d587b156.
[INFO] Setting version for gopkg.in/mgo.v2 to d90005c5262a3463800497ea5a89aed5fe22c886.
[INFO] Setting version for github.com/gorilla/handlers to 8f2758070a82adb7a3ad6b223a0b91878f32d400.
[INFO] Setting version for gopkg.in/yaml.v2 to f7716cbe52baa25d2e9b0d0da546fcf909fc16b4.
[INFO] Setting version for github.com/codegangsta/cli to a2943485b110df8842045ae0600047f88a3a56a1.
[INFO] Setting version for github.com/aokoli/goutils to 9c37978a95bd5c709a15883b6242714ea6709e64.
[INFO] Setting version for google.golang.org/cloud to fb10e8da373d97f6ba5e648299a10b3b91f14cd5.
[INFO] Setting version for golang.org/x/net to 04b9de9b512f58addf28c9853d50ebef61c3953e.
[INFO] Setting version for golang.org/x/oauth2 to 8a57ed94ffd43444c0879fe75701732a38afc985.
[INFO] Setting version for google.golang.org/api to 0caa37974a5f5ae67172acf68b4970f7864f994c.
```

A `make build` succeeded after that.

```
$ rm -rf vendor/
```

*Test 2:* Resolve dependencies using `glide up`

```
$ glide up
[INFO] Downloading dependencies. Please wait...
[INFO] Fetching updates for github.com/Masterminds/semver.
[INFO] Fetching updates for github.com/aokoli/goutils.
[INFO] Fetching updates for github.com/emicklei/go-restful.
[INFO] Fetching updates for github.com/codegangsta/cli.
[INFO] Fetching updates for github.com/ghodss/yaml.
[INFO] Fetching updates for github.com/gorilla/mux.
[INFO] Fetching updates for github.com/google/go-github.
[INFO] Fetching updates for github.com/gorilla/handlers.
[INFO] Fetching updates for gopkg.in/yaml.v2.
[INFO] Fetching updates for github.com/Masterminds/httputil.
[INFO] Fetching updates for github.com/Masterminds/sprig.
[INFO] Resolving imports
[INFO] Fetching github.com/cloudfoundry-incubator/candiedyaml into /Users/mattbutcher/Code/tmpGo/src/github.com/kubernetes/helm/vendor
[INFO] Fetching github.com/gorilla/context into /Users/mattbutcher/Code/tmpGo/src/github.com/kubernetes/helm/vendor
[INFO] Fetching gopkg.in/mgo.v2 into /Users/mattbutcher/Code/tmpGo/src/github.com/kubernetes/helm/vendor
[INFO] Fetching github.com/google/go-querystring/query into /Users/mattbutcher/Code/tmpGo/src/github.com/kubernetes/helm/vendor
[INFO] Fetching golang.org/x/oauth2 into /Users/mattbutcher/Code/tmpGo/src/github.com/kubernetes/helm/vendor
[INFO] Fetching golang.org/x/net/context into /Users/mattbutcher/Code/tmpGo/src/github.com/kubernetes/helm/vendor
[INFO] Fetching google.golang.org/cloud/compute/metadata into /Users/mattbutcher/Code/tmpGo/src/github.com/kubernetes/helm/vendor
[INFO] Fetching google.golang.org/api/storage/v1 into /Users/mattbutcher/Code/tmpGo/src/github.com/kubernetes/helm/vendor
[INFO] Downloading dependencies. Please wait...
[INFO] Setting references for remaining imports
[INFO] Project relies on 19 dependencies.
```

Note that all the things worked fine. `make build` correctly built all of the binaries.

So something between our two environments is different. Maybe if you give some more of the version information we can start to close in on it.

**Comment by sparkprime** [comment]
Ok this is weird.   I followed @technosophos steps and indeed it did work for me.  Then I tried doing it in my usual workspace (reverting to master) and it worked there as well.  However earlier, it did not work.  I can only think that the renaming of the repository may have changed something.  I'm going to close this as I can no-longer reproduce myself...

**Comment by sparkprime** [comment]
For posterity:
dcunnin@tyrion:~/helm$ go version
go version go1.6 linux/amd64
dcunnin@tyrion:~/helm$ glide --version
glide version 0.9.3-4-gd5fc6b6

**Pull request closed without merging**
