### PR TITLE
feat(helm): add --template flag to `helm version` 

### PR DESCRIPTION
**Pull request by darkowlzz**
~JSON marshal helm version value instead of printing the value.~

`helm version --template` prints the client and server version info in the provided template format.

### CODE REVIEW

**Comment by bacongobbler** [comment]
This is a backwards-incompatible change so we wouldn't be able to accept this PR as-is. However, perhaps putting this behind a feature flag like `--template` that is run through a Go template might be useful for others and would allow it to open up to certain use cases like when we want to print only the Semver tag or the git tree state.

e.g.

```
$ helm version --client --template='{"semver": "{{ .Client.SemVer }}","git-commit":"{{ .Client.GitCommit }}","git-tree-state":"{{ .Client.GitTreeState }}"}'
```

or, for just the client semver tag:

```
$ helm version --client --template="{{ .Client.SemVer }}"
```

What do you think?

**Comment by bacongobbler** [comment]
Keep in mind that kubectl also originally set this precedent of printing the value.

```
><> kubectl version --client
Client Version: version.Info{Major:"1", Minor:"7", GitVersion:"v1.7.1", GitCommit:"1dc5c66f5dd61da08412a74221ecc79208c2165b", GitTreeState:"clean", BuildDate:"2017-07-14T05:22:03Z", GoVersion:"go1.8.3", Compiler:"gc", Platform:"darwin/amd64"}
```

**Comment by darkowlzz** [comment]
> What do you think?

@bacongobbler great! that would be very nice. I have updated the PR to add the feature you suggested. Thanks 😊

**Comment by technosophos** [comment]
@bacongobbler Want to re-review this one?

**Comment by bacongobbler** [comment]
Sure, I'll give it another go along with a manual test.

**Review by bacongobbler — APPROVED** [review]
Works as advertised. Thanks!

```
><> ./bin/helm version
Client: &version.Version{SemVer:"v2.6+unreleased", GitCommit:"176e07765320d8e2d0c4dc74d9db43fb2a5fd55b", GitTreeState:"clean"}
Server: &version.Version{SemVer:"v2.6.0", GitCommit:"5bc7c619f85d74702e810a8325e0a24f729aa11a", GitTreeState:"clean"}
><> ./bin/helm version --template '{{ println .Client.SemVer }}{{ println .Server.SemVer }}'
v2.6+unreleased
v2.6.0
><> 
```

**Comment by bacongobbler** [comment]
Looks like `make docs` needs to be called though to update the CLI documentation before this PR can be merged.

**Comment by bacongobbler** [comment]
ping @darkowlzz, do you have time to rebase and re-generate the docs? Let me know. If you're too busy we can bring this through the finish line :)

**Comment by darkowlzz** [comment]
@bacongobbler oops! sorry, I totally forgot about this 😅 .
Generated docs and amended into the previous PR.

**Comment by bacongobbler** [comment]
hmm, that's the same issue we saw in #3247 as well. I'll see if I can look into it.

**Comment by bacongobbler** [comment]
This was fixed in CI, so it's just a matter of rebasing this PR and we're good to merge!

**Comment by jascott1** [comment]
Hi @darkowlzz, do you think you will be able to `make docs` and rebase this? It would be great to get this finished up. Thanks!

**Comment by darkowlzz** [comment]
@jascott1 Thanks, I've updated the docs :)

**Comment by bacongobbler** [comment]
thanks!

**Pull request merged**
