### PR TITLE
Detect kubeconfig as known argument in plugin invocations 

### PR DESCRIPTION
**Pull request by jayme-github**
**What this PR does / why we need it**:
With Helm 2 --kubeconfig is not detected as a known argument on plugin invocations. This means it depends on the order or arguments if helm picks it up or not which might not be under users control (for me in case of helmfile calling "helm diff").

Helm 3 has this fixed with https://github.com/helm/helm/commit/0650d6953de6267c0f20ca9014af25c5abb508f5

### CODE REVIEW

**Comment by paulczar** [comment]
@mattfarina 

would we need to add the following to https://github.com/helm/helm/blob/dev-v2/pkg/plugin/plugin.go#L196  
  
```
  if settings.KubeConfig != "" {
		envvars["KUBECONFIG"] = settings.KubeConfig
	}
```

**Review by mattfarina — CHANGES_REQUESTED** [review]
I ran some tests. The commit referenced in the original PR adds the value from the kubeconfig to the environment. This PR does not.

There is a priority to the passed in config...
1. The flag passing in a value
2. An environment variable for it

If there is an environment variable and a flag is passed in it takes precedent. This PR removes the possibility of a flag value overriding the environment variable. Currently the plugin would have to take care of this (in Helm v3 it's handled for you) but the option is there.

I ran some tests on a plugin and I can regularly get access to the --kubeconfig flag. I understand there are sometimes it doesn't work.

We need the environment variable set to the value from the kubeconfig flag along with this.

**Comment by jayme-github** [comment]
Thanks for the review. I've added setting/overriding the environment variable for plugins in case of --kubeconfig.

**Review by paulczar — APPROVED** [review]

**Comment by bacongobbler** [comment]
We are no longer accepting bug fixes for Helm 2. See https://helm.sh/blog/helm-v2-deprecation-timeline/ for more details.

**Pull request closed without merging**
