### PR TITLE
feat(*): add annotations to release

### PR DESCRIPTION
**Pull request by ibazhitov**
Annotations is an unstructured key value map stored with a release that
may be set by external tools to store and retrieve arbitrary metadata.

For example: currently there is no way to tell where the chart, from which
a release had been installed, came from (local file, repo, etc.). We can
store the chart's origin in the release annotations.

In future, when Helm will utilize TPRs or an addon API server to store
the release data, these annotations can easily be converted to the k8s
API's v1.ObjectMeta.Annotations.

### CODE REVIEW

**Comment by technosophos** [comment]
We have in the past refrained from automatically adding annotations and labels, and instead suggested that people do this _in the charts_. The chart convention documents cover this, and most charts that I have seen seem to implement at least some of this. For example:

```
metadata:
  name: my-release-deployment
  labels:
    app: my-release
    chart: myapp-0.1.0
    release: my-release
    heritage: Tiller
```

Can you explain why it is better to do this in Tiller code instead? And also why it should be done in  annotations instead of labels?

 I think there is an issue covering this already, and it has some associated discussion.

**Comment by ibazhitov** [comment]
> Can you explain why it is better to do this in Tiller code instead?

Sorry, I was unclear here.
I suggest attaching annotations only to the Helm's Release objects, not to the k8s objects, that are produced by Tiller when a release had been installed. I haven't found existing ways to store arbitrary metadata with Release objects, so I've decided to introduce k8s-like annotations.

Examples of such metadata would be:
- origin (repo, path in the filesystem) of the installed Chart;
- user (name, email), that installed the Release;
- comments, inserted by user, which installed the Release.

> And also why it should be done in annotations instead of labels?

Label keys have fixed length (AFAIR 63 chars?), while annotation keys don't have length limits. Also, the main purpose of labels is selecting objects, while annotations are there to store arbitrary (non-identifying) metadata with objects.
I believe, it could be also useful to attach labels along with annotations to Releases. For example, to list only releases, created by a given user.
But I don't have use-cases for labels yet, so I've proposed adding annotations only.

**Comment by ibazhitov** [comment]
Seems like the author of #2450 also wants this functionality.

BTW, I can modify the PR so we would store the annotations in the underlying ConfigMap's `metadata.annotations` instead of storing them along with the other Release data in the `data.release` field.
This way the annotations might be accessed without Tiller's help.

**Comment by technosophos** [comment]
Hmm... yeah, this is a more sophisticated approach than #2671, but would accomplish the same thing. So it might solve @kdada's problem, but also add a desirable feature to Helm.

@kdada would this solve your use case?

Regarding annotations, it seems like it might be more useful in the ConfigMap annotations, but that would cause quite a bit of extra work for other storage drivers. So leaving as-is is okay on that front.

**Comment by kdada** [comment]
@technosophos  Actually, I need the both feature. 

The `annotation` is used for runtime info. I can use it to store runtime info instead of using `values.yaml` (#2450 as your said). And I need #2671 to store static info which belongs to a chart.

**Comment by ibazhitov** [comment]
Added a one-line fixup: restore annotations on Release rollback.

**Comment by ibazhitov** [comment]
Rebased against master.

**Comment by ibazhitov** [comment]
BTW, here is the story behind this PR.

I'm working on an application -- kind of frontend to the part of Helm functionality. Among other things, it should be able to display a link to a Chart, from which a given Release had been installed.
Most likely, I'll also need to attach some other metadata, like those I've mentioned in the examples, to a Release in the future.

**Pull request closed without merging**
