### PR TITLE
Add flake8 test and fix pep8 style in expansion scripts

### LINKED ISSUE #331: Make python scripts in expansion directory follow pep8
fix pep8 for all python scripts
add tests to verify compliance

### PR DESCRIPTION
**Pull request by sebgoa**
fixes #331 

low priority, just picking this up as I walk through the code

### CODE REVIEW

**Comment by runseb** [comment]
we need flake8 on the golang env of circleCI, struggling to get this going right now.

**Comment by technosophos** [comment]
Do we have `pip` available in the container? It might be easier to set up the Python container to run Go than to set up the Go container to do Python.

**Comment by technosophos** [comment]
I did a tiny bit of poking about, and we do have pip in the container. Is it possible to just install flake8 with pip in the circle.yaml file?

**Comment by runseb** [comment]
@technosophos not sure why I missed pip....just added a pip instal lflake8 in the circle.yml seems tests pass.

There is now a
```
make test-flake8
```

It is included in the main `make test`.

I did not run the expandybird tests after my changes though...

**Comment by technosophos** [comment]
@runseb All looks good to me. If you're ready, I'll merge.

**Comment by runseb** [comment]
Yes, go ahead and merge

-Sebastien

**Pull request merged**
