### PR TITLE
Proposal: Support managing releases for external clusters in Tiller

### PR DESCRIPTION
**Pull request by tamalsaha**
Addresses #1586,  #1650 and #1714.

### CODE REVIEW

**Comment by technosophos** [comment]
We differe from Kubernetes in that proposals for us go into the issue queue as issues, not PRs. So if you'd like to just copy the text of the Markdown file into an issue and open it there, that'd be better.

There's a lot to that proposal. The core team is reading through it.

**Comment by TamalSaha** [comment]
@technosophos , I have copies the test in #1586

**Comment by technosophos** [comment]
Thanks!

**Comment by TamalSaha** [comment]
You are welcome. So, I can close this pr?

**Comment by technosophos** [comment]
yeah

**Pull request closed without merging**
