### PR TITLE
move pkg cmd/helm/strvals to pkg/strvals

### PR DESCRIPTION
**Pull request by bacongobbler**
This is another useful package outside of cmd/helm.

### CODE REVIEW

**Comment by bacongobbler** [comment]
For my use case, currently I'm maintaining a copy/paste of pkg cmd/helm/strvals to parse yaml. It would be awesome to just use the upstream package instead :)

**Review by technosophos — APPROVED** [review]
I agree. I actually needed it for my `helm-template` function, too.

**Comment by bacongobbler** [comment]
I rebased it!

**Comment by chancez** [comment]
I was about to mention to @technosophos this might help with the helm-template bug i filed! Looks like y'all are on it. Does this also cover the string slice flag stuff that allows you to provide `--set` or `--values` multiple times? Might be a good follow up.

**Comment by technosophos** [comment]
@chancez Yeah, it will make it much easier to do the multiple --set flags on helm-template.

**Pull request merged**
