### PR TITLE
Windows arm64 build

### PR DESCRIPTION
**Pull request by asmitde**
**What this PR does / why we need it**:
Adds support for Windows arm64 builds.

**Special notes for your reviewer**:
Cross compiled Helm for windows/arm64 on Surface Pro X (ARM64) in WSL2 with Go v1.22.2 linux/arm64. Tested the windows/arm64 binary in the Windows 11 powershell environment.

**If applicable**:
- [ ] this PR contains documentation
- [ ] this PR contains unit tests
- [ ] this PR has been tested for backwards compatibility

### CODE REVIEW

**Comment by rain-on** [comment]
I've replicated the behaviour specified in the PR.

Compiling on OSX 14.4 using:
`GOOS=windows GOARCH=arm64 make`

Then transferred the `bin\helm` to an arm64 virtual-machine, renamed to helm.exe, and successfully executed the binary.
👍

**Review by rain-on — APPROVED** [review]
LGTM

**Comment by rain-on** [comment]
Should pkg/plugin/plugin_test.go need an additional line after 95 to include arm64 windows?
`{OperatingSystem: "windows", Architecture: "arm64", Command: "echo -n win-arm64"},`

**Review by mattfarina — APPROVED** [review]
We discussed this in a Helm developer call on May 16, 2024 and decided to approve it.

**Pull request merged**
