### PR TITLE
[helm create] Annotations

### PR DESCRIPTION
**Pull request by naseemkullah**
**What this PR does / why we need it**:
Eases the addition of annotations (e.g. `prometheus.io/scrape: "true"` or  `"cluster-autoscaler.kubernetes.io/safe-to-evict": "true"`) for end user creating a chart.

### CODE REVIEW

**Comment by hickeyma** [comment]
cc @unguiculus @scottrigby you might be best placed to review this.

**Review by unguiculus — APPROVED** [review]
I think it makes sense to add these.

**Comment by scottrigby** [comment]
I agree with @unguiculus these make sense. However what about syntax… in some places we wrap these keys `{{- with .Values.KEY }}` (`ingress.annotations`, `imagePullSecrets`, `nodeSelector`, `affinity`, `tolerations`), but in other places we don't (`resources`). Should we be consistent about this while we're at it?

**Comment by scottrigby** [comment]
PS slightly related to some other keys in #5110

**Comment by naseemkullah** [comment]
Good point @scottrigby , although wrapping with `{{- with .Values.KEY }}` is more popular, I like the approach used in `resources` because its 2 lines less. 
But I'm open to whichever, please advise.

**Comment by scottrigby** [comment]
I'd suggest use `with` for consistency. Additional benefit is the key won't be part of the rendered template unless a user passes custom values.

**Comment by naseemkullah** [comment]
Sounds good, should this be done for `resources` as well?

**Comment by scottrigby** [comment]
I'm not asking you to increase the scope of this small PR, but if you want to do that I'm a fan of consistency, especially when it's easy.

**Comment by naseemkullah** [comment]
Sure @scottrigby not a problem, but while on the topic of consistency:
```
      {{- with .Values.nodeSelector }}
      nodeSelector:
        {{- toYaml . | nindent 8 }}
      {{- end }}
    {{- with .Values.affinity }}
      affinity:
        {{- toYaml . | nindent 8 }}
    {{- end }}
```
Should the `{{- with` align with the key or 2 spaces before it?

Also is everyone else on board with wrapping any ` toYaml` type thing with `{{- with` ? This will include `resources`,  `securityContext`s as well as the hereby added `annotations`?

@scottrigby just  playing devil's advocate: even if the rendered templates contain empty keys if values not et for the non `{{-with`-wrapped, when posted to the k8s api server the resulting objects will be the same. And going with the non-wrapped approach (as resources is e.g.) will result in way less lines and slightly more readable template imho.

**Comment by naseemkullah** [comment]
bump

**Comment by naseemkullah** [comment]
bump and OK I've wrapped all `toYaml` type stuff with `with` ...

**Review by scottrigby — APPROVED** [review]
Nice lgtm

**Comment by scottrigby** [comment]
This failed test seems unrelated

**Comment by naseemkullah** [comment]
Merged master into this branch in hopes to pass the failed test.

**Comment by naseemkullah** [comment]
Feel free to merge. :)

**Comment by bacongobbler** [comment]
docs?

**Comment by naseemkullah** [comment]
@bacongobbler Could we get these into helm 3 as well?

**Comment by bacongobbler** [comment]
We're only porting changes that were merged into Helm 2 into Helm 3 at this time. Feature additions that weren't merged into Helm 2 will have to wait until Helm 3 is released; we're trying to avoid delaying the release of helm 3 by getting bogged down in features.

**Comment by bridgetkromhout** [comment]
Hi, @naseemkullah - Thanks again for your work on this! To clarify, We're going to be cutting the last feature release for v2 soon, and this PR won't be in v2, so this one should be targeted to the dev v3 branch: https://github.com/helm/helm/tree/dev-v3. You probably also want to keep working with the charts maintainers. Thanks!

**Comment by naseemkullah** [comment]
Thanks for clarifying @bridgetkromhout 
Oh @bacongobbler was it not possible to change base branch  to `dev-v3`?

**Comment by hickeyma** [comment]
@naseemkullah Unfortunately no. You have to restart from the dev-v3 branch.

**Comment by naseemkullah** [comment]
Ok no problem, thanks

**Pull request closed without merging**
