### PR TITLE
Switch from rc to deployment for running tiller

### PR DESCRIPTION
**Pull request by pwittrock**

### CODE REVIEW

**Comment by technosophos** [comment]
I am 💯 for this. I'll do some manual tests and then LGTM.

**Comment by technosophos** [comment]
@pwittrock do you happen to know if this will run on Google Container Engine? I've heard a report that because Deployments are a beta feature, they're not enabled by default.

**Comment by technosophos** [comment]
Verified using deployments on Kubernetes 1.3.4, and @pwittrock assuaged my concerns about GKE, so I'm LGTM'ing. @pwittrock is it okay with you if I merge?

**Comment by pwittrock** [comment]
Yes, merge.  Thanks for the quick turn around.

**Pull request merged**
