### PR TITLE
pkg/chart/chart.go: add unit test for Root

### PR DESCRIPTION
**Pull request by littleroad**
**What this PR does / why we need it**:
add unit test for Root in pkg/chart/chart.go
**Special notes for your reviewer**:

**If applicable**:
* this PR contains unit tests

### CODE REVIEW

**Review by bacongobbler — COMMENTED** [review]
how is this different from TestIsRoot?

**Comment by littleroad** [comment]
> how is this different from TestIsRoot?

```
// Root finds the root chart.
func (ch *Chart) Root() *Chart {
    if ch.IsRoot() { 
        return ch
    }
    return ch.Parent().Root()
}
```
In fact, TestRoot contain TestIsRoot.

**Comment by bacongobbler** [comment]
I don't understand why a new test function was created. Instead of re-implementing the same test fixtures, why not just add

```
is.Equal(&chrt2, chrt1.Root())
is.Equal(&chrt2, chrt2.Root())
```

to the bottom of TestIsRoot?

**Comment by bacongobbler** [comment]
Or at the very least, refactor the `chart1` and `chart2` setup code in a separate function. That way we're not duplicating code.

**Comment by littleroad** [comment]
You're right, I'm sorry I didn't consider this before. since not only TestIsRoot uses chart1 and chart2, I think refactoring the chart1 and chart2 setup code in a separate function is a good idea. thx.

**Comment by technosophos** [comment]
This PR needs to reference an issue number, then it can be merged. I am marking it as "Approved" though it should not be merged until an issue is created and linked here.

**Review by technosophos — APPROVED** [review]
Approved, subject to linking an issue to this PR.

**Review by jdolitsky — APPROVED** [review]

**Comment by littleroad** [comment]
> Approved, subject to linking an issue to this PR.

Excuse me, I just wanted to confirm whether this PR that just adds a unit test also needs to create a related Issue?

**Pull request closed without merging**
