### PR TITLE
 add --col-width to `helm search`

### LINKED ISSUE #3947: port --col-width from `helm list` to `helm search
Looks like the column width in `helm search` is hardcoded at 50 characters: https://github.com/kubernetes/helm/blob/6e413a6a57d631f8d0e54bcec4a0f0f89289cbe4/cmd/helm/search.go#L134

Someone on Slack mentioned this would be useful so they can see the full output.

### PR DESCRIPTION
**Pull request by maratoid**
Fixes #3947

### CODE REVIEW

**Review by mikeln — APPROVED** [review]
LGTM
(but I have no approval rights)

**Review by bacongobbler — CHANGES_REQUESTED** [review]
one minor whitespacing issue, otherwise LGTM

**Comment by bacongobbler** [comment]
Also looks like you need to run `make docs` and commit those changes as well.

**Review by bacongobbler — APPROVED** [review]

**Comment by bacongobbler** [comment]
thanks!

**Comment by mfalkvidd** [comment]
In case someone else comes looking for this feature, the flag is now `--max-col-width`.

Example use to automatically get the correct width:
```bash
helm search --max-col-width $(tput cols)
```

**Comment by tjanson** [comment]
This flag is no longer present in `helm list`. Is that a bug? Did it simply get lost in refactoring?

**Pull request merged**
