### PR TITLE
Allow setting a resolver in the OCI registry client

### LINKED ISSUE #10623: Improve OCI registry client configuration options for devs
Congrats on the 3.8 release! Happy to see OCI-related logic was extracted out of the experimental directory, meaning 3rd party developers can just import Helm and use it.

Precisely, in my team, we'd wanted to use the Helm OCI registry client to interact with OCI registries instead of dealing directly with ORAS. However, I find the current support (as of `v3.8.0`) quite limited.
More specifically:

- We'd need to be able to customize the resolver passed through the oras Registry, as we are adding a custom header and a preconfigured httpclient with the proper auth (not only _basic auth_ but also _bearer token_)

Currently, the only `ClientOption` are  `ClientOptDebug`, `ClientOptWriter` and `ClientOptCredentialsFile`, so adding a new one allowing customizing the resolver would make the trick.

Additionally, I'd like to have more `LoginOptions` as well. Currenlt only `LoginOptBasicAuth` and `LoginOptInsecure` are available.
As stated before, we'd like to customize other things like `userAgent` or `authorization` headers (or any other header) with arbitrary values.

Relevant file: https://github.com/helm/helm/blob/v3.8.0/pkg/registry/client.go

I don't know what's your roadmap on improving this kind of stuff, but willing to contribute if you want. 

Output of `helm version`: `version.BuildInfo{Version:"v3.8.0", GitCommit:"d14138609b01886f544b2025f5000351c9eb092e", GitTreeState:"clean", GoVersion:"go1.17.6"}`

### PR DESCRIPTION
**Pull request by antgamdia**
**What this PR does / why we need it**:

As OCI was moved out of `/experimental`, third-party developers are using Helm 3.8 as their entrypoint to deal with OCI repositories (instead of dealing with ORAS directly). However, there is still some margin of improvement on the customization capabilities offered to those developers.

This PR is simply to add a way to enable devs to set up a custom containerd `resolver` for their OCI registry client.
Besides, it also exports a couple of fields, so that it becomes easier for devs to mock the `PullResult` struct in their unit tests.

closes #10623 (*)

(*) In that issue I mentioned some ways to improve the customization of the registry client, but, rather than adding a myriad of setters or ClientOpts for each aspect (custom headers, custom LoginOpts, etc.) setting a custom resolver makes the trick for us, at least.

**Special notes for your reviewer**:

After having reviewed the test suite for the client registry, I haven't found any existing code merely testing the ClientOpts, so I just added a `ClientOptResolver(nil)` to ensure the test coverage. Although the logic is trivial, please let me know if any other testing approach is required on your side.

I can confirm this change works for us: https://github.com/kubeapps/kubeapps/pull/4216

**If applicable**:
- [ ] this PR contains documentation
- [ ] this PR contains unit tests
- [x] this PR has been tested for backwards compatibility

### CODE REVIEW

**Comment by antgamdia** [comment]
Hi! Just for internal planning purposes, is there any chance/expectations for this PR to be included in the 3.8.1 release? (which, AFAIK, is to be released on March 09)

**Comment by antgamdia** [comment]
As per https://github.com/helm/helm/pull/10408#issuecomment-1051300691, I've added my change on top of this PR https://github.com/helm/helm/pull/10408.

Currently, it is just pulling their changes and just adding the `ClientOptResolver` I initially proposed, so if that PR got merged, then this one won't conflict.

However, I've also been trying to replace the `WithResolver` with the `ClientOptResolver` as I assumed it was the original intention for rebasing the PR. Unfortunately is not that easy, I think:

The registry client is being created at the top-level [`helm/root` file](https://github.com/helm/helm/blob/main/cmd/helm/root.go#L152) and, at that point, we don't have the arguments for each subcommand (like `push` , for instance). So, I can think of two options:

- A) Passing the options/settings used to create the `registryClient` back to every action, so each one can create its own `registryClient`. This way we can use the `ClientOptResolver` or similar.
- B) Allow setting the `registryClient`'s `resolver` so that each action can tune it up according to the flags in each run.

I think the `WithRegistry` approach is more versatile than creating a whole `registryClient` being created in each `NewClient(.... `ClientOptResolver(....))`

For this reason, I've been working on top of https://github.com/helm/helm/pull/10408 to allow more future customization in the future (like custom headers): `WithResolver(options ...WithResolverOption)`
This way, the actions can just modify the resolver by simply doing:

```go
registryClient.WithResolver(
  registry.WithResolverOptInsecureSkipTLSVerify(in.ChartPathOptions.InsecureSkipTLSverify),
  registry.WithResolverOptPlainHTTP(in.ChartPathOptions.PlainHTTP),
)
```

Then, it is just a matter of setting the resolver on each action's constructor, so that it does no longer uses the one created in the root, but the accordingly modified one.

However, as it should be properly unit-tested and, unfortunately, I don't have enough bandwidth this week, I've just thrown what I currently have in my fork's branch.
See commit https://github.com/antgamdia/helm/commit/eabfd0c68658684eba60a5d42333ca0051c9f79c and https://github.com/antgamdia/helm/commit/ec01638cb37789a12420ed5462f83ceb51de0430

PS: quick code-related question: why does almost every action has a `ChartPathOptions` (which already includes the tls-insecure  and plainHTTP flags and its own `registryClient`) but the `push` action does not?


So, @jdolitsky, what do you recommend?  Perhaps merging https://github.com/helm/helm/pull/10408 and https://github.com/helm/helm/pull/10638 (as is), to be included in March 9th release and next iterate to improve it with some of the options I mentioned?
Or perhaps you were suggesting another alternative I didn't get?

By the way, @pytimer, please feel free to take whatever you want from my [fork's branch](https://github.com/antgamdia/helm/tree/10623-allow-setting-oci-resolver-wip). Next week I don't have the bandwidth for it, and I don't want to be a blocker.

Thanks!

**Comment by pytimer** [comment]
> By the way, @pytimer, please feel free to take whatever you want from my [fork's branch](https://github.com/antgamdia/helm/tree/10623-allow-setting-oci-resolver-wip). Next week I don't have the bandwidth for it, and I don't want to be a blocker.

Thanks, but i'm sorry, i don't have the bandwidth this week because of my family, so maybe cannot done before March 9th release.  I can start next week if you don't have time. @antgamdia

**Comment by fovgrubby128** [comment]
Hi team, our team also waiting for this CL to support `registry.ClientOptResolver(&registry.Resolver{Resolver: resolver})`. thanks for the effort!

**Comment by pytimer** [comment]
Based on @antgamdia code, i change some code in the commit https://github.com/pytimer/helm/commit/145533ce71d18487d3b37df481f03cce95097596. But like @antgamdia said, i think `ClientOptResolver` is better for new registry client, while `WithResolver` is more suitable for modifying based on the exist client , what do you think about this @jdolitsky?

I write [the code](https://github.com/pytimer/helm/commit/145533ce71d18487d3b37df481f03cce95097596#diff-5d4849bad97d2e075ce5d0ae5af3e93dbfde235ce1345fa96148279cf706af2fR703) that how to use `ClientOptResolver` and `WithResolver` in above commit, please point out it if something wrong.

**Comment by antgamdia** [comment]
After a few months without activity on https://github.com/helm/helm/pull/10408, I'm closing this PR in favor of the initially proposed approach: https://github.com/helm/helm/pull/11129.

Please, let's move forward on this one, as it is just setting a field and exporting others. It is not related whatsoever with https or other params, as already described.

**Pull request closed without merging**
