### PR TITLE
feat(testing): enable hook parallelism

### LINKED ISSUE #7763: Add a flag to execute chart hooks in parallel
Currently, all chart hooks are executed serially. For some use cases (such as running `helm test` in CI environments), this is just too slow. In Helm v2, the `helm test` command supports the `--parallel` and `--max` flags which enable and limit parallel execution of tests, respectively. This functionality wasn't ported to Helm v3 due to test infrastructure changes.

Adding a `--parallelism` flag to Helm v3 that allows for hooks to be executed in parallel (while still respecting `"helm.sh/hook-weight"` annotations) would be really useful.

### PR DESCRIPTION
**Pull request by abaehremc**
Enables parallel execution of chart hooks. --hook-parallelism defaults to 1 to make this an opt-in feature.
    
Batching is used to comply with "helm.sh/hook-weight" annotations. A semaphore is used to limit parallelism
to the user-provided value. Some additional synchronization was necessary to run cfg.recordRelease() in a
thread-safe manner.
    
Based off of https://github.com/helm/helm/pull/7792 by akhilles.
    
Closes #7763.
    
Signed-off-by: Andrew Baehre <abaehre@morningconsult.com>

**What this PR does / why we need it**:
Adds hook parallelism with a default of 1 as a flag for applicable commands.

**Special notes for your reviewer**:
This was based on https://github.com/helm/helm/pull/7792. 
Tests were added, but if you'd like more robust tests please let me know.

**If applicable**:
- [ ] this PR contains documentation
- [x] this PR contains unit tests
- [ ] this PR has been tested for backwards compatibility

### CODE REVIEW

**Comment by mattfarina** [comment]
@abaehreMC Thank you for the pull request. This looks interesting and I like that you took backwards compatibility into account right from the start.

We recently added a [Helm Improvement Proposal process](https://github.com/helm/community/tree/master/hips). This is something that is enough of a change it should go through that. This is something we need to consider from various angles.

**Comment by abaehreMC** [comment]
> @abaehreMC Thank you for the pull request. This looks interesting and I like that you took backwards compatibility into account right from the start.
> 
> We recently added a [Helm Improvement Proposal process](https://github.com/helm/community/tree/master/hips). This is something that is enough of a change it should go through that. This is something we need to consider from various angles.

@mattfarina I would love to take credit, but the actual code is @akhilles. I'm happy to take a stab at putting something in through the Helm Improvement Proposal process, I'll see if I can't put something together in the next few days.

**Comment by abaehreMC** [comment]
For visibility - https://github.com/helm/community/pull/165.

Sorry for taking so long.

**Comment by mark007** [comment]
@abaehreMC @akhilles I'm really looking forward to this commit, thank you. This will make a HUGE improvement to many large charts I work on, which have many tens of hooks, most of which can be parallelized. This will possibly save double digit minutes in install/upgrade times of these huge charts.

**Comment by margori** [comment]
I really want and need parallel execution of hooks. It would save me several minutes in automatic deploys

**Comment by pabbott-starbucks** [comment]
Is this ticket still active? Our team would love this feature as well!

**Comment by abaehreMC** [comment]
> Is this ticket still active? Our team would love this feature as well!

This is currently going through the Helm Improvement Process (HIP) over at https://github.com/helm/community/pull/165!

Once (read "if") that gets approved this PR can get updated based on the agreed upon spec.

**Comment by dazuimao1990** [comment]
This feature really appeals to me and I'm looking forward to it coming soon. 😃

**Comment by carlosrmendes** [comment]
any updates regarding this feature?

**Pull request closed without merging**
