### PR TITLE
Add a flag var to check git is installed or not

### LINKED ISSUE #11492: plugin install command needs git
It looks that `helm plugin install` command needs git to be installed.
When I execute command in machine where git is not installed, i found error message like link below
https://github.com/snapcrafters/helm/issues/15

because of this issue, `snapcratfers` developers updated their required packages configuration.
https://github.com/snapcrafters/helm/pull/51/files#diff-56759910381a014fecfd7556dd72ddd68c747d922a5b7df2044b9ce7c552f5f5R27

So, how about changing `get-helm-3` script like below to notify users? 
here is an example I think.
https://github.com/Wonong/helm/commit/9e21460515d836cb7169acb3e7615800778fd7e1

### PR DESCRIPTION
**Pull request by Wonong**
**What this PR does / why we need it**:

This changes update `scripts/get-helm-3` to notify users to pre-install `git` CLI before installing HELM

**Special notes for your reviewer**:

close #11492 

**If applicable**:
- [ ] this PR contains documentation
- [ ] this PR contains unit tests
- [ ] this PR has been tested for backwards compatibility

### CODE REVIEW

**Comment by yxxhero** [comment]
@Wonong git is a common tool. check git is valuable.

**Review by phil9909 — CHANGES_REQUESTED** [review]
I think this is of questionable value.

It is clear why the installation fails if `wget` and `curl` are missing, they are required, but `git`?
This is only needed when installing plugins (not even for all plugins, only for "vcs" plugins) so why prevent the installation?

I'd suggest to either turn this into a warning, e.g.:

```bash
  if [ "${HAS_GIT}" != "true" ]; then
    echo "[WARNING] Could not find git. It is required for plugin installation."
  fi
```

or at least give users a way to ignore the error, e.g.:

```bash
: ${VERIFY_GIT:="true"}

# ...

  if [ "${VERIFY_GIT}" == "true" ] && [ "${HAS_GIT}" != "true" ]; then
    echo "Git is required for plugin install. Set VERIFY_GIT=false to ignore this"
    exit 1
  fi
```

**Comment by Wonong** [comment]
@phil9909 thank your comment :)
I think your first suggestion is good. It is enough to print warning log.
I will change codes to apply your opinion.

**Review by phil9909 — APPROVED** [review]

**Review by jadahbytes — APPROVED** [review]
Can confirm that the script prints the warning as expected.
(P.S. this is my 1st PR review T_T)

**Review by scottrigby — APPROVED** [review]
Straightforward user experience improvement 👍 Thanks @Wonong 
Thanks @phil9909 @yxxhero and @jadahbytes for reviews 🙌 

PS @jadahbytes welcome!

**Review by hickeyma — APPROVED** [review]

**Pull request merged**
