### PR TITLE
kube client library bump to v0.21.3

### PR DESCRIPTION
**Pull request by sbose78**
Signed-off-by: Shoubhik Bose <shbose@redhat.com>

**What this PR does / why we need it**:

**Special notes for your reviewer**:

**If applicable**:
- [ ] this PR contains documentation
- [ ] this PR contains unit tests
- [ ] this PR has been tested for backwards compatibility

### CODE REVIEW

**Review by cndoit18 — COMMENTED** [review]
Maybe we can get @dependabot to do this?

**Review by mattfarina — APPROVED** [review]

**Comment by mattfarina** [comment]
@cndoit18 If I understand it right, dependabot will update a single dependency. We need to update these as a group. When dependabot has tried to update them as individuals it has been a problem. It would be great if dependabot could update them as a group.

**Review by cndoit18 — COMMENTED** [review]
you may not have implemented `go mod tidy`. my local run is not quite the same as this

**Review by bacongobbler — APPROVED** [review]
LGTM after a rebase. v0.21.4 is the latest release if you want to bump this up one more patch release.

**Comment by sbose78** [comment]
Doing right away..

**Pull request merged**
