### PR TITLE
relative home path fixes

### PR DESCRIPTION
**Pull request by Stelminator**
should be rebased well enough and resolve:

* https://github.com/kubernetes/helm/pull/2862
* https://github.com/kubernetes/helm/issues/2975
* https://github.com/kubernetes/helm/issues/2839

### CODE REVIEW

**Comment by bacongobbler** [comment]
Hey @Stelminator! Thank you very much for submitting this PR. We always appreciate Windows fixes ;)

1. I think it might be easier to review this PR if it were split into two: one to address #2975 (adding relative path support to `helm --home`), and one to address #2839 (creating repositories.yaml with relative paths via `helm init`). Do you think that would be feasible?
2. Could you take another look at writing some more unit tests, if possible?

Thanks so much for your patience.

**Comment by Stelminator** [comment]
@bacongobbler yup, I've meant to get around to splitting it up, just haven't had the time to dedicate to it; I'll try to fit it in soon.  Thanks for specifying where to split!

**Comment by Stelminator** [comment]
@bacongobbler I've come to the realization that #2975 may be incorrectly defined.  Relative paths actually work, just not for `init` or `add`.

`add` is actually trivial, it's all of:
```diff
--- a/cmd/helm/repo_add.go
+++ b/cmd/helm/repo_add.go
@@ -86,7 +86,7 @@ func addRepository(name, url string, home helmpath.Home, certFile, keyFile, caFi
                return fmt.Errorf("repository name (%s) already exists, please specify a different name", name)
        }

-       cif := home.CacheIndex(name)
+       cif := home.RelativeIndex(name)
        c := repo.Entry{
                Name:     name,
                Cache:    cif,
diff --git a/pkg/helm/helmpath/helmhome.go b/pkg/helm/helmpath/helmhome.go
index b5ec4909..3c35c3b6 100644
--- a/pkg/helm/helmpath/helmhome.go
+++ b/pkg/helm/helmpath/helmhome.go
@@ -61,6 +61,12 @@ func (h Home) CacheIndex(name string) string {
        return h.Path("repository", "cache", target)
 }

+// RelativeIndex returns the relative path to an index for the given named repository.
+func (h Home) RelativeIndex(name string) string {
+       target := fmt.Sprintf("%s-index.yaml", name)
+       return filepath.Join(target)
+}
+
 // Starters returns the path to the Helm starter packs.
 func (h Home) Starters() string {
        return h.Path("starters")
```

`init` is actually two different pieces.  One for `initStableRepo` and one for `initLocalRepo`.  stable is almost as trivial as add, but local involves a symlink, so needs a bit more information passed around to get the correct results.

So, as I see it, there are 4 pieces here:

1. Some refactoring to get `home` passed around where it needs to be for everything else.  This makes no functional change on its own.
2. Fixing the path written into `repositories.yaml` on `repo add`.  This causes repos `add`ed to become usable.
3. Fixing the path written into `repositories.yaml` for the `stable` repo on `init`.  Very similar to 2).
4. Fixing the path written into `repositories.yaml` for the `local` repo on `init` AND putting a (sym)link in the right place.  The first part is again similar to 2) and 3), but the latter part requires computing the relative path of the symlink to the target.

In reference to 4), I think I may have neglected to correctly figure part of the hardlink for windows, but, assuming the right code for that can be made, how should I split this up for it to be accepted?

**Comment by Stelminator** [comment]
Sidenote: Please reconsider defining this as a bug fix and not adding a feature.  The feature (home being a relative path) has existed, as I understand it, since before 2.2, it just doesn't work properly.

**Comment by Stelminator** [comment]
part 1: https://github.com/kubernetes/helm/pull/3595

**Comment by Stelminator** [comment]
part 2: https://github.com/kubernetes/helm/pull/3596

**Comment by thomastaylor312** [comment]
@Stelminator so we will be releasing 2.9 fairly soon. Could this wait until then? I'm in the process of putting these in the right milestone

**Comment by Stelminator** [comment]
part 3: https://github.com/kubernetes/helm/pull/3647
part 4: https://github.com/kubernetes/helm/pull/3648

I've isolated the commits for these, but they depend on part 2: #3596

**Comment by buddyledungarees** [comment]
Any update on merging this in? This bug breaks embedding helm client configs within a project, for example.

**Comment by bacongobbler** [comment]
Closing this PR due to inactivity. Helm 3 now follows the XDG base directory standard so the issue this PR is trying to address for Helm 2 is no longer relevant in Helm 2. As per [the announcement on the mailing list](https://lists.cncf.io/g/cncf-helm/topic/last_v2_feature_release/34301238), Helm 2.15.0 is the last release where we will be merging new features for Helm 2. Thanks!

**Pull request closed without merging**
