### PR TITLE
Added HPA to sort order.

### PR DESCRIPTION
**Pull request by Constantin07**
**What this PR does / why we need it**:

Makes sure HPA resource is created after ReplicationController, ReplicaSet or Deployment as it is referencing one of the above resources.

For uninstall use the reverse order.

### CODE REVIEW

**Review by hickeyma — CHANGES_REQUESTED** [review]
@Constantin07 Thanks for pushing the changes. A few things to look at:
- Do you mind adding test to https://github.com/helm/helm/blob/master/pkg/tiller/kind_sorter_test.go 
- Can you also sign the DCO: https://helm.sh/blog/helm-dco/index.html ?

**Comment by bacongobbler** [comment]
This might be useful to port over to Helm 3 as well. Would you mind PR'ing this against the `dev-v3` branch once this has been merged?

**Comment by Constantin07** [comment]
@hickeyma test updated and DCO signed.

**Review by hickeyma — APPROVED** [review]
LGTM, thanks @Constantin07.  Can you squash the changes and I will then merge?

**Comment by Constantin07** [comment]
@hickeyma done.

**Comment by Constantin07** [comment]
ran the tests against the branch locally, all seems OK.
```
...
PASS
ok  	k8s.io/helm/pkg/urlutil	(cached)
=== RUN   TestIsCompatible
--- PASS: TestIsCompatible (0.00s)
=== RUN   TestIsCompatibleRange
--- PASS: TestIsCompatibleRange (0.00s)
=== RUN   TestGetVersionProto
--- PASS: TestGetVersionProto (0.00s)
PASS
ok  	k8s.io/helm/pkg/version	(cached)
@ ~/go/src/k8s.io/helm (add_hpa_to_sorting_order)$
```

**Comment by hickeyma** [comment]
@Constantin07 This is running successfully for me locally as well. At last building, issue seemed to be environmental.

**Comment by Constantin07** [comment]
Thanks @hickeyma

**Pull request merged**
