### PR TITLE
Bugfix: panic when chart contains requirements.lock

### PR DESCRIPTION
**Pull request by zheng1**
**What this PR does / why we need it**:

**Special notes for your reviewer**:

**If applicable**:
- [ ] this PR contains documentation
- [x] this PR contains unit tests
- [x] this PR has been tested for backwards compatibility

### CODE REVIEW

**Comment by bacongobbler** [comment]
Hi @zheng1. Can you please write a unit test that covers this case. Thanks.

**Comment by zheng1** [comment]
> Hi @zheng1. Can you please write a unit test that covers this case. Thanks.

Hi, @bacongobbler, I had added a test for this case, please take a look again.

**Review by bacongobbler — APPROVED** [review]

**Comment by bacongobbler** [comment]
needs a second maintainer to review before merging

**Review by mattfarina — APPROVED** [review]
lgtm

**Comment by mattfarina** [comment]
For some reason, the CircleCI hook failed with an HTTP response status code of 400 (Bad Request). This is why we don't have the CI info for it. I think it's for this entire PR rather than any particular commits on it.

**Review by mattfarina — APPROVED** [review]

**Comment by zheng1** [comment]
Hi, @mattfarina, what should I do next to get this PR merged?

**Comment by bridgetkromhout** [comment]
> For some reason, the CircleCI hook failed with an HTTP response status code of 400 (Bad Request). This is why we don't have the CI info for it. I think it's for this entire PR rather than any particular commits on it.

Hi, @mattfarina - Every once in a while I see that kind of timeout on various projects, and when I push a new change to that PR, it re-runs successfully. I suggest that @zheng1 may want to try that, as this may be an intermittent failure with CircleCI?

**Comment by zheng1** [comment]
It still doesn't look like circleCI has been re-run, I'll try to close and reopen the issue.

**Comment by zheng1** [comment]
Done, I think I've found a way to re-run circleCI.

**Comment by gy-lehel** [comment]
There is a logical error in this patch, as it assumes API version to be V1. The crash is caused by the fact, that during the unpacking of the tgz the requirements.lock and yaml files are unpacked before the chart metadata is taken from Chart.yaml. Since the original code expresses a difference in the processing of for API versions higher than V1 this commit will introduce an inconsistency in the accepted file list, based purely on the order of file processing!

**Comment by mattfarina** [comment]
@gy-lehel Thanks for pointing out this issue. If there is no `Chart.yaml` file in the chart a panic would still occur if this is not merged. I have looked at your PR and put it into the 3.4.1 milestone, too. The ordering issue is an issue, too.

**Comment by mattfarina** [comment]
@zheng1 Thanks for fixing the tests.

**Pull request merged**
