### PR TITLE
WIP: Migrate from golangci-lint to revive

### PR DESCRIPTION
**Pull request by jdolitsky**
Upon running `make test-style`, `golangci-lint` recommends deprecating itself for [revive](https://github.com/mgechev/revive):
```
Run make test-style
GO111MODULE=on golangci-lint run
level=warning msg="[runner] The linter 'golint' is deprecated (since v1.41.0) due to: The repository of the linter has been archived by the owner.  Replaced by revive."
```

### CODE REVIEW

**Comment by bacongobbler** [comment]
> GO111MODULE=on revive ./...
> bash: line 1: revive: command not found

Once that's resolved looks like this is good to go

**Comment by kke** [comment]
golangci-lint itself is not deprecated nor archived, but golint, which is used as one of the sublinters in golangci-lint is. They have replaced their golint dependency to revive, which is a drop-in replacement.

I would think the only necessary action in helm is to bump the used golangci-lint version.

The deprecation notices are discussed here: https://github.com/golangci/golangci-lint/issues/1987

**Comment by kke** [comment]
Also, there's already #10206

**Comment by jdolitsky** [comment]
@kke - thank you for clarifying. Closing this in favor of #10206

**Pull request closed without merging**
