### PR TITLE
Add support of accepting a specific variable for helm env

### LINKED ISSUE #8635: helm env accept a specific variable to return just that value
The `helm env` command returns a list of the Helm environment variables and their values. It would be useful if you could pass in a specific environment variable and get its value.

### PR DESCRIPTION
**Pull request by rudeigerc**
Signed-off-by: Yuchen Cheng <rudeigerc@gmail.com>

**What this PR does / why we need it**:

Closes #8635 

Add support of accepting a specific variable for `helm env`.

```
$ bin/helm env HELM_BIN
bin/helm
```

**Special notes for your reviewer**:

**If applicable**:
- [ ] this PR contains documentation
- [x] this PR contains unit tests
- [x] this PR has been tested for backwards compatibility

### CODE REVIEW

**Review by mattfarina — CHANGES_REQUESTED** [review]
Thanks for putting this pull request together. This is great.

There is one small improvement that could be made around completion.

**Review by marckhouzam — APPROVED** [review]
LGTM
I'll let @mattfarina give the final approval.

Thanks for the contribution!

**Review by mattfarina — APPROVED** [review]
This looks great. I tested and it works.

**Comment by rudeigerc** [comment]
Thank you very much! 😄

**Pull request merged**
