### PR TITLE
Helm 3-alpha1: fix(reference): Set `latest` tag properly and do some cleanups

### LINKED ISSUE #5752: Helm 3-alpha1: pushing chart without tag specified results in untagged chart instead of latest
Output of `helm version`:
`version.BuildInfo{Version:"v3.0.0-alpha.1", GitCommit:"b9a54967f838723fe241172a6b94d18caf8bcdca", GitTreeState:"clean"}`

Output of `kubectl version`:
`Client Version: version.Info{Major:"1", Minor:"14", GitVersion:"v1.14.1", GitCommit:"b7394102d6ef778017f2ca4046abbaa23b88c290", GitTreeState:"clean", BuildDate:"2019-04-08T17:11:31Z", GoVersion:"go1.12.1", Compiler:"gc", Platform:"windows/amd64"}`

Cloud Provider/Platform (AKS, GKE, Minikube etc.): 
Azure Container Registry (but should be reproducable on any OCI compatible registry)

Repro:
- `helm create test`
- `helm chart save test myreg.azurecr.io/test` (replace registry url)
- `helm chart push myreg.azurecr.io/test`

Output `helm chart push` command:
```
Using default tag: latest
The push refers to repository [myreg.azurecr.io/test]
Name: test
Version: 0.1.0
Meta: sha256:xxx
Content: sha256:xxx
latest: pushed to remote (2 layers, 2.3 KiB total)
```

Expected: 
The output indicates the the default tag (`latest`) is used, so it's expected that the remote registry now contains a `test` repository with a manifest tagged `latest`.

Actual:
The remote registry now contains a `test` repository with a single manifest, but its untagged (or at least not tagged latest).

### PR DESCRIPTION
**Pull request by muehlburger**
Signed-off-by: Herbert Mühlburger <mail@muehlburger.at>

**What this PR does / why we need it**:

- Fixes #5752.
- Adds a test and does some cleanups.

### CODE REVIEW

**Comment by bacongobbler** [comment]
based on some of the feedback provided in #5752, it doesn't look like this is the approach we want to take. @muehlburger are you working with @jdolitsky on the right path forward for this PR or should we close this?

**Comment by muehlburger** [comment]
I'd be happy to work on it with @jdolitsky.

**Review by mattfarina — APPROVED** [review]

**Review by bacongobbler — CHANGES_REQUESTED** [review]
Marking as DO NOT MERGE as there are some open questions about the design from a few core maintainers

**Comment by jdolitsky** [comment]
This appears to fix the problem as it exists today, but as mentioned above, we are leaning towards enforcing semver on tags. Let's continue convo in https://github.com/helm/helm/issues/5752

**Comment by bacongobbler** [comment]
closing as per the ongoing discussion in #5752. Let's hold off for the *right* fix rather than the *right now*, especially since the fix proposed in this PR isn't the design we want going forward. Thanks!

**Pull request closed without merging**
