### PR TITLE
feat(helm): Add --col-width to helm list and helm history

### LINKED ISSUE #2828: (cmd/helm): No way of obtaining the chart version for a release when chart name + version > 60 chars
This is somehow related to #1914 and #1915.

helm version: 2.6.0

The MaxColumn is set to 60 on `helm list` and `helm history`.

Example:
```
helm list
NAME                            	REVISION	UPDATED                 	STATUS  	CHART                                                       	NAMESPACE
methode-article-image-set-mapper	5       	Fri Aug 18 15:37:00 2017	DEPLOYED	methode-article-image-set-mapper-1.3.0-k28s-helm-integrat...	default
```

Currently there is no way to obtain the version of the chart used for the release.

**Proposed solutions**:
1. allow setting the column max length from the command line ``` helm list --max-col-length=6000```
2. introduce another flag to show full column values ``` helm list --full-output ```

### PR DESCRIPTION
**Pull request by rocky-nupt**
The default maximum length of the output table is 60 chars. When the length is greater than 60, the content will be omitted. This patch adds -f and --full-output to helm list and helm history which can display full information of releases on the screen.

Closes #2828

### CODE REVIEW

**Comment by jascott1** [comment]
@rocky-nupt What do you think about changing to `--output wide` as recently suggested in the original issue? That matches k8s and allows us to expand to other formats later.

**Comment by jascott1** [comment]
Case in point, `-o` would allow us to eventually handle `json` as requested here:
https://github.com/kubernetes/helm/issues/1534

**Comment by bacongobbler** [comment]
I'm also personally in favour of --output rather than --full-output.

**Comment by rocky-nupt** [comment]
I agree with you. I have followed your suggestion. Thanks! @jascott1

**Comment by jascott1** [comment]
@rocky-nupt Looking great! One thing, can you modify the usage text to list the 'wide' option more like kubectl? Something like 
```
specifies the output format: short|wide
```
Just a nit but from what I can tell kubectl doesn't have a 'short', its more of a default mode with optional `--output` to change it. If we don't do that is there a better term than `short` that would fit better with `wide`? (Id like to keep `wide` since it follows kubectl)

**Comment by rocky-nupt** [comment]
@jascott1 Yes, I like "wide" too which follows kubectl. I have changed it.

**Review by bacongobbler — CHANGES_REQUESTED** [review]
I feel like we should be erroring out on invalid format types. For example one may assume that if `--output=json` works, it should output as JSON. Can we make that change here to perform some form of argument sanity checking?

**Comment by sbuliarca** [comment]
I managed to test this, and it works as expected. Thank you for the changes.
I agree that a sanity check on the --output argument value would be nice.

**Comment by jascott1** [comment]
Hi @rocky-nupt 

Thanks for the PR. Do you think you will be able to resolve conflicts and add the check @bacongobbler asked for? 

Thanks,
Justin

**Comment by rocky-nupt** [comment]
How about changing 'output' to 'col-width' here? I think 'output' can be similar to it in kubectl while here only needs to change the column width. We can create a new PR about 'output'. @jascott1 @bacongobbler

**Review by bacongobbler — APPROVED** [review]

**Pull request merged**
