### PR TITLE
feat(cli): move 'helm dm' to 'helm server'

### LINKED ISSUE #245: Client: DM commands
The `helm dm...` commands are:

- `helm dm install`: Install DM on a cluster
- `helm dm uninstall`: Uninstall DM on a cluster
- `helm dm status`: Show status of a DM cluster (healthz?)
- `helm dm target`: Show the connection details of the DM cluster we're currently pointing to

The `helm dm install` command is used when `helm init` has already been run once, but we are pointing to another cluster and want to install there.

### PR DESCRIPTION
**Pull request by technosophos**
Closes #245

### CODE REVIEW

**Comment by michelleN** [comment]
Looks good!

**Comment by michelleN** [comment]
Btw @technosophos, I got an this error message `[ERROR] exit status 1` when I tried to install.. probably because I don't have a running cluster. We could probably make that error more transparent.

**Comment by technosophos** [comment]
Trying to fix this before merging the PR

**Comment by technosophos** [comment]
@michelleN Just improved the error messages to capture STDERR when kubectl fails.

**Comment by michelleN** [comment]
Sweet! lgtm

**Pull request merged**
