### PR TITLE
Add support for arm64

### PR DESCRIPTION
**Pull request by lubinsz**
Signed-off-by: Bin Lu <bin.lu@arm.com>

### CODE REVIEW

**Comment by alicefr** [comment]
It actually allows the building for various architectures not only `arm64`. Are you sure that you want to allow to set the architecture with the go variables? I opened a similar (PR)[https://github.com/kubernetes/helm/pull/4200], but it is actually wrong (my second commit) and you may have the same issue. If you set the GOARCH=arm64 it correctly cross-compiles the binaries but it copies into an x86_64 image. Currently the only way to obtain the helm images for other architecture is to build the docker image on the native architecture. My PR has the same problem. Therefore, it is risky to let the user set the GOARCH enviromental variable. It is probably more safe to evaluate the architecture with `shell uname -m`

**Comment by alicefr** [comment]
@lubinsz Do you plan to submit the PR? I'm also interested in the modification for s390x. Otherwise, I'll modify my PR, but it'd pretty similar to yours

**Comment by bacongobbler** [comment]
@alicefr if you feel like submitting a new PR that addresses the limitation, I'd be really happy to see it!

In case you missed it, there's another PR trying to get ppc64le support for tiller in #1930 that might be relevant to take a look at. Basically that PR flips a conditional flag to use an alternative Dockerfile. That might be a workable solution if we can make it work for supported architecture types (and having amd64 as the default, of course 😃).

**Comment by alicefr** [comment]
hi @bacongobbler. I'm interested for `s390x`, so I guess we have (almost) all the architectures here ;D. I investigated a little bit and it might be possible to find a more generic solution than having a Dockerfile for each architecture. It might be useful to open a new issue.

The main issue to solve are:
1- The parent image need to be right one for the architecture 
2- You need to be able to execute binaries for other architectures on `x86` with the command RUN. For example as in https://github.com/helm/helm/blob/master/rootfs/Dockerfile
```dockerfile

FROM alpine:3.7

RUN apk update && apk add ca-certificates socat && rm -rf /var/cache/apk/*
```
The possible solutions are:
To solve point 1, the command `docker build` has a new flag `--platform` (still experimental) that pick the right parent image. Of course the parent image needs to be a mutli-arch image as `alpine:3.7`
To solve point 2, you could use `binfmt_misc` in order to be able to run binaries for other architectures. You can find [here](https://www.kernel.org/doc/html/latest/admin-guide/binfmt-misc.html) more information and [here](https://ownyourbits.com/2018/06/27/running-and-building-arm-docker-containers-in-x86/) an example.

However, this implies that you need to modify your CI/CD. If your build system has a kernel v4.8-rc1 or newer, it is a lot of easier because it is not anymore needed to copy the qemu binary inside the container. You can simply use the `F` option and the building process is much more cleaner. I got a very nice answer [here](https://github.com/moby/buildkit/issues/550) if you need.

I would be glad to participate to the discussion!

**Comment by bacongobbler** [comment]
closing this PR as stale/won't get merged as-is based on the discussion in this thread. Please feel free to re-open if things change!

**Pull request closed without merging**
