### PR TITLE
WIP: feat(plugin): refactor `helm plugin`

### PR DESCRIPTION
**Pull request by bacongobbler**
This is very exploratory work. The gist of it is:

- `helm plugin install` and related subcommmands have been removed entirely from Helm
- plugins are loaded from $PATH, git (and `kubectl`) style
- `helm init -p` was removed since the plugin installer was removed
- helm commands can override existing `helm` commands. For example, loading a plugin called `helm install` will replace `helm install`.

Please have a look at the docs. I'd love to hear any feedback on this proposal.

Next steps is to write a `helm plugin` plugin to restore the original functionality of `helm plugin install`.

Signed-off-by: Matthew Fisher <matt.fisher@microsoft.com>

### CODE REVIEW

**Comment by bacongobbler** [comment]
related: https://github.com/helm/helm/pull/4798

**Comment by rimusz** [comment]
@bacongobbler removal of `helm plugin ...` for helm v3 only or it can also be for helm v2?

**Comment by bacongobbler** [comment]
This is for Helm 3. Note that this is targeted against the `dev-v3` branch and has the v3 label attached.

**Comment by bacongobbler** [comment]
We're not making any breaking changes to Helm 2, so I won't be back-porting this to Helm 2.

**Comment by rimusz** [comment]
wouldn't make a sense to ton include in PRs titles e.g. `v3`?

**Comment by bacongobbler** [comment]
labeling can be automated. Re-naming titles cannot.

**Comment by bacongobbler** [comment]
closing for now, will revisit later. A lot of the assumptions made in this PR were experimental and in practice has weird implications.

**Pull request closed without merging**
