### PR TITLE
Add purge option for completely remove a release from tiller

### PR DESCRIPTION
**Pull request by ebraminio**
~~The patch is not in final stage but I wanted to know if the general concept looks fine to the maintainers.~~ (now nearly it is) The idea here is going further on "helm delete" and not just change state of a release to DELETED but actually remove it from the store so we wouldn't need to use newly introduced "--replaced" option therefore I've added a new option on delete, "--purge" to achieve that. My concern is however that you did this intentionally for some reasons so I am waiting for your decision other than code reviews. Thank you.

---

This change is [Reviewable](https://reviewable.kubernetes.io/reviews/kubernetes/helm/1067)

### CODE REVIEW

**Comment by technosophos** [comment]
I'd like to discuss the idea in the Helm Pub Dev meeting on Aug 18.

In general, we've avoided removing things from storage because it removes the history, which makes various forensics impossible (e.g. historical reporting). Some orgs need to be able to run reports for regulatory compliance and other audits.

However, this feature has been requested several times. So clearly some of the community would rather have a clean database than historical reports. And we should honor that as long as it doesn't break anything or undermine the validity of data for others.

**Comment by technosophos** [comment]
Also, this will have implications for the `helm rollback` feature in #1004.

**Comment by technosophos** [comment]
The outcome of the meeting today was that people would take a read over the patch and weigh in here with their thoughts. The only raised concern was with the `helm rollback` feature, and my thought is that a rollback to a release that has been purged would simply be an error.

**Comment by michelleN** [comment]
@technosophos A rollback to a release that has been purged would simply be an error makes sense to me. Since we've gotten a few requests for this feature, I think we should go ahead with it. It'll make development and experimentation easier.
It is a bit unsafe so we could experiment or throw up an issue in the future for putting this functionality behind RBAC.

**Comment by technosophos** [comment]
I think we've passed through the "speak now or forever hold your peace" part of this issue. So I'm merging.

Thank you @ebraminio, and thanks for putting up with a longer-than-normal review process.

**Pull request merged**
