### PR TITLE
Update the Developer Call zoom.us link

### PR DESCRIPTION
**Pull request by nickschuch**

### CODE REVIEW

**Comment by bacongobbler** [comment]
Would you also mind changing the link in the [release checklist](https://github.com/helm/helm/blob/master/docs/release_checklist.md)?

If not I'd be happy to do that in a follow-up. Also, if you don't mind signing the CLA that'd be great. Thanks!

**Comment by nickschuch** [comment]
I don't mind at all! Sorting it all out now.

**Review by bacongobbler — APPROVED** [review]
perfect. Thank you!

**Comment by nickschuch** [comment]
My first commit! (Not going to be my last, haha)

**Pull request merged**
