### PR TITLE
bump oras minor version

### PR DESCRIPTION
**Pull request by AustinAbro321**
**What this PR does / why we need it**:
This is a minor update to the oras version while we wait for the major oras v2 upgrade. This update matters because the current auth mechanism in oras breaks when logging into an insecure repo unless an IP address is used. Oras v1.2.5 updates to use docker v25.0.1 for auth mechanisms which avoids this issue 

**Special notes for your reviewer**:

I can give the whole stack trace is wanted, but ultimately it boils down ORAS v1.2.4 calling functions which eventually use this faulty regex to determine if the domain is correct https://github.com/distribution/distribution/blob/v2.8.3/reference/regexp_deprecated.go#L12-L23

**If applicable**:
- [ ] this PR contains documentation
- [ ] this PR contains unit tests
- [ ] this PR has been tested for backwards compatibility

### CODE REVIEW

**Review by sabre1041 — APPROVED** [review]
@AustinAbro321 can you resolve the conflict?

**Comment by sabre1041** [comment]
@AustinAbro321 can you resolve the conflicting files?

**Comment by AustinAbro321** [comment]
@sabre1041 done

**Review by sabre1041 — APPROVED** [review]
LGTM

**Review by scottrigby — APPROVED** [review]
lgtm 👍 straightforward bump to [v1.2.5](https://github.com/oras-project/oras-go/releases/tag/v1.2.5). Although I'm very much looking forward to upgrading to oras v2 when/if we can (#12310).

**Comment by AustinAbro321** [comment]
@scottrigby @sabre1041 Do you think you could get this into v3.15.2? It would solve a relatively big bug for my team and I

**Pull request merged**
