### PR TITLE
Remove log in sympath

### PR DESCRIPTION
**Pull request by rkt2spc**
Remove this log so `helm template` can work properly.

### CODE REVIEW

**Review by hickeyma — COMMENTED** [review]
@rocketspacer Can you explain what this PR is supposed to fix or do?

**Comment by rocketspacer** [comment]
@hickeyma this line always write text to stdout whenever I do `helm template`
making the output un-usable for further operations like `helm template | k apply -k`

**Comment by bacongobbler** [comment]
To give some background context on this change, it was introduced as part of a CVE during the Helm security audit. More information can be found here: https://helm.sh/blog/2019-10-30-helm-symlink-security-notice/

Based on the feedback provided to us by the security team, this warning message should not be removed. Perhaps a better resolution to this may be to work on #6844, which then users could strip this log line by using a lower verbosity level such as helm package -v.

What do you think?

**Comment by bacongobbler** [comment]
FYI, pkg `log` prints these log messages on stderr, not stdout. Piping stderr to /dev/null will remove the output.

https://golang.org/pkg/log/

**Comment by rocketspacer** [comment]
@bacongobbler Your method works :)
`helm template release-123 . 2> /dev/null | grep walk.go`

**Pull request closed without merging**
