### PR TITLE
ref: require name by default on 'helm install'

### PR DESCRIPTION
**Pull request by technosophos**
This is described in the official Helm 3 proposal: https://github.com/helm/community/blob/master/helm-v3/000-helm-v3.md

The new version of `helm install` is now:

```
$ helm install NAME CHART
```

Moniker (a.k.a. "the cute namer") is gone 😢 🐼 , and the default naming scheme for `--generate-name` is now `basename(CHART)-unix_timestamp()`

### CODE REVIEW

**Comment by adamreese** [comment]
Should there be a new glide lock file?

**Comment by technosophos** [comment]
Updated Gopkg.lock

**Review by adamreese — APPROVED** [review]

**Comment by vdice** [comment]
`Moniker (a.k.a. "the cute namer") is gone` 😿 😢 😭

**Comment by technosophos** [comment]
It's like discovering that there is no Santa and no Easter Bunny on the same day. 🎅 🐰 🐼

**Pull request merged**
