### PR TITLE
Remove uselss indentation of lists

### PR DESCRIPTION
**Pull request by naseemkullah**
**What this PR does / why we need it**:
Cleans the sample chart files. No need to indent lists.

**Special notes for your reviewer**:

I guess this is more of a preference. But for a while I thought indenting lists was necessary due to stuff like this, but it actually is not and would like to prevent any confusion.

**If applicable**:
- [x] this PR contains documentation
- [x] this PR contains unit tests
- [x] this PR has been tested for backwards compatibility

### CODE REVIEW

**Review by hickeyma — COMMENTED** [review]
Thanks for the PR @naseemkullah. I am not sure however that this is an improvement. IMO, the indentation brings better clarity to the user.

**Comment by naseemkullah** [comment]
Fair enough. Thought I would try... I guess it's a question of preference then.
Feel free to close @hickeyma

**Comment by unguiculus** [comment]
I agree with @hickeyma. It's definitely not useless but rather a matter of taste. Personally, I prefer indentation as well.

**Comment by hickeyma** [comment]
@naseemkullah Thanks for understanding. Closing.

**Pull request closed without merging**
