### PR TITLE
Make GetCapabilities() method public

### PR DESCRIPTION
**Pull request by tamalsaha**
Signed-off-by: Tamal Saha <tamal@appscode.com>

### CODE REVIEW

**Comment by tamalsaha** [comment]
I am using helm as a library to render charts on my server side code. It would helpful, if this method can be made public.

**Review by jdolitsky — APPROVED** [review]
this seems straightforward - anyone opposed?

**Comment by bacongobbler** [comment]
Will take a closer look next week. Generally speaking functions like getCapabilities are made private because the underlying behaviour can change between kubernetes client releases.

**Comment by mattfarina** [comment]
@tamalsaha Can you share your use case for using this method? It's part of the actions package so I am wondering if you're not able to use the actions or your building something different. Can you help us understand more clearly?

**Comment by tamalsaha** [comment]
We have wrote a `check permissions` "action" that will check if the user / client getter has the necessary permissions to install/uninstall/update charts using SubjectReview api. We need access to the capabilities to call
 
`chartutil.ToRenderValues(chrt.Chart, vals, options, caps)`

api.

**Pull request closed without merging**
