### PR TITLE
chore(deps): Bump github.com/deislabs/oras from v0.10.0 to v0.11.1

### LINKED ISSUE #229: v0.10.0 break downstreams for `go get`
When downstream dep `github.com/deislabs/oras` like `helm.sh/helm/v3`

if someone what to use `helm.sh/helm/v3`, go get will break (golang 1.16)
```
$  go get helm.sh/helm/v3@v3.5.2
go get: helm.sh/helm/v3@v3.5.1 updating to
        helm.sh/helm/v3@v3.5.2 requires
        github.com/deislabs/oras@v0.10.0 requires
        github.com/docker/distribution@v0.0.0-00010101000000-000000000000: invalid version: unknown revision 000000000000
```

We could use `replace` to fix this. 
but not all sub pkg dep `github.com/deislabs/oras`

**if the invalid version here, and all downstreams have to set the `replace`**

should avoid the invalid version  in go mod. like main branch did.

```
github.com/docker/distribution v0.0.0-00010101000000-000000000000
github.com/docker/docker v0.0.0-00010101000000-000000000000
```

only need to set replace, when real deps `github.com/deislabs/oras`
```
replace (
	github.com/docker/distribution => github.com/docker/distribution v0.0.0-20191216044856-a8371794149d
	github.com/docker/docker => github.com/moby/moby v17.12.0-ce-rc1.0.20200618181300-9dc6525e6118+incompatible
)
```

### PR DESCRIPTION
**Pull request by morlay**
drop `replace` 

fix https://github.com/deislabs/oras/issues/229

**What this PR does / why we need it**:

**Special notes for your reviewer**:

**If applicable**:
- [ ] this PR contains documentation
- [ ] this PR contains unit tests
- [ ] this PR has been tested for backwards compatibility

### CODE REVIEW

**Review by jdolitsky — CHANGES_REQUESTED** [review]
@morlay thanks for looking into this. Can you drop the update of cobra? more context here: https://github.com/helm/helm/pull/9355

**Comment by morlay** [comment]
@jdolitsky 

`go mod download` added it. 😂

i will try to fix

**Comment by morlay** [comment]
@jdolitsky  have to wait. use go cmds can't fix it 

`github.com/deislabs/oras@v0.11.0` deps `github.com/spf13/cobra@v1.1.3`

i don't think we need another `replace` to lock it.

**Comment by jdolitsky** [comment]
@morlay - looks like the cobra one is closed. Also, oras 0.11.1 now released due to regression. Want to make these updates?

**Comment by morlay** [comment]
@jdolitsky sure. upgated.

**Review by jdolitsky — APPROVED** [review]

**Review by jdolitsky — CHANGES_REQUESTED** [review]
Ok, looks like CI failure now with `make test-style`.. maybe need to lock the docker/distribution line? Can you make sure that passes locally?

The error is
```
#!/bin/bash -eo pipefail
make test-style
GO111MODULE=on golangci-lint run --timeout 5m0s
WARN [runner] Can't run linter goanalysis_metalinter: deadcode: analysis skipped: errors in package: [/home/circleci/helm.sh/helm/cmd/helm/dependency_build_test.go:28:2: could not import helm.sh/helm/v3/pkg/repo/repotest (/home/circleci/helm.sh/helm/pkg/repo/repotest/server.go:31:2: could not import github.com/docker/distribution/registry (/go/pkg/mod/github.com/docker/distribution@v2.7.1+incompatible/registry/registry.go:15:2: could not import rsc.io/letsencrypt (/go/pkg/mod/github.com/docker/distribution@v2.7.1+incompatible/registry/registry.go:15:2: no required module provides package rsc.io/letsencrypt; to add it:
	go get rsc.io/letsencrypt)))] 
WARN [runner] Can't run linter unused: buildir: failed to load package : could not load export data: no export data for "rsc.io/letsencrypt" 
ERRO Running error: buildir: failed to load package : could not load export data: no export data for "rsc.io/letsencrypt" 
make: *** [Makefile:116: test-style] Error 3

Exited with code exit status 2
```

**Comment by morlay** [comment]
seems we have to keep the replace 😢 

```
replace (
	github.com/docker/distribution => github.com/docker/distribution v0.0.0-20191216044856-a8371794149d
)
```

**Comment by bacongobbler** [comment]
Try running `go mod tidy`. Everything compiles just fine after issuing that command, and it removes the `replace` from go.mod. In addition, it cleans up a ton of what was added into go.sum in this PR.

**Comment by bacongobbler** [comment]
Here's a patch: https://gist.github.com/bacongobbler/bb78194ee137571fe4092e44f9c15ff9

Everything compiles fine locally after applying that patch against your branch. Are you sure you're using the latest version of Go?

**Comment by morlay** [comment]
@bacongobbler it is the need to keep replace for `github.com/docker/distribution`

i use `go@1.16.2`. without the replace, testing will be failed.

**Comment by dududko** [comment]
Any update on this PR ?

**Review by jdolitsky — APPROVED** [review]
I pulled this down and tried again, there does not seem to be a way to do away with the docker/distribution replace statement for now. LGTM

**Review by bacongobbler — APPROVED** [review]
Fair enough. LGTM!

**Pull request merged**
