### PR TITLE
ref(helm): consolidate vars() function

### PR DESCRIPTION
**Pull request by pmahoney-raise**

### CODE REVIEW

**Comment by pmahoney-raise** [comment]
Oops, I initially signed in to LinuxFoundation via Google. I believe I've made GitHub my primary auth provider, and my company has signed the CLA. Thanks!

**Comment by technosophos** [comment]
This looks good.

**Review by technosophos — APPROVED** [review]
Thanks

**Comment by technosophos** [comment]
@jascott1 Do you want to take a quick peek at this one to verify?

**Comment by jascott1** [comment]
@technosophos I don't see any issues. Thanks @pmahoney-raise

**Pull request merged**
