### PR TITLE
Refactor helm.go into cli package, split commands up

### PR DESCRIPTION
**Pull request by gerred**
This is a pretty big commit. It creates the new CLI package, and makes the main package much smaller and easier to understand. In this PR, I preferred small files over large ones, to reduce a lot of the problems associated with having a 400 line main CLI file.

Functions for commands were also grouped up in a sane way. Where possible, descriptions were moved out into their own constants to alleviate @technosophos's concern about easily working with descriptions.

As a result of this, the Makefile was adjusted to set cli.version instead of main.version. I feel this ends up being much more clear when looking at the Makefile.

All of the CLI command vars still need to be documented, so I'm marking this in progress until that's done.

### CODE REVIEW

**Comment by technosophos** [comment]
I do think @gerred  is right that this is a lot easier to work with now that helm has a pretty sizable command list. Any thoughts on this @adamreese and @michelleN? Does this feel easier to work with or harder to work with?

**Comment by gerred** [comment]
Actually, I don't see the point in documenting the cmds as well. @technosophos - mind giving your opinion in that regard? I know this has been talked about before, but I'm more worried about having it documented in both the `action` package and `cli` package. These commands are small enough to be self-documenting and it may not be worth the docs getting out of sync.

**Comment by gerred** [comment]
Seems like a non-related test failed here? ^

**Comment by adamreese** [comment]
+1 for breaking up commands

**Comment by arschles** [comment]
@gerred :+1: on this. good cleanup

**Comment by adamreese** [comment]
@gerred this is ready to merge

**Pull request merged**
