### PR TITLE
fix recursion count in templates

### LINKED ISSUE #7559: template recursion bug
Recursion in template functions is not properly detected. The count is never decremented after the template executes which results in a false positive. Link to the PR which fixes this: https://github.com/helm/helm/pull/7558

Output of `helm version`:
```
version.BuildInfo{Version:"v3.0.3", GitCommit:"ac925eb7279f4a6955df663a0128044a8a6b7593", GitTreeState:"clean", GoVersion:"go1.13.7"}
```
Output of `kubectl version`:

Cloud Provider/Platform (AKS, GKE, Minikube etc.): 

With a function defined as follows:
```
{{- define "test.nonRecursive" -}}
{{- printf "this is fine" -}}
{{- end -}}
```
And a template file with
```
{{- $ok := include "test.nonRecursive" . -}}
```
repeated several thousand times, the recursion detection kicks in and returns the error
```
Error: template: ibm-dlaas/templates/test.yaml:1002:11: executing "ibm-dlaas/templates/test.yaml" at <include "test.nonRecursive" .>: error calling include: rendering template has a nested reference name: test.nonRecursive: unable to execute template
```
even though there is no recursion involved.

### PR DESCRIPTION
**Pull request by ghost**
The count in `includedNames` is incremented every time a name is seen, but is not decremented after executing the template. In a large helm chart, a function could be included many times, which exceeds the `1000` limit, without necessarily including any recursion.

Recursive functions such as
```
{{- define "test.recursionTest" -}}
{{- printf "%s" (include "test.recursionTest" .) -}}
{{- end -}}
```
are still detected and result in an error.

Closes https://github.com/helm/helm/issues/7559

### CODE REVIEW

**Comment by bacongobbler** [comment]
Duplicate of #7471?

**Comment by danielchengibm** [comment]
No, this is an issue with https://github.com/helm/helm/pull/7471. Just opened an issue here https://github.com/helm/helm/issues/7559.

**Comment by bacongobbler** [comment]
Sorry. After looking more closely at the issue I realized this was after #7443 was merged. I thought I’d wasn’t in a release yet. My bad!

Thanks for the PR.

**Review by bacongobbler — COMMENTED** [review]
Would you mind writing a unit test to cover this case? That way we can prevent this from occurring in the future. Thanks.

**Comment by danielchengibm** [comment]
Sure, I can add one, probably early next week.

**Comment by mattfarina** [comment]
Thanks for catching this and writing a great test.

**Review by mattfarina — APPROVED** [review]
This looks great. Really like the testing.

**Pull request merged**
