### PR TITLE
fix the certificates variables

### PR DESCRIPTION
**Pull request by cpanato**
when using the latest master and you want to set the ca/cert/key certificates for another path the helm only check the home directory.

Before:
```Bash
$bin/helm ls  --tls --tls-ca-cert /Users/cpanato/certificates/ca.cert.pem  --tls-cert /Users/cpanato/certificates/helm.cert.pem  --tls-key /Users/cpanato/certificates/helm.key.pem
could not read x509 key pair (cert: "/Users/cpanato/.helm/cert.pem", key: "/Users/cpanato/.helm/key.pem"): can't load key pair from cert /Users/cpanato/.helm/cert.pem and key /Users/cpanato/.helm/key.pem: open /Users/cpanato/.helm/cert.pem: no such file or directory
```

After the fix:
```Bash
$bin/helm ls  --tls --tls-ca-cert /Users/cpanato/certificates/ca.cert.pem  --tls-cert /Users/cpanato/certificates/helm.cert.pem  --tls-key /Users/cpanato/certificates/helm.key.pem
NAME                    REVISION        UPDATED                         STATUS          CHART                   APP VERSION     NAMESPACE
bumptious-macaw         1               Fri Sep  7 19:00:21 2018        FAILED          spinnaker-1.1.0         1.9.1           default
kissing-jellyfish       1               Fri Sep  7 19:12:35 2018        FAILED          spinnaker-1.1.0         1.9.1           default
kubewatch               1               Fri Jun 22 16:50:10 2018        DEPLOYED        kubewatch-0.4.0         v0.0.4          kubewatch
mysql-operator          1               Fri Jun 22 14:11:09 2018        DEPLOYED        mysql-operator-0.1.0                    default
```

also works with env variables which did not work before
```Bash
$export HELM_TLS_KEY=/Users/cpanato/certificates/helm.key.pem
$export HELM_TLS_CERT=/Users/cpanato/certificates/helm.cert.pem
$export HELM_TLS_CA_CERT=/Users/cpanato/certificates/ca.cert.pem
$bin/helm ls  --tls
NAME                    REVISION        UPDATED                         STATUS          CHART                   APP VERSION     NAMESPACE
bumptious-macaw         1               Fri Sep  7 19:00:21 2018        FAILED          spinnaker-1.1.0         1.9.1           default
kissing-jellyfish       1               Fri Sep  7 19:12:35 2018        FAILED          spinnaker-1.1.0         1.9.1           default
kubewatch               1               Fri Jun 22 16:50:10 2018        DEPLOYED        kubewatch-0.4.0         v0.0.4          kubewatch
mysql-operator          1               Fri Jun 22 14:11:09 2018        DEPLOYED        mysql-operator-0.1.0                    default
```

### CODE REVIEW

**Comment by bacongobbler** [comment]
thanks @cpanato. Let me take a look at this one and get back to you.

**Comment by bacongobbler** [comment]
@cpanato I just wrote some unit tests against master that verifies if the settings are affected by flags and environment variables. From looking at #4657 it looks to me like these flags and environment variables all indeed do not work as intended.

That being said, there are a few assumptions being made in this code that I don't necessarily agree with. I'm going to take another pass at the changes made here and see if I can come up with a cleaner approach.

**Comment by cpanato** [comment]
@bacongobbler Thanks for having time and reviewing this PR.
For the env variables you right it looks like working as expected.

however when I build the helm using the `make build` and run the following command for example:
```
bin/helm ls \
 --tls \
 --tls-ca-cert=/Users/cpanato/certificates/ca.cert.pem \
 --tls-cert=/Users/cpanato/certificates/helm.cert.pem \
 --tls-key=/Users/cpanato/certificates/helm.key.pem
```

I got this error in the console:
```
could not read x509 key pair (cert: "/Users/cpanato/.helm/cert.pem", key: "/Users/cpanato/.helm/key.pem"): can't load key pair from cert /Users/cpanato/.helm/cert.pem and key /Users/cpanato/.helm/key.pem: open /Users/cpanato/.helm/cert.pem: no such file or directory
```
Am I doing something wrong?
But looks like it is trying to get the keys from the `HELM_HOME` and not from the path I specified.

thanks again

**Comment by bacongobbler** [comment]
I'm seeing the same thing. The unit tests are correct, but the functionality is not since we're using multiple variables to perform the same task. I'll take a look at refactoring the code and get back to you.

**Comment by bacongobbler** [comment]
I've filed #4660 so we can track the bug outside of PR implementations.

**Comment by cpanato** [comment]
@bacongobbler cool

now I will get back to the other ticket for the --wait thing :)

**Pull request closed without merging**
