### PR TITLE
Add linting support for '.tar.gz' tarballs for helm charts

### LINKED ISSUE #6535: Helm3: Support .tar.gz files too
Output of `helm version`:
```
version.BuildInfo{Version:"v3.0+unreleased", GitCommit:"3fa4465eec27e1a008189a3c22d7367a75cac136", GitTreeState:"clean", GoVersion:"go1.13.1"}
```

Helm3 already supports `.tgz` tar balls for helm charts. It only seems fair to support `.tar.gz` which is the same thing but just a different / extended extension name. I understand `helm package` gives only a `.tgz` as an output. I just felt that they both are the same thing technically, but why does it not work for `.tar.gz`:

```
$ helm create test-dummy-chart
Creating test-dummy-chart

$ helm3 package test-dummy-chart/
Successfully packaged chart and saved it to: /Users/karuppiahoss/go/src/helm.sh/helm/test-dummy-chart-0.1.0.tgz

$ helm3 lint test-dummy-chart-0.1.0.tgz
==> Linting test-dummy-chart-0.1.0.tgz
[INFO] Chart.yaml: icon is recommended

1 chart(s) linted, 0 chart(s) failed

$ mv test-dummy-chart-0.1.0.tgz test-dummy-chart-0.1.0.tar.gz

$ helm3 lint test-dummy-chart-0.1.0.tar.gz
==> Linting test-dummy-chart-0.1.0.tar.gz
Error no chart found for linting (missing Chart.yaml)

Error: 1 chart(s) linted, 1 chart(s) failed
```

Just felt it could work for `.tar.gz` too. But if this doesn't seem valid, we can close it 👍

### PR DESCRIPTION
**Pull request by kamalashreen**
**What this PR does / why we need it**:
This PR adds support to lint packaged helm charts with extension `.tar.gz`.

**Special notes for your reviewer**:
'closes #6535'

**If applicable**:
- [ ] this PR contains documentation
- [x] this PR contains unit tests
- [x] this PR has been tested for backwards compatibility

### CODE REVIEW

**Comment by bacongobbler** [comment]
Thanks @KamalashreeNagaraj. At this time we are only working on bugfixes and regressions from Helm 2 for the Helm 3.0.0 release, so I've marked this as a candidate for the 3.1.0 release.

**Comment by KamalashreeNagaraj** [comment]
Sure. What implication will this have on the timelines? By when can I expect this PR to be under review?

**Comment by bacongobbler** [comment]
We just discussed in the public dev call that we are shooting for a 3.0.0 release on October 31st. We probably will be heads down until then

**Comment by bacongobbler** [comment]
Apologies for the automatic closure. We just switched the `dev-v3` branch to `master`, and the old `master` branch is now `dev-v2`. Feel free to re-open a new PR with this change. Thanks again and sorry for the hassle!

**Comment by KamalashreeNagaraj** [comment]
So I should raise the new PR to the master branch?

**Comment by hickeyma** [comment]
@KamalashreeNagaraj Yes

**Comment by KamalashreeNagaraj** [comment]
Sure. Will do it 👍 The same issue id #6535 applies right?

**Pull request closed without merging**
