### PR TITLE
use intstr.GetScaledValueFromIntOrPercent instead of the deprecated

### PR DESCRIPTION
**Pull request by phoenixsqf**
Signed-off-by: phoenixsqf <sqfphoenix@163.com>

use intstr.GetScaledValueFromIntOrPercent cause intstr.GetValueFromIntOrPercent is deprecated

### CODE REVIEW

**Comment by yxxhero** [comment]
@phoenixsqf Please fix DCO issue.

**Comment by yxxhero** [comment]
https://pkg.go.dev/k8s.io/apimachinery/pkg/util/intstr#GetValueFromIntOrPercent

**Comment by phoenixsqf** [comment]
> @phoenixsqf Please fix DCO issue.

Fixed.

**Review by yxxhero — APPROVED** [review]
LGTM

**Review by mattfarina — APPROVED** [review]

**Pull request merged**
