### PR TITLE
error eturn instead of panic for pkg/action.Configuration#Init() method

### PR DESCRIPTION
**Pull request by wuhuizuo**
Signed-off-by: wuhuizuo <wuhuizuo@126.com>

**What this PR does / why we need it**: fix issue #9698 

**What I did**: error eturn instead of panic for pkg/action.Configuration#Init() method
**Why**: since the method have a error type return value, it should not panic in method body.

**Special notes for your reviewer**:

**If applicable**:

- [x] this PR has been tested for backwards compatibility

### CODE REVIEW

**Review by cndoit18 — COMMENTED** [review]
I think these are necessary storage drivers, if there has a problem, then all the follow-up all the operations will be invalid, so there should throw panic.

**Comment by wuhuizuo** [comment]
> PRs must be linked to an existing issue. If none exists, may you please open one explaining the issue and expected outcome?
> 
> Please also write tests to test and verify this PR fixes your issue. Thanks.

I created issue #9698.

**Comment by wuhuizuo** [comment]
unit tests added.

**Comment by wuhuizuo** [comment]
close it becauseof the discussion did not reach agreement.

**Pull request closed without merging**
