### PR TITLE
Fix SIGSEGV when storage driver returns nil error (#3625)

### PR DESCRIPTION
**Pull request by nonspecialist**
This addresses #3625 where `tiller` segfaults in `uniqName` -- the check for an existing name assumes that the storage driver's `Get` function always returns a valid `error` type, but for example the `cfgmaps` driver (default) often returns a `nil`

### CODE REVIEW

**Comment by nonspecialist** [comment]
A note on testing ... this is a hard one to test for; the only existing test that _might_ trigger this is https://github.com/helm/helm/blob/b4b693c3168421c8cd7165e2fb5eb2233adefa6a/pkg/tiller/release_server_test.go#L357 and that would only trigger the issue _if_ `moniker` chose the name `happy-panda`; with the current version of `moniker` having 243 animals and 390 descriptors, that's a 1 in 94,770 chance (0.001%) of triggering the bug during testing.

I could update this PR with a bigger rewrite that allows the use of something that satisfies the `moniker` interface in order to increase the test coverage, if that's considered worthwhile.

**Comment by nonspecialist** [comment]
PR updated to add a test which, based on the original code causes a segfault and confirms that the fix is valid

**Comment by bacongobbler** [comment]
hey! looks like the commit history is mangled. Mind taking a look into fixing that?

**Comment by nonspecialist** [comment]
Yeah, whoops ... sorry. Fixing that now

**Review by bacongobbler — APPROVED** [review]
LGTM. Thanks!

**Pull request merged**
