### PR TITLE
Redefine the err variable in NewChartRepository, otherwise errors migh slip through

### PR DESCRIPTION
**Pull request by bonifaido**

### CODE REVIEW

**Comment by technosophos** [comment]
Does anyone know why this error was ignored in the first place? This seems like a rational fix to me.

**Comment by jascott1** [comment]
Looks like it slipped through without fanfare in the PR here:
https://github.com/kubernetes/helm/commit/b4ca198cc625f5dc8a3544c475b2ad4c3499c5db#diff-3c52d2d00ef683b18b7c7577450a25bdR63

**Comment by jascott1** [comment]
It probably just slipped past human eyes because the `err != nil` line on :64 looks legit. I think this is a valid fix.

**Comment by bacongobbler** [comment]
LGTM

**Review by thomastaylor312 — APPROVED** [review]

**Comment by thomastaylor312** [comment]
Good catch on this @bonifaido

**Comment by bonifaido** [comment]
This caused me strange error messages when the TLS files weren't at the right place during `helm update`.

**Pull request merged**
