### PR TITLE
make warnings in coalesce.go more explicit

### PR DESCRIPTION
**Pull request by dnozay**
**What this PR does / why we need it**:

Problem: the warnings don't give enough details about which
values are problematic, only the name of the leaf key. This is
all the more annoying when you have a chart depending on other charts.

```
mainchart
    |
    +- subchart1
    +- subchart2
    +- subchart3
```

Here are some warnings I get before the change:
```
coalesce.go:199: warning: destination for credentials is a table. Ignoring non-table value
coalesce.go:160: warning: skipped value for resources: Not a table.
coalesce.go:160: warning: skipped value for googleSheetsServiceAccount: Not a table.
coalesce.go:199: warning: destination for googleSheetsServiceAccount is a table. Ignoring non-table value
coalesce.go:199: warning: destination for resources is a table. Ignoring non-table value []
coalesce.go:199: warning: destination for credentials is a table. Ignoring non-table value
coalesce.go:199: warning: destination for credentials is a table. Ignoring non-table value
coalesce.go:160: warning: skipped value for resources: Not a table.
coalesce.go:160: warning: skipped value for googleSheetsServiceAccount: Not a table.
```

with fix:
```
coalesce.go:162: warning: skipped value for subchart1.resources: Not a table.
coalesce.go:162: warning: skipped value for subchart2.googleSheetsServiceAccount: Not a table.
coalesce.go:211: warning: destination for subchart3.aws.credentials is a table. Ignoring non-table value ()
coalesce.go:211: warning: destination for mainchart.subchart3.aws.credentials is a table. Ignoring non-table value ()
coalesce.go:211: warning: destination for mainchart.subchart2.googleSheetsServiceAccount is a table. Ignoring non-table value ()
coalesce.go:211: warning: destination for mainchart.subchart1.resources is a table. Ignoring non-table value ([])
coalesce.go:162: warning: skipped value for subchart1.resources: Not a table.
coalesce.go:162: warning: skipped value for subchart2.googleSheetsServiceAccount: Not a table.
coalesce.go:211: warning: destination for subchart3.aws.credentials is a table. Ignoring non-table value ()
```

**Special notes for your reviewer**:
n/a

**If applicable**:
- [ ] this PR contains documentation
- [x] this PR contains unit tests
- [ ] this PR has been tested for backwards compatibility

### CODE REVIEW

**Review by bacongobbler — CHANGES_REQUESTED** [review]
Hi @dnozay. Can you please remove 7090a89 from the commit list and rebase this against master?

In the future, please refrain from using RC branches as the base branch - it's best to use `master` as the base branch for your commits so that they can be cleanly merged into that branch.

Thanks!

**Comment by dnozay** [comment]
Hi @bacongobbler - I did the rebase. sorry about that.

**Review by bacongobbler — CHANGES_REQUESTED** [review]
Thank you for the rebase.

When submitting a PR, we ask that contributors provide unit tests to go along with their changes. That way, we can ensure that the fix correctly resolves the issue, and it prevents future changes from introducing a regression.

Please provide unit tests along with the fixes provided here to ensure that you're asserting the correct fix. Thanks!

**Comment by dnozay** [comment]
@bacongobbler  +tests.

**Comment by dnozay** [comment]
Hi @bacongobbler, just checking in to see if there is additional feedback besides the unit tests that you needed me to address. Thank you.

**Comment by bacongobbler** [comment]
nope. However, this will require multiple maintainers to review before it can be merged. Anything larger than `size/xs` will need more eyes on the change.

**Review by bacongobbler — APPROVED** [review]

**Comment by dnozay** [comment]
sounds good, if you have suggestions on who to add as a reviewer please add them.
thank you

**Comment by dnozay** [comment]
@bacongobbler anything we can do to get some traction on this?

**Comment by dnozay** [comment]
I could resolve conflict, but is there anybody else to take a look and review?

**Review by hickeyma — CHANGES_REQUESTED** [review]
@dnozay Do you mind rebasing? I can review the PR then.

**Comment by dnozay** [comment]
@hickeyma thank you for looking into it - I have rebased the changes.

**Comment by dnozay** [comment]
@hickeyma , would you have some time to review please?

**Comment by hickeyma** [comment]
@dnozay Pinged you on slack for some details.

**Comment by hickeyma** [comment]
@dnozay Thanks for getting back to me on Slack. Do you mind rebasing and I can finish the review?

**Comment by dnozay** [comment]
@hickeyma , rebase complete, thank you for your patience.

**Review by hickeyma — APPROVED** [review]
LGTM, thanks @dnozay

**Pull request merged**
