### PR TITLE
Updates readme with chocolatey install command for Windows

### PR DESCRIPTION
**Pull request by stefanhenseler**
I've created a chocolatey helm package and thought it makes sense to update the documentation with this new info. I use appveyor (https://ci.appveyor.com/project/synax/chocolatey-packages) to build the helm package (https://chocolatey.org/packages/kubernetes-helm) from this repo: https://github.com/synax/chocolatey-packages. Is it possible to add a webhook to trigger a build on every release of helm? Or how do you manage this for the brew formula? The appveyor webhook is: https://ci.appveyor.com/api/github/webhook?id=gl9dbj2y8ikvqghr

### CODE REVIEW

**Comment by bacongobbler** [comment]
So for homebrew, the formula is purely maintained by the community.

cc @cblecker who appears to be the most active according to https://github.com/Homebrew/homebrew-core/commits/993e941fb56b035ae3ab87c2b9081ec5ab46eeca/Formula/kubernetes-helm.rb :)

**Review by bacongobbler — APPROVED** [review]
The docs look good to me though! Let me know if you'd like me to merge this or not.

**Comment by synax** [comment]
Sure! if the doc is ok, let's do it. I'll set up a schedule for the build plan to keep the package up to date. Webhook would be nicer though :)

**Comment by bacongobbler** [comment]
sgtm :)

**Comment by cblecker** [comment]
Yeah, I just update it as a downstream consumer (and general fan) of helm. I personally would support upstream handling this on a best efforts basis, but I understand the potential for sprawl.

I normally update brew with something like this:
```
#!/usr/bin/env bash
LATEST_VERSION="$(curl -s "https://api.github.com/repos/kubernetes/helm/releases/latest" | jq -r .tag_name)"
TAG_SHA="$(curl -s "https://api.github.com/repos/kubernetes/helm/git/refs/tags/${LATEST_VERSION}" | jq -r .object.sha)"
TAG_HEAD="$(curl -s "https://api.github.com/repos/kubernetes/helm/git/tags/${TAG_SHA}" | jq -r .object.sha)"

brew bump-formula-pr --revision="${TAG_HEAD}" --tag="${LATEST_VERSION}" kubernetes-helm
```

**Comment by synax** [comment]
Just to follow up on this in case someone else wants to trigger builds for GitHub repos he does not control. I've implemented a solution using [zapier](https://zapier.com/). Zapier uses the releases [RSS feed](https://github.com/kubernetes/helm/releases.atom) to trigger my build via the [appveyor REST API](https://www.appveyor.com/docs/api/projects-builds/#start-build-of-branch-most-recent-commit). This should build a new choco package version on every release.

**Comment by bacongobbler** [comment]
Nice! I was wondering about this information myself for another project. Thanks for sharing :)

**Pull request merged**
