### PR TITLE
Fix container build and add redis chart example

### LINKED ISSUE #533: Server pods aren't starting because binaries can't run
Problem is that they're built with dynamic libraries that aren't present in the minimal alpine:3.3 base image.

/cc @runseb

### PR DESCRIPTION
**Pull request by jackgr**
Closes #533.

### CODE REVIEW

**Comment by jackgr** [comment]
@technosophos @runseb Please review

**Comment by runseb** [comment]
Chart could have been in a separate PR but I tested the cross build functionality of the new make and it works fine.

+1

**Comment by jackgr** [comment]
Thanks, @runseb.

**Comment by jackgr** [comment]
#474

**Pull request merged**
