### PR TITLE
validate_name

### LINKED ISSUE #10537: helm lint misses bad chart names
`helm lint` only catches if a chart name is missing. You can see that in the following snippet...

https://github.com/helm/helm/blob/292368a64d6c9794b4573afa5a8dc6e940a21045/pkg/lint/rules/chartfile.go#L106-L111

The `chartutil` package has the ability to validate names in some forms. We could provide better hints (like no capital letters) via lint.

Output of `helm version`: 3.7

Output of `kubectl version`: N/A

Cloud Provider/Platform (AKS, GKE, Minikube etc.): N/A

### PR DESCRIPTION
**Pull request by Akshit42-hue**
Signed-off-by: Akshit42-hue <patelakshit2025@gmail.com>
Fixes #10537 

**What this PR does / why we need it**:
Helm lint now validate the name

### CODE REVIEW

**Comment by Akshit42-hue** [comment]
@yxxhero, Please do have a look :)

**Comment by bormm** [comment]
Comparing to #10572 this here does not contain any tests.

**Comment by Akshit42-hue** [comment]
Hey @bormm, the build is failing can you please give me some leads so that I can fix it

**Comment by bormm** [comment]
> Hey @bormm, the build is failing can you please give me some leads so that I can fix it

I am looking on helm source since yesterday. So I only can guess. My first idea was you maybe used different intention, but you used tabs as the other code is using. So unfortunately I have no idea what "pkg/lint/rules/chartfile.go:21: File is not `gofmt`-ed with `-s` (gofmt)" is complaining about. I would recommend using gofmt on your machine to find out what it complains.

**Comment by joejulian** [comment]
@Akshit42-hue Are you still working on this?

**Comment by Akshit42-hue** [comment]
> @Akshit42-hue Are you still working on this?

Nope you can take it :)

**Pull request closed without merging**
