### PR TITLE
call setupconnection() after displaying client version

### LINKED ISSUE #4398: helm version does not work without tiller
`helm version` without a deployed Tiller simply outputs:
`Error: could not find a ready tiller pod`

It should at least output helm client version.

Output of `helm version`: 2.9.1

### PR DESCRIPTION
**Pull request by bacongobbler**
closes #4398

### CODE REVIEW

**Comment by bacongobbler** [comment]
tacking onto the 2.10 pile since this fixes a regression that was recently introduced.

**Review by michelleN — COMMENTED** [review]
When I manually test this with a running tiller pod, it hangs. I tested in AKS and on minikube. When I don't have a running tiller pod, it returns the client version and the error message indicating there is no ready pod as expected

**Comment by bacongobbler** [comment]
thanks for checking that, michelle. There might be something prior to this code that requires a connection to tiller.

**Comment by bacongobbler** [comment]
Found the issue; had to call `ensureClient()` after setting up the connection. I've manually tested both scenarios and it works as intended now. Thanks for catchingthat!

**Review by michelleN — APPROVED** [review]

**Comment by michelleN** [comment]
Awesome. Same. Works for me as well. Thanks!

**Pull request merged**
