### PR TITLE
remove duplicate goroutine in handleContext

### PR DESCRIPTION
**Pull request by wujunwei**
**What this PR does / why we need it**:
When installing the chart, it have created duplicated Goroutines during waiting the context to be done.
**Special notes for your reviewer**:

**If applicable**:
- [ ] this PR contains documentation
- [ ] this PR contains unit tests
- [x] this PR has been tested for backwards compatibility

### CODE REVIEW

**Comment by yxxhero** [comment]
@wujunwei Can you create a issue for thie PR. Thanks very much.

**Comment by wujunwei** [comment]
#10485 the reference PR

**Comment by wujunwei** [comment]
> @wujunwei Can you create a issue for thie PR. Thanks very much.

hi there，I have create a issue above. @yxxhero

**Comment by jayonlau** [comment]
why duplicate?

**Comment by wujunwei** [comment]
> why duplicate?

@jayonlau  because there has already create a goroutine in method [handleContext](https://github.com/helm/helm/blob/main/pkg/action/install.go#L420)

**Comment by wujunwei** [comment]
Hi @jayonlau  @yxxhero , is there anything else you need from me regarding this?

**Pull request closed without merging**
