### PR TITLE
Chart cache

### PR DESCRIPTION
**Pull request by razor-x**
This is a first step to implementing https://github.com/helm/helm/issues/4618

Please note I have not done any real Go development, so my questions may seem very basic. Ideally I can get some validation on if I'm putting things logically in the right place and can iterate from there.

Anyone is welcome to contribute code or help to this PR. I will gladly give contrib access.

Basic plan (does this make sense?):

0. Ensure there is a `helmpath` method for `$helmChartCache` that creates the cache directory
1. Add a `WithCache` function to `getter.go` that sets `cachePath = $helmChartCache/$digest`
2. Add some kind of option in Helm that would be passed as an option to `ChartDownloader` to toggle the cache: `type CacheStrategy int` (where to put this option?)
3. If this option is set, have the `ChartDownloader` function `DownloadTo` invoke `WithCache`, passing the `digest` from the chart manifest (if available, otherwise do not invoke).
4. Implement (somewhere) the actual cache wrapping behaviour when `opts.cachePath` has been set (save to `cachePath` whenever it downloads something, check `cachePath` before it downloads something)
5. Ensure this does not interfere with the verification step: it should happen every time if requested, even on files returned from the cache.
6. What path should be returned by the Getter? Should it always be the cached file or will the cached file be copied to wherever it would have normally downloaded it?

### CODE REVIEW

**Comment by bacongobbler** [comment]
Thanks for the PR. Helm 3 is in the home stretch. We are in bug fix mode now. We can add features in minor releases so I am adding it to the 3.1.0 milestone so we can hopefully start reviewing it after the initial release. I just wanted to let you know it might be a little bit before we get to this.

To answer your questions:

1. There is a `helmpath` package which provides you with convenient functions to create and access common directories. Have a look at the [CachePath](https://github.com/helm/helm/blob/484d43913f97292648c867b56768775a55e4bba6/pkg/helmpath/home.go#L23) function, and have a search for `helmpath.CachePath` in the codebase for examples.
1. I don't think we should support multiple caching strategies. One that works is good enough. :)
1. See above
1. See above
1. yep. Files can be modified out-of-band, so verification should occur regardless if it was fetched or cached locally.
1. Not sure. What does it currently return?

**Review by hickeyma — COMMENTED** [review]
@razor-x Helm 3 is now released, so it is a good time to restart this PR.  Can you rebase with latest code and push on with feedback from @bacongobbler  in https://github.com/helm/helm/pull/6733#issuecomment-545028846 ?

**Comment by bacongobbler** [comment]
ping

**Comment by razor-x** [comment]
Thanks for the update. Personally I haven't had much priority to work on this, and I'm not sure when that will change. I don't want to block this feature for anyone else looking for it, so the best I can say at the moment is that I will pick this up again when I find some time, but anyone with more urgency on this should feel free to continue from here.

**Comment by bacongobbler** [comment]
Closing for now due to inactivity. Anyone willing to push this forward, please feel free to open a new PR. Thanks!

**Comment by juniorz** [comment]
I can happily push this forward! I have opened a new PR #8831 with the proposal and current progress.

**Pull request closed without merging**
