### PR TITLE
plugin: Add output format in list command

### PR DESCRIPTION
**Pull request by Akasurde**
**What this PR does / why we need it**:
Added JSON, YAML and Table output format in helm plugin list

Signed-off-by: Abhijeet Kasurde <akasurde@redhat.com>

**Special notes for your reviewer**:

**If applicable**:
- [ ] this PR contains documentation
- [ ] this PR contains unit tests
- [ ] this PR has been tested for backward compatibility

### CODE REVIEW

**Comment by bacongobbler** [comment]
can you write tests to cover this please?

**Comment by Akasurde** [comment]
@bacongobbler Done.

**Comment by Akasurde** [comment]
@bacongobbler Anything required from my side?

**Comment by Akasurde** [comment]
@bacongobbler Any news?

**Review by hickeyma — CHANGES_REQUESTED** [review]
@Akasurde Thanks for pushing the PR. The unit test could do with loading some plugins before testing the output. Then it is testing against populated content. Have a look in https://github.com/helm/helm/blob/master/cmd/helm/plugin_test.go#L79, it should show how to load some plugins.

**Comment by Akasurde** [comment]
Can someone please help me with test?

**Comment by Akasurde** [comment]
Can someone please help me here? Parsing helm plugin list output is cumbersome.

**Pull request closed without merging**
