### PR TITLE
Updating to Kubernetes 1.22.3 packages

### LINKED ISSUE #10330: Update k8s dependencies to 1.22.3
Dependabot makes PRs for individual dependencies (e.g., [here](https://github.com/helm/helm/pulls?q=is%3Apr+is%3Aopen+label%3Adependencies)). With Kubernetes we need to update all of the dependencies together. That means updating to 0.22.3 across the board in the go.mod file.

### PR DESCRIPTION
**Pull request by dperaza4dustbit**
Updating go.mod k8s.io packages to v0.22.3

Closes #10330

Signed-off-by: David Peraza <dperaza@redhat.com>

### CODE REVIEW

**Comment by bacongobbler** [comment]
Hey @dperaza4dustbit. Thanks for your contribution.

Everything here looks good. However it looks like your sign-off doesn't follow the usual format which is causing the DCO bot to fail. It's missing the angle brackets for your email address. It should look like this  (`git commit --signoff` does this for you):

```
Signed-off-by: Matthew Fisher <matt.fisher@fermyon.com>
```

**Comment by dperaza4dustbit** [comment]
> Hey @dperaza4dustbit. Thanks for your contribution.
> 
> Everything here looks good. However it looks like your sign-off doesn't follow the usual format which is causing the DCO bot to fail. It's missing the angle brackets for your email address. It should look like this (`git commit --signoff` does this for you):
> 
> ```
> Signed-off-by: Matthew Fisher <matt.fisher@fermyon.com>
> ```

Got it, changing

**Comment by zonggen** [comment]
Code LGTM and `make test-unit` passed without error.

**Review by yxxhero — APPROVED** [review]
LGTM

**Review by bacongobbler — APPROVED** [review]

**Comment by dperaza4dustbit** [comment]
Looks like it still needs approval to run additional workflows due to first-time submitter.

**Review by cndoit18 — APPROVED** [review]

**Pull request merged**
