### PR TITLE
ref(*): correct version format for charts

### LINKED ISSUE #581: test chart package names are not formatted using semver
How come our test package names look like this: gs://kubernetes-charts-testing/redis-2.tgz and not
gs://kubernetes-charts-testing/redis-2.0.0.tgz (using semver) like in https://github.com/kubernetes/helm/blob/master/docs/design/chart_format.md#the-chart-repository

```
https://helm.sh/charts/
        apache-2.3.4.tgz
        apache-2.3.4.prov
        nginx-1.1.1.tgz
        nginx-1.1.1.prov
        nginx-1.1.2.tgz
        nginx-1.1.2.prov
        redis-0.4.0-alpha.1.tgz
        redis-0.4.0-alpha.1.prov
```

### PR DESCRIPTION
**Pull request by michelleN**
Will resolve #581.

### CODE REVIEW

**Comment by michelleN** [comment]
testing this atm...

**Comment by michelleN** [comment]
tested and it looks good:
```
helm [redis-chart*]$ kubectl get pods,svc,rc
NAME                    READY          STATUS        RESTARTS   AGE
redis-master-rc-detny   1/1            Running       0          54s
redis-slave-rc-qz718    1/1            Running       0          53s
redis-slave-rc-y4stp    1/1            Running       0          53s
NAME                    CLUSTER-IP     EXTERNAL-IP   PORT(S)    AGE
kubernetes              10.0.0.1       <none>        443/TCP    3m
redis-master            10.0.57.209    <none>        6379/TCP   54s
redis-slave             10.0.218.103   <none>        6379/TCP   53s
NAME                    DESIRED        CURRENT       AGE
redis-master-rc         1              1             54s
redis-slave-rc          2              2             53s
```
ready for review.

**Comment by michelleN** [comment]
cc/ @runseb

**Comment by runseb** [comment]
LGTM,

I agree.
It is a detail but might as well get this right from the start.

**Comment by michelleN** [comment]
sounds good. thanks.

**Pull request merged**
