### PR TITLE
add version flag to tiller binary

### LINKED ISSUE #2841: Version command/flag for tiller binary
Would it be possible to add a command / flag to tiller to retrieve the current version? (similar to the helm binary)

### PR DESCRIPTION
**Pull request by ysh7**
Fixes #2841

### CODE REVIEW

**Comment by ysh7** [comment]
re-verify CLA!

**Review by bacongobbler — CHANGES_REQUESTED** [review]
I would actually change this to a command called `tiller version` similar to how helm displays the version. e.g. https://github.com/kubernetes/helm/blob/master/cmd/helm/version.go. Would you mind making that change? Thanks!

**Comment by ysh7** [comment]
I do agree with having a version command instead of flag. Should i use cobra for tiller? Since currently there are no commands on tiller, only flags.

**Comment by bacongobbler** [comment]
Yes please!

**Comment by SlickNik** [comment]
+1 for using cobra for tiller commands as well. Standardizing shared libraries is a good thing! 😄

**Comment by ysh7** [comment]
@bacongobbler For achieving the above version command, we may also have to move existing flags into a command too. Is `tiller serve` fine?

**Comment by bacongobbler** [comment]
I would prefer that we do not change the CLI interface as there are users who do not run tiller via `helm init`, and changing the interface from `tiller` to `tiller serve` would break. I'm sure there must be a way to ensure `tiller` runs the server and `tiller version` displays version output.

If the interface has to break in order to introduce a new (low-priority) feature, we should probably push this off until we start discussing Helm 3.0 in 2018.

**Comment by SlickNik** [comment]
I tend to agree with @bacongobbler here. Having a backwards-incompatible change for a small  feature (especially in a minor release) doesn't seem very prudent. Would be good to keep the current cli interface here -- or rethink this for the next major (3.0) version.

**Comment by bacongobbler** [comment]
Worst case scenario we can accept the PR as-is and write some TODO notes in the source code to revisit this in January.

@ysh7 what do you think about that?

**Comment by ysh7** [comment]
I do agree with not doing any breaking changes. I'm add the TODO note on this one.

**Review by bacongobbler — APPROVED** [review]

**Comment by adamreese** [comment]
we removed cobra because it was extra overhead not needed https://github.com/kubernetes/helm/pull/2569

**Pull request merged**
