### PR TITLE
make HELM_HOME portable

### PR DESCRIPTION
**Pull request by Stelminator**
allow cacheFile to be relative for local index
uses a symlink with a relative path on unix

final (part4) piece of https://github.com/kubernetes/helm/pull/3327

### CODE REVIEW

**Comment by Stelminator** [comment]
depends on part 2: #3596

**Comment by Stelminator** [comment]
part 2 obsoleted by https://github.com/kubernetes/helm/pull/3613

this now depends on [part 3](https://github.com/kubernetes/helm/pull/3647) for the `"path/filepath"` import

**Comment by thomastaylor312** [comment]
@bacongobbler Did you want to review this or can I take care of it?

**Comment by bacongobbler** [comment]
@stelminator would you like to add some unit tests to this PR? After that I think this would be ready to go. I just want to make sure that this change does not affect the existing behaviour of HELM_HOME in an unexpected way.

**Comment by Stelminator** [comment]
@bacongobbler I don't have any outstanding changes, but yes, I plan to add some.  Haven't managed to find the time since yesterday.

**Comment by bacongobbler** [comment]
Sounds good. Just checking :)

**Comment by bacongobbler** [comment]
Closing this PR due to inactivity. Helm 3 now follows the XDG base directory standard so the issue this PR is trying to address for Helm 2 is no longer relevant in Helm 3. As per [the announcement on the mailing list](https://lists.cncf.io/g/cncf-helm/topic/last_v2_feature_release/34301238), Helm 2.15.0 is the last release where we will be merging new features for Helm 2. Thanks!

**Pull request closed without merging**
