### PR TITLE
Log error message on failed download

### PR DESCRIPTION
**Pull request by stan-sz**
Add logging of the actual cause of the failure to download the helm chart. Related to #10285

### CODE REVIEW

**Comment by stan-sz** [comment]
@bacongobbler - can this PR be merged for the upcoming `3.8.2` release?

**Review by hickeyma — CHANGES_REQUESTED** [review]
@stan-sz Thanks for looking to provide better error handling in this method.

I would suggest looking again at this block: https://github.com/helm/helm/blob/main/pkg/action/install.go#L753-L769

I think we need to refactor this block where the error returned from `dl.DownloadTo(name, version, settings.RepositoryCache)` is handled straight away and not this rather peculiar block with debug.  What do you think?

@bacongobbler @mattfarina If the error message is changed, does this break backwards compatibility?

**Comment by stan-sz** [comment]
Thanks for feedback. Indeed the code can be simplified to just `return filename, err`. Looking forward to hearing for concerns about back-compat.

**Comment by stan-sz** [comment]
@mattfarina It would be great if this change could be part of the upcoming release. Thanks!

**Comment by stan-sz** [comment]
@hickeyma - I've addressed your feedback in the latest iteration. Thanks!

**Comment by stan-sz** [comment]
@mattfarina is this change (and other listed under the 3.9.0 milestone) slated for the 3.9.0 release?

**Review by hickeyma — APPROVED** [review]
Thanks for pushing the fix @stan-sz and also the refactor to the code.

I think the error messages are more informative now. Examples shown:

```console
$ helm install cert-manager jetstack/cert-manager --namespace cert-manager --create-namespace --version v1.6.0

Error: INSTALLATION FAILED: repo jetstack not found
```

```console
$ helm install cert-manager jetstack/cert-manager --namespace cert-manager --create-namespace --version v0.0.0 --dry-run

Error: INSTALLATION FAILED: chart "cert-manager" matching v0.0.0 not found in jetstack index. (try 'helm repo update'): no chart version found for cert-manager-v0.0.0
```

**Comment by hickeyma** [comment]
@mattfarina Change to the error message but they bring better clarity to the user on what the error is.

**Review by scottrigby — APPROVED** [review]
Agreed these errors are helpful to pass through to the end user.

Verified locally and all looks good. Nice work!

Backwards compatibility rules documentation [hip-0004](https://github.com/helm/community/blob/main/hips/hip-0004.md#specification) says this is acceptable for CLI output:
> - errors can change if doing so increases their usability

**Pull request merged**
