### PR TITLE
Adds the flag kube-cafile and env variable HELM_KUBECAFILE for a overwrite of the certificate authority file

### PR DESCRIPTION
**Pull request by dol**
When connecting to a kubernetes api server that serves a SSL certificate which is not in the system wide certificate authority file the `helm install` command fails. Error message: `Error: Kubernetes cluster unreachable: Get https://internal.company:443/version?timeout=32s: x509: certificate signed by unknown authority`

The RP #8622 would solve this issue by adding a new flag for skipping TLS verification. IMHO it's better to provide a trusted certificate authority file rather then skipping the verification step.

The flag and env variable translate to the `CAFile` config flag of genericclioptions https://godoc.org/k8s.io/cli-runtime/pkg/genericclioptions#ConfigFlags .

There are two solutions/workarounds to this problem at the moment:

1. Add the certificate to the system wide certificate authority file
2. Create a kubeconfig file with certificate-authority.
```
KUBECONFIG=~/.mycustomkubeconfig
kubectl config set-cluster internal.company --server=https://internal.company:443 --certificate-authority=/tmp/ca.crt
kubectl config set-context some-context --cluster=internal.company --namespace=myns
kubectl config use-context some-context
HELM_NAMESPACE=myns HELM_KUBEAPISERVER=https://internal.company:443 helm install --kubeconfig="${KUBECONFIG}" some-app company/some-app
```

With this patch in place this will be reduced to:
```
HELM_NAMESPACE=myns HELM_KUBEAPISERVER=https://internal.company:443 HELM_KUBECAFILE=/tmp/ca.crt helm install some-app company/some-app
```

### CODE REVIEW

**Comment by bacongobbler** [comment]
Hey @dol. Thanks for the PR.

Looks like CI is failing here. Would you mind looking into that?

```
GO111MODULE=on golangci-lint run
WARN [runner] Can't run linter goanalysis_metalinter: deadcode: analysis skipped: errors in package: [/home/circleci/helm.sh/helm/pkg/cli/environment_test.go:63:4: duplicate field name ns in struct literal] 
WARN [runner] Can't run linter unused: buildir: analysis skipped: errors in package: [/home/circleci/helm.sh/helm/pkg/cli/environment_test.go:63:4: duplicate field name ns in struct literal] 
ERRO Running error: buildir: analysis skipped: errors in package: [/home/circleci/helm.sh/helm/pkg/cli/environment_test.go:63:4: duplicate field name ns in struct literal] 
make: *** [Makefile:104: test-style] Error 3

```

**Comment by dol** [comment]
@bacongobbler  I fixed is. It was a copy/paste error. Thanks to golangci-lint for catching this.

**Review by bacongobbler — APPROVED** [review]
Thank you for addressing the CI failure. It looks like this PR needs a rebase before we can merge.

Regardless, this LGTM. It will require another maintainer to sign off before we can merge. Thanks @dol for implementing this!

**Review by marckhouzam — APPROVED** [review]
I didn't test but the changes LGTM.

I'll let @bacongobbler do the merge.

**Comment by dgeorgievski** [comment]
If it helps this feature saved the day with running keptn generic executioner, https://github.com/keptn-sandbox/generic-executor-service, that is running a helm CLI from within a k8s cluster,

Without being able to provide the CA file to the helm client, `--kube-ca-file`, the call to the API server would fail.

**Comment by marckhouzam** [comment]
Sorry about the delay. As the last approver, I guess I should have merged. Will do now.

**Comment by dol** [comment]
Thank you for the merge and @dgeorgievski for friendly bump.

**Pull request merged**
