### PR TITLE
fix(helm): home env not set on Windows

### LINKED ISSUE #2071: Error: open .helm\repository\cache\local-index.yaml
Hi, when I am running `helm dep up` with `file://` dependency I get:

```
Repository from local path: file://components/nats
Hang tight while we grab the latest from your chart repositories...
Writing to .helm\repository\cache\.helm\repository\cache\stable-index.yaml
...Unable to get an update from the "stable" chart repository (https://kubernetes-charts.storage.googleapis.com):
        open .helm\repository\cache\.helm\repository\cache\stable-index.yaml: The system cannot find the path specified.
...Unable to get an update from the "local" chart repository (http://127.0.0.1:8879/charts):
        Get http://127.0.0.1:8879/charts/index.yaml: dial tcp 127.0.0.1:8879: connectex: No connection could be made because the target machine actively refused it.
Update Complete. ⎈Happy Helming!⎈
Error: open .helm\repository\cache\local-index.yaml: The system cannot find the path specified.
```
looking at what` helm init `has created I can see that `local-index.yaml `exist in cache but it's not a file but symlink leading to `<path>\.helm\repository\cache\.helm\repository\cache\local-index.yaml ` that doesn't exists.  As a workaround I can delete `local` repository from `repositories.yaml` and then `helm dep up` works without errors. 

Environment: Win 10, helm:2.2.1

### PR DESCRIPTION
**Pull request by pietromenna**
When setting $HELM_HOME, only $HOME was considered. This variable is not always present on Windows.

Closes #2071

### CODE REVIEW

**Review by bacongobbler — APPROVED** [review]

**Review by SlickNik — APPROVED** [review]
👍  Looks good to me. Thanks Pietro!

**Comment by thomastaylor312** [comment]
@bacongobbler Are we going to want to pull this into a 2.7.1 milestone?

**Comment by bacongobbler** [comment]
I think that'd be a good idea considering we're not planning on cutting a new release until end of December. Let's bring it up in slack and see if there are other bug fixes that should be considered as well.

**Comment by thomastaylor312** [comment]
@bacongobbler This is in the proper milestone now, so it should be good to merge when you are ready

**Comment by bacongobbler** [comment]
Since this is a size/L it needs another sign off to merge this in as per our [CONTRIBUTING policy on PR lifecycles](https://github.com/kubernetes/helm/blob/master/CONTRIBUTING.md#pr-lifecycle), otherwise I'd be happy to merge this in. I appreciate @SlickNik's review but he's not a core maintainer (but he's more than welcome to reach out to ask about joining!), so this needs another look from someone else.

Sorry for being a stickler to the rules. 😢

**Comment by thomastaylor312** [comment]
@bacongobbler No you have a point. I am still getting used to the auto applied labels (got used to looking for colors). I'll give this a review

**Review by thomastaylor312 — APPROVED** [review]
@pietromenna I apologize for the delay on this. This is ready to go pending an update to the docs

**Comment by pietromenna** [comment]
Hi @thomastaylor312 , do I need to regenerate the docs? or you mean add specific details in the documentation?

**Comment by bacongobbler** [comment]
You’ll need to rebase this PR on top of master and call `make docs` again to get the docs rebased. :)

**Comment by pietromenna** [comment]
Hi @bacongobbler . I followed the instructions as you suggested. Let me know if any further step is required. Cheers!

**Review by bacongobbler — APPROVED** [review]
rebase went well. Thanks!

**Pull request merged**
