### PR TITLE
Run 2 tiller replicas

### PR DESCRIPTION
**Pull request by ahawkins**
See #2334 for more info.

### CODE REVIEW

**Comment by egeland** [comment]
Two is definitely better than one. Three would be even more HA. 👍

**Comment by technosophos** [comment]
Can we make this a configurable option, then? It looks like we can definitely do failover simply by setting a higher replica count... but I see we already have requests for >2, and for development I would rather run with just 1.

**Comment by thomastaylor312** [comment]
Just circling back to this @ahawkins since we had a conversation about it. Could you make this configurable so we can land the feature in 2.5? After that we can work on finishing out the proposal for #2334 of how we are going to handle locking

**Comment by onorua** [comment]
@thomastaylor312 and everyone how come here from search, JFYI, I've prepared PR https://github.com/kubernetes/helm/pull/3464 to introduce `--replicas` option.

**Comment by thomastaylor312** [comment]
Thanks for letting us know @onorua

**Pull request closed without merging**
