### PR TITLE
 Use go-yaml v3 directly

### PR DESCRIPTION
**Pull request by silasdavis**
This code removes dependency on sigs.k8s.io/yaml which itself is a
mirror of github.com/ghodss/yaml.

All but one usages of ghodss/yaml were no-ops. That is they passed directly
to go-yaml v2 (gopkg.in/yaml.v2). Upgradring them to use
gopkg.in/yaml.v3 was trivial.

The one non-trivial use of ghodss/yaml was a single use of the `YAMLToJSON` function. I
have copied a minimal tree of dependency functions to chartutil/yaml to
support just that function hosted with helm.

Upgrading to yaml.v3 supports retaining comments on round-trip
serialisation which is blocking the ability for helm package to support
the --set flag see #3141.

### CODE REVIEW

**Comment by silasdavis** [comment]
I am happy to fix up the test styles (they were copied more-or-less verbatim), but let's see if there is any chance of this being accepted first.

I'm also happy to be a code owner for this package within helm if you have such a concept.

If somehow you'd find this easier to accept packaged as it's own go module in separate repo, then... I can do that, I guess.

**Comment by bacongobbler** [comment]
@silasdavis, I'm incredibly upset that you proposed this PR after I told you that we would not accept PRs that vendored code straight from ghodss/yaml. Have you tried proposing a PR to ghodss/yaml first?

**Comment by bacongobbler** [comment]
I'm closing this as this goes entirely against what we discussed As discussed earlier: propose a PR upstream that would update ghodss/yaml to yaml.v3.

**Comment by silasdavis** [comment]
On a point of order, this didn't go against what we had discussed, as I said in my previous comment on the issue I made this PR before reading your comment, so it merely goes against the last thing you said, there was no discussion to be had. Furthermore I do not consider this to be 'vendoring code'. This is a fork of a small subset of the code which I would argue reduces your liability. Unfortunately you don't seem willing to have that discussion. I'll move along.

**Pull request closed without merging**
