### PR TITLE
feat(repo): validate repo url passed in

### PR DESCRIPTION
**Pull request by michelleN**

### CODE REVIEW

**Comment by jackgr** [comment]
You can do this test more reliably by attempting to parse the URL in chart.Locator. See [repo.IsChartReference](https://github.com/kubernetes/helm/blob/master/pkg/repo/repoprovider.go#L174).

**Comment by michelleN** [comment]
I looked into using the Locator and Locator methods initially but they reference charts and will throw errors if a chart is not specified. @jackgr

**Comment by jackgr** [comment]
I see. That makes sense. 

That said, it feels to me like we should solve the problem in a library (e.g., pkg/repo and/or pkg/chart) and use the same library on both client and server.

**Comment by jackgr** [comment]
Aside:

FWIW, I've been thinking about a related problem, which is how we know which repo a chart URL belongs to. We currently have a prefix matching mechanism (which had a bug... see #467).

However, it's not ideal. We get away with it because we have one repo type, namely GCS. However, that will change as soon as anyone wants to do S3 and/or something else.

A better approach would be to actually register providers for all repo types. A provider would then be able to return 2 regex: one for a repo URL and one for a chart URL. Then, the question of which repo a chart URL belongs to could be answered unambiguously, and similarly, whether or not a given URL is a valid repo URL or chart URL.

We don't need that formality or generality yet, but it's the cleanest way to solve the problem.

**Comment by michelleN** [comment]
I can move this to the library. I think it can probably be more useful there too.

**Pull request closed without merging**
