### PR TITLE
fix(helm): added support for compressed charts containing \ in file paths

### PR DESCRIPTION
**Pull request by rodcloutier**
The purpose of this PR is to fix support for chart archive created on Windows.
On Windows, the archive can contain path with backward slash (\). The current expectation of the loader is to have all path using forward slash (/). 
These changes allow the loader to accept archived paths that contains \ as well as /.

### CODE REVIEW

**Comment by technosophos** [comment]
Sorry this is taking so long. We're a little short staffed _and_ CircleCI stopped working on the repo. So we're taking a long time to get things reviewed and merged.

**Comment by technosophos** [comment]
@adamreese can you take a look at this one?

**Review by adamreese — APPROVED** [review]
I don't have a windows machine to test on but seems sane to me.

**Comment by saardemri** [comment]
Is this fix already released? and in which version ?

**Pull request merged**
