### PR TITLE
remove io/ioutil for advanced golang

### PR DESCRIPTION
**Pull request by yanggangtony**
Signed-off-by: yanggang <gang.yang@daocloud.io>

**What this PR does / why we need it**:
We should clean all io/util package according the url: https://go.dev/doc/go1.16#ioutil
/kind cleanup

### CODE REVIEW

**Comment by yanggangtony** [comment]
/cc @sabre1041 @cndoit18 
PTAL

**Review by cndoit18 — APPROVED** [review]

**Review by phil9909 — APPROVED** [review]
LGTM

**Comment by yanggangtony** [comment]
@yxxhero 
hi , i look the tag you add..
so ,this pr will be merged in 3.11.0 and 3.11.3??

**Comment by yxxhero** [comment]
@yanggangtony this PR will be merged in 3.10.3. means the next patch release.

**Comment by yanggangtony** [comment]
> this PR will be merged in 3.10.3. means the next patch release.
@yxxhero 
thanks for reply 
got it

**Pull request closed without merging**
