### PR TITLE
fix(release): update helm owner to helm org

### PR DESCRIPTION
**Pull request by bacongobbler**
Important for commands like `helm update`

### CODE REVIEW

**Comment by mboersma** [comment]
This seems to have missed triggering Travis CI completely, perhaps because the repo had just moved to helm/helm but the GitHub integration hadn't been updated yet? Given the nature of this PR, I think it would be ok to disable required status checks temporarily to just merge this. Unless someone can figure out how to fabricate such a request to Travis CI--I couldn't.

**Comment by sgoings** [comment]
You can rebase + amend the commit + force push back to this branch.

**Comment by bacongobbler** [comment]
I'm going to be away from a laptop until tomorrow afternoon so if this is a blocker then go ahead and re-submit a new PR, otherwise I'll happily do it when I'm back home. :)

**Comment by mboersma** [comment]
Closing in favor of #238.

**Pull request closed without merging**
