### PR TITLE
fix(kube): calculate patches against cluster state

### PR DESCRIPTION
**Pull request by adamreese**
Ref: #4146

### CODE REVIEW

**Comment by bacongobbler** [comment]
Okay, I was able to reproduce the original bug by using this package: [foo-0.1.0.tar.gz](https://github.com/kubernetes/helm/files/2103643/foo-0.1.0.tar.gz)

```
><> helm plugin install https://github.com/adamreese/helm-last
><> helm fetch --untar https://github.com/kubernetes/helm/files/2103643/foo-0.1.0.tar.gz
><> helm install ./foo
><> vim foo/templates/service.yaml # change the service name from "foo" to "foo-bar"
><> kubectl create -f foo/templates/service.yaml
><> helm upgrade $(helm last) ./foo
Error: UPGRADE FAILED: no Service with the name "foo-bar" found
```

Basically how this bug boils down in master:

1. Tiller looks up based on the previous release and the target release's state to perform the diff
2. if an upgrade fails, cluster resources such as `foo-bar` may be created, but are not cleaned up
3. on subsequent upgrades, because we're diffing against the previous **successful** release and the release we are trying to uprgade to, the `foo-bar` service is "lost", causing the bug to pop up.

For what it's worth, I also tested scenarios like https://github.com/kubernetes/helm/issues/1193#issuecomment-391571016 and didn't find any issues with that scenario on master (cc @krishicks):

```
><> helm plugin install https://github.com/adamreese/helm-last
><> helm fetch --untar https://github.com/kubernetes/helm/files/2103643/foo-0.1.0.tar.gz
><> helm install ./foo
><> vim foo/templates/service.yaml # change the service name from "foo" to "foo-bar"
><> helm upgrade $(helm last) ./foo
```

No errors occurred in that scenario: service `foo` was removed, and service `foo-bar` was created. No odd side effects or bugs here.

Now, with the actual bug, #4146 attempts to fix this by diffing against the live state of the cluster, so it finds `foo-bar` service and performs a diff against that resource. Unfortunately, we found that when PR #4146 fetched the object from the api, it would calculate a patch against that same object. That is NOT the desired behaviour.

To demonstrate that, with #4146:

```
><> helm delete --purge $(helm last)
><> rm -rf foo
><> helm fetch --untar https://github.com/kubernetes/helm/files/2103643/foo-0.1.0.tar.gz
><> helm install ./foo
><> vim foo/templates/service.yaml # change the service name from "foo" to "foo-bar"
><> kubectl create -f foo/templates/service.yaml
><> kubectl edit svc foo-bar # change the port number to port 8080
><> helm upgrade $(helm last) ./foo
><> k get svc foo-bar -o yaml | grep port
  ports:
    port: 8080
```

As you can see, the cluster's current state is unchanged compared to the state that we wanted to apply. This is NOT the behaviour we want.

Now my findings finally come to this PR. This PR also performs a diff of the live state against the target state (fixing up the limitations in #4146), but because we've changed the behaviour to do a diff against live state, a whole new swath of bugs may come up. For example, here's what I found using the last example:

```
><> helm delete --purge $(helm last)
><> rm -rf foo
><> helm fetch --untar https://github.com/kubernetes/helm/files/2103643/foo-0.1.0.tar.gz
><> helm install ./foo
><> vim foo/templates/service.yaml # change the service name from "foo" to "foo-bar"
><> kubectl create -f foo/templates/service.yaml
><> kubectl edit svc foo-bar # change the port number to port 8080
><> helm upgrade $(helm last) ./foo/
Error: UPGRADE FAILED: Service "foo-bar" is invalid: [metadata.resourceVersion: Invalid value: "": must be specified for an update, spec.clusterIP: Invalid value: "": field is immutable]
```

After going through these test scenarios, I think perhaps making the error a little more informative might be our best option. What do you think, @adamreese?

**Comment by steven-sheehy** [comment]
The spec.clusterIP being immutable also occurs with kubectl apply, so don't think that's something that Helm should handle. Why not just make diffing against live cluster state a flag on helm upgrade? That way users can choose the behavior they want for their use case.

**Comment by adamreese** [comment]
Closing this PR because it was only for a discussion point.

**Comment by sdake** [comment]
@bacongobbler thanks for taking the time to prototype several different approaches to resolving all of the various problems related to `helm upgrade` being unsafe or non-functional.  I do appreciate it :)

I agree with @steven-sheehy's POV for immutable fields.  If `kubectl apply` can't modify an immutable field because Kubernetes doesn't permit modification, that is a scenario where Helm can't be made to do something that underlying APIs won't do.  That is just a fundamental limitation of the technology we either have to live with, or file defects with the Kubernetes developers.

The "immutable field" limitation isn't the limitation that I think most people want fixed; the limitation that I think most people want fixed is "If a chart is extended (via adding a configmap as an example) - the upgrade will fail in the new rev of the chart".  Ignore for a moment the idea of addressing live content in the Kubernetes cluster (which is where I think the 3 way merge comes into action).
 
 I don't understand why adding a configmap to a Helm chart would crater upgrade in a two way merge.

How are versions supposed to be upgraded if it is not viable to add resources to a Helm chart?

Cheers
-steve

**Pull request closed without merging**
