### PR TITLE
feat(*): Add capability for application charts to be used as library charts

### LINKED ISSUE #5396: Helm 3: skip any template generated in a library chart
If a library chart defines any templates, those will still be rendered as part of the release. When a chart is declared as a library chart, any templates it defines should be skipped.

Originally suggested by @prydonius in https://github.com/helm/helm/issues/5085#issuecomment-465276189. Opening the ticket here to track the issue/discussion.

### PR DESCRIPTION
**Pull request by hickeyma**
**What this PR does / why we need it**:
The PR enables application charts to be used as library charts. It specifically deals with the resource objects of an app chart so when it is defined as a library chart, its resource objects will not be rendered.  As a library chart, it is only its utilities or functions that are required.

Closes #5396 

**Special notes for your reviewer**:

**If applicable**:
- [x] this PR contains documentation
- [x] this PR contains unit tests
- [x] this PR has been tested for backwards compatibility

### CODE REVIEW

**Comment by hickeyma** [comment]
@bacongobbler @adamreese After previous rebase, `helm template` seems to now add an empty line when called. I noticed this when the [tests](https://github.com/helm/helm/blob/5ba2c501a96dd48c06cdd012c6851c6904286abd/cmd/helm/template_test.go#L68-L75) ran after the rebase.

Looking at the how the test file is [checked](https://github.com/helm/helm/blob/dev-v3/internal/test/test.go#L53), it will load without any trailing empty lines. Therefore, check fails as the template output doesn't match the test data.

Any suggestions on how to get around this?

**Comment by hickeyma** [comment]
Tests passing now.  Ready for review.

**Review by bacongobbler — CHANGES_REQUESTED** [review]
Hey Martin, thanks for taking on this issue.

Adam and I paired on this PR earlier today. We thought it might be better to handle the validation logic after the chart has been loaded, such as [when the rendering engine parses child dependencies](https://github.com/helm/helm/blob/ffff0e8c33fde7547ace267c5c91b8c60fc5262c/pkg/engine/engine.go#L267-L269) to be templated. That might be a better place to determine whether or not a child chart's templates should be rendered or not.

What are your thoughts on that approach?

**Comment by hickeyma** [comment]
> Adam and I paired on this PR earlier today. We thought it might be better to handle the validation logic after the chart has been loaded, such as when the rendering engine parses child dependencies to be templated. That might be a better place to determine whether or not a child chart's templates should be rendered or not.

@adamreese @bacongobbler Thanks for reviewing this and for you feedback. I think this is a better approach, with a cleaner insertion point to validate the files. I have updated and it is ready for review again.

**Review by bacongobbler — APPROVED** [review]

**Comment by bacongobbler** [comment]
I'll let @adamreese have a look at this one, but it looks good to ship.

**Pull request merged**
