### PR TITLE
Fix encoded path for 'helm dependency build'

### LINKED ISSUE #9821: helm dependency build fails when repo URL contains escaped
With the following : `Chart.yaml`:

```yaml
apiVersion: v2
name: "gatekeeper"
version: 0.0.1
dependencies:
  - name: gatekeeper
    repository: https://gitlab.example.org/api/v4/projects/external-packages%2fgatekeeper/packages/helm/stable/
    version: 3.4.0
```

(the ending `/` is to workaround #9764).

`helm dependency build` failed exit status 1:

```
Error: could not download https://gitlab.example.org/api/v4/projects/external-packages/gatekeeper/packages/helm/stable/charts/gatekeeper-3.4.0.tgz:
failed to fetch https://gitlab.example.org/api/v4/projects/external-packages/gatekeeper/packages/helm/stable/charts/gatekeeper-3.4.0.tgz
```

As you can see, `%2` has been replaced by `/`.

### PR DESCRIPTION
**Pull request by sathieu**
**What this PR does / why we need it**:

Fixes: #9821.

**Special notes for your reviewer**:

**If applicable**:
- [ ] this PR contains documentation
- [x] this PR contains unit tests
- [x] this PR has been tested for backwards compatibility

### CODE REVIEW

**Comment by sathieu** [comment]
@cndoit18 Please review this one (split out of #9763).

**Comment by sathieu** [comment]
@cndoit18 What is the status of this PR? Please review 👀 .

**Comment by sathieu** [comment]
@bacongobbler Please unblock tests for this PR, and please review :pray:.

**Comment by sathieu** [comment]
@hickeyma @mattfarina @jdolitsky @marckhouzam I'm desperately looking for someone to start the CI and review this PR :pray: 

Now that [Gitlab supports Helm charts](https://about.gitlab.com/releases/2021/07/22/gitlab-14-1-released/#build-publish-and-share-helm-charts), more people will be affected by this (even if it can be worked around by using the project id instead of the project path).

**Comment by hickeyma** [comment]
@sathieu I would like to test this fix manually first.  Do you have suggestion how to setup a repo path with encoded path? I tried using GitHub but it is unfortunately interpreting the path.

**Comment by sathieu** [comment]
Thanks @hickeyma You can test on gitlab.com. I've already uploaded charts here: https://gitlab.com/kubitus-project/kubitus-ingress-operator/-/packages

- https://gitlab.com/api/v4/projects/28163461/packages/helm/main -> works
- https://gitlab.com/api/v4/projects/kubitus-project%2Fkubitus-ingress-operator/packages/helm/main -> doesn't work, unless you apply this MR

NB: Gitlab doc is here: https://docs.gitlab.com/ee/user/packages/helm_repository/.

**Review by hickeyma — APPROVED** [review]
LGTM, thanks for the fix @sathieu.

**Review by yxxhero — APPROVED** [review]
LGTM

**Review by yxxhero — APPROVED** [review]
LGTM

**Review by mattfarina — APPROVED** [review]

**Pull request merged**
