### PR TITLE
Updating to Kubernetes 1.24.2

### PR DESCRIPTION
**Pull request by hickeyma**

### CODE REVIEW

**Review by yxxhero — APPROVED** [review]
LGTM

**Review by davidkarlsen — APPROVED** [review]

**Comment by mattfarina** [comment]
@hickeyma can you rebase this from main. Seems another change was merged causing a conflict.

**Comment by hickeyma** [comment]
@mattfarina Rebased

**Review by mattfarina — APPROVED** [review]

**Comment by mattfarina** [comment]
@hickeyma merge when ready

**Pull request merged**
