### PR TITLE
Add a more friendly prompt when index.yaml is empty.

### PR DESCRIPTION
**Pull request by yxxhero**
Signed-off-by: yxxhero <aiopsclub@163.com>

**What this PR does / why we need it**:
fix https://github.com/helm/helm/issues/9766
**Special notes for your reviewer**:

**If applicable**:
- [ ] this PR contains documentation
- [x] this PR contains unit tests
- [ ] this PR has been tested for backwards compatibility

### CODE REVIEW

**Review by cndoit18 — APPROVED** [review]
LGTM

**Review by bacongobbler — APPROVED** [review]
I like this change. Thanks! LGTM.

**Review by hickeyma — COMMENTED** [review]
When I manually tested this before and after the fix, I am getting the same error each time. It is as follows:

```console
$ helm repo add incubator http://mirror.azure.cn/kubernetes/charts-incubator/

Error: looks like "http://mirror.azure.cn/kubernetes/charts-incubator/" is not a valid chart repository or cannot be reached: empty index.yaml file
```

It doesn't seem to be the error from #9766 and the error as provided in the fix.

@yxxhero @bacongobbler what do you think?

**Comment by yxxhero** [comment]
@bacongobbler @hickeyma I'll reconfirm it again.

**Comment by yxxhero** [comment]
@bacongobbler @bacongobbler http://mirror.azure.cn/kubernetes/charts-incubator/ this web site return 403 directlly.

**Comment by yxxhero** [comment]
> I see something completely different on main @hickeyma.
> 
> ```
> ><> ./bin/helm repo add incubator http://mirror.azure.cn/kubernetes/charts-incubator/
> Error: looks like "http://mirror.azure.cn/kubernetes/charts-incubator/" is not a valid chart repository or cannot be reached: failed to fetch http://mirror.azure.cn/kubernetes/charts-incubator/index.yaml : 403 Forbidden
> ```
> 
> When using this branch:
> 
> ```
> ><> ./bin/helm repo add incubator http://mirror.azure.cn/kubernetes/charts-incubator/
> Error: looks like "http://mirror.azure.cn/kubernetes/charts-incubator/" is not a valid chart repository or cannot be reached: failed to fetch http://mirror.azure.cn/kubernetes/charts-incubator/index.yaml : 403 Forbidden
> ```
> 
> But the error message you shared is the same as what @yxxhero proposed in this PR. Am I missing something?
> 
> See line 54:
> 
> > ErrEmptyIndexYaml = errors.New("empty index.yaml file")

This behave is right.

**Comment by yxxhero** [comment]
https://github.com/helm/helm/blob/20e2aec79365d0ec6c3230a7d0288d9a386bbc6a/pkg/repo/chartrepo.go#L127

when the website returns 403, loadIndex func don't run.

**Review by hickeyma — APPROVED** [review]
My apologies, referencing an old Helm binary by mistake instead of main and fix branches.

LGTM, thanks for the improvement @yxxhero

**Pull request merged**
