### PR TITLE
remove steps for categorizing changelogs

### LINKED ISSUE #5119: Proposal: sort fixes/new features in release notes
While reading https://github.com/helm/helm/releases I have noticed kind of mess: bugs fixes are mixed up with new features etc.
Can you please make a release notes sorted so there are sections like:
- new features
- bug fixes
- documentation changes
- etc
?

### PR DESCRIPTION
**Pull request by bacongobbler**
This reverts commit e3c6385959bca1d632ee59d1fccbcb1c612a53c5.

Signed-off-by: Matthew Fisher <matt.fisher@microsoft.com>

closes #5119

### CODE REVIEW

**Comment by bacongobbler** [comment]
Marking for the 2.15.0 release so we don't have outdated documentation on the release process

**Review by thomastaylor312 — APPROVED** [review]
Good to go on rebase

**Comment by bacongobbler** [comment]
rebased

**Comment by przemolb** [comment]
Hmm, are you going to categorize the changes during each release to let people see top level overview of changes or not ? I personally would like to avoid reading git commits to find out what is new, what is fixed etc

**Comment by bacongobbler** [comment]
Yes. What we typically do is write up a short summary on all the changes that occurred that release. That way, the information that users really want to see (new features, bug fixes, doc changes, etc.) are all available as part of the release notes.

Commit messages like "fixed a typo" or "added extra padding to resource templates" isn't helpful to community members.

**Pull request merged**
