### PR TITLE
Moving myself to maintainer emeritus

### PR DESCRIPTION
**Pull request by thomastaylor312**

### CODE REVIEW

**Review by hickeyma — CHANGES_REQUESTED** [review]
Sorry to see you go @thomastaylor312. Been a pleasure working with you.

I am pushing back because the emeritus list should be organized in alphabetic order!

**Comment by thomastaylor312** [comment]
Oh right!

**Comment by thomastaylor312** [comment]
Ok, repushed and re-alphabetized (I wasn't the only one out of order)

**Review by hickeyma — APPROVED** [review]
LGTM :)

**Review by bacongobbler — APPROVED** [review]
As the great captain Jean Luc Picard of the USS Enterprise would say: Make it so.

LGTM. Thank you for all your hard work on the project!

**Pull request merged**
