### PR TITLE
Fixed broken link from "chart.md" to "charts.md"

### PR DESCRIPTION
**Pull request by christensenemc**
Found and fixed this broken link in the docs.

---

This change is [Reviewable](https://reviewable.kubernetes.io/reviews/kubernetes/helm/1350)

### CODE REVIEW

**Comment by christensenemc** [comment]
I signed it!

**Comment by technosophos** [comment]
Thanks! I'll watch for the linuxfoundation bot to pass, then merge. Sometimes (I am told), you have to force-push the same commit again to get that to go green after signing.

**Comment by christensenemc** [comment]
linuxfoundation cla signed.  I'll give it a bit and then try force pushing.

**Comment by technosophos** [comment]
Thanks! Merged!

**Pull request merged**
