### PR TITLE
Fix init wait on tls

### LINKED ISSUE #4051: `helm init --wait` doesn't appear to work with TLS
When I run:

    helm init \
        --wait \
        --tiller-tls \
        --tiller-tls-cert ${tmp}/tiller.cert.pem \
        --tiller-tls-key ${tmp}/tiller.key.pem \
        --tls-ca-cert ${HELMHOME}/ca.pem \
        --tiller-tls-verify \
        --service-account=tiller

I get the following error:

> Error: could not ping Tiller: x509: cannot validate certificate for 127.0.0.1 because it doesn't contain any IP SANs

Output of `helm version`:

    Client: &version.Version{SemVer:"v2.9.0", GitCommit:"f6025bb9ee7daf9fee0026541c90a6f557a3e0bc", GitTreeState:"clean"}

Output of `kubectl version`:

    Client Version: version.Info{Major:"1", Minor:"9", GitVersion:"v1.9.2", GitCommit:"5fa2db2bd46ac79e5e00a4e6ed24191080aa463b", GitTreeState:"clean", BuildDate:"2018-01-18T10:09:24Z", GoVersion:"go1.9.2", Compiler:"gc", Platform:"linux/amd64"}
    Server Version: version.Info{Major:"1", Minor:"8+", GitVersion:"v1.8.8-gke.0", GitCommit:"6e5b33a290a99c067003632e0fd6be0ead48b233", GitTreeState:"clean", BuildDate:"2018-02-16T18:26:58Z", GoVersion:"go1.8.3b4", Compiler:"gc", Platform:"linux/amd64"}

Cloud Provider/Platform (AKS, GKE, Minikube etc.): 
GKE

### PR DESCRIPTION
**Pull request by aswinkarthik**
Fixes #4051 

The failure was due to the hostname getting passed as `127.0.0.1` which did not match the hostname of the certificate.

## Changes

- Added `--tiller-tls-hostname` flag for `init` command.
- Fixed a debug statement I stumbled upon (additional commit). I can remove the commit on debug statement from this PR if it should not be included.

Now the following command works,

```
helm init \
    --wait \
    --tiller-tls \
    --tiller-tls-cert ${tmp}/tiller.cert.pem \
    --tiller-tls-key ${tmp}/tiller.key.pem \
    --tls-ca-cert ${HELMHOME}/ca.pem \
    --tiller-tls-verify \
    --tiller-tls-hostname ${TLS_HOSTNAME} \
    --service-account=tiller
```

### CODE REVIEW

**Comment by thomastaylor312** [comment]
@aswinkarthik It looks like this was already implemented in #4444. Can you validate that the issue was solved with that PR and let us know if there was anything we still need to address?

**Comment by aswinkarthik** [comment]
@thomastaylor312 Its still needed. The flags added `addFlagsTLS` is not for the `init` command [here](https://github.com/bacongobbler/helm/blob/master/cmd/helm/helm.go#L132). And I think the reason is the difference in the flag names. Normally, `addFlagsTLS` adds flags as `--tls-key` as in [here](https://github.com/bacongobbler/helm/blob/master/cmd/helm/helm.go#L318), however on `init` command it is `--tiller-tls-key` as in [here](https://github.com/bacongobbler/helm/blob/master/cmd/helm/init.go#L126) (Its prefixed with `tiller`).

The above mentioned PR only adds `tls-hostname` to all the subcommands after a tiller has been initialized but not to the `init` command itself and that was causing the issue #4051 . This PR fixes that.

**Review by bacongobbler — APPROVED** [review]
Thanks!

**Comment by bacongobbler** [comment]
Mind rebasing this PR? Once that's done we can merge this. Thanks!

**Comment by aswinkarthik** [comment]
@bacongobbler Done

**Pull request merged**
