### PR TITLE
chore(deps): add dependabot.yml

### PR DESCRIPTION
**Pull request by ylz-at**
Signed-off-by: Jinesi Yelizati <i63888888@163.com>

**What this PR does / why we need it**:

With this PR, [Dependabot](https://dependabot.com/) can automatically/daily scan the dependencies described in `go.mod` and create a pull request if there is a newer version of the upstream package available.

The maintainers of this repository don't need to check the versions of the upstream packages manually. They can simply merge the PR if the tests in CI passed.
 
How Dependabot works:
  - Dependabot checks for updates
  - Dependabot opens pull requests
  - You review and merge

You can check my forked repository https://github.com/ylz-at/helm/pulls to see what kind of PRs does Dependabot create.
And in `ylz-at/helm` there are already 5 PRs automatically created by Dependabot.

**Special notes for your reviewer**:
Dependabot is already integrated with github.
The features in settings -> `Security & Analysis` -> `Configure security and analysis features` should be enabled.

**If applicable**:
- [ ] this PR contains documentation
- [ ] this PR contains unit tests
- [ ] this PR has been tested for backwards compatibility

### CODE REVIEW

**Comment by ylz-at** [comment]
For the effect, please see the PRs under https://github.com/ylz-at/helm

**Review by hickeyma — CHANGES_REQUESTED** [review]
@ylz-at Thank you for pushing the PR. Do you mind providing some background to this PR explaining the reason for the change and the benefit.

**Comment by ylz-at** [comment]
@hickeyma I updated the description, please see.

**Comment by bacongobbler** [comment]
See also https://docs.github.com/en/github/administering-a-repository/about-github-dependabot-version-updates.

Dependabot was acquired by GitHub on May 2019. https://dependabot.com/blog/hello-github/

**Review by bacongobbler — APPROVED** [review]

**Comment by bacongobbler** [comment]
Because this may impact other core maintainer's workflows (thinking specifically of @adamreese here), we should probably bring this up in the weekly dev call just to make everyone's aware of this change and are okay with integrating dependabot into the pipeline.

**Review by bacongobbler — APPROVED** [review]
As discussed in the call, any automation to help keep the project up-to-date would be a welcome change. If there are issues with dependabot and we need to revert, we can just remove this file.

Thank you!

**Pull request merged**
