### PR TITLE
fix(template): helm template "--show-only" flag producing duplicates when flag used more than once

### PR DESCRIPTION
**Pull request by lbontecou**
## Issue
https://github.com/helm/helm/issues/7203

## Summary
---
* While migrating from helm2 to helm3, we began switching `--execute` parameters to the new `--show-only` parameter that was listed as being equivalent. 
* We found our `helm template <name> <chart> --show-only template1.yaml --show-only template2.yaml --values values.yaml | kubectl replace --force -f -` commands failing due to "Resource already exists" errors. 
* Using grep, we were able to identify our issue, duplicated outputs when multiple --show-only were used.
```
$ helm template myapp myapp --show-only templates/job.yaml --values values.yaml | grep Source 
# Source: app/templates/job.yaml

$ helm template myapp myapp --show-only templates/configmap.yaml --values values.yaml | grep Source 
# Source: myapp/templates/configmap.yaml

$ helm template myapp myapp --show-only templates/configmap.yaml --show-only templates/job.yaml --values values.yaml  | grep Source   
# Source: myapp/templates/configmap.yaml
# Source: myapp/templates/configmap.yaml
# Source: myapp/templates/job.yaml
```

## Solution
---
* Identified an incorrect looping logic. 
* Tested using `make` and `./bin/helm` 
```
$ helm template myapp myapp --show-only templates/configmap.yaml --values values.yaml | grep Source 
# Source: myapp/templates/configmap.yaml

$ helm template myapp myapp --show-only templates/configmap.yaml --show-only templates/job.yaml --values values.yaml  | grep Source   
# Source: myapp/templates/configmap.yaml
# Source: myapp/templates/migrations-job.yaml
```

### CODE REVIEW

**Comment by bacongobbler** [comment]
Thanks! Would you mind writing some unit tests to cover this? Have a look at [template_test.go](https://github.com/helm/helm/blob/master/cmd/helm/template_test.go) for some examples. Let me know if you have any questions.

**Comment by bacongobbler** [comment]
testdata output can be generated by running

```
$ cd cmd/helm # this is important; seems to only work when in the cmd/helm directory
$ go test -update
```

Run this once the unit test is created, and the testdata output will be generated for you.

**Review by hickeyma — CHANGES_REQUESTED** [review]
@hoboken515 Fix looks good, thanks for this. As suggested by @bacongobbler in https://github.com/helm/helm/pull/7204#issuecomment-564602910, I think unit test on this would be useful.

**Comment by hoboken515** [comment]
I want to create the tests for this, may take me awhile to find the time / get up to speed on how to do so in the code base. Thanks for the inputs on how to do that @bacongobbler

**Comment by hoboken515** [comment]
@bacongobbler @hickeyma unittests added

**Comment by hickeyma** [comment]
@hoboken515 Can you rebase to fix the conflicts?

**Comment by hoboken515** [comment]
rebased

**Review by hickeyma — APPROVED** [review]
LGTM, thanks for catching and fixing this @hoboken515

**Pull request merged**
