### PR TITLE
Enable cross-compilation 

### PR DESCRIPTION
**Pull request by maratoid**
Currently trying to cross-compile with make bootstrap results in an error:

```
GOOS=linux GOARCH=amd64 make bootstrap build
....
go build -o bin/protoc-gen-go ./vendor/github.com/golang/protobuf/protoc-gen-go
GOBIN=/Users/marat/dev/go/src/k8s.io/helm/bin go install  -tags '' -ldflags ' -X k8s.io/helm/pkg/version.Version=v2.0.0-alpha.2+eb2625b' k8s.io/helm/cmd/...
go install: cannot install cross-compiled binaries when GOBIN is set
go install: cannot install cross-compiled binaries when GOBIN is set
make: *** [build] Error 1
```

This PR enables building make bootstrap build with GOOS and GOARCH

### CODE REVIEW

**Comment by technosophos** [comment]
This looks fine to me, but I'm going to give @adamreese a chance to review, since he's sort of the de facto keeper of the Makefile.

**Comment by adamreese** [comment]
@maratoid We are using this method to help performance of local dev builds.  This patch would increase build time from 0.38s to 17.04s for a developer.  I have started working on a cross-build target for building release binaries that should meet this requirement without adding load for devs.

```
% time make build
GOBIN=/Users/adamreese/p/go/src/k8s.io/helm/bin go install  -tags '' -ldflags ' -X k8s.io/helm/pkg/version.Version=v2.0.0-alpha.2+5cd8f4d' k8s.io/helm/cmd/...
make build  0.38s user 0.21s system 117% cpu 0.503 total
```
```
% time make build
make build-cross  17.04s user 1.56s system 143% cpu 12.967 total
```

**Comment by maratoid** [comment]
How about this? 
Not using explicit GOBIN, still using go install, so caching still happens, figure out where to copy binaries from based on 'go env' output.
 
Should still yield the short build times

**Comment by adamreese** [comment]
The purpose of the `./bin` directory is to avoid modifying the users GOPATH.  If you are using helm for your day job, you will most likely have a released version in your PATH.  Then if you hack on a new feature and build it would override the versioned binary, polluting your environment.

We could keep `build` as is and add `build-cross` to handle building for non-native platforms.  I have used gox which allows you to build into directory structures like `./bin/{{.OS}}/{{.Arch}}`

**Comment by maratoid** [comment]
One last attempt - now without GOBIN root pollution.

**Comment by technosophos** [comment]
I know I'm weighing in on this late, but would it make the most sense to just add a separate `make` target for cross compiling?

@maratoid's first solution feels cleaner, since it uses `go build` for the cross compile. But we don't want that as the default because it takes so much longer. However, a dedicated cross compile would actually solve a lot of our existing use cases -- like generating an official binary for each release. And for a cross-compile target, we don't really care so much about the build time.

Could we do something like what Glide does? https://github.com/Masterminds/glide/blob/master/Makefile#L23

I don't have super strong feelings about whether we use gox. And @maratoid could probably make the arch and os configurable to handle just single-architecture cross-compile.

Thoughts on that?

**Comment by technosophos** [comment]
Since this sorta stalled out, @adamreese has been working on some simple Makefile changes to try to get this idea into master. Can you take a look and tell me what you think?

**Comment by maratoid** [comment]
gox it is then.

**Comment by technosophos** [comment]
Thanks. Sorry about all the confusion on this issue. I think we're spread a little thin, and consequently we are not always doing the best job of communicating. I'll take responsibility for dropping the ball on this, and I'll try not to let it happen again. And I really do appreciate the amount of effort you put into it.

**Pull request closed without merging**
