### PR TITLE
Add utility function to get port forwarded tiller hostname

### PR DESCRIPTION
**Pull request by ostlerc**
I didn't change any binaries to use this to minimize possible conflicts.
Main purpose of adding this is to simplify external developers creating
a helm client.

### CODE REVIEW

**Comment by ostlerc** [comment]
signed CLA

**Comment by bacongobbler** [comment]
What do you think about passing in a working client config and client and leave the boilerplate back in `setupConnection`? e.g.

```
func TillerHost(kubeClient kubernetes.Interface, kubeConfig *rest.Config, namespace string) (string, error) {
```

Also, you happen to have a unit test or reference implementation that demonstrates how one can use this new function?

I'll also there's also some work being done in #3506, so it might be good to see where that PR's going. :)

**Comment by ostlerc** [comment]
the purpose of this function is to remove boilerplate for setting up a helm client. here is an example of how to use the function.

```
	h, err := helm.TillerHost("", "")
	if err != nil {
		// handle err
	}
	c := helm.NewClient(helm.Host(h))
```

By requiring the user to pass in the client config it requires the user to know how to create a correct client config, which defeats one of the purposes of this function. Obviously there are scenarios where users desire a more custom client configuration. This function does nothing more than glue a few default steps together. I am not convinced it's necessary to support custom configurations with this helper function, but a possible solution to get the best of both could be to make a second function that gives default configuration by doing the same steps as defined in this function (attempt in cluster, fail over to loading the context provided by the user). If you could perhaps tell me why this scenario is more likely I could understand your desire for this addition better.

As for the unit test, there is little functionality to test and a large scope of things to mock out here. Since this function is so high level, it hits a lot of top level functions. It's hard to mock out top level functions... maybe you can tell me a good way to do it. I'm not saying it's not possible, certainly not worth it IMO though.

**Comment by ostlerc** [comment]
lack of interest from maintainers on this, so i'm going to close. i'll manage my own fork

**Pull request closed without merging**
