### PR TITLE
Fix broken link to Related section on Plugins page

### PR DESCRIPTION
**Pull request by elazar**
Current points to https://docs.helm.sh/using_helm/related.md#helm-plugins

Should point to https://docs.helm.sh/related/#helm-plugins

### CODE REVIEW

**Review by jascott1 — APPROVED** [review]
Thanks!

**Comment by jascott1** [comment]
@elazar Thank you for the PR. If you could agree to the CLA we can merge your patch.

**Comment by elazar** [comment]
@jascott1 Done.

**Comment by bacongobbler** [comment]
I think we should hold off on merging this. In helm-www we have URL rewrite rules to handle internal URLs such as this. If there's a bug in the internal doc routing, we should try to fix it there first before hardcoding internal URLs.

**Comment by bacongobbler** [comment]
https://github.com/helm/helm-www/blob/5eaca6cd9ca050330cd35e185dba30417d941431/docs.helm.sh/gulpfile.js#L245-L271

**Comment by elazar** [comment]
If that's the case, it looks like there may be a couple of other similar changes to be made.

In `docs/kubernetes_distros.md`:

```markdown
See [Tiller and role-based access control](https://docs.helm.sh/using_helm/#role-based-access-control) for more information.
```

In `docs/release_checklist.md`:

```markdown
The [Quickstart Guide](https://docs.helm.sh/using_helm/#quickstart-guide) will get you going from there.
```

**Pull request closed without merging**
