### PR TITLE
Upsert into the quick start.

### PR DESCRIPTION
**Pull request by squillace**
good stuff is good to know.

### CODE REVIEW

**Comment by SlickNik** [comment]
Thanks for the PR @squillace. This is indeed good info to know!

Just had a question around whether this would make more sense in the subsequent "Helm Upgrade and Helm Rollback" section (rather than the current -- "Helm Install" -> "Customising a Chart Before Installing" section). What do you think? 

Looks good to me! 👍

**Comment by thomastaylor312** [comment]
@squillace It looks like the tests are failing on `make docs`. Seeing as you didn't change any code, I am assuming this needs a rebase against master

**Review by michelleN — APPROVED** [review]

**Comment by michelleN** [comment]
ping @squillace

**Comment by bacongobbler** [comment]
This is part of the [Chart Tips and Tricks](https://github.com/helm/helm/blob/36d2c716b3194cceb4b22f32259990a04014b5f5/docs/charts_tips_and_tricks.md#upgrade-a-release-idempotently), so this good info is indeed part of the docs already and is safe to close. Thanks @squillace!

**Pull request closed without merging**
