### PR TITLE
feat(helm): add --kube-version flag to helm template

### PR DESCRIPTION
**Pull request by superbrothers**
This PR adds --kube-version flag to helm template. It allows you to specify the Kubernetes version used as Capabilities.KubeVersion.Major/Minor (e.g. 1.7).

```
      --kube-version string    the Kubernetes version used as Capabilities.KubeVersion.Major/Minor (e.g. 1.7)
```

/ref technosophos/helm-template#27
/cc @technosophos

### CODE REVIEW

**Comment by superbrothers** [comment]
How are you going to mock thease values? We are using the helm-template just to template charts for several k8s versions, so it is better for us to be able to specify the k8s version as a flag. However it might be good to support helm's targeting k8s versions only.

**Comment by bacongobbler** [comment]
We "mock" the kubernetes version in `helm lint` as seen in https://github.com/kubernetes/helm/pull/2901. We can just share those values we use in `helm lint` with `helm template`, providing sane defaults.

> We are using the helm-template just to template charts for several k8s versions, so it is better for us to be able to specify the k8s version as a flag.

Just out of curiosity, is this because your chart is relying on alpha/beta kubernetes features? For users only running on top of stable kubernetes features, changes between minor releases does not change how the template is generated, so I would argue that this would be an unused feature once alpha/beta kubernetes features become stable.

Additionally, `helm template` was originally designed to help chart developers debug their charts; not necessarily be an intermediary step to pump out of the templating engine. It appears there are a number of users doing exactly that today, though. I wonder if this is something we should embrace and support, or if using `helm template` as a standalone `kubectl apply` template engine is out of the scope of `helm template`. 

Anyone else have thoughts on this PR?

**Comment by bacongobbler** [comment]
Perhaps there's also a third option here:

- `--with-tiller`: connects to tiller and fetches its capabilities

This way we can see how the templates will be generated based on what instance of tiller we are pointing at.

**Comment by jascott1** [comment]
@bacongobbler Im kinda against the `--with-tiller` since you can just do a `install --dry-run --debug`.

I think this PR is a good idea but we like @bacongobbler said we should use the same defaults as `lint`

**Comment by bacongobbler** [comment]
So in the meeting we all came to the agreement that there is value in this feature flag, however it seems like we will need to update the docstring to make it clear that we are overriding the existing kube version. Also we need to use the same defaults as done in `helm lint` so the user does not have to explicitly set this flag by default, but has the option to override it.

**Comment by superbrothers** [comment]
Thank you so much, so I will modify this PR as follows:

1. Use the same defaults as done in helm lint
    - https://github.com/kubernetes/helm/blob/8b512808df5f5f25a433d9d4e689309ef3ad6ec9/pkg/lint/rules/template.go#L57-L66
1. Modify the docstring of --kube-version flag
    - `override the Kubernetes version used as Capabilities.KubeVersion.Major/Minor (e.g. 1.7)`
1. make doc

**Comment by superbrothers** [comment]
@bacongobbler I've modified this PR. Could you please review the changes?

**Review by bacongobbler — APPROVED** [review]
looks like an AWESOME change. Thanks!

**Pull request merged**
