### PR TITLE
feat(tiller): support version constraint on chart

### PR DESCRIPTION
**Pull request by technosophos**
This provides the Chart.yaml field `tillerVersion`, which is a semver
range. It allows users to choose to constrain a chart to a specific
version.

The reason for this is that we keep introducing new template functions,
but we have no way of saying "this chart will only work with Tiller
newer than...".

The check on version is _only_ done on Tiller. The client does not check
at all, since it does not do any template expansion on its own.

### CODE REVIEW

**Comment by technosophos** [comment]
I am open to discussion on whether or not we _want_ to support this feature. I just realized with some testing, though, that each time we add new template functions, we make it possible of a new chart to break on an old version of Tiller.

**Comment by seh** [comment]
Since we don't allow user-level contribution to the function map used during template expansion, at least we know that new functions can't clobber existing user-defined functions.

I do think this version constraint is useful capability to have in Helm, but it does require that the chart developer realize that he's relying on a given version of Tiller. A chart developer who tries Helm for the first time wouldn't know that, say, `required` is rather new, and hence wouldn't know to warn users that his chart won't work with Helm version 2.2. Ideally, this is something that the chart packaging process would detect and annotate automatically. That is, each function would need an associated Tiller version at which it first came into service, and the packager would need find the maximum Tiller version of all functions used in the chart.

There may be other capabilities relied upon in a chart besides the set of functions, such as [importing child values](https://github.com/kubernetes/helm/blob/master/docs/charts.md#importing-child-values-via-requirementsyaml).

**Comment by technosophos** [comment]
@seh I'm not sure whether you are in favor of or opposed to the change I've done here. It seems like it's a precursor to the features you suggest.

The `tillerVersion` field should be optional. I'm envisioning its current primary use case being the Kubernetes Helm repos, where we're hopefully dealing with seasoned developers. The use case for the first-time chart developer is: ignore tillerVersion until you need it.

The importing of child values is a particularly interesting case, since that is not Tiller-side functionality. It's handled on the client. I'll have to think about that a bit.

**Comment by seh** [comment]
I think it's useful, and didn't intend to argue against pursuing it. Rather, I was just warning that—like SemVer—while the version constraint's interpretation is easy to understand, its utility relies on the publisher specifying and changing the version appropriately. It's a contract of sorts, and the publisher can violate the contract without realizing it.

**Review by adamreese — APPROVED** [review]

**Comment by technosophos** [comment]
Okay. Understood.

**Pull request merged**
