### PR TITLE
feat(repo): remove repo by name + refactors

### PR DESCRIPTION
**Pull request by michelleN**
This is in reference to #235

### CODE REVIEW

**Comment by michelleN** [comment]
cc/ @jackgr @adamreese

**Comment by technosophos** [comment]
Non-blocking: Did we have a client-side function that took HTTPErrors and displayed a pretty error message?

**Comment by michelleN** [comment]
Not specifically a client side one. We're currently using the format pkg to format errors in the client. @technosophos

**Comment by jackgr** [comment]
:+1:

**Pull request merged**
