### PR TITLE
feat(*): Adds support for timeout flag

### LINKED ISSUE #1678: Make hook timeout configurable
Currently there is no way to set a custom timeout value for lifecycle hooks. Because `Jobs` just restart if they fail with a non-zero exit code (no matter the restart policy), it would be nice to have a configurable timeout value for how long to wait on lifecycle hooks.

### PR DESCRIPTION
**Pull request by thomastaylor312**
Installs, rollback, upgrade, and delete now accept a `--timeout` flag
that allows the user to specify the maximum number of seconds that
any kubernetes command can take.

Closes #1678

### CODE REVIEW

**Comment by thomastaylor312** [comment]
This is my first time messing around with Tiller, so please let me know if there are any glaring problems I may have missed

**Comment by technosophos** [comment]
Nice!

What do you think about adding an absolute time limit on the server side -- e.g. to not let anything stay idle for more than ( I don't know) :30 minutes? Maybe that would make it possible to do something like send a `-1` and have that be interpreted as "longest I'm allowed to run".

That's just a suggestion, though. The current PR looks good to me.

**Comment by thomastaylor312** [comment]
@technosophos That isn't a bad idea. The default right now is 5 minutes if the use doesn't set the `--timeout` flag, but from a user perspective I think it should be configureable to any level. If someone wants to run their `helm upgrade` for an hour for some reason, I think they should be able to.

Also, I'll resolve those conflicts and push

**Comment by thomastaylor312** [comment]
I am waiting on a response [here](https://github.com/kubernetes/helm/pull/1648#issuecomment-267707423) before I resolve the conflict. That PR was missing a commit and now there is some broken code in master

**Comment by technosophos** [comment]
I think I got the fix in question merged on Friday. I'll re-test, though.

**Comment by thomastaylor312** [comment]
@technosophos Let me pull the latest and rebase again

**Comment by thomastaylor312** [comment]
@technosophos So I figured it out. The [committed version](https://github.com/kubernetes/helm/blob/master/_proto/hapi/services/tiller.proto#L192) of the protobuf definition does not match the [auto generated code version](https://github.com/kubernetes/helm/blob/master/pkg/proto/hapi/services/tiller.pb.go#L250). So when I regenerated the new Go code to handle the protobuf generation, builds started failing. This should be a pretty easy fix though and I can open a PR for it

**Comment by thomastaylor312** [comment]
@technosophos Ok, this has been rebased against master and all conflicts resolved. Unit tests and manual validation on my end all work.

**Comment by technosophos** [comment]
Fabulous. Merging into 2.2.0

**Pull request merged**
