### PR TITLE
Update the Helm version docs

### LINKED ISSUE #8144: Update `heml version` documentation for `SemVer v3.x.y`
https://helm.sh/docs/helm/helm_version/ documentation for helm3 has a version string from helm2, i.e.

```
version.BuildInfo{Version:"v2.0.0", GitCommit:"ff52399e51bb880526e9cd0ed8386f6433b74da1", GitTreeState:"clean"}
```

```
$ snap info helm | grep installed
installed:          3.2.1             (232) 10MB classic

$ helm version
version.BuildInfo{Version:"v3.2.1", GitCommit:"fe51cd1e31e6a202cba7dead9552a6d418ded79a", GitTreeState:"clean", GoVersion:"go1.13.10"}
```

Whatever release process is building the documentation could be tweaked to update that version.

### PR DESCRIPTION
**Pull request by andytom**
**What this PR does / why we need it**:
Have just updated the helm version docs to include the GoVersion field.

closes #8144

**Special notes for your reviewer**:

**If applicable**:
- [x] this PR contains documentation
- [ ] this PR contains unit tests
- [ ] this PR has been tested for backwards compatibility

### CODE REVIEW

**Review by liuming-dev — APPROVED** [review]

**Comment by liuming-dev** [comment]
It seems that `versionDesc ` gets no opportunity to be shown in the command output in any case, could this be removed instead of keeping this? @hickeyma @bacongobbler 

https://github.com/helm/helm/blob/5840e529e143d3f63539a312b81848f0b25ff6ba/cmd/helm/version.go#L30-L51

**Comment by bacongobbler** [comment]
I’m not sure what you’re talking about, @liuming-dev. It’s quite clearly shown with `helm help version` which is wired up [here](https://github.com/helm/helm/blob/master/cmd/helm/version.go#L63).

**Review by bacongobbler — APPROVED** [review]
Thank you!

**Comment by liuming-dev** [comment]
Sorry, I got it wrong. @bacongobbler :joy:

**Review by mattfarina — APPROVED** [review]
lgtm

**Pull request merged**
