### PR TITLE
Typo fix Timout->Timeout

### PR DESCRIPTION
**Pull request by AdamDang**
Line 56: Timout->Timeout

### CODE REVIEW

**Comment by bacongobbler** [comment]
Can you sign off on the DCO?

**Comment by AdamDang** [comment]
OK,I've signed off just now.

**Comment by bacongobbler** [comment]
Please see https://github.com/helm/helm/pull/6138/checks?check_run_id=183025790

**Comment by mattfarina** [comment]
@AdamDang If you follow the directions on the _Checks_ tab at the top it can help you fix the DCO signoff issue.

Unfortunately, Helm v2 lives on the edge of what circleci provides for memory. This latest error looks to be from that. When you see `/usr/local/go/pkg/tool/linux_amd64/link: signal: killed` that is what's usually happening. Helm v3 has no such issue.

**Comment by bacongobbler** [comment]
I'm going to close this ticket due to inactivity, but please re-open if this still needs to be addressed. Thanks!

**Pull request closed without merging**
