### PR TITLE
Added PodPreset to install order

### LINKED ISSUE #8587: Install order: podpreset before depoyments
Output of `helm version`:
```
version.BuildInfo{Version:"v3.1.1", GitCommit:"afe70585407b420d0097d07b21c47dc511525ac8", GitTreeState:"clean", GoVersion:"go1.13.8"}
```
Output of `kubectl version`:
```
Client Version: version.Info{Major:"1", Minor:"18", GitVersion:"v1.18.3", GitCommit:"2e7996e3e2712684bc73f0dec0200d64eec7fe40", GitTreeState:"clean", BuildDate:"2020-05-20T12:52:00Z", GoVersion:"go1.13.9", Compiler:"gc", Platform:"linux/amd64"}
Server Version: version.Info{Major:"1", Minor:"18+", GitVersion:"v1.18.6-dhc", GitCommit:"dff82dc0de47299ab66c83c626e08b245ab19037", GitTreeState:"dirty", BuildDate:"2020-08-11T01:30:09Z", GoVersion:"go1.13.9", Compiler:"gc", Platform:"linux/amd64"}
```

I have a helm chart with a podpreset:
```
apiVersion: settings.k8s.io/v1alpha1
kind: PodPreset
spec:
  selector:
    matchLabels:
      inject: mypodpreset
```
and a deployment which uses the podpreset:
```
apiVersion: apps/v1
kind: Deployment
spec:
  template:
    metadata:
      labels:
        inject: mypodpreset
```

The problem is, that helm seems to create the podpreset AFTER the deployment. This leads to missing environment variables in the pods.

I suggest to deploy the podpresets before deployments, so they can even be used in the same helm chart in which they are defined and not just in other charts.

### PR DESCRIPTION
**Pull request by DatzAtWork**
Added PodPreset to install order before any pods are created.

#closes #8587

What this PR does / why we need it:
Adds the PodPreset to the install order to make sure it is installed before pods are created.
This allows to use PodPresets not just in other Helm charts but even in the very same Helm chart.

Special notes for your reviewer:

If applicable:

this PR contains documentation
this PR contains unit tests
this PR has been tested for backwards compatibility

### CODE REVIEW

**Comment by bacongobbler** [comment]
@DatzAtWork in order for the github sign-off to work correctly, you need to link your email address to your github account.

For example, here's what my profile looks like:

image

And here's how I sign off on my work:

```
Signed-off-by: Matthew Fisher <matt.fisher@microsoft.com>
```

Hope that helps.

**Comment by ericsuhong** [comment]
We are currently facing an issue where podpresets are being installed AFTER deployments by helm, so would like to get this merged into master as soon as possible!

**Comment by bacongobbler** [comment]
[ping](https://github.com/helm/helm/pull/8618#issuecomment-676550560).

**Comment by bacongobbler** [comment]
closing as inactive. Please re-open another PR once you are ready to address the comments I provided earlier. Thanks.

**Comment by michaelurban** [comment]
Is this going to be addressed? It looks like a PR was closed or wasn't considered for administrative reasons. The issue stands.

**Comment by bacongobbler** [comment]
@michaelurban the original submitter was not responding to comments made by core maintainers. Please feel free to take the work that the original author wrote and address the comments I laid out above. THanks.

**Pull request closed without merging**
