### PR TITLE
fix(manager): refactor REST API to make it modular

### LINKED ISSUE #359: Manager needs a refactor to be more modular and hence more testable
Manager's REST API testing coverage is currently at 0%. And this is blocked on some changes that need to be made to the manager package. We need a little bit of refactoring of the top level API to make it easier to test things in isolation (and with mocks). Some reworking of the HTTP handler and the init logic should be good.

Along the way, I'll also fix the flag parsing code, which is redundant right now. It's in that same block of code.

I'm envisioning doing a pass to make it testable, and then we can backfill the API tests as we go.

### PR DESCRIPTION
**Pull request by technosophos**
This modifies the startup and initial handling of the REST API to make
it modular, remove the init() methods, and remove reliance on global
vars.

Closes #359

### CODE REVIEW

**Comment by adamreese** [comment]
package `manager/router` could be moved to `pkg/router` so other it can be used by resourcifier and expandybird

**Comment by technosophos** [comment]
It is not reusable in its current form (by design) because of the context.

**Comment by adamreese** [comment]
You got me excited with a title of `make it modular` and then bam

**Comment by jackgr** [comment]
@adamreese +1 to making all 3 services use the same REST framework. Currently, they're all a bit different, and this change, if confined to manager, will make manager and resourcifier differ even more than they do already.

**Comment by jackgr** [comment]
@technosophos thanks for taking the initiative to clean up the REST handling. Like the factoring of encoding, configuration and context. However, it's not clear to me that we gain a lot by building our own router. It has some shortcomings, like requiring all paths to be symmetrical for both GET and POST, as well as being an ongoing maintenance item vs. using a third party router like Gorilla.

Did you consider sticking with Gorilla and using its context mechanism to inject the dependencies? If so, what didn't you like about that option?

**Comment by technosophos** [comment]
@adamreese @jackgr I guess I should explain the motivation for the "router" package.

Basic reason:

I would consider two things to be the core of this: The `Handler/HandlerFunc` pair and the `Context`. The intent of these is not to provide a generic thing, but to provide a very specific type-safe thing. And the reason for this is that Go is a strongly typed language. We should not be subverting the type system by passing around `interaface{}` types. @adamreese the rest is pretty easy to generalize if we have a need for it. (Encoder, for example, could easily go in `pkg`... and maybe I should put it there.)

Details:

There are a number of things that I don't like about Gorilla Mux. But the main reason I am keen to remove it is because the context implementation requires runtime type checking, rather than compile time type checking. Because this leads to obscure and difficult to find bugs (and has some other performance implications), I've been removing contexts that use `interface{}` from just about everything I do.

So all I did was implement an http.Handler, and then made it possible to do dependency injection via a strongly typed Context object. There's no muxing or serious HTTP operations going on here, because that's all provided by Go's built-in HTTP implementation. The sum total of this code is only 44 lines of very generic code.

A bunch of the code in the router.go file is actually to provide immutability of the routes table, which we need to do regardless of whether we're using Gorilla or http.Server. We could get rid of the Routes struct altogether if we don't care about immutability -- it just means we have to be careful (by convention) to not introduce a race condition.

I tried to use the Gorilla mux path resolver, but it's unexported. So I had to switch to another path resolver. I don't really care what path resolver we use. So if there's another that you prefer, I'm happy to look at it.

I don't know what is meant by needing path symmetry. One certainly doesn't need GET and POST routes to "match" for anything. Verbs are handled independently. But maybe I'm just misunderstanding.

**Comment by technosophos** [comment]
LOL... in hindsight, I should have just said "If Go had generics, Gorilla Mux would be great"

**Comment by adamreese** [comment]
merging by request of @technosophos

**Pull request merged**
