### PR TITLE
Fixed link for Windows

### PR DESCRIPTION
**Pull request by mebrein**

### CODE REVIEW

**Review by bacongobbler — APPROVED** [review]

**Comment by bacongobbler** [comment]
@mebrein mind signing the CLA? :)

**Comment by mebrein** [comment]
Just signed the CLA

**Review by bacongobbler — APPROVED** [review]

**Comment by bacongobbler** [comment]
Looks like this needs to be rebased.

**Comment by mebrein** [comment]
In the mean time the binaries are updated to 2.8.1. Better cancel this and contact owner to update release script.

**Pull request closed without merging**
