### PR TITLE
feat: Sort releases by Namespace name

### LINKED ISSUE #5652: List sorted by namespace
Can I list releases (i.e. `helm ls`) by namespace order?
Maybe `-n` ?

Output of `helm version`:
```
Client: &version.Version{SemVer:"v2.13.1", GitCommit:"618447cbf203d147601b4b9bd7f8c37a5d39fbb4", GitTreeState:"clean"}
Server: &version.Version{SemVer:"v2.13.1", GitCommit:"618447cbf203d147601b4b9bd7f8c37a5d39fbb4", GitTreeState:"clean"}
```

Output of `kubectl version`:
```
Client Version: version.Info{Major:"1", Minor:"14", GitVersion:"v1.14.0", GitCommit:"641856db18352033a0d96dbc99153fa3b27298e5", GitTreeState:"clean", BuildDate:"2019-03-26T00:04:52Z", GoVersion:"go1.12.1", Compiler:"gc", Platform:"darwin/amd64"}
Server Version: version.Info{Major:"1", Minor:"10+", GitVersion:"v1.10.13-eks-g484b8", GitCommit:"484b857e3134d55ac6373fea2f51798fefa0533f", GitTreeState:"clean", BuildDate:"2019-03-08T05:32:36Z", GoVersion:"go1.10.8", Compiler:"gc", Platform:"linux/amd64"}
```

Cloud Provider/Platform (AKS, GKE, Minikube etc.): 
AWS

### PR DESCRIPTION
**Pull request by jan25**
Added sorting release list by release Namespace name.

This PR adds new option to `helm ls` command:
`helm ls -n` and
`helm ls --namespace-name` both sort release list by namespace name

closes #5652

**Special notes for your reviewer**:

**If applicable**:
- [x] this PR contains documentation
- [x] this PR contains unit tests
- [ ] this PR has been tested for backwards compatibility

### CODE REVIEW

**Comment by QwertyJack** [comment]
Pretty good !

**Comment by jan25** [comment]
@hickeyma Hi! Should we go ahead with this MR? I'll look into resolving conflicts if so

This has been open for a while now, if not needed I can close this MR and we can close the reported issue as well.

**Comment by hickeyma** [comment]
@jan25 Let me raise it at the dev meeting on Thursday to see if we are still accepting new functionality into the v2 code base.

**Comment by hickeyma** [comment]
@bacongobbler @thomastaylor312 @mattfarina Is this functionality we want in 2.15.0 or should it push out to Helm 3?

**Comment by thomastaylor312** [comment]
@hickeyma I think this would be best to move to Helm 3

**Comment by hickeyma** [comment]
@jan25 I am going to close this PR. If you would like to still deliver this functionality, create a new PR for Helm 3. Thank you for your effort on this.

**Comment by jan25** [comment]
@hickeyma thanks! I'll open a PR with Helm 3 when i find some time.

**Pull request closed without merging**
