### PR TITLE
add note about RBAC-enabled clusters

### LINKED ISSUE #3664: helm 2.8.1/2.8.2 issues with GKE clusters
I'm having issues trying run helm in a GKE cluster, I keep getting permission issues: 

```
$ helm list
Error: configmaps is forbidden: User "system:serviceaccount:kube-system:default" cannot list configmaps in the namespace "kube-system": Unknown user "system:serviceaccount:kube-system:default"
```
Then when I try to install any chart I get the following: 

```
$ helm install stable/wordpress --name wordpress 
Error: release wordpress failed: namespaces "default" is forbidden: User "system:serviceaccount:kube-system:default" cannot get namespaces in the namespace "default": Unknown user "system:serviceaccount:kube-system:default"

$ helm install stable/docker-registry --name docker-registry
Error: release docker-registry failed: namespaces "default" is forbidden: User "system:serviceaccount:kube-system:default" cannot get namespaces in the namespace "default": Unknown user "system:serviceaccount:kube-system:default"

$ helm install stable/concourse --name concourse
Error: release concourse failed: namespaces "default" is forbidden: User "system:serviceaccount:kube-system:default" cannot get namespaces in the namespace "default": Unknown user "system:serviceaccount:kube-system:default"
```
I'm using the following versions: 

* k8s: 1.7.12-gke.1, 1.8.7-gke.1 and 1.9.3-gke.0
* helm: 2.8.1 & 2.8.2
* tiller: 2.8.1 & 2.8.2

I've tried removing my `$HOME/.helm/` directory, creating a new cluster, reinstalling tiller several times but none worked.

### PR DESCRIPTION
**Pull request by bacongobbler**
closes #3664 

Note that this is basically a re-iteration of the admonition above, so if there's a way we can consolidate those admonitions, any feedback would be appreciated!

### CODE REVIEW

**Comment by bacongobbler** [comment]
LGTM

**Comment by bacongobbler** [comment]
I just had an idea: what if we linked to the [kubernetes distribution guide](https://github.com/kubernetes/helm/blob/master/docs/kubernetes_distros.md) instead, and then from there we noted that GKE has RBAC enabled by default?

The end result would be

IMPORTANT: See [the Kubernetes Distribution Guide](https://github.com/kubernetes/helm/blob/master/docs/kubernetes_distros.md) for any specific setup steps required.

IMPORTANT: If you are using a multi-tenant cluster where resources are shared, it is strongly recommended installing Tiller using a secured configuration. For guidance, see [Securing your Helm Installation](https://github.com/kubernetes/helm/blob/master/docs/securing_installation.md).

And then under GKE:

Google Kubernetes Engine enables Role-Based Access Control by default. For guidance, see [the Role Based Access Control Guide](https://github.com/kubernetes/helm/blob/master/docs/rbac.md).

**Comment by bacongobbler** [comment]
I kinda want to incorporate that guide in the docs so we can keep that up to date

**Comment by bacongobbler** [comment]
I think what I'l do is just update the distro guide with that RBAC note and put your suggestion in as well. Just so we have our bases covered.

**Comment by thomastaylor312** [comment]
Ok, let me know when you'd like me to review

**Comment by thomastaylor312** [comment]
@bacongobbler Did you still want to add this?

**Comment by bacongobbler** [comment]
yes for sure! I'll make it a TODO for tomorrow. Thanks for the ping.

/remove-lifecycle rotten

**Comment by bacongobbler** [comment]
this has been noted in the GKE distro notes, so we can close this.

**Pull request closed without merging**
