### PR TITLE
Increase timeout for operations per second

### PR DESCRIPTION
**Pull request by LucasSaldanha21**
**What this PR does / why we need it**:

**Special notes for your reviewer**:

**If applicable**:
- [ ] this PR contains documentation
- [ ] this PR contains unit tests
- [ ] this PR has been tested for backwards compatibility

### CODE REVIEW

**Comment by yxxhero** [comment]
@BlazeF35 maybe we can make it configurable. CLI flag or other methods.

**Comment by BlazeF35** [comment]
yes, it would be very helpful

**Comment by yxxhero** [comment]
@BlazeF35 I think so. I don't like fixed value.

**Comment by felipecrs** [comment]
BTW I did some tests recently with this PR (which is based on https://github.com/felipecrs/helm/pull/2), and I could no longer find a situation in which it helped.

In fact, I don't even remember why I did it (but probably it was an attempt to solve https://github.com/helm/helm/issues/9761), and I don't even trust myself that it provided any help back then.

My advice would be to close it indeed, unless we find a way to reproduce a situation in which increasing these timeouts actually improves something.

**Pull request closed without merging**
