### PR TITLE
Handle resource apiVersion upgrades

### PR DESCRIPTION
**Pull request by jlegrone**
Related to https://github.com/helm/helm/issues/6850, and an alternative implementation to https://github.com/helm/helm/pull/7575.

### Steps to Reproduce

Create a chart with

```yaml
apiVersion: apps/v1beta2
kind: Deployment
```

Deploy a release of that chart, then switch to apps/v1:

```diff
- apiVersion: apps/v1beta2
+ apiVersion: apps/v1
kind: Deployment
```

Run `upgrade`, and you should get the following error before this patch:

```
rendered manifests contain a new resource that already exists. Unable to continue with update: existing resource conflict: namespace: default, name: version-migrate-test, existing_kind: apps/v1, Kind=Deployment, new_kind: apps/v1, Kind=Deployment
```

### CODE REVIEW

**Comment by bacongobbler** [comment]
thanks @jlegrone! Will give this a spin later this afternoon.

**Comment by bacongobbler** [comment]
First off: this is MUCH cleaner of an implementation. Thank you.

Here's what I tested:

1. I installed a sample chart with a Deployment using the `extensions/v1beta1` API
  - upgrade without changing the apiVersion - :heavy_check_mark: 
  - switch template to use the `apps/v1` API and upgrade - :heavy_check_mark: 

2. I installed a sample chart with a Deployment using the `apps/v1` API
  - upgrade without changing the apiVersion - :heavy_check_mark: 

3. install a sample chart with a Deployment that already exists in the cluster

In case 3, I found an issue with this PR's behaviour.

Helm 3.1.0:

```
><> helm template wordpress wordpress/ --show-only templates/deployment.yaml | kubectl apply -f -
deployment.apps/wordpress configured
><> helm install wordpress wordpress/
Error: rendered manifests contain a resource that already exists. Unable to continue with install: existing resource conflict: namespace: default, name: wordpress, existing_kind: apps/v1, Kind=Deployment, new_kind: apps/v1, Kind=Deployment
><> helm list
NAME	NAMESPACE	REVISION	UPDATED	STATUS	CHART	APP VERSION
```

`existingResourceConflict` returns an error, preventing the release from being created.

With this PR:

```
><> ~/bin/helm version
version.BuildInfo{Version:"v3.1+unreleased", GitCommit:"d8bff5fdbd57234ad8a78c91a6688d3ff41a0cd4", GitTreeState:"clean", GoVersion:"go1.13.8"}
><> ~/bin/helm install wordpress ./wordpress/
Error: deployments.apps "wordpress" already exists
><> ~/bin/helm list
NAME     	NAMESPACE	REVISION	UPDATED                               	STATUS	CHART          	APP VERSION
wordpress	default  	1       	2020-02-18 15:32:56.23260213 -0800 PST	failed	wordpress-7.5.4	5.2.4
```

A failed pre-flight check should not deploy a release in a failed state. Would you mind looking further into this?

**Comment by hickeyma** [comment]
Thanks @jlegrone for this PR.  It seems like a clean way to handle the API deprecation issue.

I did some testing similar to @bacongobbler but unfortunately didn't have the same success.  My angle of testing is from the #7219 view point.

I tested as follows:

1. Installed scaffold chart in k8s 1.15 cluster (using helm from master branch) with following apiVersion:

``` ---
# Source: chrt-7625/templates/deployment.yaml
apiVersion: extensions/v1beta1
```

```console
$ helm ls
NAME         	NAMESPACE	REVISION	UPDATED                                	STATUS  	CHART             	APP VERSION
chrt-7625    	default  	1       	2020-02-19 14:51:41.390839657 +0000 UTC	deployed	chrt-7625-0.1.0   	1.0       
```

2. Upgraded the cluster to 1.16 including the worker node

3. Built Helm binary with this PR changes 

4. Tried but failed to upgrade the release `chrt-7625 ` as follows:
- `apiVersion: extensions/v1beta1`- ***FAILED***
- `apiVersion: apps/v1` - ***FAILED***

```console
$ helm upgrade chrt-7625 chrt-7625/
Error: UPGRADE FAILED: unable to build kubernetes objects from current release manifest: unable to recognize "": no matches for kind "Deployment" in version "extensions/v1beta1"
```

5. Succeeded in new install of chart `chrt-7625` with `apiVersion: apps/v1` in deployment

**Comment by bacongobbler** [comment]
@hickeyma are you testing with an older version of Kubernetes? I had to test this PR with a 1.14.10 cluster using `minikube start --kubernetes-version v1.14.10`.

**Comment by hickeyma** [comment]
Talking to @bacongobbler on Slack confirms that my testing is more concerned with the upgrading the cluster which automatically updates the resources APIs (to the latest version) in the cluster, which are then at odds with the API versions in the Helm release metadata. This is the issue #7219 .

**Comment by jlegrone** [comment]
Still working on this, unfortunately it's more involved than it appeared at first glance.

**Comment by jlegrone** [comment]
Superseded by https://github.com/helm/helm/pull/7649

**Pull request closed without merging**
