### PR TITLE
make get script sudo optional

### PR DESCRIPTION
**Pull request by rimusz**
Signed-off-by: rimas <rmocius@gmail.com>

### CODE REVIEW

**Comment by bacongobbler** [comment]
This was implemented in https://github.com/helm/helm/pull/4649. You can use the `--no-sudo` flag to disable the use of `sudo`. Or is there something else that I'm missing here?

**Comment by rimusz** [comment]
another option using the env var `USE_SUDO`

**Comment by mattfarina** [comment]
@rimusz Are you asking that the choice to use sudo or not be exposed as an environment variable in addition to a flag? Is that what this PR is intended to solve?

**Review by bacongobbler — APPROVED** [review]
`--use-sudo` will take preference in case both `$USE_SUDO` and `--use-sudo` are set, so I'm OK with this. LGTM

**Pull request merged**
