### PR TITLE
--registry-config flag is not honored

### PR DESCRIPTION
**Pull request by EItanya**
Fix for https://github.com/helm/helm/issues/7351

### CODE REVIEW

**Review by bacongobbler — CHANGES_REQUESTED** [review]
some small changes needed but looks good!

**Comment by jdolitsky** [comment]
LGTM given Matt's comments addressed

**Comment by EItanya** [comment]
@bacongobbler addressed your comments, merging with master seemed to do the trick

**Review by jdolitsky — APPROVED** [review]

**Comment by jdolitsky** [comment]
@EItanya thanks for your patience w/ this, would you mind rebasing to resolve the conflicts?

**Review by bacongobbler — APPROVED** [review]

**Pull request merged**
