### PR TITLE
First alias would be dependency rename

### PR DESCRIPTION
**Pull request by sushilkm**
Fixes https://github.com/kubernetes/helm/issues/2508

### CODE REVIEW

**Comment by technosophos** [comment]
This looks good to me. I'll give @thomastaylor312 the final word, though.

**Comment by sushilkm** [comment]
@thomastaylor312 I would suggest to get this in and then i can keep working on fixing as per new `requirements.yaml` as i have already started on same, but it seems it would take some time to get that in 👍

**Comment by sushilkm** [comment]
@thomastaylor312  nevermind, I was able to update the PR with the new `requirements.yaml` structure referred in https://github.com/kubernetes/helm/issues/2508 so its up for review now 👍

**Comment by thomastaylor312** [comment]
@sushilkm Thanks for doing that. I won't have time tonight, but I'll try to get this reviewed by tomorrow night

**Review by thomastaylor312 — APPROVED** [review]
Code looks good and manual testing was good. Thank you for the extra effort to switch up how aliases were defined in the requirements file!

**Pull request merged**
