### PR TITLE
more friendly error message when missing values.yaml

### LINKED ISSUE #7222: Helm3 warning in case of missing values.yaml
**Problem**

It's mostly my own stupidity, but maybe it can help the future users of helm. So I renamed my `values.yaml` to `values-old.yaml`, and I created a value.yaml. Then I run `helm template .` and it's throw me issues it can't find the .Values.xxx however I double check the variable many times and they must correct. As a new helm user I thought something with my layout of the value.yaml. Than I read there is a command `helm lint .` and this told me there isn't `values.yaml` at all.

**Solution**
It make sense to me adding a warning in that case, something like _Anyway we are lack of values.yaml_. 

Output of `helm version`:
```
version.BuildInfo{Version:"v3.0.1", GitCommit:"7c22ef9ce89e0ebeb7125ba2ebf7d421f3e82ffa", GitTreeState:"clean", GoVersion:"go1.13.4"}
```

Output of `kubectl version`: **not related**
```
Client Version: version.Info{Major:"1", Minor:"15", GitVersion:"v1.15.3", GitCommit:"2d3c76f9091b6bec110a5e63777c332469e0cba2", GitTreeState:"clean", BuildDate:"2019-08-19T11:13:54Z", GoVersion:"go1.12.9", Compiler:"gc", Platform:"linux/amd64"}
```

Cloud Provider/Platform (AKS, GKE, Minikube etc.): **not related**

### PR DESCRIPTION
**Pull request by zwwhdls**
fix #7222

When missing values.yaml and no "--set" input, make the error message more friendly.

### CODE REVIEW

**Comment by PumpkinSeed** [comment]
I prefer to not to use reflection package. In that case you check the length of the array. Reflection is always a heavy operation.

**Comment by zwwhdls** [comment]
@PumpkinSeed You are right, I have changed this. Thank you.

**Comment by bacongobbler** [comment]
can you please write a test for this?

**Comment by zwwhdls** [comment]
Hi @bacongobbler ,

Sorry for late conflict fix. I have fetched forked registry and fixed the conflict until now.

**Comment by bacongobbler** [comment]
`helm lint` already captures this case.

```
><> helm lint test-7234/
==> Linting test-7234/
[INFO] Chart.yaml: icon is recommended
[INFO] values.yaml: file does not exist
```

The values file is optional, which is why this error message is not displayed. There are valid use cases out there where the values.yaml file is not necessary, and displaying an "error message" is misleading in those cases.

`helm lint` captures this case, and that's intentional. So we are not going to accept this. Thank you for your submission.

**Pull request closed without merging**
