### PR TITLE
Load StorageClass before PersistentVolume is loaded.

### PR DESCRIPTION
**Pull request by nauxliu**
Load StorageClass before PersistentVolume and PersistentVolumeClaim are loaded.

### CODE REVIEW

**Comment by redbaron** [comment]
We've been bitten by it too, can someone please have a look?

**Comment by thomastaylor312** [comment]
We don't currently have a minor version patch incoming, but this will probably deserve it. I'll bring it up in the developer meeting tomorrow

**Review by thomastaylor312 — APPROVED** [review]
This should be good to go. I will come back and tag this appropriately if we decide to cut a bugfix release. Thank you for catching this!

**Comment by seh** [comment]
@NauxLiu, please add a unit test case to cover this new kind in a follow-on PR.
See [file _pkg/tiller/kind_sorter_test.go_](https://github.com/kubernetes/helm/blob/master/pkg/tiller/kind_sorter_test.go) for the existing test into which you can add a new table entry to cover both the installation and uninstallation order.

**Comment by thomastaylor312** [comment]
@NauxLiu I will go back and add tests because it was my mistake to not catch that

**Pull request merged**
