### PR TITLE
fix(helm): resolve relative chart paths

### LINKED ISSUE #3168: Installing charts with --repo option from a repo with relative paths fails
I have a repository index with relative paths:
```
  spark:
  - apiVersion: v1
    created: 2017-11-20T08:24:41.035796831Z
    description: A Helm chart for Kubernetes
    digest: 7d9c80037b56ef684dd0805d0c1f9a7ac36139a8aa331035844e82a7c229e3a1
    name: spark
    urls:
    - spark-0.1.1.tgz
    version: 0.1.1
```

When I run `helm install spark --repo http://my-helm-repo` I get 
```
Error: Non-absolute URLs should be in form of repo_name/path_to_chart, got: spark-0.1.1.tgz
``` 

I expected that the chart would be resolved relative to the repo url, but they apparently it did not.

Tested with helm 2.6.2, 2.7.0 and 2.7.2.

### PR DESCRIPTION
**Pull request by hoesler**
resolves #3168

### CODE REVIEW

**Comment by hoesler** [comment]
I'm not sure if the updated docs should be part of this PR, but I found that the `--repo` install option is missing.

Furthermore, I'm find it challenging to write a test case for this fix. Maybe someone can guide me, as I'm new to the helm code and Go. All test cases in `TestInstall` don't use a server backend, as I understand the code. But if I reuse the test server from `TestFetchCmd`:
 - will the fake client really use it?
 - can I easily modify the test server to serve relative URL's?

**Review by technosophos — APPROVED** [review]
Yes, this is the right fix. Thank you.

**Comment by technosophos** [comment]
Updating the docs is good.

For testing, I think I would suggest extracting that bit of logic you wrote into a function, and then just writing a simple test that asserts that the newly rewritten URL matches what you were expecting. Anything more is probably too elaborate.

**Comment by hoesler** [comment]
Thanks for your comments. I turned the URL resolution logic into a function, as you suggested. Furthermore, I decided to apply it already in `FindChartInRepoURL`. That way, other commands, like fetch, can benefit from this fix as well.

**Review by bacongobbler — APPROVED** [review]

**Comment by bacongobbler** [comment]
Thanks!

**Pull request merged**
