### PR TITLE
docs(helm): change `trunc 24` in base charts

### LINKED ISSUE #1637: Change `trunc 24` in all base charts
Since Kube 1.4, the upper limit for a chart name is now 54 characters instead of 14 or 24.

There are several example charts in the code that use 24 or 14 (e.g. `trunc 14` in the code). Those need to be updated.

### PR DESCRIPTION
**Pull request by wilkers-steve**
The upper limit for a chart name is now 54 characters, instead of
14 or 24 in older versions of Kubernetes. This replaces `trunc 24`
in the example chart provided to `trunc 54` to reflect the new
length available.

Closes #1637

### CODE REVIEW

**Comment by prydonius** [comment]
According to https://github.com/kubernetes/kubernetes/pull/29523, the limit is actually 63 chars. Can you confirm, @wilkers-steve?

**Comment by wilkers-steve** [comment]
@prydonius after looking, it does look like 63 is indeed the limit.  I'll let @technosophos chime in before changing it since he filed the issue.  63 is also referenced in a change on the Tiller side regarding resource names it seems, found here: https://github.com/technosophos/k8s-helm/commit/9effe7a50569edadb542b9a6f3c6bc6cb3a4effb

**Comment by technosophos** [comment]
I thought we were reserving several characters for a suffix (`-` plus 8).

**Comment by prydonius** [comment]
@technosophos oh right, now I see where that comes from! I think the 54 char limit is important for the release name, but the chart templates are truncating the whole `{{Release.Name}}-{{Chart.Name}}` so the limit here should be 63.

**Comment by technosophos** [comment]
Okay. @wilkers-steve if you wanna do a quick update, I'll merge when it's ready.

Adding this to the 2.1.3 milestone

**Comment by wilkers-steve** [comment]
@technosophos done :)

**Comment by prydonius** [comment]
This LGTM, thanks @wilkers-steve!

**Comment by technosophos** [comment]
Thanks!

**Comment by technosophos** [comment]
Backported for 2.1.3

**Pull request merged**
