### PR TITLE
Fix repo url decoding

### LINKED ISSUE #6048: helm should not urldecode urls
helm --debug repo add t7 "http://localhost/some%2Fpath/test"
Error: Looks like "http://localhost/some%2Fpath/test" is not a valid chart repository or cannot be reached: Failed to fetch http://localhost/some/path/test/index.yaml : 404 Not Found

notice how  "some%2Fpath" gets translated into "some/path"

This is not expected. It is expected that helm leaves the url alone and that "some%2Fpath" gets transferred to the server.

Output of `helm version`:
Client: &version.Version{SemVer:"v2.11.0", GitCommit:"2e55dbe1fdb5fdb96b75ff144a339489417b146b", GitTreeState:"clean"}
Server: &version.Version{SemVer:"v2.11.0", GitCommit:"2e55dbe1fdb5fdb96b75ff144a339489417b146b", GitTreeState:"clean"}

### PR DESCRIPTION
**Pull request by karuppiah7890**
**What this PR does / why we need it**:
Fixes #6048 

**Special notes for your reviewer**:
To test better - I added mocks, and a memory based filesystem so that nothing gets written to the actual file system

**If applicable**:
- [ ] this PR contains documentation
- [x] this PR contains unit tests
- [ ] this PR has been tested for backwards compatibility

### CODE REVIEW

**Comment by karuppiah7890** [comment]
Once this is merged, I will try to port the same logic into `release-2.14` and `dev-v3` branches

**Comment by bacongobbler** [comment]
> pkg/urlutil/urlutil_test.go:1::warning: file is not gofmted with -s (gofmt)

**Comment by bacongobbler** [comment]
@karuppiah7890 generally speaking we only cut patch releases for the latest (in this case, 2.14.x). We don’t usually cut patch releases for older revisions. We also don’t cherry-pick commits into the release branch until we’re ready to cut a patch. Given this is a low severity issue that didn’t previously work, we probably won’t cut a patch release with this fix. I don’t believe this was a regression in older behaviour, just an enhancement that fixes odd behaviour.

Would you mind re-opening this against master instead? We can cherry-pick this in should we decide to do a 2.14 patch release. Thanks!

**Comment by karuppiah7890** [comment]
Sure, I'll raise it against master. Also, it's weird that the fmt error occurred, in local it occured and I fixed it in one of the commits if you see the list of commits. Anyways, let me raise with master and see if it's still a thing

**Comment by karuppiah7890** [comment]
Closing this as I'm going to raise a PR against master^

**Comment by karuppiah7890** [comment]
The new PR is here - #6060

**Pull request closed without merging**
