### PR TITLE
Parse reference templates in predictable order

### PR DESCRIPTION
**Pull request by asenci**
Fix issue #7701

### CODE REVIEW

**Comment by jdolitsky** [comment]
@asenci this change looks generally straightforward. Could we just add a test to pkg/engine/engine_test.go to ensure this bug doesnt get re-introduced?

**Review by jdolitsky — CHANGES_REQUESTED** [review]
see comment above

**Comment by asenci** [comment]
> see comment above

Hope this is ok, not sure how to reliably reproduce the issue due to the randomness in the map iteration, so I am repeating the test 100 times hopping to hit the wrong order at least once.

It's not pretty, but from my observations 100 iterations should be more than enough to guarantee at least one hit, and shouldn't slow down the tests too much.

**Review by jdolitsky — APPROVED** [review]
👍

**Review by technosophos — APPROVED** [review]
LGTM

**Pull request merged**
