### PR TITLE
Update to latest sprig

### PR DESCRIPTION
**Pull request by binoculars**
Just want to use some newer functions in the latest sprig

/cc @technosophos

### CODE REVIEW

**Comment by jascott1** [comment]
@binoculars Im not sure we want to use an arbitrary commit point from spring master. AFAIK we have been using official releases.

**Comment by binoculars** [comment]
In that case, I would definitely appreciate someone with write access to the sprig repo cutting a release.

Other deps are pinned to SHAs, so I figured that it didn't matter much. Either way, the goal is to get the new/updated functions in helm.

**Comment by bacongobbler** [comment]
I'll see what I can do.

**Comment by mattfarina** [comment]
@binoculars I just cut a sprig release. New version is [v2.13.0](https://github.com/Masterminds/sprig/releases/tag/v2.13.0). Can you update to that?

**Comment by binoculars** [comment]
@mattfarina thanks so much. Got the test passing now. `glide up` was bumping the kube version to a beta and was causing build errors. Should be g2g now.

**Comment by binoculars** [comment]
Resolves #2902

**Comment by binoculars** [comment]
Anything else I should do to get this merged?

**Review by bacongobbler — APPROVED** [review]

**Pull request merged**
