### PR TITLE
ADD support for updating TILLER_HISTORY_MAX when upgrading

### PR DESCRIPTION
**Pull request by mattclegg**
> When doing a helm init --max-history=N --upgrade --debug, the returned deployment manifest shows TILLER_HISTORY_MAX env var set on the deployment with the correct value.
> But when doing a kubectl log <tiller_pod>, it shows Max history per release is 0. Doing a describe on the deployment also shows that the TILLER_HISTORY_MAX is missing.

### CODE REVIEW

**Comment by mattclegg** [comment]
a new comment

**Comment by bacongobbler** [comment]
The code here looks *very* frail and I'm afraid of introducing new bugs. Would you mind adding some unit tests around `updateEnv`?

**Comment by gmanolache** [comment]
+1

**Comment by jmlrt** [comment]
👍

**Comment by davidchua** [comment]
Hi guys,

I've taken the liberty to try working on the tests but I'm not sure how to send a PR to a PR and I'm not sure how to move this forward. Any comments/help will be appreciated.

https://github.com/davidchua/helm/commit/af316d34ff0fed9f59301766e0f44fc8d4b3babb

cc @mattclegg

**Comment by mleneveut** [comment]
@bacongobbler can we merge this as there is some unit tests now ?

**Comment by gramidt** [comment]
LGTM!

**Comment by bacongobbler** [comment]
those unit tests have not been merged into this PR. If someone wants to incorporate those changes @davidchua suggested and re-open a new PR, we can take a look into it.

**Comment by gramidt** [comment]
@bacongobbler I'll incorporate those changes and re-open a new PR as recommended. Thank you for all of your help!

**Comment by rossf7** [comment]
I've opened a new PR #5867 as suggested here. I checked in #helm-dev that this made sense. Thx! @bacongobbler

**Pull request closed without merging**
