### PR TITLE
Avoid downloading the same chart multiple times

### PR DESCRIPTION
**Pull request by Antiarchitect**
Actually one of my charts problem. I have 16 separate gitlab-runner charts inside my big one (don't ask) and it is very slow and annoying when Helm downloads the same chart 16 times on update

Before:
```
Update Complete. ⎈Happy Helming!⎈
Saving 16 charts
Downloading gitlab-runner from repo https://charts.gitlab.io
Downloading gitlab-runner from repo https://charts.gitlab.io
Downloading gitlab-runner from repo https://charts.gitlab.io
Downloading gitlab-runner from repo https://charts.gitlab.io
Downloading gitlab-runner from repo https://charts.gitlab.io
Downloading gitlab-runner from repo https://charts.gitlab.io
Downloading gitlab-runner from repo https://charts.gitlab.io
Downloading gitlab-runner from repo https://charts.gitlab.io
Downloading gitlab-runner from repo https://charts.gitlab.io
Downloading gitlab-runner from repo https://charts.gitlab.io
Downloading gitlab-runner from repo https://charts.gitlab.io
Downloading gitlab-runner from repo https://charts.gitlab.io
^C
```

After:
```
Update Complete. ⎈Happy Helming!⎈
Saving 16 charts
Downloading gitlab-runner from repo https://charts.gitlab.io
Already downloaded gitlab-runner from repo https://charts.gitlab.io
Already downloaded gitlab-runner from repo https://charts.gitlab.io
Already downloaded gitlab-runner from repo https://charts.gitlab.io
Already downloaded gitlab-runner from repo https://charts.gitlab.io
Already downloaded gitlab-runner from repo https://charts.gitlab.io
Already downloaded gitlab-runner from repo https://charts.gitlab.io
Already downloaded gitlab-runner from repo https://charts.gitlab.io
Already downloaded gitlab-runner from repo https://charts.gitlab.io
Already downloaded gitlab-runner from repo https://charts.gitlab.io
Already downloaded gitlab-runner from repo https://charts.gitlab.io
Already downloaded gitlab-runner from repo https://charts.gitlab.io
Already downloaded gitlab-runner from repo https://charts.gitlab.io
Already downloaded gitlab-runner from repo https://charts.gitlab.io
Already downloaded gitlab-runner from repo https://charts.gitlab.io
Already downloaded gitlab-runner from repo https://charts.gitlab.io
Deleting outdated charts
```

P.S. I'm very bad at Golang (working with it second time in my life) so any fixes and optimizations are welcomed!

### CODE REVIEW

**Comment by technosophos** [comment]
The auto-labeler did not fire for this issue. Manually labeling.

**Review by technosophos — APPROVED** [review]
LGTM

**Comment by technosophos** [comment]
I believe this just needs a second LGTM, and we can merge.

**Review by hickeyma — APPROVED** [review]
LGTM, thanks @Antiarchitect

**Pull request merged**
