### PR TITLE
Add --hide-values flag

### PR DESCRIPTION
**Pull request by codersasha**
**What this PR does / why we need it**:

There is a need to run `helm install`/`helm upgrade` commands in Debug mode without leaking secrets (see #7275). This PR fixes that in a more general way by adding a `--hide-values` flag, which, when combined with `--debug`, prints relevant debugging information (such as why a helm upgrade command failed) but does not display the values or manifest file, removing the risk of leaking secret config and sensitive manifest contents.

This PR was partially inspired by the feedback on #9130.

**Special notes for your reviewer**:

I haven't signed my commit, as per the contribution guidelines -- still figuring out how to do that 😅 -- but very happy for someone to take over this PR and rewrite it as they see fit. This is a very important PR for our organisation and, without it, we have no way of easily debugging our `helm install` deploy commands on CI. We cannot run with `--debug` and risk leaking secrets and other sensitive manifest values, so we need a flag like this to skip displaying the values entirely.

**If applicable**:
- [X] this PR contains documentation
- [X] this PR contains unit tests
- [X] this PR has been tested for backwards compatibility

### CODE REVIEW

**Comment by sashamor** [comment]
Yeah, that makes sense. I had similar concerns when writing this PR.

What do you think of, `--debug=VERBOSE` (the default `--debug`) and `--debug=QUIET` (the equivalent of `--hide-values`).

**Comment by sashamor** [comment]
Closing as we found another solution - this is a `sed` command that deletes everything from `USER-SUPPLIED VALUES:` down:

```bash
helm install --debug ... | sed '/USER-SUPPLIED VALUES:/,$d'
```

We now use this in our deploys, so we can debug when a deploy fails, but not print any secrets/configuration that may reveal sensitive data.

**Comment by wirwolf** [comment]
But its сrutches...

**Comment by wirwolf** [comment]
@codersasha But its сrutches...

**Pull request closed without merging**
