### PR TITLE
Proposed: Add Vagrantfile for build

### PR DESCRIPTION
**Pull request by sebgoa**
While trying to understand the build I wrote this Vagrantfile.

Might be useful

Tested with:

```
$ vagrant up
$ vagrant ssh
```

In the VM:

```
$ cd src/github.com/kubernetes/deployment-manager
$ make bootstrap
$ make build
```

### CODE REVIEW

**Comment by jackgr** [comment]
Might be worth putting it in a folder, so that folks don't think it's required. I suppose they'd know that if they read the README, but given that it's not required, seems cleaner to move it down a level. What do you think?

**Comment by technosophos** [comment]
Some documentation on what this is for would be good. I was expecting it to start a DM cluster inside of Kubernetes. But it looks like it's actually just a VM with the source code mounted into it. I'm not really sure what to do with it.

I think we could add it to `hack/` if it's primarily for builds or developers.

**Comment by runseb** [comment]
@jackgr @technosophos putting it in hack is fine.

It's indeed just a build machine. I like to make sure I can reproduce environment and not make any local setup assumptions.

**Comment by jackgr** [comment]
@runseb please address the comments and resubmit.

**Comment by runseb** [comment]
@jackgr how about I put a small README in `/hack` and write some small instructions there.
It might be confusing to put it in the main README.

**Comment by jackgr** [comment]
Fine. I think the key is to put the Vagrantfile in hack, which it isn't in
this PR.

Jack Greenfield | Google

**Comment by runseb** [comment]
@jackgr yes it is, I just forced pushed on the PR..so there is a README and the vagrant file under /hack

**Comment by jackgr** [comment]
I see. thanks.

Jack Greenfield | Google

**Pull request merged**
