### PR TITLE
update dependency gopkg.in/yaml.v2 to v2.3.0 from v2.2.8

### LINKED ISSUE #7704: "Unexpected unclosed action in template clause" when trying to render templated string from values.yaml
Many charts currently support Prometheus Operator by optionally adding "prometheusRule" objects to the cluster. A user can then just add the rules in his "values.yaml". The supplied values can be templated strings and will be used by a "prometheusrule.yaml" template. This works for simple rules, but in most cases the chart will just refuse to render properly. The funny thing is, that even the example alerts that can be found in the values.yaml files of many charts are not working. 

I don't know where the problem exactly is, but it looks like something is trying to pretty print the values by inserting a "\n" at a position where it should not be and this breaks the template in most cases (see `"{{ template \"test.fullname\"\n    . }}` in the complete error message below). I already tried all kinds of workarounds like removing whitespaces, playing with single and double quotes, yaml multiline ... nothing seems to work.

values.yaml:
```
prometheusRule:
  enabled: true
  additionalLabels: {}
  namespace: "monitoring"
  rules:
    - alert: MyTestAlert
      expr: my_test_alert_with_a_long_name_kjlgnkjfdg{service="{{ template "test.fullname" . }}-mymetricsservice"} / 3600 > 1
      for: 1m
      labels:
        severity: critical
      annotations:
        description: |-
          The {{ template "test.fullname" . }} has a problem. The value is {{ "{{ $value }}" }}
        summary: Something {{ "{{ $value }}" }}
```

prometheusrule.yaml:
```
{{- if .Values.prometheusRule.enabled }}
apiVersion: monitoring.coreos.com/v1
kind: PrometheusRule
metadata:
  name: {{ template "test.fullname" . }}
{{- with .Values.prometheusRule.namespace }}
  namespace: {{ . }}
{{- end }}
  labels:
    app: {{ template "test.name" . }}
    chart: {{ template "test.chart" . }}
    release: {{ .Release.Name | quote }}
    heritage: {{ .Release.Service | quote }}
{{- with .Values.prometheusRule.additionalLabels }}
{{ toYaml . | indent 4 }}
{{- end }}
spec:
{{- with .Values.prometheusRule.rules }}
  groups:
    - name: {{ template "test.name" $ }}
      rules: {{ tpl (toYaml .) $ | nindent 8 }}
{{- end }}
{{- end }}
```

Output of `helm template .`:
```console
Error: template: test/templates/prometheusrule.yaml:21:16: executing "test/templates/prometheusrule.yaml" at <tpl (toYaml .) $>: error calling tpl: error during tpl function execution for "- alert: MyTestAlert\n  annotations:\n    description: The {{ template \"test.fullname\" . }} has a problem. The value is\n      {{ \"{{ $value }}\" }}\n    summary: Something {{ \"{{ $value }}\" }}\n  expr: my_test_alert_with_a_long_name_kjlgnkjfdg{service=\"{{ template \"test.fullname\"\n    . }}-mymetricsservice\"} / 3600 > 1\n  for: 1m\n  labels:\n    severity: critical": parse error at (test/templates/prometheusrule.yaml:6): unexpected unclosed action in template clause
```

Output of `helm version`:
```console
version.BuildInfo{Version:"v3.1.1",` GitCommit:"afe70585407b420d0097d07b21c47dc511525ac8", GitTreeState:"clean", GoVersion:"go1.13.8"}
```
```console
Client: &version.Version{SemVer:"v2.14.1", GitCommit:"5270352a09c7e8b6e8c9593002a73535276507c0", GitTreeState:"clean"}
Server: &version.Version{SemVer:"v2.14.1", GitCommit:"5270352a09c7e8b6e8c9593002a73535276507c0", GitTreeState:"clean"}
```

### LINKED ISSUE #8789: Incorrect behavior of toYaml function
Output of `helm version`: 
`version.BuildInfo{Version:"v3.3.1", GitCommit:"249e5215cde0c3fa72e27eb7a30e8d55c9696144", GitTreeState:"clean", GoVersion:"go1.14.7"}`

Output of `kubectl version`:
```
Client Version: version.Info{Major:"1", Minor:"17+", GitVersion:"v1.17.9-eks-4c6976", GitCommit:"4c6976793196d70bc5cd29d56ce5440c9473648e", GitTreeState:"clean", BuildDate:"2020-07-17T19:00:19Z", GoVersion:"go1.13.9", Compiler:"gc", Platform:"linux/amd64"}
Server Version: version.Info{Major:"1", Minor:"17+", GitVersion:"v1.17.9-eks-4c6976", GitCommit:"4c6976793196d70bc5cd29d56ce5440c9473648e", GitTreeState:"clean", BuildDate:"2020-07-17T18:46:04Z", GoVersion:"go1.13.9", Compiler:"gc", Platform:"linux/amd64"}
```

Cloud Provider/Platform (AKS, GKE, Minikube etc.):  EKS

Hi,

I've ran into a problem with toYaml function.

Content on values.yaml:

```yaml
application.yaml:
  logging:
    pattern.console: "%date{ISO8601} %-5level [%thread] %mdc{workflowId:--} %logger{36} : %msg%n%ex"
```

Content of `templates/configmap.yaml':

```yaml
apiVersion: v1
kind: ConfigMap
metadata:
  name: test-configuration
data:
  application.yaml: |
    {{- toYaml (index .Values "application.yaml") | nindent 4 -}}
```

Helm command:
```
helm template attributor .
````

Actual output (incorrect pattern.console:):
```yaml
---
# Source: attributor/templates/configmap.yaml
apiVersion: v1
kind: ConfigMap
metadata:
  name: test-configuration
data:
  application.yaml: |
    logging:
      pattern.console: '%date{ISO8601} %-5level [%thread] %mdc{workflowId:--} %logger{36}
        : %msg%n%ex'
```

Expected output:
```yaml
---
# Source: attributor/templates/configmap.yaml
apiVersion: v1
kind: ConfigMap
metadata:
  name: test-configuration
data:
  application.yaml: |
    logging:
      pattern.console: '%date{ISO8601} %-5level [%thread] %mdc{workflowId:--} %logger{36} : %msg%n%ex'
```

### PR DESCRIPTION
**Pull request by laverya**
**What this PR does / why we need it**:

This fixes https://github.com/helm/helm/issues/8789 and fixes https://github.com/helm/helm/issues/7704 by changing the yaml marshalling behavior to not wrap lines in strings unless the string contains a newline.

**Special notes for your reviewer**:

**If applicable**:
- [x] this PR contains unit tests

### CODE REVIEW

**Comment by laverya** [comment]
Adding a unit test to exercise this before I actually put this up for review

**Comment by marckhouzam** [comment]
This impact of this upgrade were first detected by https://github.com/kubernetes/kubernetes/pull/95571

**Comment by mattfarina** [comment]
I think we should hold off on this for a bit. The reason being that this one package is by Kubernetes to handle things internally as well as by Helm when dealing with manifests and templates. There could be unintended side effects. We need to be very careful with this one.

**Comment by laverya** [comment]
While I can understand doing that @mattfarina, I don't think this change has the potential to break anything more than tests (and those tests are in grave danger already, as demonstrated by the cobra upgrade)

(but I don't think this is critical, either)

**Comment by mattfarina** [comment]
@laverya This isn't just a tests problem.

First, I want longer lines in YAML and I do not like the wrapping at 80 characters. If I could wave a magic wand, this is what I would want.

The problem is that software like Kubernetes and Helm are used to run high impact widely used software that businesses rely on. You don't want to make a change that accidentally takes causes an application to crash that many people use or that is a high impact to a companies bottom line. Software like this needs to move slow and not break things. It's boring infrastructure (like roads and bridges) that you want to work well.

This change has the potential to affect running software. The Kubernetes tests failing tell us that something is changing. I've helped people code around the 80 character limit knowing it's there.

The approach is conservative due to safety.

**Comment by laverya** [comment]
Makes sense @mattfarina 

If only nowrap could have been the default from the start 😦

**Comment by bacongobbler** [comment]
Closing as we are not planning to accept this.

> This change has the potential to affect running software. The Kubernetes tests failing tell us that something is changing. I've helped people code around the 80 character limit knowing it's there.

**Pull request closed without merging**
