### PR TITLE
shouldn't send nil to errchan

### PR DESCRIPTION
**Pull request by carlory**

### CODE REVIEW

**Comment by bacongobbler** [comment]
can you explain this change? As far as I understand, the code *wants* to send the error.

ping @adamreese as he worked on this section

**Comment by carlory** [comment]
if no error occurs, this function may return an error. @bacongobbler 

```go
func (t *Tunnel) ForwardPort() error {
	...
	select {
	case err = <-errChan:
		return fmt.Errorf("forwarding ports: %v", err)
	case <-pf.Ready:
		return nil
	}
}
```

**Comment by carlory** [comment]
@adamreese Could you please take a quick look at this, Thank you!

**Review by technosophos — APPROVED** [review]
This appears to be technically correct. If a nil is returned on the channel, it could trigger an spurious error simply because sending a nil is still sending _something_ on the channel. So a `select` will get triggered on the error channel.

**Comment by technosophos** [comment]
Oh! Wait! I think we do indeed need @adamreese to weigh in on this. The question is whether it is intentional that we error out of `ForwardPort` returns before `pf.Ready` is triggered. If that's the intent, than even a nil on the channel should trigger the error case. That seems a little odd (since the error would be "forwarding ports: nil"), but it might be intended.

Relavant code:

**Comment by bacongobbler** [comment]
closing as inactive/intentional.

**Pull request closed without merging**
