### PR TITLE
Update related.md with new helm-github plugin

### PR DESCRIPTION
**Pull request by stevemcquaid**
Add helm-github plugin to list in documentation

### CODE REVIEW

**Comment by bacongobbler** [comment]
Hey @stevemcquaid! Once you accept the CLA we'd be happy to pull this in.

**Comment by stevemcquaid** [comment]
Thanks @bacongobbler! Still waiting on the verification email for the CLA. I'm 99% sure the first email bounced and the website doesn't have an option to resend. 

I have ticket # 48185 open with linux foundation if anyone here has access to that system.

**Comment by stevemcquaid** [comment]
@k8s-ci-robot CLA should now be signed.

**Comment by stevemcquaid** [comment]
👍

**Pull request merged**
