### PR TITLE
Upgrade golang to 1.13

### PR DESCRIPTION
**Pull request by ialidzhikov**
**What this PR does / why we need it**:
Upgrade golang to 1.12.9.

**Special notes for your reviewer**:

**If applicable**:
- [ ] this PR contains documentation
- [ ] this PR contains unit tests
- [ ] this PR has been tested for backwards compatibility

### CODE REVIEW

**Comment by Avni-Sharma** [comment]
Hi @ialidzhikov  . Is there any specific reason as to why aren't we using go 1.13?

**Comment by karuppiah7890** [comment]
@Avni-Sharma I don't think so. Probably this happened because [go 1.13 got released](https://blog.golang.org/go1.13) (Sept 3rd) only after this PR (Sept 1)

**Comment by karuppiah7890** [comment]
This fixes #6379 . @ialidzhikov please update the PR to use go v1.13 😄 

cc @bacongobbler @mattfarina

**Comment by mattfarina** [comment]
The error in CI is an odd one. It reads

```
pkg/chartutil/capabilities_versions_generated.go:1:1:warning: package comment should be of the form "Package chartutil ..." (golint)
```

The package comment is in `doc.go` and follows the proper format. I'm also unable to reproduce the problem locally. hrm...

**Comment by bacongobbler** [comment]
superseded by https://github.com/helm/helm/pull/6577. Thanks.

**Pull request closed without merging**
