### PR TITLE
Change port forward command order in default note

### PR DESCRIPTION
**Pull request by Aisuko**
Signed-off-by: Aisuko <urakiny@gmail.com>

**What this PR does / why we need it**:

We should take to get `POD_NAME` at first and forward pod's port to the local port, at last, print it to the screen.

**Special notes for your reviewer**:

**If applicable**:
- [x] this PR contains documentation
- [ ] this PR contains unit tests
- [ ] this PR has been tested for backwards compatibility

### CODE REVIEW

**Comment by hickeyma** [comment]
@Aisuko Looks good. Can you rebase and push changes to kick off a build again? Seemed an issue with build system previously.

**Comment by Aisuko** [comment]
@hickeyma  Rebuild has been succeeded. Would you mind give a lgtm?

**Review by hickeyma — APPROVED** [review]
LGTM, thanks.

**Review by hickeyma — APPROVED** [review]
LGTM, thanks.

**Comment by bacongobbler** [comment]
`kubectl port-forward` is a perpetually running command. Once invoked, it waits for user input to exit (CTRL + C), which is why the `echo` was on the earlier line. Now when a user copies those commands and attempts to execute them, the `echo` will not be shown.

I think this needs to be reverted.

**Pull request merged**
